### ISSUE TITLE
Move to corefx Span<T>

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#1005]
And remove the il compile steps... please.

Basically am on hold with contributions till it happens as its too painful to compile or test

/cc @KrzysztofCwalina @davidfowl @AtsushiKan @Drawaes

**Comment by Drawaes** [comment]
Yeah the barrier to run unit tests and debug with that IR compilation step means I am going to hold off working on the TLS stuff untilike it's gone as well (there might be some that think that is a good thing)

**Comment by KrzysztofCwalina** [comment]
@AtsushiKan is working on it.

**Comment by benaadams** [comment]
Resolved by @AtsushiKan's PR https://github.com/dotnet/corefxlab/pull/1013

Corefxlab compiles and tests in VS now!
