### ISSUE TITLE
Consider adding CancellatonToken to ReadAsync or Cancel method to IPipelineReader

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1017]
Right now, to force the await to continue, the caller needs to do a 0 byte write. This is a little bit hacky since that write needs to be synchronized with other writes into the same PipelineReaderWriter. The concern with a cancellation token passed into read is the allocation per read to register the callback that fires on cancellation. A cancel method would do the same thing but would avoid the per read allocation and be synchronized with the writer. The downside to that is that it's a different pattern that we currently use in .NET.

**Comment by KrzysztofCwalina** [comment]
cc: @stephentoub
