### ISSUE TITLE
Fix downgrade warnings in the build

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1018]
We have 186 downgrade warnings since the move to System.Memory. This is because System.Memory is using the latest corefx dependencies but corefxlab is downgrading them to stable deps:

![image](https://cloud.githubusercontent.com/assets/95136/20554050/00b63e5e-b10e-11e6-8b93-0ad0b2fdd13e.png)

Can we make System.Memory use stable dependencies? Or should we make corefxlab use the latest dependencies as well?

/cc @weshaggard @joshfree

**Comment by weshaggard** [comment]
cc @ericstj 

We have been given explicit direction for our packages be self-consistent and reference the same versions. 

If corefxlab wants to use pre-release packages from corefx then I would suggest either using all the latest versions or ignore the down-grade warnings and hope for the best.

**Comment by davidfowl** [comment]
> ignore the down-grade warnings and hope for the best

YOLO

**Comment by davidfowl** [comment]
Ok so its currently broken to consume this package:

https://github.com/dotnet/coreclr/issues/8302
