### ISSUE TITLE
Should Memory.Slice be checked?

### ISSUE THREAD

**Issue by svick** [dotnet/corefxlab#1031]
[Looking at the source code](https://github.com/dotnet/corefxlab/blob/8f61599/src/System.Slices/System/Buffers/Memory.cs#L53), it seems that `Memory<T>.Slice` is not checked, i.e. the caller can specify any `index` and `length` they want and they will get a new `Memory<T>` back.

The result of specifying incorrect values for those parameters is either `Memory<T>` that represents a different section of the owner (i.e. not a subsection of the original `Memory<T>`), or one whose `Span` throws (if it's outside the bounds of the owner).

Is this intentional? Isn't checking here worth it to prevent bugs?

**Comment by Drawaes** [comment]
If the span already throws do we need to pay the price of a second check?

**Comment by svick** [comment]
@Drawaes That covers the case when you get outside the bounds of the owner. But when you stay within the bounds of the owner, you can get outside the bounds of the original `Memory<T>`, but you won't get any exception. I think such behavior could easily hide bugs.

**Comment by KrzysztofCwalina** [comment]
This is a good question/tradeoff. I am torn. I think we should implement a full pipeline benchmark and see what the effect of adding these checks would be. I would prefer the checks to be added, but there is finite price that we can/should pay for it. 

@davidfowl, @vancem

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, can you triage this issue? I would like to remove all System.Memory issues from corfxlab. thanks.

**Comment by ahsonkhan** [comment]
Memory.Slice is checked. This issue is out-dated.
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Memory.cs#L166
```C#
if ((uint)start > (uint)_length || (uint)length > (uint)(_length - start))
```

@svick, feel free to re-open if you still have concerns.
