### ISSUE TITLE
Pipelines ReadAsync() could take an "expected size"

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1032]
Because the flow is inverted there is less understanding at the lower levels of the expected data. Often the application protocols have an idea (or if no the application protocol at least the intermediate ones).

For instance in Tls if I only get a partial frame, I know the size of the rest of the frame. Rather than having to loop over and over on ReadAsync() if I haven't got enough yet it would be good to be able to call 

ReadAsync(expectedFrameSize) and it not return until the connection closes/dies/or there are enough bytes to fill that amount.

Later we could also consider if required how to ensure this is on a single internal buffer. Some implementations such as SSPI require all the data to be contiguous, if we know that upfront the lower layer could be notified that I need the next x bytes in a single buffer. An extension some how of @mgravell "zero or tiny" buffer per socket, push that down to the lower pipeline, it decodes the size out, calls back with

ReadAsync(xxxBytes, contiguousMemory:true)

This can come later, but if that information is being pushed down and just reduces the looping the rest can be looked at later.

**Comment by davidfowl** [comment]
I don't think that later part is doable but not returning from ReadAsync until there's some limit reached is reasonable.

**Comment by Drawaes** [comment]
Second part is a nice to have not a requirement but I think pushing down the number of bytes needed might stop two things spinning round on a partial receive. So 1 is more important than 2 :)
