### ISSUE TITLE
Primitive parsing in invariant culture: Support thousands separator and decimal point?

### ISSUE THREAD

**Issue by botaberg** [dotnet/corefxlab#1033]
The current BCL parsers such as uint.TryParse support thousands separators and decimal points in invariant culture. Should we support this?

The specific BCL behavior is as follows:
- Thousands separator characters (commas) are always accepted unless they are at the beginning of the string. For instance, "1,,,,,,00,,,," parses as 100.
- Decimal points are accepted as long as all digits after the decimal point are 0. For instance, "10.0000" parses as 10.

**Comment by botaberg** [comment]
@KrzysztofCwalina What do you think?

**Comment by botaberg** [comment]
A generalization of the question: Should the behavior be like uint.TryParse called with NumberStyles.None?

https://msdn.microsoft.com/en-us/library/system.globalization.numberstyles(v=vs.110).aspx

**Comment by KrzysztofCwalina** [comment]
I think we need parsing APIs optimized for performance of machine to machine communication. The fact that humans cannot reliably read numbers without decimal separators just gets in the way :-)

And so, I think "invariant" should not mean NumberStyles.None. If it's too limiting in some scenarios, a custom encoding data ("en-us") can be used, and it will trigger the full culture support.

**Comment by KrzysztofCwalina** [comment]
@AtsushiKan, shoudl we close this?

**Comment by AtsushiKan** [comment]
I assume this issue was opened before TryParse took a format symbol parameter. Right now, if we support separators, it should be if the 'N' symbol is passed but that's already tracked as a separate issue (https://github.com/dotnet/corefx/issues/24986)
