### ISSUE TITLE
Memory<T> ToString

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/corefxlab#1044]
Memory<T> ToString shouldn't truncate; either return the string on multiple lines or throw an exception if the length is too long, but don't just stop at the 8th byte? as this could lead to confusion
...

public override string ToString()
{
            var sb = new StringBuilder();
            var data = Span;
            sb.Append("[");
            bool first = true;
            for(int i=0; i<Length; i++) {
                if (i > 7) break;

**Comment by Tragetaschen** [comment]
It should, in the debugger, show 64MiB of data rendered to a string, or nothing but that an exception happened while accessing the variable?

The current implementation sounds like a reasonable compromise.
