### ISSUE TITLE
Howto build lib+app using System.IO.Pipelines?

### ISSUE THREAD

**Issue by malachib** [dotnet/corefxlab#1048]
Sorry for the newbie question, but I am struggling to get my app functioning in this scenario:

- o lib A consuming System.IO.Pipelines - v0.1.0-e161207-1
produces netstandard1.3, netstandard1.6 and netstandard1.6.2 output successfully.  Only netstandard1.6.2 contains the pipeline code
- o app B consuming lib A 

No matter what I do with app B, it won't bring in netstandard1.6.2, only netstandard 1.6 - thus excluding the pipeline code.  My best guess is something like this in app B:

```
      "dependencies": {
        "NETStandard.Library": "1.6.2-beta-24806-05", // This doesn't help
        "Microsoft.NETCore.App": {
          "version": "1.2.0-beta-001137-00",
          "type": "platform"
        }
      }
```
But no luck.  Any advice?

**Comment by davidfowl** [comment]
I made a sample here https://github.com/davidfowl/PipelinesSample.

**Comment by malachib** [comment]
Thank you for the sample - it is helpful.  Unfortunately, I didn't clarify exactly before, I am compiling libs in side by side directories so they are inline instead of nuget'd.  I don't know if that does/should make a difference here?

Also, I notice your repo no longer uses 1.6.2-* and now using 1.6.0 and friends.  This likely obviates my issue for the time being (I will test more tonight), although I have a feeling I'll still have to solve it for another scenario.

**Comment by KrzysztofCwalina** [comment]
seems like the issue is resolved.
