### ISSUE TITLE
Non blocking read for pipelines

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1050]
For something like TLS where there is overhead per packet. I want to readasync start a frame do all the processing and then do a quick Read non blocking to check for anymore data before I close that frame.

**Comment by davidfowl** [comment]
You can do that already right? Check to see if the result of the read call is completed after calling advance before awaiting it.

**Comment by Drawaes** [comment]
Good thinking. Is it worth wrapping in a ReadNonBlocking ? If so I am happy to write it in a small PR as an extension otherwise I can just do it in my own project.

**Comment by benaadams** [comment]
Peek?

**Comment by muratg** [comment]
We believe this is done. (TryRead.)  Should we move it to 2.0.0 and close?  (ping @joshfree)

**Comment by Drawaes** [comment]
This is done correct with TryRead
