### ISSUE TITLE
Some community chat

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1051]
Either slack, gitter, or cooler microsoft teams? For corefxlabs where crazy ideas can be bounced around pre issue posting giving more fluid discussions in the open.

**Comment by grahamehorner** [comment]
yammer?

**Comment by aL3891** [comment]
Theres always the [aspnetcore slack](https://aspnetcoreslack.herokuapp.com/), that's pretty much a .net slack these days :)

**Comment by KrzysztofCwalina** [comment]
cc: @terrajobst

**Comment by Drawaes** [comment]
cc: @benaadams @terrajobst @davidfowl when channels was in early development the gitter channel was great but now it is dead. The asp.net is meh... we need to build something there are great ideas out there and github issues are a rubbish way of bouncing around early ideas. Orleans has managed to build a good solid chat community I think the same can be done for corefxlabs....

**Comment by benaadams** [comment]
It kinda came together for a time; when channels and the aspnet standup were in gitter; but aspnet has moved back to ephemeral youtube chat, channels has been absorbed to corefxlabs with no IM; and MS has likely moved to teams. Now using IM for coordination/discussion is like whispering in the wind...

**Comment by Drawaes** [comment]
Bumping this.... maybe a corefxlabs gitter?

**Comment by ReubenBond** [comment]
Gitter would be great. It works well for us Orleans devs: https://gitter.im/dotnet/orleans

**Comment by M-Zuber** [comment]
Re gitter, a reminder that you can create groups not tied to a repo, so it could be a very good solution

**Comment by benaadams** [comment]
The repo is the grain of sand the pearl forms around 😉

**Comment by terrajobst** [comment]
Resolved as fixed:

https://gitter.im/dotnet/corefxlab
