### ISSUE TITLE
Optimization: UTF8Encoding methods can probably be made faster/refactored

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefxlab#1052]
See previous coreclr issue @ https://github.com/dotnet/coreclr/issues/6759

future corefxlab UTF8Encoding speclet/prototype work should address feedback above and ensure devs like @jamesqo will be happy with new prototyped APIs

**Comment by shiftylogic** [comment]
UTF-8 <=> UTF-16 uses the same algorithm as CoreCLR now. We are getting great performance numbers now.
