### ISSUE TITLE
Stitching multiple readable buffers together

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1060]
In TLS there is two layers of framing. The Record frame and the protocol frame. A record frame is wrapped inside the protocol frame. However the record frame can be much larger than the record frame. Therefore I need to be able to unwrap and decrypt the record fragments in place.

I then need to slice off the headers, and trailers to get the actual record data. At this point if I don't have the complete frame I will need to preserve and check multiple of these. It would be nice if at this point I didn't need to construct a collection or my own linked list but instead could append the start cursor of the second list to the end cursor of the first. 

I am not sure if this is possible today but as I believe they are linked lists of buffers internally this should be possible.

**Comment by davidfowl** [comment]
Code samples would help me understand better here. Is this across multiple calls to ReadAsync? 
 
       ReadAsync()                ReadAsync()
[ header | payload ] -> [ header | payload ]

Is that what it looks like?  You want to string multiple payloads together into a single readable buffer?

**Comment by Drawaes** [comment]
The other problem with the internal channel is that the process needs to be synchronised. Async won't work because the current payload may change the encryption state which will change the way the next [header] frame will be handled (encrypted or not, renegotiated keys etc)

One way to solve it but seems unclean is to hold a list of buffers that makes up the current payload. Obviously then I have to enumerate that and the readables which is a mess.

**Comment by Drawaes** [comment]
@davidfowl does this kinda help (P.S. don't mention spacing, var it's mock code)
[Gist of Demo](https://gist.github.com/Drawaes/009d39f80ba6caf045b2b8372d4917fa)

**Comment by Drawaes** [comment]
What would be a solution is if You could build an I SEQUENCE from a bunch of preserved readablebuffers. So in effect you would end up with a selectmany to use linq terminology

**Comment by davidfowl** [comment]
> (P.S. don't mention spacing, var it's mock code)

My eyes

**Comment by Drawaes** [comment]
I have got past this by making an internal channel for now. It's really a
sync operation so it's a bit over kill but it works

**Comment by Drawaes** [comment]
[Managed TLS using an internal handshake channel](https://github.com/Drawaes/corefxlab/blob/ManagedTlsV3/src/System.IO.Pipelines.Networking.Tls.Managed/SecurePipeline.cs#L56-L64)

Shows how I have used an internal channel. This might actually be preferable if a new handshake happens during communication (renegotiation for certs etc).

**Comment by Drawaes** [comment]
@KrzysztofCwalina is this solved with the multi span reader that you have made over readonly bytes?

**Comment by KrzysztofCwalina** [comment]
I would say the reader is trying to solve it. It will be solved when the pipeline APIs use the same abstraction to represent multi-segmented buffers as the reader. Today, the reader operates over ReadOnlyBytes and the pipeline APIs use ReadableBuffer.

**Comment by davidfowl** [comment]
Yep, as soon as we get through this push converting Kestrel to pipelines, we'll look at merging the APIs. We're very very close.

**Comment by ahsonkhan** [comment]
Does [ReadOnlySequence](https://github.com/dotnet/corefx/blob/8e53c7efea4efd28ba9d111dd4e70e3ca2f987f3/src/System.Memory/src/System/Buffers/ReadOnlySequence.cs#L19) resolve this issue?
