### ISSUE TITLE
[Channels] No way for Reader to detect Read failure due to Write end completion

### ISSUE THREAD

**Issue by anurse** [dotnet/corefxlab#1068]
**Repro repo:** https://github.com/anurse/corefxlab-1068-repro

**Repro steps:**

1. Clone the above repro repo
2. Restore and run the console app project

**Expected behavior:** We are able to gracefully terminate the reader when the channel is closed

**Actual behavior:** `ReadAsync` throws an internal exception which we have no way of catching (short of catching `Exception` and using `GetType`...gross)

This seems like a case where we need ReadAsync to return a type which can indicate if the task completed due to a result becoming available or because the Channel was closed, similar to how Pipelines has a `ReadResult` type with an `IsCompleted` property. I realize there is `WaitToReadAsync` but I still think there is value in `ReadAsync` completing in a way that allows the caller to detect why it is completing, even if it is just a public exception type (though I'm always a bit nervous about exceptions-as-control-flow).

/cc @davidfowl @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
Andrew, if it's blocking you, feel free to make the exception type public, and we'll sort it out when I'm back.

**Comment by anurse** [comment]
I'll look at that. For now I did a terrible no-good very bad hack :) https://github.com/aspnet/SignalR/commit/944ad6142963061d48462d840d759321a6871bbe#diff-4ccd5d321726b6b360e521c80697e077R188

**Comment by anurse** [comment]
And I think that because `WaitToReadAsync` exists, I'd actually be OK with using the exception here. If you really want to have a "clean" and "pure" API, use `WaitToReadAsync` and `TryRead` in combination. The only reason I can't use `WaitToReadAsync` is that I have my own implementation of `IReadableChannel` that uses a Pipeline under the covers and Pipelines don't really have a clean way to "wait for read" right now so I wasn't able to implement that API. Long-term I expect we'd avoid implementing `IReadableChannel` but for various reasons that was the easiest first attempt at solving the problem we're exploring :)

**Comment by anurse** [comment]
Let's make the exception type public for now. :) /cc @stephentoub

**Comment by stephentoub** [comment]
> Let's make the exception type public for now.

Already did ;)

**Comment by davidfowl** [comment]
Exception for close isn't the cleanest way to do it. It would be great if there was a way to detect the end of the channel without an error.

**Comment by stephentoub** [comment]
> It would be great if there was a way to detect the end of the channel without an error.

The are several: 
- using WaitForReadAsync, where the returned task will have a result of false if nothing more is or will be available to read
- using Completion, which will complete in the same condition 
- using the async enumerator for the channel, where the task returned from MoveNextAsync has same behavior 

What additional way is needed?

**Comment by davidfowl** [comment]
> using the async enumerator for the channel, where the task returned from MoveNextAsync has same behavior

Too ugly. Needs language support.

> using Completion, which will complete in the same condition

Using completion is too error prone. It's easy to check completion at the wrong time which may result in missed data. It *may* be useful in scenarios where something other than the consumer wants to check if the channel is complete.

> using WaitForReadAsync, where the returned task will have a result of false if nothing more is or will be available to read

In the below example, if the producer does `WriteAsync` followed by `Complete()` on the channel, will the consumer get that data?

```C#
while (await channel.WaitToReadAsync())
{
    ByteBuffer buffer;
    if (channel.TryRead(out buffer))
    {
        ConsumeBuffer(buffer);
    }
}
```

I haven't looked at the implementation to see if WaitForReadAsync returns true if the consumer hasn't consumed everything. Also does anything change if the channel is unbuffered?

**Comment by stephentoub** [comment]
> Too ugly

Really?  We're talking about:
```C#
var e = c.GetAsyncEnumerator();
while (await e.MoveNextAsync())
{
    Use(e.Current);
}
```
I agree that language support makes it nicer, e.g.
```C#
foreach (await var current in c)
{
    Use(current);
}
```
but not so much so that it's "too ugly".

> language support.

As you know, this is something being actively looked at for C# 8.

> Using completion is too error prone. It's easy to check completion at the wrong time which may result in missed data

How so?  A channel isn't considered completed until it's been marked for completion AND it has no more data left to consume.  There is no race condition.

> the producer does  WriteAsync  followed by  Complete()  on the channel, will the consumer get that data?

Yes, the consumer will get the data.

> Also does anything change if the channel is unbuffered?

No.

**Comment by anurse** [comment]
> How so? A channel isn't considered completed until it's been marked for completion AND it has no more data left to consume. There is no race condition.

If this is the case, then we should be fine. @davidfowl was under the impression (and I thought had done some testing) that it was not. My impression was what @stephentoub indicated, that the completion is only triggered after the last item is read.

**Comment by davidfowl** [comment]
Yep, it's ok to close this item
