### ISSUE TITLE
Productize Parsing APIs

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1070]
Parsing APIs design document is at https://github.com/dotnet/corefxlab/blob/master/docs/specs/parsing.md

We identified the following work items required to productize the APIs:

Priority 0
- [x] remove old APIs (.Internal sub-namespace)
- [x] remove `EncodingData(byte[][] symbols, TextEncoding encoding, Tuple<byte, int>[] parsingTrie)`
- [ ] remove all custom parsers from System.IO.Pipelines (and other corefxlab components)
- [x] make sure APIs can support non-invariant cultures (by implementing and testing prototype)

Priority 1
- [x] implement parsing APIs for integer types
- [x] support UTF8 and UTF16 invariant
- [x] performance tests and improvement for integer parsing
- [x] support fast lower case and upper case hexadecimal parsing
- [x] generate parsers using T4 templates
- [x] support Boolean
- [x] full test coverage (including .NET compatibility tests)
- [ ] ASCII and ISO-8859-1 (required by networking protocols)

Priority 2
- [ ] full support for non-invariant cultures
- [ ] support BigInteger parsing
- [ ] support URI parsing
- [x] support DateTime, DateTimeOffset 
- [x] support GUID
- [x] support 'G', 'D', 'R', 'X' formats
- [x] clean up code, including performance tests (we have too many of them)
- [x] add GC allocation tests (the low level APIs should not allocate)
- [-] add performance tests comparing to C++ performance
- [ ] add support for parsing discontinuous buffers (higher level APIs)
- [x] do formal API review

Priority 3
- [x] support Single, Double
- [x] support Decimal
- [x] support TimeSpan
- [x] support all numeric and date time format strings.
- [ ] support UTF16BE

**Comment by KrzysztofCwalina** [comment]
I moved the workitems from the spec to this issue. It's easier to update.

@joshfree, @botaberg, @terrajobst, @davidfowl

**Comment by botaberg** [comment]
Thanks, @KrzysztofCwalina !

**Comment by KrzysztofCwalina** [comment]
@botaberg, I updated the list. Mainly rearranged priorities

**Comment by GSPP** [comment]
Are `byte*` overloads even necessary? Can they not be fully replaced with the span version?

**Comment by ahsonkhan** [comment]
> Are `byte*` overloads even necessary? Can they not be fully replaced with the span version?

You are right, they are not necessary if we replace them with APIs that take span.

**Comment by KrzysztofCwalina** [comment]
I updated the list at the top of the issue with workitems that we have completed.
The remaining workitems are the following:

- [ ] remove all custom parsers from System.IO.Pipelines (and other corefxlab components)
- [ ] ASCII, UTF16BE, and ISO-8859-1 (required by networking protocols)
- [ ] full support for non-invariant cultures
- [ ] support BigInteger parsing
- [ ] support URI parsing
- [ ] add support for parsing discontinuous buffers (higher level APIs)

I will close this issue and open separate issues for the punted/postponed items as I consider the basic Utf8Parser/Formatter to be successfully productized

**Comment by ahsonkhan** [comment]
Also UTF16, not just UTF16BE.
