### ISSUE TITLE
[Question] Related to roadmap and release

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#1087]
Understanding there are various variables for progress on some of the components (parsing, format, encoding, etc.) described in [roadmap](https://github.com/dotnet/corefxlab/blob/master/docs/roadmap.md), could you provide some info on timeline?  For example, I noticed the new Span has moved to [CoreFx](https://github.com/dotnet/corefx).  Assuming the parsing, encoding APIs will eventually move there.  Is the plan to have those moved by the Spring 2017 release of .NET Core 2 and .NET Standard 2?  In addition, what are the steps to take to test out the new APIs?  Is it simply just adding the NuGet package?

Thanks in advance and looking forward to the progress in this area.

**Comment by KrzysztofCwalina** [comment]
@joshfree should be able to talk about the timeline.

As to trying the APIs, just use the nuget package. See https://github.com/dotnet/corefxlab#how-to-use

**Comment by shaggygi** [comment]
Thanks @KrzysztofCwalina

**Comment by shaggygi** [comment]
From my understanding, the APIs will be included within ASP.NET Core 2.0 timeframe.  However, they will be in a "semi-private" state.  They will be made public later in 2017 around the 2.1 release.

Again, this is my interpretation based on conversations in [live.asp.net](https://live.asp.net/).  As @DamianEdwards says...  "It's just a roadmap." :smile:
