### ISSUE TITLE
Productize Encoding APIs

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1091]
Pri 0
- [x] Make encoding between UTF8 and UTF16 (both ways) fast

Pri 1
- [x] Hide System.Text.Utf8 and System.Text.Utf16 namespaces, except for Utf8String
- [x] Add TextEncoder overloads hinted in comments in source.
- [x] Move UnicodeCodePoint to some subnamespace, or hide for now, if not needed by bullet above
- [ ] Support other encodings, e.g. 8859-*
- [x] We need ability to continue (as opposed to restart) encoding after output buffer space has been exhausted

Pri 2
- [x] Rename EncodingData to something better
- [x] Rename TextEncoder.Id type, and Scheme property

**Comment by KrzysztofCwalina** [comment]
@joshfree, @terrajobst, @shiftylogic, @ahsonkhan, @botaberg, I added this issue to track work related to formatting APIs. Feel free to add/tweak workitems.

**Comment by joshfree** [comment]
>> System.Text.Utf8 and System.Text.Utf16 namespaces need to be designed properly

Is this just a catch all item or can you quickly enumerate some additional issues here?

**Comment by KrzysztofCwalina** [comment]
Let's just change the workitem to "hide the APIs except for Utf8String". I will make the update.

**Comment by KrzysztofCwalina** [comment]
@joshfree, @ahsonkhan, I updated the workitem list. I tried to make it clearer, added priorities, and sorted in the order I think the work should be done.

**Comment by KrzysztofCwalina** [comment]
All of the items except for 8859-* support are done. I created #1727 to track the remaining item and so closing this issue.
