### ISSUE TITLE
Parsing routines fail when called with the default format

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1106]
Repro:

        ulong value;
        int consumed;
        if(PrimitiveParser.TryParseUInt64(new byte[] { (byte)'1' }, out value, out consumed)
        {
            Console.WriteLine(value);
        }

Result:
System.NotImplementedException was unhandled
  HResult=-2147467263
  Message=Format with precision not supported.
  Source=System.Text.Primitives
 
Expected:
prints '1'

**Comment by botaberg** [comment]
Taking a look now.

**Comment by botaberg** [comment]
This is due to the observation that default(TextFormat) has precision 0 rather than NoPrecision:

if (format.HasPrecision)
{
       throw new NotImplementedException("Format with precision not supported.");
}

Should the default be precision 0 rather than NoPrecision? What is the difference between precision==0 and precision==NoPrecision?

**Comment by KrzysztofCwalina** [comment]
NoPrecision means that precision was not specified. Precision==0 means it was specified as 0. The default being 0 will screw up some formatting routines. I think there are two solutions:
1. When entering methods, convert the default format to NoPrecision.
2. Treat 0 value of the filed, as "no precision specified" and when the precision is explicitly set to zero, set the filed to some value that means 'zero", i.e. use one bit (high bit) in the precision filed to mean "the value was set"

I think the first option is better. The second option means that all code that wants to red the precision would have to clear the bit.

**Comment by KrzysztofCwalina** [comment]
@botaberg fixed it.
