### ISSUE TITLE
Design precondition contract for PrimitiveParser.TryParse main overloads

### ISSUE THREAD

**Issue by botaberg** [dotnet/corefxlab#1110]
Design precondition contract for PrimitiveParser.TryParse main overloads - the ones that take TextFormat and EncodingData objects as parameters.

Currently, it is difficult to decipher what inputs are valid and which ones are not. With a proper precondition contract, the checks will be a lot simpler and easier to read. For reference, these are the current checks:

            if (encoding == default(EncodingData))
            {
                encoding = EncodingData.InvariantUtf8;
            }

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoding.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseByte(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseByte(text, out value, out bytesConsumed);
                }
            }
            else if (encoding.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.Cast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseByte(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseByte(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

**Comment by botaberg** [comment]
Created this as per @KrzysztofCwalina's comments in PR #1109.

**Comment by KrzysztofCwalina** [comment]
I think we now cleaned up and documented the contact.
