### ISSUE TITLE
Span Debugger Viewers Must Work in VS2017

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1122]

**Comment by ahsonkhan** [comment]
Is this a duplicate of https://github.com/dotnet/corefx/issues/14376?

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, should this be tracked in corefx now?

**Comment by ahsonkhan** [comment]
Yes, the issue in corefx that is already open should be sufficient to track this work.
