### ISSUE TITLE
Add BoundedChannelFullMode.Ignore for Channel Writing

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#1127]
It would be nice to ignore items written to a channel if it has already reached its buffered capacity.  Would by adding another enum of BoundedChannelFullMode.Ignore help this scenario?

```csharp
Channel<int> myChannel = Channel.CreateBounded<int>(3, BoundedChannelFullMode.Ignore);
myChannel.Out.WriteAsync(1);
myChannel.Out.WriteAsync(2);
myChannel.Out.WriteAsync(3);
myChannel.Out.WriteAsync(4);  // This should be ignored and never added to queue.
var value = myChannel.In.ReadAsync().Result; // value = 1.
// myChannel should include 2 items (2, 3).
```

Using the Wait enum in example above will still add 4 to queue after ReadAsync() and myChannel includes 3 items (2, 3, 4).

I was comparing this to TDF BufferBlock like below:

```csharp
BufferBlock<int> bufferBlock = new BufferBlock<int>(new DataflowBlockOptions { BoundedCapacity = 3 });
bufferBlock.SendAsync(1);
bufferBlock.SendAsync(2);
bufferBlock.SendAsync(3);
bufferBlock.SendAsync(4);  // This is ignored and never added to queue.
var bufferBlockValue = bufferBlock.Receive();
// bufferBlockValue includes 2 items (2, 3).
```

**Comment by stephentoub** [comment]
This is a reasonable thing to add; I'll do so. 

However, the comment about dataflow isn't correct. That last SendAsync's value will be added once room is available, at which point is returned task will complete successfully, just like with WriteAsync with the default options on the bounded channel.

**Comment by shaggygi** [comment]
Gotcha.  I missed this by breakpointing and didn't give a chance to add last SendAsync.  Thanks for reviewing.

**Comment by shaggygi** [comment]
Thanks @stephentoub
