### ISSUE TITLE
Should ReadableChannel and WritableChannel properties be swapped

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#1128]
This is most likely my misinterpretation, but should ReadableChannel and WritableChannel properties in Channel be swapped?  Looking at a channel as a box... you can write to (In) and read from (Out).

```csharp
public abstract class Channel<TWrite, TRead>
{
    public abstract ReadableChannel<TRead> In { get; }
    public abstract WritableChannel<TWrite> Out { get; }
    ...
}
```

In addition, looking at the abstract classes the keywords confuse me a little as it is opposite to Channel property names.

```csharp
public abstract class ReadableChannel<T>
{
    public abstract bool TryRead(out T item);  // out keyword.

public abstract class WritableChannel<in T>
{
    public abstract bool TryWrite(T item);
```

I understand it is one of those "getting familiar with the API", but when starting to use it... it's a little confusing.

**Comment by stephentoub** [comment]
That's how I originally had it, but @KrzysztofCwalina recommended I swap them to what they are now, e.g. to match Console.Out/In. It depends on whether the direction is from the perspective of the producer/consumer or from the perspective of the channel itself.

**Comment by shaggygi** [comment]
Gotcha.  I guess it would be good to keep consistent then.  Thanks for insight.
