### ISSUE TITLE
Position: Equals(object), Typo?

### ISSUE THREAD

**Issue by airbreather** [dotnet/corefxlab#1145]
https://github.com/dotnet/corefxlab/blob/cf42c37bcb1a78ebf29556f354292dd0d4306cd6/src/System.Collections.Sequences/System/Collections/Sequences/Position.cs#L43

Should be `this.Equals((Position)obj)`, not `base.Equals((Position)obj)`, right?  Otherwise, aren't you unboxing then re-boxing to fall back to the reflection-based `ValueType.Equals(object)`, which has to iterate the fields because it contains an object reference?

**Comment by ahsonkhan** [comment]
This was fixed as part of https://github.com/dotnet/corefxlab/pull/1933/files#diff-98ff257313db5bec83b87d192d5b1f43.

This type eventually became [SequencePosition](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/SequencePosition.cs#L51)

cc @KrzysztofCwalina, @pakrym 

Closing
