### ISSUE TITLE
Move the Span based TextEncoder to Performance benchmark project

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1148]
From PR #1139 
https://github.com/dotnet/corefxlab/pull/1139#issuecomment-274113683

Please move the Span based implementation to a benchmark test. We want to be running this benchmark periodically to drive span performance down to be in the ballpark of the pointer one.

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, is this still relevant or we should close?

**Comment by ahsonkhan** [comment]
I don't know if there is value in keeping the Span based implementation but I will look into this to confirm.
