### ISSUE TITLE
Tests need to be fixed for VS2017 upgrade

### ISSUE THREAD

**Issue by crummel** [dotnet/corefxlab#1155]
I disabled some tests that were failing after the upgrade.
For individual tests, they are tagged with "VS2017".
I also took projects that used xunit.performance.core out of the build, I believe these were failing because that package needs to be upgraded to the latest SDK as well:
- Benchmarks
- System.Binary.Base64.Tests
- System.Slices.Tests
- System.Text.Json.Tests

Projects that used RESX files also failed:
- System.CommandLine.Tests
- System.Collections.Generic.MultiValueDictionary.Tests
- System.IO.Pipelines.Tests
- System.Text.Formatting.Globalization.Tests
- System.Time.Tests

I'm not familiar enough with resource stuff to know why those are an issue.

**Comment by ahsonkhan** [comment]
System.Text.Primitives.Tests can also not be discovered since it references xunit.performance.core

**Comment by ahsonkhan** [comment]
System.Text.Json.Tests do not reference xunit.performance.core. They shouldn't be skipped.

**Comment by davidfowl** [comment]
@ahsonkhan is this done?

**Comment by ahsonkhan** [comment]
I need to remove performance tests (and dependency to xunit.performance.core) from the following projects and move them to Benchmarks:
System.Binary.Base64.Tests
System.Slices.Tests

These tests (along with the functional unit tests within these projects) don't show up in VS test explorer as long as they have benchmark tests in them. I am trying to resolve the issue with the xunit.perf team.

This should be complete:

> Projects that used RESX files also failed:
System.CommandLine.Tests
System.Collections.Generic.MultiValueDictionary.Tests
System.IO.Pipelines.Tests
System.Text.Formatting.Globalization.Tests
System.Time.Tests`

**Comment by ahsonkhan** [comment]
This issue has been fixed by updating the package reference to stable versions of xunit and xunit.runner.visualstudio, and by updating to a new xunit.performance.core package (along with PRs referenced in this issue).
