### ISSUE TITLE
System.CommandLine - Mark options themselves as mandatory?

### ISSUE THREAD

**Issue by christophediericx** [dotnet/corefxlab#1163]
> Version used: 0.1.0-e170127-2

Whenever an option is specified on the command line, it is required (by default) to have a *value* passed in for that option.

> _Normally, options must supply an argument value (or it's considered an error)._

However, there seems to be no easy way to mark the options **themselves** as mandatory (thus resulting in errors being automatically reported when these options are not specified on the command line).

One would think that writing something like this could work:

```csharp
var s = ArgumentSyntax.Parse(args, syntax =>
{
    Func<Argument<string>,string> formatErrorMessage = 
        (x) => $"Mandatory option '{x.Help}' ({string.Join("|", x.Names)}) not specified!";

    var option1 = syntax.DefineOption("a|aarg", ref arg1, true, "Argument a");
    var option2 = syntax.DefineOption("b|barg", ref arg2, true, "Argument b");

    if (option1.IsRequired && !option1.IsSpecified)
        syntax.ReportError(formatErrorMessage(option1));

    if (option2.IsRequired && !option2.IsSpecified)
        syntax.ReportError(formatErrorMessage(option2));
});
```
But even this naive approach has a couple of distinct disadvantages:

1. The above will make the builtin `--help` option not work correctly anymore, so we'll need to special case for that.
2. Execution is halted the moment the first time `ReportError(..)` is called (while arguably, that method could internally just add the errors to an internal collection before rendering all in bulk at the end).

Unless I miss the canonical way of performing this ("marking an option as mandatory"), it seems to me that a substantial amount of code is needed (from a client perspective) in order to support this very common use case with the `System.CommandLine` library.

From that perspective it might be a feature worth considering?

**Comment by alexperovich** [comment]
You are correct, there isn't a way to mark an option as required. The existing parameter `isRequired` is misleading because it represents if the value is required or not. This should be added.
I will rename the existing parameter and add support for required options.

**Comment by alexperovich** [comment]
After a discussion with @terrajobst about the original reason required options were not included I agree with him. Options are by definition optional. If your application has some data that is required then it should be a parameter.
The only case in unix CLI tools where options can become "required" is when options are in sets, i.e. if you specify option "a" then option "b" must also be specified. This case should be handled by the application, not this library. This example can be implemented like this:
``` C#
var a = syntax.DefineOption("a|apple", ref value1);
var b = syntax.DefineOption("b|banana", ref value2);

if (a.IsSpecified && !b.IsSpecified)
    syntax.ReportError("fatal: cannot specify 'a' without also specifying 'b'");
```

I will still rename the `isRequired` parameter because it is badly named.

**Comment by christophediericx** [comment]
Fair enough, thank you for taking the time to investigate. Renaming the parameter will definitely go a long way already as to avoid confusion.

**Comment by dmitry-azaraev** [comment]
Required options is actually are *named* parameters. All [real-world libraries](https://docs.python.org/3/library/argparse.html#required) define this strictly without any "Options are by definition optional.".

**Comment by Basketcasesoftware** [comment]
This discussion makes an assertion but leaves the implementation unexplained (sorry I'm so late to the party).
The statement "If your application has some data that is required then it should be a parameter." leaves me scratching my head. 
Assume I have an application "foof". I need to have a mandatory item and a variable number of options.
foof blah [options]
How would this be set up using System.CommandLine? How would the help feature work? I tried doing this with a combination of the core API and Dragonfruit. Fail. 
This may be just a weakness of the documentation of the API which uses as its only example project one that has nothing but a set of options on a RootCommand.
