### ISSUE TITLE
System.CommandLine - Equals sign in command line arguments not handled correctly

### ISSUE THREAD

**Issue by christophediericx** [dotnet/corefxlab#1164]
> System.CommandLine version used: 0.1.0-e170127-2
> dotnet version used: 1.0.0-rc3-004530

As per the documentation,

> _Both, the single letter form, as well as the long forms, support arguments. Arguments must be separated by either a space, an equal sign or a colon:_

However, when specifying an option value with the equals sign, it is not recognized correctly. This occurs both for short and long name option naming. It occurs both when passing arguments through dotnet-run and when setting them in the debug options in Visual Studio 2017 RC3):

```csharp
var arg1 = string.Empty;

var s = ArgumentSyntax.Parse(args, syntax =>
{
    var option1 = syntax.DefineOption("a|aarg", ref arg1, true, "Argument a");
});

Console.WriteLine($"Selected option: {arg1}!");
```

Using a space or a colon works:
```
dotnet run -- -a "C:\Temp\aFile.tmp"
Selected option: C:\Temp\aFile.tmp!
```

```
dotnet run -- -a:"C:\Temp\aFile.tmp"
Selected option: C:\Temp\aFile.tmp!
```

But using an equals sign fails:

```
dotnet run -- -a="C:\Temp\aFile.tmp"
error: option -a requires a value
```

```
dotnet run -- --aarg="C:\Temp\aFile.tmp"
error: invalid option --aarg=C
```

**Comment by alexperovich** [comment]
That is very odd behavior. What happens when you `dotnet publish` and then run the resulting executable?

**Comment by christophediericx** [comment]
I just tried it out, and the exact same symptoms can be seen after a `dotnet publish` (versions of dotnet and System.CommandLine as quoted above).

It's probably just the lexer getting confused because of the colon in the argument value as the option is parsed correctly without the colon.

e.g.

`dotnet run --myarg="C:\Temp\myfile.bin"`

does **not** work correctly, while

`dotnet run --myarg="argwithoutcolon"`

does work.

**Comment by alexperovich** [comment]
When you ran it the second time did you actually run the executable file created by `dotnet publish`? My guess is that the dotnet-run executable is doing something strange to the arguments when they are passed into your program. This test (https://github.com/dotnet/corefxlab/blob/master/tests/System.CommandLine.Tests/System/CommandLine/Tests/ArgumentLexerTests.cs#L43) tests that the "=" works properly.

**Comment by christophediericx** [comment]
I did run the assembly as generated by `dotnet publish`. 

As stated above, the problem seems to occur only when the argument value itself contains one of the _delimiters_ (e.g. `--myarg="C:\Temp\myfile.bin"`. The (arguably overly simplistic) test linked to does not reflect this scenario.

**Comment by alexperovich** [comment]
I have a fix and will submit a PR.
