### ISSUE TITLE
Run codeformatter on corefxlab sources

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1200]
cc: @joshfree

**Comment by joshfree** [comment]
thanks @KrzysztofCwalina; this will help us get a bit tidier 👔

**Comment by davidfowl** [comment]
Omg yes it will fix @KrzysztofCwalina's formatting 😛

**Comment by benaadams** [comment]
There going to be PRs constantly changing the formatting rules? 😉

**Comment by ahsonkhan** [comment]
Due to the following issue, we can't run codeformatter on the corefxlab solution: https://github.com/dotnet/codeformatter/issues/256, using https://github.com/dotnet/codeformatter/releases/tag/v1.0.0-alpha6.
