### ISSUE TITLE
System.Text.Primitives.Tests fails on my machine when I run all tests

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1211]
```
Failed   System.Text.Utf8.Tests.Utf8EncoderTests.TestEncodingInputBufferMaxSize
Error Message:
 System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
Stack Trace:
   at System.Text.Utf8.Tests.Utf8EncoderTests.TestEncodingInputBufferMaxSize() in C:\Users\dfowler\Documents\GitHub\corefxlab\tests\System.Text.Primitives.Tests\Encoding\Utf8EncoderTests.cs:line 69
```

```
Failed   System.Text.Utf8.Tests.Utf8EncoderTests.TestEncodingOutputBufferMaxSize
Error Message:
 System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
Stack Trace:
   at System.Span`1.ToArray()
   at System.Text.Utf8.Tests.Utf8EncoderTests.TestEncodingOutputBufferMaxSize() in C:\Users\dfowler\Documents\GitHub\corefxlab\tests\System.Text.Primitives.Tests\Encoding\Utf8EncoderTests.cs:line 96
Passed   System.Text.Utf8.Tests.Utf8EncoderTests.TryPartialUtf16ToUtf8DecodingTest(outputSize: 7, expectedConsumed: 2, inputBytes: ['µ¿Ö', 'µ║û', 'ΦÉ¼', 'σ£ï', 'τó╝'], expected1: [230, 168, 153, 230, 186, ...], expected2: [232, 144, 172, 229, 156, ...])
Passed   System.Text.Utf8.Tests.Utf8EncoderTests.TryPartialUtf16ToUtf8DecodingTest(outputSize: 2, expectedConsumed: 2, inputBytes: ['H', 'e', 'l', 'l', 'o'], expected1: [72, 101], expected2: [108, 108, 111])
```

```
C:\Users\dfowler\Documents\GitHub\corefxlab\scripts\build.ps1 : Some tests failed in project
C:\Users\dfowler\Documents\GitHub\corefxlab\scripts\..\tests\System.Text.Primitives.Tests\System.Text.Primitives.Tests.csproj
At line:1 char:1
+ C:\Users\dfowler\Documents\GitHub\corefxlab\scripts\build.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build.ps1
```

```
** Build failed. 1 projects failed to build or test. **
    C:\Users\dfowler\Documents\GitHub\corefxlab\scripts\..\tests\System.Text.Primitives.Tests\System.Text.Primitives.Tests.csproj
```

/cc @KrzysztofCwalina @ahsonkhan

**Comment by ahsonkhan** [comment]
![downloadmoreram](https://cloud.githubusercontent.com/assets/6527137/22850516/4a55b8ec-efbf-11e6-9b44-fb6918bdf059.png)


I do not get that error locally or in the CI (as long as I remain < 2 GB). 
Granted theses tests hog up 2+ GB of memory each.

int32.MaxValue = 2147483647 (i.e. 2^31 - 1)
char = 2 bytes
(2147483647*2 bytes)/1000/1000/1000 => 4.3 GB

int maxCharArraySize = int.MaxValue / 4 => A char array of size a bit over 1 GB.
int maxByteArraySize = int.MaxValue / 2 => A byte array of size a bit over 1 GB.

I am surprised you have both tests failing. The intention was to try and create an input span of length int32.MaxValue but that resulted in size > 2GB.
I would think that < 2 GB is fine. **If not, we could disable (or maybe even remove) the TestEncodingInputBufferMaxSize() and TestEncodingOutputBufferMaxSize() tests. Given how memory intensive they are, it would make sense to remove them. If you have 5+ GB to spare on your machine, you wouldn't have this issue.**

**Comment by benaadams** [comment]
>  If you have 5+ GB to spare on your machine, you wouldn't have this issue.

Lol - Can you do an "outerloop" type thing like coreclr/corefx?

**Comment by ahsonkhan** [comment]
> Lol - Can you do an "outerloop" type thing like coreclr/corefx?

I couldn't really figure out how to do that. Can you link me to place where I can see a sample?
Is [this](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/Span/Clear.cs#L254) what you are suggesting?

**Comment by benaadams** [comment]
I mean keep the tests, but only run them when specifically requested. Alas, not sure how it works, think its a dotnet bot thing.

**Comment by ahsonkhan** [comment]
PR #1212 - Tests removed

**Comment by Petermarcu** [comment]
Corefx uses attributes on the tests to mark them as outer loop and then you can ask dotnetbot to test with those set of tests. These types of tests are perfect cases for that.

**Comment by ahsonkhan** [comment]
> 

I see, like [this](https://github.com/dotnet/corefxlab/blob/master/tests/System.Text.Primitives.Tests/Encoding/PerformanceTests.cs#L19)?
```C#
...
[Trait("category", "performance")] 
[Trait("category", "outerloop")] 
public class Utf8StringPerformanceTests 
...
```

**Comment by Petermarcu** [comment]
Yeah and your device runs need to opt out of that by default while ci would run them, or just merge commits in ci.

**Comment by Petermarcu** [comment]
Device was supposed to be dev.

**Comment by KrzysztofCwalina** [comment]
This was moved to outerloop and then to corefx when we productized Utf8Parser/Formatter.

**Comment by ahsonkhan** [comment]
For clarification: The particular tests that this issue was about got removed, but other tests were moved to outerloop/corefx.

> PR #1212 - Tests removed
