### ISSUE TITLE
System.IO.Pipelines Unhandled exception on threadpool

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1216]
When writing an adapter for Kestrel (not the pipeline version of kestrel) it seems that when calling

ReadAsync() on a connection that is then closed with no more data I get an exception that I cannot catch that brings down the entire Kestrel process

![kestrel crash](https://cloud.githubusercontent.com/assets/16406969/22940819/16bf6004-f2db-11e6-86cb-733a703d3beb.gif)

The code is at

[Sample Server](https://github.com/Drawaes/Leto/tree/master/samples/SampleASPNetServer)
[Code that blows](https://github.com/Drawaes/Leto/blob/master/src/Leto.Tls13/SecurePipelineConnection.cs#L155)

This pipeline is actually the stream coming from Kestrel that should be encrypted and then output

**Comment by Drawaes** [comment]
![Stack Trace](https://files.gitter.im/dotnet/corefxlab/HyOo/blob)

**Comment by davidfowl** [comment]
What does this have to do with pipelines?

**Comment by Drawaes** [comment]
It only seems to blow when using pipelines readasync

**Comment by davidfowl** [comment]
Ah, is this the Stream wrapper?

**Comment by benaadams** [comment]
PipeFactory.ExecuteCopyToAsync is throwing exception (connection died) into the threadpool; trashing the process; not sure how it gets to the threadpool though 😄

**Comment by davidfowl** [comment]
async void 😄

**Comment by benaadams** [comment]
I won't say anything... 🙊

**Comment by Drawaes** [comment]
In my code? I have a try catch all around... And I tried with async task and async void... anyway not critical thought you might want to know cause it nukes the process

**Comment by benaadams** [comment]
You can't catch methods that are async void... and if they let an exception escape; by design, they crash the process.

**Comment by Drawaes** [comment]
I know... I thought it was a comment on my async void for my loop

**Comment by Drawaes** [comment]
Fixed and merged
