### ISSUE TITLE
IBufferPool Lease behavior when requesting too large size

### ISSUE THREAD

**Issue by tmds** [dotnet/corefxlab#1230]
The MemoryPool IBufferPool.Lease throws when requesting a size which is too large. The IBufferPool interface offers no way of figuring out what too large is.

A boolean could be added to Lease which specifies if the requested size must be ensured. When set to false, the method is allowed to return less than the requested memory. When set to true, it would behave as-is.

```
OwnedMemory<byte> Lease(int size, bool ensure);
```

**Comment by KodrAus** [comment]
Hmm, I wouldn't want a lease to return _less_ than I ask for. If the pool can't fulfill the memory requirements in a single lease I think it should either give me a useful return type so I can handle it without resorting to a `catch` block (maybe by allocating outside the pool), or give me multiple blocks.

**Comment by tmds** [comment]
> Hmm, I wouldn't want a lease to return less than I ask for.

It depends on the use-case.
Setting ensure to false says: it is acceptable to return less.

> If the pool can't fulfill the memory requirements in a single lease I think it should either give me a useful return type so I can handle it without resorting to a catch block (maybe by allocating outside the pool), or give me multiple blocks.

It is possible to allocate multiple blocks when by setting ensure to false.

Allocating outside the pool isn't always an option. An IBufferPool should be allowed to allocate from a specific region only.
Avoiding the exception could be implemented as an IBufferPool extension method:
```C#
OwnedMemory<byte> TryLease(this IBufferPool pool, int size)
{
  var mem = pool.Lease(size, ensure: false);
  if (mem.Length < size)
  {
    mem.Dispose();
    return null;
  }
  return mem;
}
```

**Comment by tmds** [comment]
An interesting case is when there is no more memory.
Lease with ensure set to false could return null in that case. Returning a memory object with a zero length could result in subtle errors. For example, a socket receive operation on a zero length buffer can cause a 0 return which may then be interpreted as end-of-stream.

**Comment by KodrAus** [comment]
That makes sense, I'm starting to the benefit of letting protocols decide how strict they need to be.

**Comment by tmds** [comment]
Alternative that can throw when no memory is available:
```
OwnedMemory<byte> Lease(int desired, int fallback);
```
Examples:
```
Lease(1024, 0);    // return null when no memory is available
Lease(1024, 1);    // throws when no memory is available
Lease(1024, 1024); // at least 1024 bytes available or throws
```

**Comment by tmds** [comment]
After looking closer at the other classes. I think memory allocations are controlled by invoking WritableBuffer.Ensure. The parameter provided to the method should be the minimal contiguous length required.

To allocate a region of non contiguous buffers for writing, Advance with the remaining size of the current Memory.
