### ISSUE TITLE
WritableBuffer: add support for non-contiguous Write

### ISSUE THREAD

**Issue by tmds** [dotnet/corefxlab#1233]
The WSARecvFrom/recvmsg calls support receiving to a non-contiguous memory region.

I don't think the WritableBuffer supports allocating for such operations.

I.e. doing something like:
```C#
int allocated = 0;
while (allocated < needed)
{
   allocated += writableBuffer.Length;
   buffers.Add(writableBuffer.Memory);
   if (allocated < needed)
   {
       // adds a new segment available for writing at end of write head list
       // doesn't update the writeHead
       // Writable.Memory points to new segment
       writableBuffer.AllocSegment();
   }
}

int received = recvmsg(buffers);

// crosses segments
// updates writeHead
// writeHead.Next = null, Allocated segments after writeHead are Disposed
// Writable.Memory points to writeHead
writableBuffer.AdvanceWriter(received);
```

Ensure and Append should throw InvalidOperationException when writeHead.Next != null.

**Comment by tmds** [comment]
@davidfowl makes sense?

**Comment by davidfowl** [comment]
Hmm, no this doesn't work today. I need to think about it a bit.

**Comment by tmds** [comment]
The ReaderBuffer non-contiguous read:
```C#
foreach (var memory in readableBuffer)
{
    buffers.Add(memory);
}
int sent = sendmsg(buffers);
reader.Advance(...);
```

@davidfowl does this look okay? What would be a good way to calculate the argument for the Advance call?

**Comment by tmds** [comment]
@davidfowl any thoughts so far?

**Comment by davidfowl** [comment]
Sorry dude, I'm heads down on getting back the kestrel perf right now. Haven't had enough free time recently to think about this.

**Comment by tmds** [comment]
@davidfowl can I send a PR for this?

This is what I have in mind:
Add a `BufferSegment _readTail` to `Pipe`.
The current behavior would be `_readTail=_readHead`.
`AllocSegment` would allocate at the `_readTail` and return the `Memory`.
There are some debug asserts for `_readHead.Next==null`, these would become: `if (_readHead!=_readTail) throw InvalidOperation(...)`.
`Advance` would cross `BufferSegments`, and remaining `BufferSegments` would be `Disposed`.

**Comment by davidfowl** [comment]
Nope, it's just not critical right now and I'd rather not churn something this fundamental. I promise I'll spend some time understanding how important this is so I can give feedback. Right now I'm in the process of cutting back all unnecessary APIs from pipelines that aren't used in mainline scenarios.

**Comment by davidfowl** [comment]
@tmds we can discuss it in https://gitter.im/dotnet/corefxlab

**Comment by davidfowl** [comment]
So you want to be able to allocate more than a segment before you write right? I'm not a fan of the AllocSegment thing. Also if we do this, we don't have a way to represent a multi segment writable buffer. I guess you could convert to a `ReadableBuffer` in order to write.

**Comment by tmds** [comment]
Tried to write a benchmark to see the difference in performance: https://gist.github.com/tmds/4b1d60ec3d1ba6c814bd64410eb5ff79.

Time it takes to receive 2MB using NumberOfBuffers in recvmsg:
```
 Method | NumberOfBuffers |        Mean |     StdDev |
------- |---------------- |------------ |----------- |
     Do |               1 | 744.1416 us |  7.4406 us |
     Do |               2 | 604.0534 us | 10.7491 us |
     Do |               3 | 578.8301 us | 22.8482 us |
     Do |               4 | 560.0194 us | 15.8505 us |
     Do |              16 | 533.2147 us | 22.3705 us |
     Do |              32 | 533.4341 us |  8.3006 us |
     Do |              64 | 592.2064 us | 14.3578 us |
```

CC @Drawaes

**Comment by tmds** [comment]
After discussing with @Drawaes this was a list of scenarios where larger package revival is expected:
- ssl
- http2
- http 1.1 pipelining
- other protocols which are receive heavier

I understand these are not high priority scenarios to optimize for.

I've looked at the cases where recvmsg would return a lower number of bytes. I believe when that happens it is acceptable to call it again until it delivered all promised bytes. So I can allocate Memory upfront using Ensure&Advance.

**Comment by Drawaes** [comment]
#1032 might feed into this because in a size prefixed scenario like tls you know the expected size before any processing should be done

**Comment by tmds** [comment]
Alternative API:
```
IPipeWriter.AllocBuffer() : OwnedBuffer<byte>
WritableBuffer.Append(OwnedBuffer<byte>, offset, length);
```

This API is simpler since it isn't adding state to the WritableBuffer and more flexible. The user needs to handle the refcounting.

**Comment by tmds** [comment]
Since allocations can be done from a separate MemoryPool,
It seems the only thing missing to enable this scenario is the ability to add an OwnedBuffer to a WritableBuffer.
```
WritableBuffer.Append(OwnedBuffer<byte>, offset, length);
```

@davidfowl thoughts?

**Comment by davidfowl** [comment]
I don't think anything needs to be added to the existing APIs to support this. If we did want to support this (and I'm not sure we do), I think we would tweak `Advance` and alloc to support multiple buffers. One problem is that the pool cannot indicate what buffer size it can support so  its hard to know what to pass to lease. I guess if the pool never throws, then the caller can lease until the desired amount is allocated.

```
// Reserve 16K
var buffer = pipe.Alloc(4096 * 4);
// Write into 2K
buffer.Advance(2048);
buffer.FlushAsync();

// This would effectively n00p because we previously reserved 16K but didn't use all of it.
var next = pipe.Alloc(100);
```

```
// Reserve 8K
var buffer = pipe.Alloc(2 * 4096);
// Write 5K
buffer.Advance(5 * 1024);
buffer.FlushAsync();
```

We also need to support Advancing across multiple buffers.

It would require storing another pointer to know when it needs to allocate a new buffer. Today pipe uses the commitHead as the extent of the writer.

**Comment by tmds** [comment]
To do the //Write into 2k you'd call AsReadableBuffer to get the Buffers?

The Writable.Append(OwnedBuffer) allows for more scenarios.
- You can do recmsg with a fixed number of buffers independent of the number of available bytes. Only buffers which are filled are added to the pipeline. The rest can go back to the pool.
- Some network APIs allow multiple buffers to be provided but won't fill them up completely. I think RIOReceive is like this.

**Comment by davidfowl** [comment]
> To do the //Write into 2k you'd call AsReadableBuffer to get the Buffers?

We would need to expose them as a `ReadableBuffer` yes.

> The Writable.Append(OwnedBuffer) allows for more scenarios.

I don't like the fact that the buffer comes from an arbitrary place. Though I guess if it's reference place, I guess though if you don't dispose it it's your problem and you will leak memory. Today we try to avoid exposing anything from pipelines to avoid this. You call Alloc and Advance and the ref count is incremented and decremented as needed.

This is a power user API, and it's very close to Append(`ReadableBuffer`), now I'm wondering if that can't just be used for this (if we made it easier to make a `ReadableBuffer`).

The API I propose above keeps the model of the pipe in place and doesn't expose users to `OwnedBuffer<byte>` or reference counting or the `BufferPool`.

**Comment by tmds** [comment]
> I don't like the fact that the buffer comes from an arbitrary place.

I would also prefer to allocate it from the PipeWriter.

> This is a power user API, and it's very close to Append(ReadableBuffer), now I'm wondering if that can't just be used for this (if we made it easier to make a ReadableBuffer).

I looked at this and it seems it would only be adding overhead compared to WritableBuffer.Append.

> The API I propose above keeps the model of the pipe in place and doesn't expose users to OwnedBuffer<byte> or reference counting or the BufferPool.

That is what you want in the first scenario. Buffers that exist out of the pipeline. I looked at this shortly and it seems the user would have to either Append it to the Writer or call Dispose. He wouldn't have to increment/decrement the refcount.

**Comment by davidfowl** [comment]
> That is what you want in the first scenario. Buffers that exist out of the pipeline. I looked at this shortly and it seems the user would have to either Append it to the Writer or call Dispose. He wouldn't have to increment/decrement the refcount.

I don't agree, that's just the solution you proposed. What I proposed achieves the same without breaking the model. The moment the user has to get an `OwnedBuffer<T>`, they have to know where to get it from. The pool isn't exposed directly from the `PipeFactory` so you would need a reference to it to even get an `OwnedBuffer<T>`.

**Comment by tmds** [comment]
When are the buffers disposed that weren't used in the advance?

**Comment by tmds** [comment]
If you alloc 5 buffers and fill 1,5 (eg recvmsg). What happens to the 3 that weren't used?

**Comment by davidfowl** [comment]
They'll get cleaned up when both the reader and writer go away (in dispose).

**Comment by tmds** [comment]
> They'll get cleaned up when both the reader and writer go away (in dispose).

This may leave much memory unused. Especially if the reader is providing a lot of buffers to recvmsg. It would be nice if those buffers were disposed on Advance or FlushAsync. Or with the alternative API, the user can Append them if they are filled, Dispose them if they are not used or keep them for the next call to recvmsg (which may be for another socket).

**Comment by benaadams** [comment]
Its up to the source pipe which knows its protocol what its doing with the unused buffers; presumably you'd add them back to the next receive call? Don't see how it interacts with Advance or Flush

**Comment by davidfowl** [comment]
> This may leave much memory unused. Especially if the reader is providing a lot of buffers to recvmsg. It would be nice if those buffers were disposed on Advance or FlushAsync. Or with the alternative API, the user can Append them if they are filled, Dispose them if they are not used or keep them for the next call to recvmsg (which may be for another socket).

Too bad? When you allocate another 5K, it would just allocate whatever was unused from the previous alloc. It's only wasted if you never write again.

**Comment by tmds** [comment]
> Too bad?

If you decide so.

> It's only wasted if you never write again.

This may be the case. Why waste this memory pending on each connection if there is no indication it will ever be written.

**Comment by davidfowl** [comment]
To preserve a clean programming model that doesn't expose users to `OwnedBuffer<T>`.

**Comment by tmds** [comment]
The writer api is geared to getting formatted data from the application to the network. The other way around is less supported, network APIs are based on buffers.

**Comment by benaadams** [comment]
@tmat not sure I understand; the source has control of their buffers (e.g. [SocketConnection : IPipeConnection](https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines.Networking.Sockets/SocketConnection.cs)).

Why should these empty buffers be moving upstream out of the source? You'd just be either bloating memory use or causing extra memory pool contention.

**Comment by tmds** [comment]
@benaadams The goal is to call recvmsg with more than 1 buffer to return more data with a single system call. The amount of buffers may be fixed (e.g. 5 buffers offering 20k mem) or based on the available bytes on the socket.
recvmsg isn't garanteed to fill all the buffers, so the unused buffers either remain allocated and unused on the pipe(1). Or the producer of the pipe needs to dispose them(2). Or he can use him for another recv operation(3). This other recv call may be for a different socket, the unused buffers are stored at the eventloop and not per connection. The last option is the nicest as it doesn't bloat memory like (1) and doesn't cause extra contention like (2).

**Comment by benaadams** [comment]
But what's that got to do with the pipe? That's all under your control as the writer of the event loop and receive interface/translation (from socket to pipe)

**Comment by benaadams** [comment]
Oh I think I kinda get what you are talking about... You mean when the socket "completes" with no more receive data; you want to get the uncommitted chain of buffers `.Next -> .Next -> .Next` and put it somewhere else?

**Comment by benaadams** [comment]
Oh I think I kinda get what you are talking about... You mean when the socket "completes" with no more receive data; you want to get the uncommitted chain of buffers `.Next -> .Next -> .Next` and put it somewhere else? (because you are over allocating up front)

**Comment by benaadams** [comment]
Oh I think I kinda get what you are talking about... You mean when the socket "completes" with no more receive data; you want to get the uncommitted chain of buffers `.Next -> .Next -> .Next` and put it somewhere else? (because you are over allocating up front)

So "complete" of the source should dispose of any chained buffers that have not been committed?

**Comment by benaadams** [comment]
Whether option (2) is option (3) is just dependent on where the source of your memory pool is

**Comment by tmds** [comment]
> Oh I think I kinda get what you are talking about... You mean when the socket "completes" with no more receive data; you want to get the uncommitted chain of buffers .Next -> .Next -> .Next and put it somewhere else? (because you are over allocating up front)

Exactly.

> So "complete" of the source should dispose of any chained buffers that have not been committed?

Or alternatively, only the filled buffers are added to the pipeline.
```
var buffers = pool + pipe.AllocateBuffers(); // up to fixed amount/available
[used, unused] = recv(buffers);
pipe.Append(used);
pool.Add(unused);
```

> Whether option (2) is option (3) is just dependent on where the source of your memory pool is

Yes, a pool at socket level leads to unused buffers (same as 1) or contention (because of Dispose unused). At event loop level, you use the buffers for the next recv.

**Comment by benaadams** [comment]
> Or alternatively, only the filled buffers are added to the pipeline.

You are just going to stick them back in the next receive aren't you? It only applies on close, else why did you over allocate in the first place?

**Comment by tmds** [comment]
> You are just going to stick them back in the next receive aren't you? It only applies on close, else why did you over allocate in the first place?

Not sure what you mean by "it only applies on close". The next receive is for a different socket.
Allocating more than 1 buffer is to be able to receive more than 4K.

**Comment by benaadams** [comment]
> The next receive is for a different socket.

Ok so you are talking about non-blocking IO where the OS buffers then copies on call? Rather than async IO where it writes to your buffer then tells you when its ready?

**Comment by tmds** [comment]
> Ok so you are talking about non-blocking IO where the OS buffers then copies sync on call? Rather than async IO where it writes to your buffer then tells you when its ready?

Yes. The async operation is waiting for the socket to become readable. Once it is readable, perform a receive with buffers. There are no in-flight buffers while waiting for the socket to become readable.

> So allocate some more buffers to keep the chain long; then add the unfinshed ones plus your new ones back to receive.

I don't understand.

**Comment by benaadams** [comment]
So in your event loop you'd probably want be creating `ReadableBuffer`s per socket/pipe with something like:
```csharp
public struct ReadableBuffer 
{
    // ...
    ReadableBuffer Create(OwnedBuffer<byte> data, int offset, int length) { ... }
    ReadableBuffer Append(OwnedBuffer<byte> data, int offset, int length) { ... }
    // ...
```
Then you'd use ``WritableBuffer.Append(ReadableBuffer buffer))``

**Comment by benaadams** [comment]
Well maybe a "WritableOwnedBuffer" that has a `public ReadableBuffer AsReadableBuffer()` instead of making `ReadableBuffer` writable

**Comment by davidfowl** [comment]
I don't see how you get the buffers back after you append them. The pipe is still going to be holding onto them even if they are appended and remain unused. You can't use those buffers for another receive operation anyways because the pipe *is* per connection. It's the one managing memory on your behalf. This breaks the model (like I've been saying) so it's possible pipelines isn't for this scenario and you need something a bit lower that then copies the buffer into the pipe

**Comment by benaadams** [comment]
@davidfowl you can append `ReadableBuffer` to the pipe so just need a way of creating them from a sequence of `OwnedBuffer<byte>`s (e.g. where the append chains `BufferSegment`s together)

The pipe would still handle the disposal once they have been added to the pipe (and the'd get reused if appropriate as they are `OwnedBuffer<byte>` rather than raw arrays)

But deciding what to add to the pipe would happen outside by the source(s) and it would need to be getting stuff from the pool directly (and passing it to the unmanaged receive calls).

**Comment by benaadams** [comment]
i.e. you can create `ReadableBuffer`s from arrays; but that can only be GC'd arrays.

In fact all it would need is one method to enable this scenario
```csharp
public static ReadableBuffer Create(OwnedBuffer<byte>, int offset, int length)
```

**Comment by benaadams** [comment]
i.e. you can create `ReadableBuffer`s from arrays; but that can only be GC'd arrays.

In fact all it would need is one method to enable this scenario
```csharp
public static ReadableBuffer Create(OwnedBuffer<byte> data, int offset, int length)
```

Then you'd just loop though the used buffers
```
pipe.Append(ReadableBuffer.Create(usedBuffer, 0, usedLength));
```

**Comment by davidfowl** [comment]
Is the idea that pipe only ever gets perfectly filled memory?  What does the overall code look like?

**Comment by benaadams** [comment]
Psudeo code like
```csharp
void Receive(List<PipeSocket> activatedSockets)
{
    var buffers = new Queue<OwnedBuffer<byte>>();

    foreach(var activatedSocket in activatedSockets)
    {
        // Make sure 5 buffers are available
        while(buffers.Count < 5)
        {
            buffers.Enqueue(_pool.Rent());
        }
        
        var socket = activatedSocket.Socket;
        var dataReceived = Receive(socket, buffers);
        
        while (dataReceived > 0)
        {
            var buffer = buffers.Dequeue();
            var dataLength = Math.Min(buffer.Length, dataReceived);
            dataReceived -= dataLength;
            
            activatedSocket.Pipe.Append(ReadableBuffer.Create(buffer, 0, dataLength));
        }
    }
    
    // Return unused buffers
    while(buffers.Count > 0)
    {
        _pool.Return(buffers.Dequeue());
    }
}
```

**Comment by davidfowl** [comment]
That looks fine. A few comments:

I'm assuming this ups the ref count of the buffer to 2.
```C#
activatedSocket.Pipe.Append(ReadableBuffer.Create(buffer, 0, dataLength));
```

You can't return the buffers to the pool here. This code should decrement the ref count but not call return (there is no return anyways).

```C#
// Return unused buffers
    while (buffers.Count > 0)
    {
        var buffer = buffers.Dequeue();
        buffer.Release();
        if (!buffer.HasOutstandingReferences)
        {
             buffer.Dispose();
        }
    }
```

**Comment by benaadams** [comment]
K, updated code; with feedback and the Queue was bugging me as it would mean the Receive call would enumerate.

**Comment by tmds** [comment]
> But something like that anyway?

Yes

The bufferpool can live for the duration of the PollThread. The overall code is something like:

```
PollThread()
{
   while (running)
   {
        events = WaitForEvents(sockets);
        foreach (readableSocket in events.readableSockets)
        {
            readableSocket.CompleteReadable(); // completes await Readable
        }
   }
   foreach (buffer in _localPool)
   {
        // return unused buffers to pool
   }
}

ReadFromSocket(socket, writer)
{
   while (!complete)
   {
      await Readable(socket); // completed by PollThread
      RefillLocalPool(_localPool, writer.Pool); // fill _localPool from PipeFactory pool
      [used, unused] = recvmsg(_localPool);
      _localPool = unused;
      var wb = writer.Alloc();
      foreach (buffer in filled)
         wb.Append(used); // pipe owns these buffers
      await wb.FlushAsync();
   }
}
```

**Comment by davidfowl** [comment]
```C#
RefillLocalPool(_localPool, writer.Pool); // fill _localPool from PipeFactory pool
```

That's not a thing, but you can control both pools since you can create the pipe factory.

```C#
foreach (buffer in _localPool)
   {
        // return unused buffers to pool
   }
```

The ones that have nothing written into it yea, that's doable.

**Comment by tmds** [comment]
> That's not a thing, but you can control both pools since you can create the pipe factory.

With the design currently described in the Kestrel repo, the Transport doesn't get hold of the PipeFactory or it's MemoryPool.

**Comment by davidfowl** [comment]
It will need to. It came up in the PR

**Comment by tmds** [comment]
@benaadams @davidfowl 
What is preferable?
```
WritableBuffer.Append(ReadableBuffer.Create(ownedBuffer, offset, length));
```
or
```
WritableBuffer.Append(ownedBuffer, offset, length);
```

**Comment by benaadams** [comment]
The first. The second has the wrong connotations and exposes the uncommon api on the common user api.

**Comment by tmds** [comment]
Implemented in https://github.com/dotnet/corefxlab/pull/1386

Thanks @davidfowl @benaadams
