### ISSUE TITLE
System.IO.PipeLines.Pipe confusion with System.IO.Pipes

### ISSUE THREAD

**Issue by matthewDDennis** [dotnet/corefxlab#1247]
Another case of different things with similar names the may come back to bite you.

**Comment by davidfowl** [comment]
Yea, I know. Naming is hard

**Comment by muratg** [comment]
@ahsonkhan what's the plan with this for 2.0? Are we renaming things?

cc @joshfree

**Comment by ahsonkhan** [comment]
I don't know if we want to rename things for 2.0... @davidfowl, is this issue valid? If so, should we target this fix for 2.1?

**Comment by muratg** [comment]
We'll do this as a part of a larger rename. Closing.
