### ISSUE TITLE
Pipeline SocketConnect constructor does not use passed in IPipeFactory

### ISSUE THREAD

**Issue by matthewDDennis** [dotnet/corefxlab#1248]
I'm working on a Redis Client and thought I would try out the System.IO.Pipeline package.
I'm liking what I see, but wish there was more documentation.

Reading the source code I found that the SocketConnect does not use the passed in PipeFactory if not null.  The offending lines are indicated with >>>.

~~~ c#
        internal SocketConnection(Socket socket, PipeFactory factory)
        {
            socket.NoDelay = true;
            _socket = socket;
            if (factory == null)
            {
                _ownsFactory = true;
                factory = new PipeFactory();
            }
            _factory = factory;

            // TODO: Make this configurable
            // Dispatch to avoid deadlocks
>>>     _input = PipeFactory.Create(new PipeOptions
            {
                ReaderScheduler = TaskRunScheduler.Default,
                WriterScheduler = TaskRunScheduler.Default
            });
>>>      _output = PipeFactory.Create(new PipeOptions
            {
                ReaderScheduler = TaskRunScheduler.Default,
                WriterScheduler = TaskRunScheduler.Default
            });
...
~~~

these should be
~~~ c#
    _input = _factory.Create(...
    _output = _factory.Create(...
~~~

**Comment by davidfowl** [comment]
Actually it does use the passed in Factory. https://github.com/dotnet/corefxlab/blob/dfe509f570bcd72d8afc211daff5175ac6cf0865/src/System.IO.Pipelines.Networking.Sockets/SocketConnection.cs#L115

**Comment by matthewDDennis** [comment]
Yeah, but damn that looked like a static method on the PipeFactory class.  Might want to change the property name to prevent confusion, especially since its private.

Why use a Property when a readonly field is faster?

**Comment by matthewDDennis** [comment]
Moreover, _factory is only used in the contstructor, so _factory only needs to be set if the constructor creates the PipeFactory so it can be disposed. _ownsFactory is now redundant as _factory is only non-null if the Socket connection owns the factory.
The dispose become
~~~ c#
_factory?.Dispose();
_factory = null;
~~~

**Comment by muratg** [comment]
@matthewDDennis please file another issue for property vs readonly field suggestion. 

Closing this one.
