### ISSUE TITLE
Consider adding Span.TryWrite that takes an index

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1253]
From PR #1251 where
```C#
public static bool TryWrite<[Primitive]T>(this Span<byte> slice, T value)
```
was added.

Is it useful to have an overload which writes to an index other than the start of the span?

https://github.com/dotnet/corefxlab/pull/1251#discussion_r103069995

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, do you still feel we need this?

**Comment by ahsonkhan** [comment]
I ran some rudimentary performance tests and it looks like we could get some perf wins (20%+) if we do provide an overload that takes in an index rather than slicing for all the [BinaryPrimitives](https://github.com/dotnet/corefx/blob/40cbd5636851093309b841db4d53af369b7ef1c6/src/System.Memory/ref/System.Memory.cs#L265-L366) APIs.

```C#
[MethodImpl(MethodImplOptions.NoInlining)]
public static void TryWriteSlice(Span<byte> buffer)
{
    while (buffer.Length > 0)
    {
        TryWriteInt16BigEndian(buffer, 5);
        buffer = buffer.Slice(2);
    }
}

[MethodImpl(MethodImplOptions.NoInlining)]
public static void TryWriteIndex(Span<byte> buffer)
{
    for (int i = 0; i < buffer.Length; i += 2)
    {
        TryWriteInt16BigEndian(buffer, i, 5);
    }
}
```
TryWriteSlice (red) vs. TryWriteIndex (green)
![image](https://user-images.githubusercontent.com/6527137/37630946-8938241a-2ba4-11e8-928b-89427d615ec7.png)

The new overload would have single change:
https://github.com/dotnet/corefx/blob/40cbd5636851093309b841db4d53af369b7ef1c6/src/System.Memory/src/System/Buffers/Binary/Writer.cs#L64
```C#
//From:
Unsafe.WriteUnaligned<T>(ref MemoryMarshal.GetReference(buffer), value);
//To:
Unsafe.WriteUnaligned<T>(ref Unsafe.Add(ref MemoryMarshal.GetReference(buffer), index), value);
```

![image](https://user-images.githubusercontent.com/6527137/37631172-b56783d6-2ba5-11e8-8653-210e9fef88cc.png)


cc @jkotas

**Comment by jkotas** [comment]
> The new overload would have single change

What guarantees that the index is valid?

**Comment by jkotas** [comment]
Also, sorting out the security issues for the generic BinaryPrimitives APIs is higher priority than this: https://github.com/dotnet/corefx/issues/27094 . That's something that needs to be done for 2.1.

Performance tweaks like this are for post-2.1.

**Comment by ahsonkhan** [comment]
> What guarantees that the index is valid?

Ah, yes, of course, we would need to do argument validation as well.
```C#
if ((uint)index > (uint)buffer.Length) // throw;
```

But that doesn't have too much affect on the perf results.

> That's something that needs to be done for 2.1. Performance tweaks like this are for post-2.1.

Yes, of course.

**Comment by jkotas** [comment]
> `if ((uint)index > (uint)buffer.Length) // throw;`

This is not the correct way to validate the `index` is valid.

**Comment by ahsonkhan** [comment]
> This is not the correct way to validate the `index` is valid.

Yep, that did it. If we do proper validation, we no longer see the performance difference.

`if ((uint)index > (buffer.Length - Unsafe.SizeOf<T>()))`

Closing this issue. Thanks!

**Comment by ahsonkhan** [comment]
In fact, the disassembly gets larger (along with possible perf regression):
![image](https://user-images.githubusercontent.com/6527137/37632133-ea077048-2ba9-11e8-803c-941ec5696dcd.png)
