### ISSUE TITLE
IOutput/BytesReader API thoughts.

### ISSUE THREAD

**Issue by anurse** [dotnet/corefxlab#1264]
## `IOutput` should work well for raw binary data.

There are some nice helpers for `IOutput` that append values after encoding as text. We should also provide binary equivalents. Possibly just by having a `TextEncoder.Raw` value or something?

## What happens in `IOutput` when we run out of space

`Append` methods tend to behave by doing `while(!TryAppend(...)) Enlarge()`. What happens when we run out of space? Should `Enlarge` just throw? Or could `Enlarge` fail more gracefully by either just not increasing the size of the buffer, or returning a boolean indicating if the enlarge succeeded (both of which the caller could detect)

## `IInput` abstraction

I think it might be a good idea to introduce an `IInput` that matches with `IOutput` and provides the API currently provided by `BytesReader`. We can still use `BytesReader` as a `struct` by accepting it generically (`TryParse<T>(this T self, ...) where T: IInput`), assuming I'm remembering how generics work correctly. If we had this abstraction, in theory, all the parsers could use this, so they can handle both single-span and multi-span inputs. I also do think there can still be value in a reference-type version of `BytesReader`, since there are a lot of cases where you want to pass the reader into some helper which will read some data and advance, but you don't want to/can't use `ref` (extension methods in particular; we could really use `ref`-based extension methods ;)). Incurring the one-time boxing copy (and the heap pressure) may sometimes be a better performance decision. (@benaadams just involuntarily cringed the moment I wrote this ;P)

## `BytesReader` lookahead

When reading a single byte, `BytesReader` is able to basically guarantee that `Unread` will contain the data. However, when reading a multi-byte value, you might run out of data part way through the value. More stateful parsers can handle this by buffering what they've seen so far and returning control to the reader, but we don't want everything to be that stateful (especially not primitive parsers). Ideally, you want a way to check if there's enough data to parse a value. `ReadableBuffer` has a `Length` which is calculated once and cached. I think `BytesReader` will need something similar. Another way to handle this would be a `TryReadBytes(int count)` which simply returns `false` and does not advance unless it can gather all the requested data.

**Comment by KrzysztofCwalina** [comment]
Great feedback. Thanks! 
Are any of these blocking?  

ReadOnlyBytes need to be a struct. It's used as a primitive representation of segmented memory.

**Comment by anurse** [comment]
Nothing is blocking yet. The `ReadOnlyBytes` struct thing is something we need to review in our code base first right now. @davidfowl was mentioning that we're seeing an impact from copying large structs around and may actually shift a few things to be boxed, and interface like `IInput` (used via Generics) might help will enabling varied solutions like this.

**Comment by benaadams** [comment]
Can make some structs smaller without going full boxing

**Comment by anurse** [comment]
I think this now covers the main feedback I have from using these APIs. ping @davidfowl @KrzysztofCwalina

**Comment by muratg** [comment]
Closing this one.  @anurse if you're still interested in this, could you file a bug in CoreFX repo?
