### ISSUE TITLE
String to ASCII Bytes Encoder (Span)

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#1269]
Implementation [here](https://github.com/benaadams/coreclr/blob/ef35f8f1749ff08e460ae353222c034d86acdc0b/src/mscorlib/src/System/Text/EncodingForwarder.cs#L181-L329) that can be adapted (was merged to coreclr; but were some behaviour issues on non-ascii failure conditions for XML with Encoders, what exchange chars to use etc)

The implementation does the 7 bit check (i.e ASCII); however an additional 8-bit variant might be desirable also (where it checks is not 16 bit only).

**Comment by GrabYourPitchforks** [comment]
@benaadams What's the context for this? It seems like you're advocating turning a `Span<char>` (or `Vector<ushort>`) into a `Span<byte>` (`Vector<byte>`) while also checking for integer overflow at the same time. Does such logic belong as a first-class encoder type within the Framework?

**Comment by benaadams** [comment]
> It seems like you're advocating turning a Span<char> (or Vector<ushort>) into a Span<byte> (Vector<byte>) 

Didn't use `Vector<T>`; couldn't get the perf for narrowing https://github.com/dotnet/coreclr/issues/16474

Was advocating for a `ASCII.TryEncode(string, Span<byte>, out ...)` to go with a `UTF8.TryEncode(string, Span<byte>, out ...)` as there are some places that don't accept UTF8 so a UTF8-to-wire encoder is no good.

**Comment by benaadams** [comment]
Though think it would be part of `Encoding` as couldn't find Utf8 encoders anymore? Just saying Ascii needs some ❤️ too

**Comment by benaadams** [comment]
Probably more interesting than this is HTMLEncoding strings -> Utf8 wire format, which I have: [`WriteUtf8HtmlString<T>(ref this BufferWriter<T> buffer, string text)`](https://github.com/benaadams/FrameworkBenchmarks/blob/9d940f533c14130ab5b627b61ab142c90abfbac3/frameworks/CSharp/aspnetcore-mono/PlatformBenchmarks/Utilities/BufferExtensionsText.cs)

As you currently have to `string -> htmlencode -> string -> utf8encode -> bytes` as well as being more conservative in htmlencoding (as it doesn't know what the end encoding can support); you get an extra string allocation from the intermediate htmlencoded string.

**Comment by benaadams** [comment]
Probably more interesting than this is HTMLEncoding strings -> Utf8 wire format, which I have: [`WriteUtf8HtmlString<T>(ref this BufferWriter<T> buffer, string text)`](https://github.com/benaadams/FrameworkBenchmarks/blob/9d940f533c14130ab5b627b61ab142c90abfbac3/frameworks/CSharp/aspnetcore-mono/PlatformBenchmarks/Utilities/BufferExtensionsText.cs) and uses an updated `TryEncodeAsciiCharsToBytes`

As you currently have to `string -> htmlencode -> string -> utf8encode -> bytes` as well as being more conservative in htmlencoding (as it doesn't know what the end encoding can support); you get an extra string allocation from the intermediate htmlencoded string.

**Comment by GrabYourPitchforks** [comment]
Adding UTF8 support for all of the web encoders is definitely on the radar. I have a list of other minor perf improvements I want to make at the same time.
