### ISSUE TITLE
Add a script to PerfHarness that runs benchmarks on high priority for consistent results

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1284]
The idea is to have something like below but that enables the caller to pass all arguments to dotnet.exe passed to it from the command line (such as assembly name, run -c Release, etc).

We want the benchmarks to run on a dedicated core with high priority to enable consistency in the results.

Discussed in PR #1278

```bat
@echo off

cls
for /l %%i in (1,1,10) do (
  echo %%i: START "title" /B /WAIT /HIGH /AFFINITY 0x2 dotnet.exe run -c Release -- --assembly System.Slices.Tests --perf:typenames System.Slices.Tests.PerformanceTests
  START "title" /B /WAIT /HIGH /AFFINITY 0x2 dotnet.exe run -c Release -- --assembly System.Slices.Tests --perf:typenames System.Slices.Tests.PerformanceTests
)
```

**Comment by KrzysztofCwalina** [comment]
Some benchmarks. There are others, like the pipeline multithreaded benchmarks, that we don't want to affinitize. i.e. this needs to be an option.

**Comment by ahsonkhan** [comment]
Since we are now using BDN, this issue is no longer relevant.

cc @adamsitnik

**Comment by adamsitnik** [comment]
BDN enforces this by default, every process it starts runs as high priority.
