### ISSUE TITLE
GCHandle like API for pinning span/memory

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1287]
Today we have TryGetPointer but it's not safe to use unless you're using native memory or you pinned the underlying buffer. A safer API for pinning and unpinned outside of lexical scope and across async calls is needed. Maybe this should only be on memory and not span (though there might be cases for the latter).

/cc @jkotas @KrzysztofCwalina @mjp41

**Comment by jkotas** [comment]
I think it should be something like:

```
struct PinnedMemoryHandle
{
     void Alloc<T>(Memory<T> memory);
     void Free();
     void * PinnedPointer { get; }
}
```

The usage pattern is same as GCHandle.

**Comment by mjp41** [comment]
I like an API like @jkotas is proposing.  I think it makes sense, and helps me understand the correct usage of TryGetPointer.  Does this mean that TryGetArray would go away, and we would do the relevant GCHandle for pinning in Memory?

**Comment by mjp41** [comment]
Would it be nicer for `Memory` to return one of these structs?

```csharp
PinnedMemoryHandle Memory<T>.GetPinnedMemoryHandle()

struct PinnedMemoryHandle {
    void Free();
    IntPtr GetPinnedPtr()
}
```

Possibly, using IDisposable?

**Comment by Drawaes** [comment]
I think it should support IDisposable like

https://github.com/Drawaes/Leto/blob/master/src/Leto.Tls13/Internal/PointerFromMemory.cs

But obviously natively

**Comment by jkotas** [comment]
These are "no copy" structs holding unmanaged resource. You have to be careful about not creating multiple copies,  disposing one copy, and still accessing other copy. It is different from the usual IDispose contract where calling dispose multiple times is fine, and it does not matter on which copy.

The shape of GCHandle APIs encourages the right behavior of never creating copies, and makes it clear to people that it is not an ordinary IDisposable type. 

So this is an API design question whether we like GCHandle prior art for this, or whether we would prefer something else.

**Comment by jkotas** [comment]
> https://github.com/Drawaes/Leto/blob/master/src/Leto.Tls13/Internal/PointerFromMemory.cs

This is class. I agree that if this was a class, the IDisposable would be fine for it. However, my proposal is a struct to avoid heap allocations.

**Comment by Drawaes** [comment]
My problem with the gchandle approach is the "clutter" in the code.. having to try finally vs a using. I understand the issues around dual release and maybe They are insurmountable but I think the using block is a neater approach. I think there is already a solid foundation of if you access an already disposed item you are likely to het an exception.

**Comment by Drawaes** [comment]
I know that is a class it's more as an example of the API that would be nice... it's also able to reset so u can pool

**Comment by Drawaes** [comment]
The question is what does that class being proposed give you over an extension method that returns a GCHandle?

**Comment by mjp41** [comment]
@Drawaes `TryGetPointer` as it is currently being used is also for unmanaged memory, this would give a way to hook into preventing that unmanaged memory going away.

So for the use case @davidfowl pointed me at, the API is often used across an Async call, so the `using` syntax is less important. 

[UvWriteReq](https://github.com/dotnet/corefxlab/blob/cd413fcfb1c63e26de2d7bf70969c8d5df3797e3/src/System.IO.Pipelines.Networking.Libuv/Interop/UvWriteReq.cs#L103

Ideally, the call back could then free the handles associated with `TryGetPointer` (that don't currently exist).

**Comment by Drawaes** [comment]
Okay that is different to the use case I had in mind which is more like 

https://github.com/Drawaes/Leto/blob/master/src/Leto.Tls13/BulkCipher/OpenSsl11/AeadBulkCipherInstance.cs#L115

**Comment by davidfowl** [comment]
That code would change to look like this:

```C#
foreach (var memory in buffer.AsReadableBuffer())
{
    if (memory.Length == 0)
    {
        continue;
    }
    var span = memory.Span;
    var length = span.Length;
    fixed (byte* ptr = &span.DangersGetPinnableReference())
    {
        var inPtr = (IntPtr)ptr;
        ThrowOnError(EVP_CipherUpdate(_ctx, inPtr, ref outLength, inPtr, length));
        buffer.Advance(outLength);
    }
}
```

**Comment by Drawaes** [comment]
In that case, ignore previous comments re the wait struct.

**Comment by davidfowl** [comment]
@pdeligia did this

**Comment by trampster** [comment]
#1290 only works on memory and the Create method is internal which means the only way to use it is through it's constructor which takes a pointer!  This means it does not allow the pinning of ether Span or Memory without unsafe.

**Comment by stephentoub** [comment]
> This means it does not allow the pinning of ether Span or Memory without unsafe.

Whether you're using a `void*` or an `IntPtr`, it's equally unsafe, it just happens that the latter doesn't require the C# `unsafe` keyword.

**Comment by trampster** [comment]
Yes, they are equally unsafe, however use of the unsafe keyword puts restrictions on where the code can run. Whereas IntPtr does not.

I've found that Memory<T> has a Pin() method which would do exactly what I need except I need it for Span.

Seeing as this issue says memory/span and the solution only does memory and not span. Then this issue was not actually resolved.

**Comment by stephentoub** [comment]
> Seeing as this issue says memory/span and the solution only does memory and not span. Then this issue was not actually solved.

You can directly pin a span, e.g.
```C#
fixed (byte* ptr = span) { … }
```
There's no need for any additional API to do so (you can also use its GetPinnableReference method directly and pin via the resulting ref, or MemoryMarshal.GetReference and do the same).  Memory can live on the heap, and thus you need a GCHandle-like API that allows for pinning it with a scope beyond that of the stack; that's not the case with span.

**Comment by trampster** [comment]
Yes but that code uses pointers, so requires the unsafe keyword, which restricts where the code can run.

**Comment by jkotas** [comment]
> unsafe keyword which means your code can only be used in full trust environment

Pointer-like operations with IntPtr were prohibited in partial trust environments as well.

Also, note that partial trust is not a thing with .NET anymore. It was never supported in .NET Core, and it was officially deprecated in .NET Framework as well: https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security-basics

**Comment by trampster** [comment]
Thank jkotas, 

What about mono/xamarin environments? If they are fine, then I'm OK with unsafe. 

If this is the case why do we still have compiler warnings about unsafe in dotnet core. Why do we still need to build with /unsafe etc if this makes no difference.

**Comment by jkotas** [comment]
> What about mono/xamarin environments?

Yes, they are fine.

> If this is the case why do we still have compiler warnings about unsafe in dotnet core. 

The unsafe `code is still less desirable than safe code. The compiler warnings, etc. make it less convenient to write unsafe code.

**Comment by trampster** [comment]
Good to know. Thanks for the patent replies.
