### ISSUE TITLE
Finalize API shape of SpanExtensionsLab and merge with SpanExtensions

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1292]
Merge the Span Extensions from corefxlab into corefx:
corefx: https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/SpanExtensions.cs
corefxlab: https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/SpanExtensions.cs

**Comment by davidfowl** [comment]
Also https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs

**Comment by ahsonkhan** [comment]
@davidfowl, can you open a separate issue for that? Thanks :)

**Comment by davidfowl** [comment]
What would the issue be? Figure out where IndexOfVectorized should live?

**Comment by ahsonkhan** [comment]
I am not sure. I am not familiar with System.Buffers.Experimental or which of the methods implemented there are used/useful. If IndexOfVectorized is the only one relevant to you, that could be the issue.

**Comment by jkotas** [comment]
We should have just one IndexOf that is vectorized and that lives in System.Memory in corefx. The cut-off between non-vectorized and vectorized IndexOf performance is pretty low (IIRC, <10 bytes), and so having just one vectorized IndexOf is the right default choice. If somebody needs IndexOf hyper-optimized for just a few bytes, they can build their local specialized version of it.

What needs to happen for it is to get System.Memory building in corefx with reference to System.Vectors. @benaadams submitted PR for it a while ago, but got lost in the intricacies of the corefx build system. Let me know if you need help moving it forward.

**Comment by davidfowl** [comment]
That would be ideal.

**Comment by KrzysztofCwalina** [comment]
I like the default to be vectorized, but I would not remove the optimized one and ask people to implement it on their own. Why don't we rename IndexOfVectorized to IndexOf and then move the the non-vectorized IndexOf back to corfxlab buffers.experimental and call it something liek EarlyIndexOf

**Comment by jkotas** [comment]
Sounds good to me. 

I do not plan to work on it, but it should be easy to do because of I have added the build plumbing for using SIMD in System.Memory in the corefx makefiles.

**Comment by benaadams** [comment]
Will add it; had problem before because of the SIMD reference

**Comment by benaadams** [comment]
Added PR for Vector path for IndexOf to corefx https://github.com/dotnet/corefx/pull/17143

**Comment by ahsonkhan** [comment]
This is done.
