### ISSUE TITLE
Add Span.IndexOfAny overload

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1293]
`Span.IndexOfAny(Span<byte> span, byte value)`

@davidfowl, should the signature take a Span<byte> value instead, i.e.
`Span.IndexOfAny(Span<byte> span, Span<byte> values)`?

Note, we don't need index/count as initially requested:
`Span.IndexOfAny(Span<byte> span, byte value, int index, int count)`

**Comment by benaadams** [comment]
> should the signature take a Span value instead

Its introducing an unnecessary for loop into the implementation to be general case; would be better to use `Span<byte> values` as a params type overload; so:

```csharp
Span.IndexOfAny(Span<byte> span, byte value)
Span.IndexOfAny(Span<byte> span, byte value1, byte value2)
Span.IndexOfAny(Span<byte> span, byte value1, byte value2, byte value3)
Span.IndexOfAny(Span<byte> span, Span<byte> values)
```

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/17357
