### ISSUE TITLE
Span.StartsWith(ReadOnlySpan<T>|ReadOnlySpan<byte>)

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1294]
1. Is StartsWith in the right place? i.e. on Span or extension methods
2. Do we have the right StartsWith, i.e. over T or over byte?
3. Is it efficiently implemented?
4. Should StartsWith have an overload that takes an index?

**Comment by jkotas** [comment]
> Is it efficiently implemented?

It is not because of it depends on SequenceEquals in corefx that is not very efficient. Making Starts with efficient is really about making SequenceEquals efficient.

> Should StartsWith have an overload that takes an index?

I do not think so (at least - not for performance reasons).

**Comment by davidfowl** [comment]
Do we even need StartsWith? Is there a `T[]` equivalent?

**Comment by ahsonkhan** [comment]
StartsWith was added as part of https://github.com/dotnet/corefx/pull/17322 (API reviewed here https://github.com/dotnet/corefx/issues/17414)

1) It is an extension method on Span
2) There are overloads for byte and T
3) SequenceEqual has been improved using vectors (https://github.com/dotnet/corefx/pull/17029)
4) No, as per @jkotas comments.

Hence closing.
