### ISSUE TITLE
Remove System.Slices

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1295]
@KrzysztofCwalina, can you provide more details/context?

**Comment by KrzysztofCwalina** [comment]
I think OwnedMemory, Memory, ReadableBuffer/ReadOnlyBytes should ship in a package called something like System.Buffers.<something>, maybe System.Buffers.Primitives. 

At that point, why do we still need System.Slices? What other APIs are there that won't be either in System.Memory or in System.Buffers.<something>?

**Comment by ahsonkhan** [comment]
cc @davidfowl

**Comment by jkotas** [comment]
> System.Buffers., maybe System.Buffers.Primitives.

I would vote for System.Buffers.

**Comment by KrzysztofCwalina** [comment]
The problem with System.Buffers is that it already exists in corefx. We probably don't have enough bake in time to put these types there.

**Comment by jkotas** [comment]
I see ... so should be just some temporary name that does not really matter then?

**Comment by aL3891** [comment]
I like System.Memory[.]Primitives because it feels like "memory" is a more generic concept than "buffer".

**Comment by shiftylogic** [comment]
Slices is gone with #1319. There is a couple pieces of span extension cleanup being done as part of a different work item.
