### ISSUE TITLE
Span pinning support

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1305]

**Comment by ahsonkhan** [comment]
Is this already done?
From the uber Span<T> issue in the CoreCLR repo, this is checked - Make sure there is a way to pin Span<T> for interop

**Comment by davidfowl** [comment]
Only work left here to do would be compiler work to make it so it goes from being this:

```C#
fixed (byte* ptr = &span.DangerousGetPinnableReference())
{
} 
```

To

```C#
fixed (byte* ptr = span)
{
} 
```

Basically the compiler would have some logic to look for that method to detect if an object is pinnable. 

Does that sound right @jkotas ?

**Comment by jkotas** [comment]
Correct.

**Comment by KrzysztofCwalina** [comment]
Plus we now have APIs to pin Memory long term (i.e. using Memory.Pin)

**Comment by schungx** [comment]
I can't seem to find a Pin method under Memory...

**Comment by davidfowl** [comment]
It got renamed to Retain()
