### ISSUE TITLE
Slicing pattern with range

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1306]
@davidfowl 
Does slicing using a range refer to code like this (using '..')?
```C#
Span<byte> buffer = ...

Span<byte> view1 = buffer.Slice(3, 2);
Span<byte> view2 = buffer[3..4];
 
// view1 == view2
```

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, do you still want to keep this open?

**Comment by ahsonkhan** [comment]
That depends on whether we want to support range syntax or not.
This was from the initial discussion/backlog of span items where we were considering slicing using range. I presume that is what the syntax would look like.

Changing to future.

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina, if we are getting the Range syntax support by 2.1, we should consider adding support for it for Span. Should we change the milestone of this issue to 2.1? Let me know and I will move it over to corefx.

**Comment by KrzysztofCwalina** [comment]
Yeah, once we settle on the design for Range, we can add APIs. I would not add them sooner.
