### ISSUE TITLE
Add stress tests for Span<T> APIs

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1313]
- Tests with multiple threads to confirm that Span<T> APIs are stateless and thread safe
- Tests with lots of GC allocations to confirm that when GC moves addresses around, the use of Span is still correct

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, is that something we should track in corefx now?

**Comment by ahsonkhan** [comment]
Tracking this issue in https://github.com/dotnet/corefx/issues/28227 now. Closing.
