### ISSUE TITLE
FlushAsync returns before reader Advances

### ISSUE THREAD

**Issue by tmds** [dotnet/corefxlab#1316]
```C#
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var factory = new PipeFactory())
            {
                var pipe = factory.Create();
                Task.WaitAll(new[] {
                    ReadFromPipe(pipe.Reader),
                    WriteToPipe(pipe.Writer)
                });
            }
        }

        static async Task WriteToPipe(IPipeWriter writer)
        {
            var buffer = writer.Alloc(2048);
            buffer.Advance(2048);
            System.Console.WriteLine("FlushAsync");
            await buffer.FlushAsync();
            System.Console.WriteLine("FlushAsync Returns");
        }

        static async Task ReadFromPipe(IPipeReader reader)
        {
            await Task.Delay(1000);
            System.Console.WriteLine("ReadAsync");
            var result = await reader.ReadAsync();
            System.Console.WriteLine("ReadAsync Returns");
            var buffer = result.Buffer;
            reader.Advance(buffer.End);
        }
    }
```

outputs:
```
FlushAsync
FlushAsync Returns
(1 sec)
ReadAsync
ReadAsync Returns
```

It was surprising to me to see FlushAsync return before anything was consumed by the reader. Is this expected behavior?

**Comment by Drawaes** [comment]
I would say so. Take the case of a socket if you have space you are really signalling that the data is ready to be consumed not waiting u til it has. The only time I would imagine flush to block is to apply back pressure

**Comment by tmds** [comment]
If the writer is faster than the reader, there should be something to slow it down. Otherwise the pipe will start buffering until it exhausts the memory.

**Comment by Drawaes** [comment]
You mean like #1178

**Comment by Drawaes** [comment]
It's really up to the connection to provide back pressure as it is providing the buffers... remember the flow is inverse to normal streams.

**Comment by tmds** [comment]
I mean like https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines/Pipe.cs#L405-L409
Looks like PipeOptions.{MaximumSizeHigh, MaximumSizeLow} control this behavior and their defaults never block the FlushAsync.
```
                var pipe = factory.Create(new PipeOptions()
                    {
                        MaximumSizeHigh = 1,
                        MaximumSizeLow = 1
                    }
                );
```
outputs:
```
FlushAsync
(1 sec)
ReadAsync
ReadAsync Returns
FlushAsync Returns
```

**Comment by tmds** [comment]
@davidfowl The default PipeOptions will cause the Pipe to buffer when the Reader can't keep up with the Writer. In case the average writing speed is higher than the average reading speed, it will buffer till it runs out of memory. Perhaps the default should be changed?

**Comment by davidfowl** [comment]
The creator of the pipe should configured the size. I don't know how to pick a good default when the usage of the pipe isn't known.

**Comment by davidfowl** [comment]
Also, FlushAsync would never block, it returns an incomplete awaitable that the writer is supposed to wait on.

**Comment by tmds** [comment]
> Also, FlushAsync would never block, it returns an incomplete awaitable that the writer is supposed to wait on.

I mean it is never waiting

> I don't know how to pick a good default when the usage of the pipe isn't known.

1 may be a better magical constant than 0 to avoid the memory exhaustion.

> The creator of the pipe should configured the size. 

In the proposed Transport abstraction for Kestrel the PipeOptions come from the transport. I am not sure what proper values are for this and how they depend on the transport. 0 would be a bad value here too.

**Comment by Drawaes** [comment]
I would prefer the default to buffer than not

**Comment by tmds** [comment]
> I would prefer the default to buffer than not

Why?

**Comment by Drawaes** [comment]
Because my experience with WCF in corporate environments. The restrictive thresholds were rarely adjusted and performance was blamed on the technology.

**Comment by tmds** [comment]
Do you have non-zero number in mind?

**Comment by tmds** [comment]
The actual default of MaximumSizeHigh is Int64.MaxValue. That is the amount it can buffer now.

**Comment by davidfowl** [comment]
The default value isn't being changed right now.

**Comment by tmds** [comment]
> The default value isn't being changed right now.

Ok

Another question: the lengths in Pipe are typed long, would int suffice?
