### ISSUE TITLE
Question: Why do we have an extension method on ArraySegment that returns ArraySegment?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1326]
https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/SpanExtensions_array.cs#L78

Can we remove this? Was the initial intention to return a Span<T>?

@KrzysztofCwalina

**Comment by benaadams** [comment]
I assume was experiments for https://github.com/dotnet/corefx/issues/10528 (which now has coreclr PR https://github.com/dotnet/coreclr/pull/9926)

**Comment by KrzysztofCwalina** [comment]
Yeah, the method should be an instance method on ArraySegment.

**Comment by ahsonkhan** [comment]
So, I would imagine SpanExtensions_array.cs isn't the right place for this, correct?
Why is an instance method on ArraySegment in the public static class SpanExtensionsLabs?

**Comment by davidfowl** [comment]
I would remove it, it doesn't belong here.

**Comment by ahsonkhan** [comment]
Removed. Closing.
