### ISSUE TITLE
Throw when advancing writable buffer that has no memory.

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefxlab#1331]
Happens when you do 
```
buffer = _pipe.Writer.Alloc();
buffer.Advance(10);
```
Right now only `Debug.Assert` is fired

**Comment by muratg** [comment]
@pakrym might have already fixed this. He'll verify and close.

**Comment by pakrym** [comment]
Fixed via https://github.com/dotnet/corefxlab/pull/1347
