### ISSUE TITLE
Add support for multiple awaiters in FlushAsync

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1334]
While trying to implement `WriteAsync` in Kestrel there is a scenario where concurrent writes can be handled by locking and then by doing `Alloc()`, `Commit()`, `FlushAsync()`. The `FlushAsync()` awaiter doesn't support multiple awaiters today.

This is the current workaround https://github.com/aspnet/KestrelHttpServer/blob/4dfef631b3befba12edd144b7bd3d13baddbf5db/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/SocketOutput.cs#L126-L158

/cc @pakrym

**Comment by Drawaes** [comment]
This may help in the TLS case i am fighting where the app and the TLS layer are allowed to write frames concurrently

**Comment by muratg** [comment]
We need this for SignalR Core RTM (corresponds to 2.1.0 RTM).
