### ISSUE TITLE
No way to check if the Writer is completed before calling Alloc

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1335]
Since adding this exception https://github.com/dotnet/corefxlab/blob/891a1642328e8ef25f5d64639551c2eb5acda7a8/src/System.IO.Pipelines/Pipe.cs#L102 its now very hard to determine if it's safe to call `Alloc` without tracking completed state in another bool. We should expose something on the `IPipeWriter` or support returning an invalid `WritableBuffer` with a bool.

```C#
var factory = new PipeFactory();
var pipe = factory.CreatePipe();
pipe.Writer.Complete();
var buffer = pipe.Alloc();
if (!buffer.IsWritable)
{
   return;
}

// The following operations should throw for a complete writer
buffer.Advance();
buffer.Commit();
buffer.FlushAsync();
```

/cc @pakrym @halter73

**Comment by pakrym** [comment]
I'm hesitant, this forces users to write all writer code inline and convey out of band completions through other mechanisms.

**Comment by muratg** [comment]
Assigning to @pakrym for 2.0.0
