### ISSUE TITLE
Add benchmark comparing Memory slicing to Span slicing

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1341]
`Memory.Slice(...).Span` vs `Memory.Span.Slice(...)` 

/cc @ahsonkhan @KrzysztofCwalina

**Comment by shiftylogic** [comment]
Test added (#1353)

 Test Name                                      | Metric                | Iterations |    AVERAGE |    STDEV.S |        MIN |        MAX
:---------------------------------------------- |:--------------------- |:----------:| ----------:| ----------:| ----------:| ----------:
 Benchmarks.ComparisonBench.MemorySliceThenSpan | Duration              |    1001    |      2.206 |      0.385 |      1.979 |      7.162
 Benchmarks.ComparisonBench.MemorySliceThenSpan | Instructions Retired  |    1001    | 1.112E+007 | 5.237E+005 | 1.100E+007 | 2.730E+007
 Benchmarks.ComparisonBench.MemorySliceThenSpan | Branch Mispredictions |    1001    |   1833.175 |   7594.183 |      0.000 | 2.294E+005
 Benchmarks.ComparisonBench.MemorySliceThenSpan | Cache Misses          |    1001    |    257.790 |   1222.194 |      0.000 |  20480.000
 Benchmarks.ComparisonBench.MemorySpanThenSlice | Duration              |    1001    |      1.476 |      0.084 |      1.386 |      3.004
 Benchmarks.ComparisonBench.MemorySpanThenSlice | Instructions Retired  |    1001    | 8.198E+006 | 1.608E+005 | 8.100E+006 | 1.260E+007
 Benchmarks.ComparisonBench.MemorySpanThenSlice | Branch Mispredictions |    1001    |    957.506 |   2555.650 |      0.000 |  61440.000
 Benchmarks.ComparisonBench.MemorySpanThenSlice | Cache Misses          |    1001    |     98.206 |    626.896 |      0.000 |   4096.000
