### ISSUE TITLE
MemoryPool.AllocateSlab calculation

### ISSUE THREAD

**Issue by tmds** [dotnet/corefxlab#1344]
From MemoryPool.AllocateSlab:
```
var firstOffset = (int)((_blockStride - 1) - ((ulong)(basePtr + _blockStride - 1) % _blockStride));

var poolAllocationLength = _slabLength - _blockStride;
```

Shouldn't firstOffset be substracted from poolAllocationLength?
~~Is the '_blockStride - 1' needed in the firstOffset calculation?~~

**Comment by benaadams** [comment]
firstOffset is the amount to discard to page align the blocks post allocation

**Comment by tmds** [comment]
Since poolAllocationLength doesn't take firstOffset into account, I wonder if the last block is completely in the Slab when firstOffset>0.

**Comment by benaadams** [comment]
It allocates `var slab = MemoryPoolSlab.Create(_slabLength);` but only uses `poolAllocationLength` which is `_slabLength - _blockStride` so there is `_blockStride` free in the slab to allow for alignment

**Comment by tmds** [comment]
Did you notice the block that is allocated after the for loop?
https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines/MemoryPool.cs#L159-L164

**Comment by benaadams** [comment]
The for loop test is one less `offset + _blockLength < poolAllocationLength`

**Comment by tmds** [comment]
You're right. The loop leaves enough space for the last block. Thanks.
