### ISSUE TITLE
Does Span IndexOf overload that takes multiple byte values have a bug?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1352]
I was writing some tests to validate correctness for IndexOf overloads and noticed this bug.

https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/SpanExtensions.cs#L156

```C#
     [Fact]
        public static void MakeSureNoChecksGoOutOfRangeTwo_Byte()
        {
            byte[] a = new byte[42];
            a[0] = 99;
            a[1] = 99;
            a[40] = 99;
            a[41] = 99;
            Span<byte> span = new Span<byte>(a, 1, 40);
            int index = span.IndexOf(99, 98);
            Assert.Equal(-1, index);
        }
```

Message: Assert.Equal() Failure
Expected: -1
Actual:   0

The sequence of bytes 99, 98 do not exists anywhere in the span and hence the index should be -1.

cc @benaadams, @davidfowl, @KrzysztofCwalina

**Comment by ahsonkhan** [comment]
Shouldn't this be a BitwiseAnd?
https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/SpanExtensions.cs#L188

Also, we are using the same vData to compare to both values0 and values1?
https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/SpanExtensions.cs#L187

cc @shiftylogic, thoughts?

**Comment by benaadams** [comment]
> Shouldn't this be a BitwiseAnd?

Can't be two bytes at the same time

> Also, we are using the same vData to compare to both values0 and values1?

Want to find one or the other; then return the first

**Comment by benaadams** [comment]
Test is wrong, you are adding 2 bytes then starting at second one; should be?
```
Span<byte> span = new Span<byte>(a, 2, 38);
```

**Comment by ahsonkhan** [comment]
> Test is wrong, you are adding 2 bytes then starting at second one; should be?

I think I misunderstood what these IndexOf overloads do:

```C#
byte[] a = new byte[10];
a[0] = 99;
a[9] = 98;
Span<byte> span = new Span<byte>(a);
int index = span.IndexOf(99, 98);
```
a = "99, 0, 0, 0, 0, 0, 0, 0, 0, 98"
What should index be? Should it be 0? Shouldn't it be -1 since "99, 98" is not found anywhere?
I thought IndexOf(99, 98) looks for where 99 and 98 appear together.

Is it IndexOf either 99 or 98 whichever is first?

**Comment by benaadams** [comment]
Maybe it should be called `IndexOfAny` 😆 

Will make PR
