### ISSUE TITLE
Consider throwing exception if Advance would turn Pipe into deadlocked mode

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefxlab#1381]
When `Flush` is waiting for backpressure and `Advance` does not reduce pipe length past backpressure threshold .

/cc @davidfowl

**Comment by benaadams** [comment]
Is it only needed if Advance doesn't advance? (e.g. examined is full buffer)

**Comment by pakrym** [comment]
Advance might advance but if it does not decrease length past lower backpressure threshold `FlushAsync` would never return and `ReadAsync` continuation never scheduled leaving pipe in "deadlocked" state.

**Comment by benaadams** [comment]
Shouldn't the `ReadAsync` immediately return in that situation as there is more data to consume?

e.g.
```csharp
while (processing)
{
    var result = await Input.Reader.ReadAsync();
    var examined = result.Buffer.End;
    var consumed = result.Buffer.End;

    try
    {
        ProcessTwoBytes(result.Buffer, out consumed, out examined);
        // consumed and examined moved on 2 bytes
    }
    finally
    {
        Input.Reader.Advance(consumed, examined);
    }
}
```

**Comment by benaadams** [comment]
Is only if `examined == result.Buffer.End` and there is no more data that there is a problem?

**Comment by pakrym** [comment]
Yeah, you are right, it should be "examined everything but consumed not enough"

**Comment by tmds** [comment]
Related to https://github.com/dotnet/corefxlab/issues/1355

**Comment by muratg** [comment]
@pakrym has a PR almost ready, moving to 2.0.0.
