### ISSUE TITLE
Make ReadResult smaller wrapper

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1393]
`ReadableBuffer` on `ReadResult` should call back into the pipe instead of nesting the struct. It's typically accessed once per read loop so there's no need to make `ReadResult` a bigger struct. It should store the `Pipe` and the state.

The other benefit of storing the `ReadableBuffer` state on the pipe directly is that we may be able to support `Advance` that takes an `int` (relative offset from start of the readable buffer). We wouldn't need to calculate the length anymore (but we would still need to find the end cursor and walk to the end to get the new read head).

/cc @pakrym @halter73

**Comment by davidfowl** [comment]
Might not be a huge benefit, need to profile https://github.com/dotnet/corefxlab/pull/1395

**Comment by muratg** [comment]
We don't need this in Kestrel RTM, so moving out to 2.1.0.
