### ISSUE TITLE
Remove redundant Span tests and move others to corefx

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1403]
From https://github.com/dotnet/corefxlab/pull/1401

**Comment by ahsonkhan** [comment]
We should remove the tests that are duplicates of ones in CoreFx and also move any non-duplicate tests that are specifically testing span to the CoreFx tests.

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, can we close this?

**Comment by ahsonkhan** [comment]
No, we have quite a few Span tests still in https://github.com/dotnet/corefxlab/tree/master/tests/System.Buffers.Primitives.Tests and we need to remove them if they are duplicated in the corefx tests (such as [this](https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Primitives.Tests/BasicUnitTests.cs#L10)). Some of them are testing interesting scenarios which did not get ported over and we need to move them.

From a cursory view, here are some examples:
https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Primitives.Tests/BasicUnitTests.cs#L332
https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Primitives.Tests/CastTests.cs#L54
https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Primitives.Tests/CastTests.cs#L90
https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Primitives.Tests/CastTests.cs#L126
https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Primitives.Tests/OverflowTests.cs#L27

**Comment by joshfree** [comment]
@ahsonkhan can you move this to an up-for-grabs milestone=future dotnet/corefx issue (the portion about porting additional tests to the corefx repo).
