### ISSUE TITLE
corfxlab does not build with lots of NotImplementedExceptions

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1409]
The exceptions propagate from AsSpan.

**Comment by davidfowl** [comment]
Is everything broken right now?

**Comment by KrzysztofCwalina** [comment]
Yes. Hopefully @ahsonkhan can take a look at this soon.

**Comment by davidfowl** [comment]
😞

**Comment by ahsonkhan** [comment]
These PRs should resolve the issues.
https://github.com/dotnet/corefxlab/pull/1357
https://github.com/dotnet/corefxlab/pull/1373

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefxlab/pull/1373
