### ISSUE TITLE
Flushing a pipe without a writablebuffer

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1412]
I have the problem that in my code that is mostly sync I call "Commit" on my writers. When all the framing/operations (encryption handshakes etc) are done and the flight is ready to be sent

https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines/Pipe.cs#L325

The flush being internal on the pipe stops me from flushing without a writablebuffer. This means I have to either track when I am doing my last write operation (tough when the next write is dependent on various conditions) or make an empty writer to flush, or drag the same writer through all the methods by ref.

What I need is the ability to schedule the reader without having to have a writer to commit.

**Comment by benaadams** [comment]
Can't you just https://github.com/Drawaes/Leto/pull/1
