### ISSUE TITLE
Reader.TryRead returns false when data has been commited

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1413]
https://gist.github.com/Drawaes/09369e0f2f074531dc54de5412c2ae51

Shows the behavior I would have expected to work. But instead it returns false. I would expect it to check available bytes not flushed bytes or am I missing something.

**Comment by davidfowl** [comment]
That could be made to work. Currently `TryRead` looks at the `awaitable` to know if there's data available.

**Comment by benaadams** [comment]
"flushed bytes" means nothing; it should return true if there are "committed bytes"

**Comment by benaadams** [comment]
Might also want to check the awaitable to make sure you aren't awaiting a read and also `tryread`ing

**Comment by davidfowl** [comment]
@benaadams yep, if you're signaled or there's data committed.

**Comment by Drawaes** [comment]
I can try to PR it shortly if u want

**Comment by davidfowl** [comment]
That sounds good. Also write a bunch of tests to make sure all the cases are covered. E.g.

- TryRead should return false when available bytes == 0
- TryRead should return true when available bytes > 0

**Comment by davidfowl** [comment]
Now that I think about it, there's already a `_length` property that has the amount of unconsumed bytes in the pipe. This change should be trivial.

**Comment by Drawaes** [comment]
Yup... it's the tests that are key :)

**Comment by muratg** [comment]
Looks like this was fixed, so closing.

**Comment by Drawaes** [comment]
Correct, forgot to close
