### ISSUE TITLE
Need to simplify getting Buffer from Array and ArraySegment

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1417]
Since async APIs are supposed to take `Buffer<T>` instead of `Span<T>` we need to make sure it easy to create a `Buffer<T>` from an array segment. You first have to create an `OwnedBuffer<T>` then you have to access the Buffer property from that.

The code looks like this today:

### ArraySegment

```C#
public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
{
    var ownedBuffer = OwnedBuffer<byte>.Create(new ArraySegment<byte>(buffer, offset, count));
    return _pipe.WriteAsync(ownedBuffer.Buffer);
}
```

/cc @KrzysztofCwalina

**Comment by benaadams** [comment]
https://github.com/dotnet/corefxlab/pull/1343#discussion_r107009126 🙉

**Comment by mgravell** [comment]
I have to be honest: as a consumer it wasn't at all obvious that I needed an `OwnedBuffer<>`  - just did (literally copy/paste from some real code I wrote naively), where `range` is `ArraySegment<byte>`:

            Buffer<byte> buffer = range.Array; // y u no convert?
            buffer = buffer.Slice(range.Offset, range.Count);

Dare I ask: what is `OwnedBuffer<byte>` doing here?

**Comment by benaadams** [comment]
@mgravell  See also https://github.com/dotnet/corefxlab/issues/1437

**Comment by Drawaes** [comment]
Making sure you can say pin the memory and hold the pin between async calls?

**Comment by mgravell** [comment]
@Drawaes  ah, I don't have any scenarios where that would be dangerous - in my scenario I don't need to pin until the `Span<T>` level

**Comment by mgravell** [comment]
@benaadams  what Toub describes is pretty much how I understood `Buffer<T>`, especially since there is implicit conversion from `T[]`. It really isn't obvious that this is overhead;

**Comment by Drawaes** [comment]
So the problem comes with native api calls that are async. You need to pin the memory until the async call comes back. Things like RIO, Openssl where you pass a pinned buffer that will be used at an undetermined future time.

**Comment by Drawaes** [comment]
In saying that I just realised my TLS lib doesn't need to PIN due to cunning (or luck)... I am off to delete some code.

**Comment by ahsonkhan** [comment]
@davidfowl, has this issue been resolved?

cc @KrzysztofCwalina 

You can now do the following:
```C#
public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
{
    return _pipe.WriteAsync(new ArraySegment<byte>(buffer, offset, count));
}
```

**Comment by ahsonkhan** [comment]
ping @davidfowl - can the issue be closed?
