### ISSUE TITLE
CommandLine: Support plugin architectures

### ISSUE THREAD

**Issue by xgalaxy** [dotnet/corefxlab#1423]
How can I use the System.CommandLine in a plugin based application wherein each plugin DLL that is loaded by the host application may need to get and interpret the command line arguments in addition to the main application?

Not sure if this scenario is possible? Any pointers would be useful.

**Comment by alexperovich** [comment]
You would need to have the plugins use `Environment.GetCommandLineArgs` and pass that result to the parser.
