### ISSUE TITLE
Decide on the representation for Utf8String

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1447]

**Comment by omariom** [comment]
What are the goals?

**Comment by KodrAus** [comment]
I was chatting to @nblumhardt about this recently and thought the current design for utf8-strings we've got now was ok where you wrap a slice of bytes in a `Utf8String` to perform string-specific ops on it as needed.

What's being redesigned?

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina, @shiftylogic can elaborate on the details.

**Comment by KrzysztofCwalina** [comment]
I think the issues title is worded too strongly. The issue was meant to be: are we ok with stack only Utf8String (as designed currently) or we would rather have something like System.String but holding UTF8 bytes and then use Span<byte> to represent slices of UTF8 strings?

In other words, this issues is about making our minds on what the canonical UTF8 string representation in .NET should be.

**Comment by ahsonkhan** [comment]
> I think the issues title is worded too strongly.

Please update the title accordingly.

**Comment by benaadams** [comment]
Is like someone left a flag for you... https://github.com/dotnet/coreclr/blob/master/src/vm/object.h#L1066-L1077

Still think should a be an ascii string representation (essentially a shim over a byte array)

**Comment by migueldeicaza** [comment]
I would like to have access to `Utf8Strings` beyond the stack and if someone desires views into the `Utf8String`, perhaps those could be Spans.   Utf8String should really become a universal replacement for string in .NET, not only for performance reasons, but also to avoid the poor Unicode handling that we do, and we force our users to do with the current set of APIs.

**Comment by tannergooding** [comment]
I have a proposal here: https://github.com/dotnet/csharplang/issues/688, the specific section on `Data Declarations` is interesting as it could be used to embed and reference UTF8 strings in assemblies.
