### ISSUE TITLE
Eliminate ReadHex and use Parsers

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1450]
Used here:
https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs#L252

**Comment by KrzysztofCwalina** [comment]
I think this is done/outdated.

**Comment by ahsonkhan** [comment]
We are still using ReadHex instead of our new Parsers here:
https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs#L302


```C#
        private static int UnescapePercentEncoding(ref int scan, Span<byte> buffer)
        {
            if (buffer[scan++] != '%')
            {
                return -1;
            }

            var probe = scan;

            var value1 = ReadHex(ref probe, buffer);
            if (value1 == -1)
            {
                return -1;
            }
```

cc @GrabYourPitchforks

**Comment by i3arnon** [comment]
@karelz, I would like to take this issue.
