### ISSUE TITLE
Remove General Purpose APIs from ReadableBufferExtensions

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1451]
https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs#L17

**Comment by davidfowl** [comment]
What is this?

**Comment by ahsonkhan** [comment]
Likely related to https://github.com/dotnet/corefxlab/pull/983
The issue may not be about System.IO.Pipelines.Text.Primitives and may have been resolved already.

cc @KrzysztofCwalina, can you confirm?

**Comment by KrzysztofCwalina** [comment]
I updated the title.
I think it's fine to have extensions that are truly over the ReadableBuffer. But I don't think we should have APIs like GetAsciiString(this Span<byte> span) there. I attempted to generalize this method late in the last sprint, but it broke some subtle Kestrel code. We should attempt to do it again at some point.

**Comment by ahsonkhan** [comment]
This was removed as part of https://github.com/dotnet/corefxlab/pull/2244/files#diff-f068a9a90622744a09a45fd29b213dbaL16. Closing.
