### ISSUE TITLE
System.CommandLine package depends on Microsoft.Net.Compilers

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefxlab#1456]
The latest builds of the System.CommandLine package depend on Microsoft.Net.Compilers:

https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.CommandLine

This is a regression from prior builds. My guess is this dependency was meant to be PrivateAssets="all" (formerly known as a development dependency).

**Comment by ahsonkhan** [comment]
Has this issue been resolved in https://github.com/dotnet/corefxlab/commit/11838237c3f298fe0eec177f7cbeadf0dab22a95?

**Comment by AArnott** [comment]
It looks like it. The latest CI on myget.org has the dependency removed. Thanks.
