### ISSUE TITLE
Create an IOutput implementation for pipelines that isn't tied to Text Encoding

### ISSUE THREAD

**Issue by anurse** [dotnet/corefxlab#1460]
Right now there's only [`PipelineTextOutput`](https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines.Text.Primitives/PipelineTextOutput.cs) which has a `TextEncoder` associated with it and implements `ITextOutput`, it'd be good to have a version that isn't tied to a `TextEncoder`. We could just achieve that by allowing the `TextEncoder` to be optional, but there is a broader conversation that needs to happen on making `IOutput` useful for raw binary output as well (see https://github.com/dotnet/corefxlab/issues/1264) so I didn't want to jump straight to that solution :).

**Comment by KrzysztofCwalina** [comment]
Isn't the following what you are asking for: https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/IOutput.cs

**Comment by anurse** [comment]
Yes, but I'm looking for a concrete implementation. Updated to clarify
