### ISSUE TITLE
Synchronize Pipe.Complete

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1468]
If 2 threads call Pipe.Complete at the same time, it's possible to double free. We're pretty sure it's causing this issue in Kestrel https://github.com/aspnet/KestrelHttpServer/issues/1690

**Comment by pakrym** [comment]
Fixed in https://github.com/dotnet/corefxlab/commit/4b96e38568cffd36b2bacb8b17722348a36436ff
