### ISSUE TITLE
Poor TextEncoder.TryDecode performance (UTF8)

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#1476]
I'm writing a spike of protobuf-net using the new pipelines / spans / textencoder / valuetask etc APIs.

Things are going well enough, but I'm seeing very bad performance from `TextEncoder.TryDecode` compared to the old `Encoding.GetString`

results:

```
old sync code, old encoder: 7021ms
new async code, old encoder: 8318ms
new async code, new encoder: 17000ms
```

The 7021 vs 8318 is fine, especially considering the in-progress state and the fact that I've barely started optimizing; however, the only difference between the 8318 vs 17000 is `TextEncoder.TryDecode` vs `Encoding.GetString`. This suggests a serious performance difference between the legacy and new code, which could be very harmful for any code relying on the new codebase.

Test rig is here: https://github.com/mgravell/protobuf-net/tree/async/src/AsyncSpike (if in doubt, commit https://github.com/mgravell/protobuf-net/tree/2c4a8fa44e163e718a8d7dc86840319e97d734e2) - just needs `dotnet run -c Release`

.... discuss .... :)

**Comment by mgravell** [comment]
(cheeky /cc @KrzysztofCwalina and @shiftylogic , because you both seem to be active in this area)

**Comment by mgravell** [comment]
random thing: can anyone tell me how to run the `[Benchmark]` tests? there doesn't seem to be a pre-existing test-harness (per the documentation) for these; is there some voodoo I need to do to run them? I'm looking at adding some decoding tests and I have some ideas to improve performance...

**Comment by shiftylogic** [comment]
https://github.com/dotnet/corefxlab/tree/master/scripts/PerfHarness

**Comment by mgravell** [comment]
thanks; looking; I got them running, at least, although for some reason the args don't seem to be passed down to the child process, so the filters don't work; I can hack around that locally, though; baseline (PR to follow):

```
    Test Name                                                                                                                                                                                                              | Metric                | Iterations |   AVERAGE |   STDEV.S |       MIN |        MAX
    :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |:--------------------- |:----------:| ---------:| ---------:| ---------:| ----------:
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.DecodingPerformanceTestUsingCoreCLR(charLength: 1000, minCodePoint: 0, maxCodePoint: 127)                                                                     | Duration              |    1001    |     0.002 |     0.003 |     0.001 |      0.064
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.DecodingPerformanceTestUsingCoreCLR(charLength: 1000, minCodePoint: 128, maxCodePoint: 2047)                                                                  | Duration              |    1001    |     0.007 |     0.009 |     0.006 |      0.267
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.DecodingPerformanceTestUsingCoreCLR(charLength: 1000, minCodePoint: 2048, maxCodePoint: 65535)                                                                | Duration              |    1001    |     0.012 |     0.027 |     0.009 |      0.610
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.DecodingPerformanceTestUsingCorefxlab(charLength: 1000, minCodePoint: 0, maxCodePoint: 127)                                                                   | Duration              |    1001    |     0.037 |     0.109 |     0.030 |      3.484
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.DecodingPerformanceTestUsingCorefxlab(charLength: 1000, minCodePoint: 128, maxCodePoint: 2047)                                                                | Duration              |    1001    |     0.038 |     0.017 |     0.034 |      0.505
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.DecodingPerformanceTestUsingCorefxlab(charLength: 1000, minCodePoint: 2048, maxCodePoint: 65535)                                                              | Duration              |    1001    |     0.044 |     0.007 |     0.039 |      0.105

```

**Comment by mgravell** [comment]
sigh.... well I screwed up *that* PR... resetting my local to try again...

**Comment by ahsonkhan** [comment]
> for some reason the args don't seem to be passed down to the child process, so the filters don't work;

What are the commands you are running and with what args?

**Comment by mgravell** [comment]
variations of:

    ..\..\dotnet\dotnet run -c Release -- --assembly System.Text.Primitives.Tests

and:

    ..\..\dotnet\dotnet run -c Release -- --perf:typenames EncodingPerfComparisonTests

in both bases the `args` parameter in `Main` was empty, so it ran everything... I just hacked it locally :)

**Comment by ahsonkhan** [comment]
>  for some reason the args don't seem to be passed down to the child process, so the filters don't work;

FYI, there was a bug passing in cli for passing args: https://github.com/dotnet/cli/pull/6313  which got fixed recently. So when we update to a newer version, you won't see these issues anymore.

**Comment by shiftylogic** [comment]
Performance now matches the CLR implementation (or slightly better).
