### ISSUE TITLE
Pipelines tests and samples fail to build in VS

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1478]
When I try to build corflab.sln in VS, I get the following build errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected dependency 'Microsoft.NETCore.App' with no version number.	System.IO.Pipelines.Performance.Tests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.NETCore.App' with no version number.	System.IO.Pipelines.Performance.Tests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.NETCore.App' with no version number.	System.IO.Pipelines.Performance.Tests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error	CS0103	The name 'Dns' does not exist in the current context	System.IO.Pipelines.Samples	D:\git\corefxlab\samples\System.IO.Pipelines.Samples\HttpClient\LibuvHttpClientHandler.cs	277	Active

**Comment by ahsonkhan** [comment]
Issue resolved by https://github.com/dotnet/corefxlab/pull/1503 (+ using newer version of VS).
