### ISSUE TITLE
Utf8String: desired features

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/corefxlab#1510]
Would like to have the following features, ran into these while porting some Go code:

* `LastIndexOf (uint codepoint)`
* `TrimStart (Utf8String prefix)`
* `TrimEnd (Utf8String suffix)`

**Comment by A-And** [comment]
@migueldeicaza 
Could you clarify the `TrimStart ` and `TrimEnd ` functionality? 

Were you thinking of Go's `TrimPrefix` and `TrimSuffix` functions (i.e. removing a specified prefix/suffix if present, string is unchanged if not) or more of a managed string's `TrimStart ` and `TrimEnd` (i.e. remove any occurrence of a character in a set passed as an argument)?

**Comment by KrzysztofCwalina** [comment]
This APIs were added by @A-And and merged into master.
