### ISSUE TITLE
UTF8 Encoder doesn't do validation if input is UTF8 bytes.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1514]
From: https://github.com/dotnet/corefxlab/pull/1508

https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8TextEncoder.cs#L104

This returns true even if inputUtf8 contains invalid UTF8 bytes.
```C#
utf8.TryEncode(inputUtf8, encodedBytes, out int charactersConsumed, out bytesWritten)
```
Another example is if "InputBufferLargerThanOutputBuffer". The CopyTo throws an exception:
System.ArgumentException : Destination is too short

This isn't the expected behaviour for other encodings. We should be allowed to restart with a larger buffer to complete:
```C#
Assert.False(utf8.TryEncode(inputUtf8, encodedBytes1, out int charactersConsumed1, out bytesWritten1));
encodedBytes2 = new Span<byte>(new byte[expectedBytesWritten - bytesWritten1]);
Assert.True(utf8.TryEncode(inputUtf8.Slice(charactersConsumed1), encodedBytes2, out int charactersConsumed2, out bytesWritten2));
```

cc @KrzysztofCwalina, @shiftylogic

**Comment by ahsonkhan** [comment]
Assigning to @GrabYourPitchforks, as this overlaps with the UTF-8 work he has been doing.

**Comment by GrabYourPitchforks** [comment]
@ahsonkhan, I don't see the type `Utf8TextEncoder` across any of our repos, and the earlier link seems dead. Can you point me to the method we should investigate? Thanks!

**Comment by ahsonkhan** [comment]
TextEncoders were re-designed here: https://github.com/dotnet/corefxlab/pull/1622

Here is the method in question, now:
https://github.com/dotnet/corefxlab/blob/4f23c82316b5e14ef8379ab6e4653bb43ab92dd8/src/System.Text.Primitives/System/Text/SymbolTable/SymbolTable_utf8.cs#L51
