### ISSUE TITLE
Should TryEncode(string, ...) return an out charactersConsumed parameter? 

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1515]
From: https://github.com/dotnet/corefxlab/pull/1508

Similar to the other TryEncode overloads, should the one that takes string as an input also return an `out charactersConsumed`?

https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Primitives/System/Text/TextEncoder.cs#L220

Sample test InputBufferLargerThanOutputBuffer would require the out parameter. Is this not  a feasible scenario where we restart encoding using a bigger/separate buffer?

```C#
temp = testEncoderUnicode.GetBytes(inputString);
expectedBytes = Text.Encoding.Convert(testEncoderUnicode, testEncoder, temp);
expectedBytesWritten = expectedBytes.Length;
encodedBytes1 = new Span<byte>(new byte[expectedBytesWritten / 2]);
string inputStr = inputString;
Assert.False(utf8.TryEncode(inputStr, encodedBytes1, out bytesWritten1));
encodedBytes2 = new Span<byte>(new byte[expectedBytesWritten - bytesWritten1]);
// Can’t do this since we do not have out charactersConsumed
Assert.True(utf8.TryEncode(inputStr.Substring(charactersConsumed1), encodedBytes2, out bytesWritten2));    
```

cc @KrzysztofCwalina, @shiftylogic

**Comment by ahsonkhan** [comment]
From @KrzysztofCwalina:
> Substring allocates, and so the right way to write this code is to convert the string to Span<char>.

Definitely. However, even if we were to convert to a Span, to Slice, we need charactersConsumed (unless you are suggesting we restart from the beginning of the string).

```C#
temp = testEncoderUnicode.GetBytes(inputString);
expectedBytes = Text.Encoding.Convert(testEncoderUnicode, testEncoder, temp);
expectedBytesWritten = expectedBytes.Length;
encodedBytes1 = new Span<byte>(new byte[expectedBytesWritten / 2]);
string inputStr = inputString;
Assert.False(utf8.TryEncode(inputStr, encodedBytes1, out bytesWritten1));
encodedBytes2 = new Span<byte>(new byte[expectedBytesWritten - bytesWritten1]);
// Can’t do this since we do not have out charactersConsumed
Assert.True(utf8.TryEncode(inputStr.AsSpan().Slice(charactersConsumed1), encodedBytes2, out bytesWritten2)); 
```
Otherwise, why provide a string overload?

**Comment by ahsonkhan** [comment]
@shiftylogic, what are your thoughts on this?

**Comment by shiftylogic** [comment]
There is no System.String variant of TryEncode anymore, so this is no longer an issue.
