### ISSUE TITLE
Move OwnedBuffer.Add to some better location

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1529]

**Comment by jkotas** [comment]
S.R.CS.Unsafe should be a good place. It has both `void*` and `ref T` overloads for most methods. `void*` overloads for Add and Subtract are missing for no good reason.

**Comment by ahsonkhan** [comment]
@jkotas, should I open an issue in corefx to propose this addition?

**Comment by jkotas** [comment]
I think so

**Comment by ahsonkhan** [comment]
This will be fixed in https://github.com/dotnet/corefx/pull/20886 and once we get the latest corefx package, we can remove the Add API from OwnedBuffer.

**Comment by ahsonkhan** [comment]
Unsafe.Add added here:
https://github.com/dotnet/corefx/pull/20886

To Do now: Replace OwnedBuffer.Add (and its uses) with Unsafe.Add
