### ISSUE TITLE
System.IO.FileSystem.Watcher.Polling uses Windows specific API FindFirstFileExW

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1534]
https://github.com/dotnet/corefxlab/blob/master/src/System.IO.FileSystem.Watcher.Polling/System/IO/PollingWatcher.cs#L95

Hence, the tests only run for Windows for now and disabled for the rest, here:
https://github.com/dotnet/corefxlab/pull/1532

cc @KrzysztofCwalina

**Comment by ahsonkhan** [comment]
@MisinformedDNA, can this issue be closed now?

**Comment by MisinformedDNA** [comment]
Yes please.
