### ISSUE TITLE
Pipes: WritableBuffer.Write() throws InvalidOutOfRangeException when writing empty array

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefxlab#1547]
_From @cesarbs on May 16, 2017 21:49_

![image](https://cloud.githubusercontent.com/assets/924164/26129825/c13c1c5e-3a46-11e7-93e8-b0ef64ce8577.png)

![image](https://cloud.githubusercontent.com/assets/924164/26129852/e3b82bf6-3a46-11e7-8625-622ba7d8006c.png)

_Copied from original issue: dotnet/corefx#19845_

**Comment by stephentoub** [comment]
@cesarbs, did you intend to open this in corefxlab rather than corefx?

**Comment by cesarbs** [comment]
@stephentoub Yes, sorry.

**Comment by pakrym** [comment]
Fixed by https://github.com/dotnet/corefxlab/pull/1552
