### ISSUE TITLE
Missing NeutralResourcesLanguageAttribute

### ISSUE THREAD

**Issue by moozzyk** [dotnet/corefxlab#1548]
I am testing a UWP app which pulls Channels via SignalR and which does not compile in Release mode due to an internal compiler error which I think might be caused by missing NeutralResourcesLanguageAttribute on the Channels assembly

```
```
1>------ Build started: Project: SignalRTest, Configuration: Release x86 ------
1>  SignalRTest -> C:\Users\XXXX\documents\visual studio 2017\Projects\SignalRTest\SignalRTest\bin\x86\Release\SignalRTest.exe
1>C:\Users\XXXX\.nuget\packages\System.Threading.Tasks.Channels\0.1.0-e170516-2\lib\netstandard1.3\System.Threading.Tasks.Channels.dll : warning MSB3817: The assembly "C:\Users\XXXX\.nuget\packages\System.Threading.Tasks.Channels\0.1.0-e170516-2\lib\netstandard1.3\System.Threading.Tasks.Channels.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).
1>  Starting .NET Native compilation
1>  Processing application code
1>C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24211\x86\ilc\IlcInternals.targets(936,5): error : Internal compiler error: Object reference not set to an instance of an object.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by muratg** [comment]
@joshfree @ahsonkhan We need this by SignalR RTM (in the 2.1 wave.)  Though it would be much better to get this in SignalR preview1 (in the 2.0 RTM wave.)

**Comment by stephentoub** [comment]
@joshfree, I don't see NeutralResourcesLanguage applied to any other assemblies in corefxlab.  I can certainly add one as a one-off to System.Threading.Tasks.Channels, but if (?) we should have them on all of the corefxlab assemblies, seems like it be better for someone familiar with the build infrastructure to put it in one place centrally, e.g. wherever the other assembly-level attributes are applied?

**Comment by joshfree** [comment]
@stephentoub feel free to chat with @ahsonkhan and @crummel if you need assistance with build infra or if you want to hand this off.

Could you do the quick one-off attribute fix and make sure this is the only change required to unblock SignalR's use of Channels before we go further?

**Comment by stephentoub** [comment]
> Could you do the quick one-off attribute fix and make sure this is the only change required to unblock SignalR's use of Channels before we go further?

Already did. My question was more about someone doing the same for the whole repo; wasn't clear to me why this one lib would be different.
