### ISSUE TITLE
Review Brotli PR and address any pending feedback

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefxlab#1565]
Review https://github.com/dotnet/corefxlab/pull/1544#pullrequestreview-38272209 feedback in person with @Vedin and submit follow up PR as necessary.

**Comment by joshfree** [comment]
@shiftylogic PTAL

**Comment by ahsonkhan** [comment]
@shiftylogic, @Vedin, is this complete?

**Comment by ahsonkhan** [comment]
Resolved in later PRs (such as https://github.com/dotnet/corefxlab/pull/1567 / https://github.com/dotnet/corefxlab/pull/1575 / https://github.com/dotnet/corefxlab/pull/1587).
