### ISSUE TITLE
Maestro is telling us to pick up a 2.0 cli but 2.1 assemblies from CoreFx

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefxlab#1566]
https://ci.dot.net/job/dotnet_corefxlab/job/master/job/windows_nt_debug_prtest/70/consoleFull#-13547394508943a369-e80c-4557-899a-c780301de2ed
> [xUnit.net 00:00:01.0025439]     System.Binary.Base64.Tests.Base64Tests.GenerateDecodingMapAndVerify [FAIL]
06:42:12 [xUnit.net 00:00:01.0044529]       System.IO.FileNotFoundException : Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
06:42:12 [xUnit.net 00:00:01.0056781]       Stack Trace:
06:42:12 [xUnit.net 00:00:01.0070664]            at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, Int32 length)
06:42:12 [xUnit.net 00:00:01.0071538]            at System.SpanExtensions.SequenceEqual(Span`1 first, ReadOnlySpan`1 second)
06:42:12 [xUnit.net 00:00:01.0072078]            at System.Binary.Base64.Tests.Base64Tests.GenerateDecodingMapAndVerify()
06:42:12 [xUnit.net 00:00:01.0096265]     System.Binary.Base64.Tests.Base64Tests.GenerateEncodingMapAndVerify [FAIL]
06:42:12 [xUnit.net 00:00:01.0096993]       System.IO.FileNotFoundException : Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
06:42:12 [xUnit.net 00:00:01.0097849]       Stack Trace:
06:42:12 [xUnit.net 00:00:01.0098787]            at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, Int32 length)
06:42:12 [xUnit.net 00:00:01.0099370]            at System.SpanExtensions.SequenceEqual(Span`1 first, ReadOnlySpan`1 second)
06:42:12 [xUnit.net 00:00:01.0099770]            at System.Binary.Base64.Tests.Base64Tests.GenerateEncodingMapAndVerify()
06:42:12 [xUnit.net 00:00:01.0138640]   Finished:    System.Binary.Base64.Tests
06:42:13 Failed   System.Binary.Base64.Tests.Base64Tests.GenerateDecodingMapAndVerify
06:42:13 Error Message:
06:42:13  System.IO.FileNotFoundException : Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
06:42:13 Stack Trace:
06:42:13    at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, Int32 length)
06:42:13    at System.SpanExtensions.SequenceEqual(Span`1 first, ReadOnlySpan`1 second)
06:42:13    at System.Binary.Base64.Tests.Base64Tests.GenerateDecodingMapAndVerify()
06:42:13 Failed   System.Binary.Base64.Tests.Base64Tests.GenerateEncodingMapAndVerify
06:42:13 Error Message:
06:42:13  System.IO.FileNotFoundException : Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
06:42:13 Stack Trace:
06:42:13    at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, Int32 length)
06:42:13    at System.SpanExtensions.SequenceEqual(Span`1 first, ReadOnlySpan`1 second)
06:42:13    at System.Binary.Base64.Tests.Base64Tests.GenerateEncodingMapAndVerify()
06:42:13 
06:42:13 
Total tests: 5. Passed: 3. Failed: 2. Skipped: 0.

**Comment by ahsonkhan** [comment]
This issue is not about the GenerateDecodingMapAndVerify test cases.
The packages from corefx are not being produced (or consumed) properly. Span APIs across the board don't work since the System.Numerics.Vectors packages is not found.

**Comment by ahsonkhan** [comment]
@shiftylogic, can we close this issue now?

**Comment by ektrah** [comment]
@ahsonkhan @shiftylogic I was monitoring this issue because some of my test cases fail with the same exception (System.IO.FileNotFoundException : Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. **at** `System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, Int32 length)`) when I run them on .NET Core 2.0. Should this work now?
