### ISSUE TITLE
Buffer overrun in Base64Encoder.TryDecode

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefxlab#1579]
This line https://github.com/dotnet/corefxlab/blob/604ebd8ae3ad303f44317673f3e5a7ca2c39ed07/src/System.Binary.Base64/System/Binary/Base64.cs#L385 writes 4 bytes, but the previous line only ensures 3 bytes are available in the buffer.

```
    while (sourceIndex < srcLength - 4)
    {
        result = Decode(ref Unsafe.Add(ref srcBytes, sourceIndex));
        if (result == -1) throw new FormatException();  // invalid bytes
        if (destIndex > destLength - 3) goto FalseExit;
        Unsafe.WriteUnaligned(ref Unsafe.Add(ref destBytes, destIndex), result); <--- bug
        destIndex += 3;
        sourceIndex += 4;
    }
```

**Comment by ahsonkhan** [comment]
> but the previous line only ensures 3 bytes are available in the buffer.

Base 64 Decoding goes from 4 bytes to 3 bytes. So the check is correct.

Does WriteUnaligned write 4 bytes because we are writing an int, which is 4 bytes? Therefore, should we just write one byte at a time instead since we only need to write 3 bytes?

**Comment by jkotas** [comment]
You either need to write one byte at a time (or two bytes + one byte). Or you need to ensure that you use the fast loop only when there is spare byte available in the output buffer - this is likely faster (related to the other issue that I have just opened).

**Comment by ahsonkhan** [comment]
> Or you need to ensure that you use the fast loop only when there is spare byte available in the output buffer

Is writing 3 bytes, one byte at a time, slower than writing 4 bytes (all at once, as an int)?

> You either need to write one byte at a time (or two bytes + one byte). 

I wonder if this gets us any perf wins. And like you said, writing 4 bytes at a time instead might be faster.

**Comment by jkotas** [comment]
> Is writing 3 bytes, one byte at a time, slower than writing 4 bytes (all at once, as an int)?

Measure it...

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefxlab/pull/1586.
