### ISSUE TITLE
Base64Encoder.TryDecode can be much faster

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefxlab#1580]
The current Base64.Base64Encoder needs ~18 instructions to decode a single byte. The path length of this loop is 73 instructions:

```
            while (sourceIndex < srcLength - 4)
            {
                result = Decode(ref Unsafe.Add(ref srcBytes, sourceIndex));
                if (result == -1) throw new FormatException();  // invalid bytes
                if (destIndex > destLength - 3) goto FalseExit;
                Unsafe.WriteUnaligned(ref Unsafe.Add(ref destBytes, destIndex), result);
                destIndex += 3;
                sourceIndex += 4;
            }
```

There is a lot of overhead  in the piece meal split into a bunch of little functions with a ton of arguments. I think you should be able to get under 10 instructions to decode a single byte by streamlining the implementation (about 2x better than the current state), and proportional improvement in throughput.

**Comment by ahsonkhan** [comment]
>  proportional improvement in throughput

I did not see any perf improvement when I made this change initially, and hence I left it as is. I will try again without the helper functions and see if we get a performance improvement.

**Comment by ahsonkhan** [comment]
> There is a lot of overhead in the piece meal split into a bunch of little functions with a ton of arguments.

I removed the use of the functions and in-lined the code:
```C#
while (sourceIndex < srcLength - 4)
{
    byte b0 = Unsafe.Add(ref srcBytes, sourceIndex);
    byte b1 = Unsafe.Add(ref srcBytes, sourceIndex + 1);
    byte b2 = Unsafe.Add(ref srcBytes, sourceIndex + 2);
    byte b3 = Unsafe.Add(ref srcBytes, sourceIndex + 3);

    if (b0 == s_encodingPad || b1 == s_encodingPad || b2 == s_encodingPad || b3 == s_encodingPad) goto InvalidExit;

    byte i0 = s_decodingMap[b0];
    byte i1 = s_decodingMap[b1];
    byte i2 = s_decodingMap[b2];
    byte i3 = s_decodingMap[b3];

    if (i0 == s_invalidByte || i1 == s_invalidByte || i2 == s_invalidByte || i3 == s_invalidByte) goto InvalidExit;

    byte r0 = (byte)(i0 << 2 | i1 >> 4);
    byte r1 = (byte)(i1 << 4 | i2 >> 2);
    byte r2 = (byte)(i2 << 6 | i3);

    result = r2 << 16 | r1 << 8 | r0;

    if (destIndex > destLength - 3) goto DestinationSmallExit;
    Unsafe.WriteUnaligned(ref Unsafe.Add(ref destBytes, destIndex), result);
    destIndex += 3;
    sourceIndex += 4;
}
```
Did you have something else in mind because the change above did not improve performance.

![image](https://cloud.githubusercontent.com/assets/6527137/26615033/f108eb14-4578-11e7-90ac-d6b60cdbffe7.png)

**Comment by jkotas** [comment]
Try this:

```
            ref sbyte decodingMap = ref Unsafe.As<byte, sbyte>(ref s_decodingMap[0]); // TODO: Change the type of s_decodingMap to sbyte[] to avoid Unsafe.As

            while (sourceIndex < srcLength - 4) // TODO: you can make this more efficient by using unsafe pointer as the loop limit
            {
                int i0 = Unsafe.Add(ref srcBytes, sourceIndex);
                int i1 = Unsafe.Add(ref srcBytes, sourceIndex + 1);
                int i2 = Unsafe.Add(ref srcBytes, sourceIndex + 2);
                int i3 = Unsafe.Add(ref srcBytes, sourceIndex + 3);

                i0 = Unsafe.Add(ref decodingMap, i0);
                i1 = Unsafe.Add(ref decodingMap, i1);
                i2 = Unsafe.Add(ref decodingMap, i2);
                i3 = Unsafe.Add(ref decodingMap, i3);

                i0 <<= 18;
                i1 <<= 12;
                i2 <<= 6;

                i0 |= i3;
                i1 |= i2;

                i0 |= i1;

                if (i0 < 0) throw new FormatException();  // invalid bytes

                if (destIndex > destLength - 3) goto FalseExit; // TODO: you can get rid off this line by including it in loop limit

                Unsafe.Add(ref destBytes, destIndex) = (byte)(i0 >> 16);
                Unsafe.Add(ref destBytes, destIndex + 1) = (byte)(i0 >> 8);
                Unsafe.Add(ref destBytes, destIndex + 2) = (byte)i0;

                destIndex += 3;
                sourceIndex += 4;
            }
```

**Comment by ahsonkhan** [comment]
> Try this:

![image](https://cloud.githubusercontent.com/assets/6527137/26649264/3a029a1e-45fa-11e7-8034-08552df44536.png)

**Open questions:**
- Why do we need our decodingMap to be sbyte? Should the map have negative values (say -1) for invalid indices instead of byte.MaxValue (since byte.MaxValue won't fit)?
- Is `if (i0 < 0)` sufficient to capture all invalid bytes cases? I have to work through some examples to convince myself of that. When will i0 be negative? If nothing in the decodingMap is negative, I don't see how bit 31 of i0 ever gets set to 1. I get that 255 -> -1 when you cast from byte to sbyte, so is that what the above algorithm relies on?
- Is `Unsafe.Add(ref decodingMap, i0);` faster than array indexer? I will measure and see. I had assumed array indexer was optimal.

**Comment by jkotas** [comment]
> Why do we need our decodingMap to be sbyte? 

So that we get negative number for bad input, and can use a single `if (i0 < 0)` check to invalid input. It also answers your second question.

> Is Unsafe.Add(ref decodingMap, i0); faster than array indexer?

Array indexer has range check. This one does not.

**Comment by ahsonkhan** [comment]
> Is `if (i0 < 0)` sufficient to capture all invalid bytes cases?

This isn't sufficient since you could have the padding character as the first or second (or third but not fourth) byte and that is invalid.

ABYZ (A and B cannot be '=', Y & Z can be '=', if Y is '=' so must Z).
- XXXX (valid)
- XXX= (valid)
- XX== (valid)
- XX=X (invalid)
- =XXX (invalid)

```C#
[Theory]
[InlineData(0, 0)]
[InlineData(0, 1)]
[InlineData(0, 2)]
[InlineData(0, 3)]
[InlineData(61, 0)] // Test failed
[InlineData(61, 1)] // Test failed
[InlineData(91, 0)]
[InlineData(91, 1)]
[InlineData(91, 2)]
[InlineData(91, 3)]
[InlineData(200, 0)]
[InlineData(200, 1)]
[InlineData(200, 2)]
[InlineData(200, 3)]
[InlineData(255, 0)]
[InlineData(255, 1)]
[InlineData(255, 2)]
[InlineData(255, 3)]
public void BasicDecodingInvalidBytes(byte invalidByte, int index)
{
    Span<byte> source = new byte[8];
    for (int i = 0; i < source.Length; i++)
    {
        if (i == index)
            source[i] = invalidByte;
        else if (i < 4)
            source[i] = 50;
        else
            source[i] = 80;
    }

    Span<byte> decodedBytes = new byte[Base64Decoder.ComputeDecodedLength(source)];
    Assert.Equal(TransformationStatus.InvalidData,
        Base64.Decoder.Transform(source, decodedBytes, out int consumed, out int decodedByteCount));
}
```

**Comment by jkotas** [comment]
> This isn't sufficient since you could have the padding character as the first or second (or third but not fourth) 

These should be handled outside of the main fast decoding loop. I do not think you want to make the main fast decoding loop slower for something that only occurs at most once. Replace `throw new FormatException();` with `break;`.

**Comment by ahsonkhan** [comment]
> that only occurs at most once.

What are you referring to here?
Why would the padding character occur at most once? The fast loop is incapable of detecting invalid padding character appearing when not expected. 

> Replace `throw new FormatException();` with `break;`.

Even if we break, the condition is not getting caught by `if (i0 < 0)`.
