### ISSUE TITLE
Consider moving the stackalloc to where it is needed in ITransformation.Pipe

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1585]
From #1574 (https://github.com/dotnet/corefxlab/pull/1574#discussion_r119425083)

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, is this still relevant?

**Comment by ahsonkhan** [comment]
Yes. I can revisit it once we decide if such Transformation pipeline helper APIs are something we want to productize (along with IBufferOperation/IBufferTransformation).
