### ISSUE TITLE
Canceled spelled wrong

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefxlab#1665]
https://github.com/dotnet/corefxlab/blob/bc3d3a502f14624f679a990befc454c0c97a055b/src/System.IO.Pipelines/FlushResult.cs#L13

https://github.com/dotnet/corefxlab/blob/bc3d3a502f14624f679a990befc454c0c97a055b/src/System.IO.Pipelines/ResultFlags.cs#L7

**Comment by ahsonkhan** [comment]
http://grammarist.com/spelling/cancel/
> In American English, the verb cancel is usually inflected canceled and canceling—with one l. This is not a rule, however, and exceptions are easily found. In varieties of English from outside the U.S., including Canadian, British, and Australian English, cancelled and cancelling are the preferred spellings.

**Comment by BrennanConroy** [comment]
Yep, and we use the single 'l' version everywhere
