### ISSUE TITLE
Case insensitive mode for System.CommandLine

### ISSUE THREAD

**Issue by daveaglick** [dotnet/corefxlab#1667]
I'd like to propose a case insensitive mode for System.CommandLine. This was left unresolved in the readme file:

```
Should we support a case insensitive mode?
```

While many CLIs do make a distinction between case for option and parameter names, some do not and it would be nice to opt-in to ignoring case when both defining and parsing the arguments.

Here's how I think it should work:
- The `ArgumentSyntax` class has a public read/write property `ArgumentComparison` of type `StringComparison` that defaults to `StringComparison.Ordinal`
- This property would typically be set to an alternate value in the `ArgumentSyntax.Parse()` `defineAction` function
- All string comparisons for defining and parsing command, option, and argument names would use the defined `StringComparison` instead of the current `StringComparison.Ordinal` being used everywhere

I am prepared to submit a PR for this if there is interest. Since it's opt-in by changing the `ArgumentSyntax.ArgumentComparison` property and the default matches what is currently being used the change will be fully backwards-compatible.

**Comment by ahsonkhan** [comment]
cc @terrajobst, @alexperovich
