### ISSUE TITLE
System.CommandLine - Add overload to store value to object properties

### ISSUE THREAD

**Issue by jonjbar** [dotnet/corefxlab#1669]
syntax.DefineOption and other similar methods require a `ref` argument to store the parsed value:

`DefineOption(string name, ref bool value, bool requireValue, string help);`

This makes it harder than it should to store the parsed option to an object property. E.g. the following is impossible:

`syntax.DefineOption("v|verbose", ref _optionsGlobal.IsVerbose);`

One solution is to use a local variable, which is cumbersome.

What could be better is to provide an overload where the value can be stored via an anonymous function, something like:

`syntax.DefineOption("v|verbose", value => _optionsGlobal.IsVerbose = value);`

**Comment by daveaglick** [comment]
I don't seem to have any trouble storing to an object property:
https://github.com/Wyamio/Wyam/blob/develop/src/clients/Wyam/Commands/BuildCommand.cs#L67

Not saying that this wouldn't make for a good enhancement generally, just that I'm wondering why you're having trouble with this specific use case...

**Comment by jonjbar** [comment]
@daveaglick I'm quite new to .net but I believe the explanation is that you are not using public fields (without getters and setters): https://github.com/Wyamio/Wyam/blob/develop/src/clients/Wyam/Commands/ConfigOptions.cs
If you did, you wouldn't be able to use the "ref" keyword: https://stackoverflow.com/a/1403036/184404
Also, I'm using properties as fields are not allowed in an Interface: https://stackoverflow.com/a/5698494/184404

Does that make sense ?

**Comment by daveaglick** [comment]
@jonjbar Ah, of course - that's a total brain fart on my part. Properties won't work because they're just syntactic sugar for getter and/or setter methods which obviously can't be passed by ref. I typically name fields with an `_` prefix but named these ones like properties for this very reason.

**Comment by vcsjones** [comment]
Well, to give @daveaglick a *little* credit, you can make this work with properties:

```csharp
    class Program
    {
        public bool _isVerbose;
        public ref bool IsVerbose
        {
            get
            {
                return ref _isVerbose;
            }
        }

        void Foo()
        {
            ArgumentSyntax syntax = null;
            syntax.DefineOption("v|verbose", ref IsVerbose, true, "Is verbose, duh.");
        }

        static void Main()
        {
        }
    }
```

But yeah, ref properties are probably not the solution here. An overload that takes `Action<T>` is probably cleaner.

**Comment by daveaglick** [comment]
@vcsjones Don't give me too much credit - I had no idea you could use C# 7 ref returns for properties like this. That's super cool.
