### ISSUE TITLE
Resolution Scope on CilTypeReference: System.Reflection.Metadata.Cil

### ISSUE THREAD

**Issue by SantiFdezM** [dotnet/corefxlab#167]
The resolution scope on CilTypeReference is not yet decoded. This could be one of the following options:

-String (resolution scope name)

-CilEntity (CilModuleDefinition, CilModuleReference, CilTypeReference, CilAssemblyReference)

See https://github.com/dotnet/corefxlab/blob/master/src/System.Reflection.Metadata.Cil/src/CilEventDefinition.cs#L80-L91

cc @AlexGhiondea

**Comment by ahsonkhan** [comment]
cc @safern
