### ISSUE TITLE
System.IO.Compression.Brotli resolves incorrect brotli native libs

### ISSUE THREAD

**Issue by csyszf** [dotnet/corefxlab#1677]
I built my project in `microsoft/aspnetcore-build:1.1.2`, and deployed it in `microsoft/aspnetcore:1.1.2`.
Then an exception occurred after i triggered the brotili compression:

> An unhandled exception occurred while processing the request.
DllNotFoundException: Unable to load DLL 'brotlienc.dll': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
System.IO.Compression.Interop+Brotli.BrotliEncoderCreateInstance(IntPtr allocFunc, IntPtr freeFunc, IntPtr opaque)

It seems that the [OS conditional](https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Compression.Brotli/System.IO.Compression.Brotli.csproj#L24) not work

Did i use the package wrong?

**Comment by ahsonkhan** [comment]
cc @shiftylogic 
Any ideas to help resolve this issue?

**Comment by shiftylogic** [comment]
Can you provide more detail on your development and deployment environments? Also, details on how you are deploying would be helpful.

**Comment by csongysun** [comment]
@shiftylogic 
I use VS2017 on Win10 x64 for develop and debug, and deployed to docker for staging test.
Deployment details:
* OS: ubuntu 16.04
* Clone the project
* Use the `microsoft/aspnetcore-build:1.1.2` for building project 
```shell
docker run -it --rm -v=$(pwd):/src \
    -v=$HOME/.nuget/packages:$HOME/.nuget.packages \
    -w=/src/src/$arg microsoft/aspnetcore-build:1.1.2 \
    bash -c 'rm -rf ./obj && rm -rf ./bin  && dotnet restore --verbosity d && dotnet publish -c Release -o ./obj/Docker/publish'
```
* Build image from `microsoft/aspnetcore:1.1.2`

Dockerfile:
```dockerfile
FROM microsoft/aspnetcore:1.1.2
ARG PROJECT
WORKDIR /app
COPY src/${PROJECT}/obj/Docker/publish .
RUN echo "dotnet ${PROJECT}.dll --urls http://*:80" > run.sh
```

* Docker run a container with the image

____________________

It would failed when it try to create a brotli stream:
>System.DllNotFoundException: Unable to load DLL 'brotlienc.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.IO.Compression.Interop.Brotli.BrotliEncoderCreateInstance(IntPtr allocFunc, IntPtr freeFunc, IntPtr opaque)
   at System.IO.Compression.BrotliNative.BrotliEncoderCreateInstance()
   at System.IO.Compression.Brotli.State.InitializeEncoder()
   at System.IO.Compression.BrotliStream..ctor(Stream baseStream, CompressionMode mode, Boolean leaveOpen, Int32 bufferSize)
   at CNBlogs.Msg.Web.Compression.BrotliCompressionProvider.CreateStream(Stream outputStream) in /src/src/CNBlogs.Msg.Web/Compression/BrotliCompressionProvider.cs:line 17
   at Microsoft.AspNetCore.ResponseCompression.BodyWrapperStream.OnWrite()

**Comment by shiftylogic** [comment]
I see what is going on.

The library is a portable library but uses the build environment to determine what native library to load. This works fine in the CI system since we build and run everything on the target machine. However, the package that is uploaded to myget is built in a Windows environment. Though it has all the artifacts necessary to run on any platform, the determination to use the Windows dlls was made at compile time.

I'll look into a fix for this. Thanks for bringing it up.

If you want to workaround the issue for yourself in the short-term, you could build the package out of CoreFxLab yourself via a Linux build environment and it should work for you.

**Comment by csongysun** [comment]
@shiftylogic Thanks for your help, I'll try to build a package for Linux environment.
