### ISSUE TITLE
Should Tensor<T> be backed by Buffer<T> instead of T[]?

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefxlab#1680]
The idea behind Tensor is to provide multi-dimensional array semantics on top of a segment of memory.   Today that is done using `T[]` but `Span<T>` *may* be a better fit. 

One thought about this is around how well interop works with Span<T>.  @stephentoub is it possible to pass a Span<T> to a pinvoke without copy?

**Comment by stephentoub** [comment]
> @stephentoub is it possible to pass a Span to a pinvoke without copy?

The plan is for P/Invoke to natively support `Span<primitive>` just as `primitive[]` is supported in DllImport signatures today.  But that's largely just syntactic sugar, and the underlying functionality can still be achieved, just manually.  Instead of something like:
```C#
[DllImport(...)]
static extern void Foo(Span<byte> bytes, int bytesLength);
...
Span<byte> bytes = ...;
Foo(bytes, bytes.Length);
```
you'd do:
```C#
[DllImport(...)]
static extern unsafe void Foo(byte* bytes, int bytesLength);
...
Span<byte> bytes = ...;
fixed (byte* ptr = &bytes.DangerousGetPinnableReference())
{
    Foo(ptr, bytes.Length);
}
```

**Comment by stephentoub** [comment]
> Today that is done using T[] but Span<T> may be a better fit.

`Span<T>` is a by-ref type; for it to be contained in a `Tensor<T>`, `Tensor<T>` would also need to be a by-ref type, which means it would incur the same constraints, e.g. stack-only, couldn't be a generic type argument, etc.

Potentially it could be backed by a `Buffer<T>` instead of a `T[]` or a `Span<T>`, though.  `Buffer<T>` can be constructed from either ` T[]` or a `T*`, so it would allow for `Tensor<T>` to wrap some existing native buffer while not incurring the constraints of having a `Span<T>` field.

**Comment by ericstj** [comment]
I don't think we want those constraints.  Let's look into Buffer<T>.

Will we be shipping Buffer<T> downlevel?  That'll be one of the concerns.  I'm planning to make Tensor<T> work for old versions of desktop.

**Comment by stephentoub** [comment]
> Will we be shipping Buffer downlevel? 

I believe that's in the plan, but @KrzysztofCwalina can answer for sure.

**Comment by KrzysztofCwalina** [comment]
Yes, Buffer<T> (now renamed to Memory<T>) will be in System.Memory.dll, which is an out-of-band package that should work down level.

cc: @ahsonkhan

**Comment by ericstj** [comment]
Got it.  I've started playing around with this and think it'll work.  I'll probably have both array and buffer 
 (and potentially unsafe T*) overloads for convenience but store as a buffer internally and expose as a buffer for interop.

**Comment by ahsonkhan** [comment]
> `Buffer<T>` can be constructed from either ` T[]` or a `T*`, so it would allow for `Tensor<T>` to wrap some existing native buffer while not incurring the constraints of having a `Span<T>` field

We currently do not have a way to construct `Buffer<T>` from a `T*`.

> Will we be shipping Buffer downlevel?

Yes, that is in the works currently: https://github.com/dotnet/coreclr/pull/13583

**Comment by stephentoub** [comment]
> We currently do not have a way to construct Buffer<T> from a T*.

I'll re-share my previous feedback that there should be a way to construct a `Buffer<T>` from a `T*` , and ideally without allocation :smile:

**Comment by KrzysztofCwalina** [comment]
There is a way to construct Memory<T> from T*, it just requires 50 or so lines of boilerplate code (to create a subtype of OwnedMemory).
We of course should (and will) add such subtype to the platform

**Comment by KrzysztofCwalina** [comment]
BTW, if we changed OwnedMemory.Pin and AsSpan to again support ranges (i.e. these two methods taking index and count), we could create a subtype of OwnedMemory that would manage lifetimes of multiple native pointers. This way, using native memory with Memory<T> would not have allocation overhead.

**Comment by Drawaes** [comment]
I had this exact discussion with @davidfowler the other night. The problem comes in SSLStream. You pass in a buffer and it decrypts in place. But that means you either slice a new buffer to return where the decrypted data is (allocate a buffer) or pass out an index and count which is just messy. Span doesn't work because it's async and you need to hold the result off stack.

**Comment by KrzysztofCwalina** [comment]
@Drawaes, why not use, and slice, Memory<T>?

**Comment by Drawaes** [comment]
So I was still working in a world were it was buffer and a class ;) so it should be fine with a struct.  Would be nice to have a struct that carries a pin plus the memory but I can write that myself ;)

**Comment by ericstj** [comment]
So I'm getting back to this and I see now that Buffer (now Memory<T>) doesn't have an array accessor.  Is the idea that you grab the Span and access with that?

If I'm going to be doing a lot of accesses would it make sense to get a pointer out of the span and interact with that instead?

In my scenario Slicing isn't important so I wonder if I end up paying overhead wrapping an array in a Memory object.

Do you think it would make more sense to have my types have modes (similar to Memory itself) where internally I have either a Memory<T>, T[], or T* so that I can use an optimal method of access, or should I just use Span and let the JIT/Runtime work to give me the best code.

**Comment by ahsonkhan** [comment]
> Is the idea that you grab the Span and access with that?

Yes

> If I'm going to be doing a lot of accesses would it make sense to get a pointer out of the span and interact with that instead?

You shouldn't need to get the pointer. Span indexer should be fast (at least for fast span).
cc @jkotas

**Comment by ericstj** [comment]
Got it, just wanted to understand best practice.  Do you suppose it matters that I'm also making this work on desktop where we won't have fast span?  I suppose we can measure that when we get there.

**Comment by jkotas** [comment]
It is the similar trade off as indexing into array vs. pinning the array and using unsafe pointers to avoid bounds checks.

**Comment by ahsonkhan** [comment]
> Do you think it would make more sense to have my types have modes (similar to Memory itself) where internally I have either a Memory, T[], or T* so that I can use an optimal method of access, or should I just use Span and let the JIT/Runtime work to give me the best code.

This is a good question. I am not certain which approach would be best. I am leaning towards using Span since it is meant to cover such a scenario and provide value to developers. If there are performance concerns with using Span for your scenario, we should address them.

cc @KrzysztofCwalina

**Comment by ericstj** [comment]
> It is the similar trade off as indexing into array vs. pinning the array and using unsafe pointers to avoid bounds checks.

I thought the JIT would understand array indexing inside a loop and avoid method calls and bounds checks even though the array wasn't pinned, where with Span I'll have both.

Ultimately this is all hypothetical and I need to try it out and measure to see if it matters.  It sounds like folks are saying: use Memory/Span and don't pre-emptively optimize.  I'll give it a try and let you know.

**Comment by jkotas** [comment]
> I thought the JIT would understand array indexing inside a loop and avoid method calls and bounds checks even though the array wasn't pinned, where with Span I'll have both

For fast Span (ie .NET Core today), the JIT does the exact same optimizations (bounds check removal, etc.) as for arrays. It understands the span indexing the same way as array indexing.

**Comment by KrzysztofCwalina** [comment]
You can read about the bounds checks optimizations at https://github.com/Microsoft/dotnet-blog/pull/256

**Comment by ericstj** [comment]
Thanks folks.  I want to make it clear that I'm aware of the optimizations that are happening, but its always good to have that information.

I'm pointing out that a good percentage of the customers of this library will not have fast-span, so I'll be moving from an array-based implementation (where they did get bounds check optimizations) to slow-span (where they will not get bounds check optimizations). 

Will that matter?  TBD.  I need to measure.  I can mitigate by making my types modal and working on the array or pointer instead.

**Comment by jkotas** [comment]
You should use Span or Memory as exchange type - not matter whether it is slow Span or fast Span.

If you find bad performance bottlenecks in particular methods with slow Span, you can optimize them using unsafe as necessary. These should be local optimizations. They should not affect overall design of the library. 

FWIW, ASP.NET Core Kestrel in .NET Core 2.0 shipped with their own local copy of slow Span and it was not a performance problem for them.
