### ISSUE TITLE
Add vectorization to Tensor operations

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefxlab#1683]
We should be able to easily vectorize the method bodies of https://github.com/ericstj/corefxlab/blob/563f023fe14a11a9ccb78f935475203ff3ba2b9c/src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.cs.

My thought to do this is add a Vector<T> method to https://github.com/ericstj/corefxlab/blob/563f023fe14a11a9ccb78f935475203ff3ba2b9c/src/System.Numerics.Tensors/System/Numerics/TensorTemplate.ttinclude#L59 and use this if `Vector.IsHardwareAccelerated`, otherwise just use the normal IL.

**Comment by ericstj** [comment]
Dependent on #1798

**Comment by tannergooding** [comment]
This issue was moved to dotnet/corefx#34511
