### ISSUE TITLE
System.IO.Compression.Brotli: .NET Standard 1.4 -> 1.1

### ISSUE THREAD

**Issue by Taritsyn** [dotnet/corefxlab#1684]
@Vedin It would be nice in the `System.IO.Compression.Brotli` library to downgrade .NET Standard version from 1.4 to 1.1. In general, class libraries which target a lower [.NET Platform Standard](https://github.com/dotnet/standard/blob/master/docs/versions.md) version, can be loaded by the largest number of existing platforms. Key libraries are still targeted on .NET Standard 1.1  (e.g., [`System.IO.Compression`](https://www.nuget.org/packages/System.IO.Compression/)).

Problems with the compilation will not be.

**Comment by danmosemsft** [comment]
@Taritsyn do you want to contribute a PR?

**Comment by Taritsyn** [comment]
Here is [my microscopic PR](https://github.com/dotnet/corefxlab/pull/1696).
