### ISSUE TITLE
Provide docs/example usage of System.IO.FileSystem.Watcher.Polling

### ISSUE THREAD

**Issue by lloydjatkinson** [dotnet/corefxlab#1688]
Currently there is no documentation for `PollingWatcher`. After reading the source I came up with what I believe should work, however I'm not seeing the breakpoint I added to the `ChangedAction` method being hit (and no output from the `Changed` action either).

```
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var watcher = new PollingWatcher(@"C:\Test",
                includeSubdirectories: true))
            {
                watcher.AddExtension(".txt"); // Also tried "txt"

                watcher.Changed = () => Console.WriteLine("Changes.");
                watcher.ChangedDetailed = ChangedAction;
                watcher.Start();
            }

            Console.ReadLine();
        }

        public static void ChangedAction(IEnumerable<FileChange> changes)
        {
            foreach (var file in changes)
            {
                Console.WriteLine($"{file.Name} {file.ChangeType}");
            }
        }
    }
```

If possible would documentation or an example of how PollingWatcher is envisioned to be used be provided? That would be great!

**Comment by lloydjatkinson** [comment]
Just realised there are tests for this, so I compared those to my current code and realised I wasn't subscribing correctly:

```
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var watcher = new PollingWatcher(@"C:\FCBA",
                includeSubdirectories: true))
            {
                watcher.AddExtension(".txt"); // Also tried "txt"

                watcher.Changed += () => Console.WriteLine("Changes.");
                watcher.ChangedDetailed += (changes) => ChangedAction(changes);
                watcher.Start();
            }

            Console.ReadLine();
        }

        public static void ChangedAction(IEnumerable<FileChange> changes)
        {
            foreach (var file in changes)
            {
                Console.WriteLine($"{file.Name} {file.ChangeType}");
            }
        }
    }
```

However, still no actions being fired when files change. I will checkout the repo and run the unit test next to see what I'm doing wrong.

**Comment by KrzysztofCwalina** [comment]
@lloydjatkinson, your code does not work because the watcher gets disposed right after it's started (at the end of the using statement).

**Comment by Kennedoom** [comment]
Did the old PollingWatcher code handle remote directory monitoring at all? Unable to use the latest versions at the moment due to a .NET Framework incompatibility with our live servers (pain in the neck) so stuck with the older code.

In my own dev testing, trying to connect to one of our other boxes, the directory just gets dropped from the list in the PollingWatcher during the start method.
