### ISSUE TITLE
System.CommandLine - Enforce required parameters

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/corefxlab#1689]
If you define a parameter and inspect the return `Argument`, the `IsRequired` property is set to true.  There doesn't appear to be any built-in validation logic that enforces parameter values are specified.  This can be solved by with the following pattern:

```
string sourceUrl = null;
Argument sourceUrlArg = syntax.DefineParameter("source-url", ref sourceUrl, "Base URL of the source code");
SourceUrl = sourceUrl;

if (sourceUrlArg.IsRequired && !sourceUrlArg.IsSpecified)
{
    syntax.ReportError($"`{sourceUrlArg.Name}` must be specified.");
}
```

I would expect that the System.CommandLine library would provide this functionality out of the box.

**Comment by MichaelSimons** [comment]
This is actually more difficult to implement on your own.  If you validate the parameter value is specified within the ArgumentSyntax.Parse method then prevent the built-in help functionality from running if a help option is specified but the parameter value isn't.

**Comment by andresmoschini** [comment]
@MichaelSimons, @daveaglick, @bricelam do you think that it could work?

```csharp
static class ArgumentSyntaxExtensions
{
    public static void ValidateRequiredParameters(this ArgumentSyntax syntax)
    {
        var missedArguments = syntax.GetActiveArguments()
            .Where(x => x.IsRequired && !x.IsSpecified);

        if (missedArguments.Any() && !syntax.IsHelpRequested())
        {
            var messages = missedArguments.Select(x =>
                $"`{string.Join("|", x.GetDisplayNames())}` must be specified.");
            syntax.ReportError(string.Join("\r\n", messages));
        }
    }

    // I had to copy the code because the original method is private
    // See https://github.com/dotnet/corefxlab/blob/e5950f4e145529e12915235e44afdf2eedcbca7c/src/System.CommandLine/System/CommandLine/ArgumentSyntax.cs#L85
    public static bool IsHelpRequested(this ArgumentSyntax syntax) =>
        syntax.RemainingArguments.Any(a => string.Equals(a, @"-?", StringComparison.Ordinal)
        || string.Equals(a, @"-h", StringComparison.Ordinal)
        || string.Equals(a, @"--help", StringComparison.Ordinal));
}
```
 Am I missing something? Is there a better approach?

**Comment by MichaelSimons** [comment]
@andresmoschini - looks reasonable to me.  My preference however would be to bake this into the library as the default behavior.
