### ISSUE TITLE
Single quoted names on System.Reflection.Metadata.Cil

### ISSUE THREAD

**Issue by SantiFdezM** [dotnet/corefxlab#169]
When an identifier (type, method, file, module, field, property, etc) name is not a valid msil name.

i.e:

`<>_System`

It needs to be single quoted in order to be valid and not have a syntax error.

i.e:

`'<>_System'`

cc @AlexGhiondea

**Comment by AlexGhiondea** [comment]
@SantiFdezM -- would you like to pick this up?

**Comment by SantiFdezM** [comment]
Yes!! @AlexGhiondea
