### ISSUE TITLE
Define semantics of value passed to buffer.Ensure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefxlab#1704]
`WriteableBuffer.Write(...)` can end up passing 0 into `buffer.Ensure` if it skips the fast path which results in an infinite loop and memory "leak"

https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines/WritableBufferExtensions.cs#L40

@pakrym

**Comment by davidfowl** [comment]
Done
