### ISSUE TITLE
Move Buffer<T> and friends to corlib, netstandard, system.runtime

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1711]

**Comment by KrzysztofCwalina** [comment]
Before the move, we also agreed to do the following cleanup:

1.	Cleanup span/buffer equality APIs (as discussed in review) <= Done (https://github.com/dotnet/corefxlab/pull/1646)
2.	Rename Buffer<T> to Memory<T>
3.	Remove offset from OwnedBuffer.Pin
4.	Remove OwnedBuffer.Add (will submit PR for this soon – using Unsafe.Add - https://github.com/dotnet/corefx/pull/20886)
5.	Remote IsRetainable and change Release return type to bool (PR needs to be updated - https://github.com/dotnet/corefxlab/pull/1648)

**Comment by ahsonkhan** [comment]
> Span and Buffer ctros should be the same. See dotnet/corefx#23471

Is this work item solely about removing Memory(T[], int) ctor or are there other constructors we want to add/remove?

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina, can we consider this work/issue complete? The extension work can be tracked by the api review issue - https://github.com/dotnet/corefx/issues/23862

**Comment by KrzysztofCwalina** [comment]
Yeah, go ahead and close it. Just make sure the extensions issue does not get lost.
