### ISSUE TITLE
API Review Cleanup for System.Text.Primitives

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1714]
These are cleanup workitems based on API reviews, and other discussions that we would like to do before moving the component to corefx repo:

- [x] hide byte* and char* parsing APIs. Span APIs should be used instead
- [ ] More datatypes can be formatted than parsed. We should make the parse/format API symmetrical. #1755
- [x] PrimitiveParser has inner types for efficient invariant and hex parsing. This is also inconsistent with the formatting APIs. I would hide the hex inner types and add invariant inner types to the formatter. e.g. public static class Formatter { public static class Ut8 {…}  public static class Ut16 {…}  public static class Custom {…}  }.
- [x] Namespace should be System.Buffers (in a separate workitem we will place the APIs in System.Buffers.dll)
- [x] Move ParsedFormat to System namespace (we will use it for more than just text)
- [x] Rename TransformationStatus to OperationStatus (we will rename the interface later)
- [x] TransformationStatus.NeedMoreSourceData to TransformationStatus.NeedMoreData 
- [x] Consider renaming PrimitiveFormatter to Formatter and PrimitiveParser to Parser

**Comment by AtsushiKan** [comment]
Official api review is done.
