### ISSUE TITLE
Move System.Text.Primitives to Corefx

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1716]
- [ ] Move the following types (with dependencies): PrimitiveParser, PrimitiveFormatter, Utf16, Utf32, Utf8
- [ ] The types should move to System.Buffers.dll
- [ ] Most types move to System.Buffers.Text namespace. ParsedFormat moves to System.Buffers

**Comment by KrzysztofCwalina** [comment]
done (not Utf16 and 32, but we will track it separately)

**Comment by ahsonkhan** [comment]
From https://github.com/dotnet/corefxlab/issues/1730#issuecomment-349014262

> Looks like we should be able to replace our `TryParseInt32` method
https://github.com/aspnet/SignalR/blob/e4671392ecd9c4c23c2d65492c29f322f9610efe/src/Microsoft.AspNetCore.SignalR.Common/Internal/Encoders/LengthPrefixedTextMessageParser.cs#L94
with the one from System.Buffers.Binary.BinaryPrimitives
Don't think we have any other spots we do similar things, but I'm not familiar with the System.Binary APIs

@BrennanConroy, can you replace the method you linked above with our Utf8Parser?

https://github.com/dotnet/corefx/blob/master/src/System.Memory/ref/System.Memory.cs#L418

**Comment by BrennanConroy** [comment]
Looks possible, I'll try it out today

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/pull/1200
