### ISSUE TITLE
Struct tearing issue with Buffer<T>?

### ISSUE THREAD

**Issue by mjp41** [dotnet/corefxlab#1717]
I have been a bit remis on checking on the progress of `Buffer<T>`.  I just read the code. Is there a struct tearing issue with it? There are a bunch of checks like

```csharp
    if (_index < 0)
```

And then they go on to do some unsafe cast based on this.

```csharp
   Unsafe.As<OwnedBuffer<T>>(...)
```

But by this point the underlying storage could have been updated to point to an array instead of an `OwnedBuffer`, and thus the method won’t exist on this object type.

My understanding is that the `readonly` does not save you here, as that only modifies what the struct can do to the storage, but the containing object can override that, using struct copies. 

@KrzysztofCwalina @ahsonkhan @jkotas

**Comment by jkotas** [comment]
Buffer<T> is unsafe type. It has struct tearing issues, conversions to Span have lifetime issues, ... . It was decided that squeezing every cycle out of it is more important than safety.

I think the problem now is how to explain this in documentation, how to ensure that code that operates on `Buffer<T>` is treated as security risk and gets same level of scrutiny as unsafe code, etc.

**Comment by mjp41** [comment]
Closing as this is addressed in the PR on CoreCLR: https://github.com/dotnet/coreclr/pull/13583
