### ISSUE TITLE
Add CancellationToken to ReadableChannel<T>

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1723]
So that I don't have to convert this task (https://github.com/dotnet/corefxlab/blob/1d690999ac3d4010b282def0cb946bea72a214a3/src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ReadableChannel.cs#L22) to a `CancellationToken` (related https://github.com/dotnet/corefx/issues/23590)

**Comment by stephentoub** [comment]
@davidfowl, can you be more specific?  You want to pass a CancellationToken to a ReadableChannel?  You want ReadableChannel to expose a CancellationToken that's canceled when it completes?  Something else?  And specific to ReadableChannel?

**Comment by davidfowl** [comment]
> You want ReadableChannel to expose a CancellationToken that's canceled when it completes?

This. Specific to ReadableChannel because that's where the Task that represents completion exists today.

**Comment by stephentoub** [comment]
Thanks.  I'm hesitant to add another "this is completed property", but I'll think about it some more.  In the meantime, it's of course possible to add one's own Task->CancellationToken conversion: https://github.com/dotnet/corefx/issues/23590#issuecomment-325975594
