### ISSUE TITLE
Productize System.Binary.Base64

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1729]
Probably in this order:

- [x] Move non-obsolete APIs to  ~System.Buffers.dll~ System.Memory.dll in corefx and namespace ~System.Buffers~ System.Buffers.Text
- [x] Port SignalR to the new APIs
- [x] Remove corfxlab project.
- [x] Ensure good test coverage

**Comment by ahsonkhan** [comment]
Waiting for SignalR to start using these APIs for validation as the last work item for this issue, similar to https://github.com/dotnet/corefxlab/issues/1730#issuecomment-337632375.

@muratg, @moozzyk @BrennanConroy

**Comment by moozzyk** [comment]
I will start looking into tomorrow.

**Comment by ahsonkhan** [comment]
This is now complete. See https://github.com/aspnet/SignalR/pull/1127
