### ISSUE TITLE
System.Reflection.Metadata.Cil shouldn't use yield return on IEnumerators.

### ISSUE THREAD

**Issue by SantiFdezM** [dotnet/corefxlab#173]
This shouldn't be used because this is inefficient an sometimes unpredicatble.

See:
https://github.com/dotnet/corefxlab/blob/master/src/System.Reflection.Metadata.Cil/src/CilAssembly.cs#L324-L332

There is a lot of places where this is used.

cc @AlexGhiondea

**Comment by AlexGhiondea** [comment]
@SantiFdezM -- would you like to pick this up?

**Comment by SantiFdezM** [comment]
Yes -- this week. @AlexGhiondea

**Comment by felipegtx** [comment]
@SantiFdezM care to explain why you think *yield* is bad in this case? I'm specially curious on the 'unpredicatble' topic.
