### ISSUE TITLE
Productize System.Binary Reader/Writer

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1730]
- [x] hide public static void RequiresInInclusiveRange(int start, uint length);
- [x] Why don't we have Try* versions of BE and LE?
- [x] Conduct API review
- [x] Move the code to corefx repo into ~System.Buffers~ System.Memory dll and System.Buffers namespace
- [ ] Port SignalR to the new APIs
- [x] Remove corfxlab project.
- [x] Ensure good test coverage

**Comment by ahsonkhan** [comment]
> Port SignalR to the new APIs

@KrzysztofCwalina, @muratg, @pavel, this is the only thing left for this work item. Can we consider this issue complete?

**Comment by KrzysztofCwalina** [comment]
I would wait till SignalR is actually ported. It's a good validation for the API

**Comment by muratg** [comment]
@moozzyk @BrennanConroy FYI

**Comment by ahsonkhan** [comment]
@moozzyk, @BrennanConroy, have you guys ported SignalR to use these new APIs?

**Comment by muratg** [comment]
cc @anurse

**Comment by BrennanConroy** [comment]
Looks like we should be able to replace our `TryParseInt32` method
https://github.com/aspnet/SignalR/blob/e4671392ecd9c4c23c2d65492c29f322f9610efe/src/Microsoft.AspNetCore.SignalR.Common/Internal/Encoders/LengthPrefixedTextMessageParser.cs#L94
with the one from System.Buffers.Binary.BinaryPrimitives

Don't think we have any other spots we do similar things, but I'm not familiar with the System.Binary APIs

**Comment by BrennanConroy** [comment]
I don't see anything we can replace with the System.Binary APIs

**Comment by ahsonkhan** [comment]
> I don't see anything we can replace with the System.Binary APIs

OK. I thought maybe you were reading/writing binary data from/to primitives like int32.

**Comment by anurse** [comment]
SignalR did previously have more custom binary parsing, but we ended up changing to using existing protocols and other parsers not supported in System.Binary (such as variable-length integers). It's possible it was just missed.

**Comment by ahsonkhan** [comment]
Given that SignalR doesn't have a scenario for these APIs yet, I would consider this issue complete.
