### ISSUE TITLE
Should CilDecoder decode tokens for instructions as CilEntity on System.Reflection.Metadata.Cil?

### ISSUE THREAD

**Issue by SantiFdezM** [dotnet/corefxlab#174]
Should decoded tokens be referenced as CilEntity objects instead of strings on `CilStringInstruction`?

In order to do this there should be an implementation of CilMemberReference (FieldRef, MethodRef) and CilMethodSpecification.

cc @AlexGhiondea

**Comment by ahsonkhan** [comment]
cc @safern
