### ISSUE TITLE
System.CommandLine - Is it possible to strip dependencies?

### ISSUE THREAD

**Issue by ghost** [dotnet/corefxlab#1760]
Hello everyone,

after experimenting with CLAP: .NET Command-Line Auto-Parser, Command Line Parser Library and Fluent Command Line Parser I finally was pointed to System.CommandLine and instantly setup NuGet and gave it a try and I am pleased that I have found a decent library that wasn't as outdated or bad as the other projects.

Unfortunately NuGet installed a huge amount of dependencies which results in 100 DLLs in my binary folder of the application which seem to be NETStandard or so. Is there any way to strip these dependencies and make this bearable? 100 DLLs with 5 MB just for a 25 KB console application is a ridiculous overkill 😅

**Comment by YohDeadfall** [comment]
@ahsonkhan This issue and [other](https://github.com/dotnet/corefxlab/labels/area-System.CommandLine) should be closed since the project is archived.
