### ISSUE TITLE
Improve Diagnose Api of (Buffered)Channel

### ISSUE THREAD

**Issue by JanEggers** [dotnet/corefxlab#1782]
hi there,

im currently experimenting with System.Threading.Tasks.Channels.Channel.

for perfromance analysis it would be really great if BoundedChannel would be a public type and has properties that express the current buffer fill level.

Right now im using reflection to get that Info but i wonder why you make that an internal. (the info is there via debugview but neither toString or any public api can be used to get that information)

im using that information to determine performance bottlenecks in my app. I know that consumers of buffers with growing fill level have to be optimized.

**Comment by KrzysztofCwalina** [comment]
@stephentoub, is this still relevant? If yes, should we move it to corefx? I would like to remove System.Threadin.Channels issues from corfxlab

**Comment by stephentoub** [comment]
It's still relevant (though debatable whether we should do it or not).  Feel free to move it to corefx. Thanks.

**Comment by KrzysztofCwalina** [comment]
@JanEggers, could I please ask you to move this to corefx repo? The component itself was moved there and it would be good to have the issue there as well.

**Comment by stephentoub** [comment]
This issue was moved to dotnet/corefx#25162
