### ISSUE TITLE
BytesReader seems not to work correctly

### ISSUE THREAD

**Issue by JanEggers** [dotnet/corefxlab#1783]
im using System.Buffers.Experimental 0.10-e170922-1

and i have two issues with BytesReader:

1. Advance and ReadBytes dont increment Index (acording to source it looks fine so i dont know if im missing something)

![image](https://user-images.githubusercontent.com/6747376/30773637-c0720d9e-a074-11e7-914f-782e03b33459.png)

2. When reading more bytes then present i get a nullpointer exception, i would expect argument or invalidoperaationexception.

**Comment by Drawaes** [comment]
Bytesreader is a struct right? I would presume you are passing it into a function and reading and then in the outer function it hasn't advanced. You need to pass by ref if this is your situation.

**Comment by JanEggers** [comment]
thx man. i passed it in the constructor if my reader if i pass it to every call it works as expected. im not used to structs anymore :)

**Comment by Drawaes** [comment]
👍
