### ISSUE TITLE
Index out of range while slicing ReadOnlyBuffer

### ISSUE THREAD

**Issue by JanEggers** [dotnet/corefxlab#1791]
hi there im having issues with ReadOnlyBuffer.

![image](https://user-images.githubusercontent.com/6747376/30910204-196eb9a8-a384-11e7-94a4-c1004f809826.png)

![image](https://user-images.githubusercontent.com/6747376/30910282-61fa484a-a384-11e7-9bab-0222d1536701.png)

the ReadCursor is at 4018 end is 4032 and im trying to slice 2. why do i get index out of bounds exception? for me the segment in the cursor looks broken as readcursor.tosting ends with hello w but the segment seem to just contain the first character

**Comment by JanEggers** [comment]
the issue seems to be that the buffer is not a single span buffer and end.index is smaller than start.index

**Comment by JanEggers** [comment]
i switched to ReadableBufferReader and now the issue is more clear. the end of the buffer is set wrong by System.IO.Pipelines.Socket.SocketConnection. the reader has readcursor at index 3116 with end = true but the read result (input) of the socket pipe says end is readcoursor at 3120 but that does not have IsEnd = true so i suppose the endcoursor of the readbuffer produced by the socket is wrong.

![image](https://user-images.githubusercontent.com/6747376/31048503-838c769e-a61e-11e7-84c2-681dc7cf3e5c.png)

**Comment by davidfowl** [comment]
@JanEggers just FYI, we have no plans to ship:

- System.IO.Pipelines.Networking.Libuv
- System.IO.Pipelines.Networking.Sockets
- System.IO.Pipelines.Networking.Windows.RIO

These implementations exist to help push the design of pipelines forward but the true implementations will ship as part of the bedrock effort described here https://github.com/aspnet/KestrelHttpServer/issues/1980.

We should still make sure this isn't a general pipeline issue.

**Comment by JanEggers** [comment]
im just experimenting with the bits i can find until the rock rocks

**Comment by davidfowl** [comment]
Kewl. Also you might want to look at https://github.com/aspnet/KestrelHttpServer/blob/bb9840a5529405fb0a78d8acf748e9390786e9b0/src/Kestrel.Core/Internal/Http/HttpParser.cs to see how a very fast parser can be written using pipelines APIs today.

**Comment by JanEggers** [comment]
my fault after all, reader.end == input.end, the issue was my parser that calculated the remaining bytes based on reader.Index and not reader.ConsumedBytes. for me it would have been less confusing if the reader has a Length property with the length of the buffer or Index could be renamed to IndexInCurrentSpan like the Span property should be CurrentSpan to indicate it is not the complete span, or if there would be a Property with the total remaining bytes because that was where i screwed it up.
