### ISSUE TITLE
Consider a data type that has similar characteristics to Tensor but can handle heterogeneous data

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefxlab#1794]
Basic idea is a DataTable that is more friendly to interop.  It could be composed of tensors.

Python uses a Pandas DataFrame.

An open standard for such a format is https://arrow.apache.org/

An implementation of this in python (and a few other languages) is feather https://github.com/wesm/feather.  We could create .NET bindings for feather or implement arrow ourselves in .NET.  It could be composed-of/share-code-with/wrap tensor or be a separate library entirely.

**Comment by danmosemsft** [comment]
I'm going to close as dupe.
