### ISSUE TITLE
x86

### ISSUE THREAD

**Issue by KevinJosephMorin** [dotnet/corefxlab#18]
I have a Windows 10 x64 Preview machine running Visual Studio 2015.  When I git clone the corefxlab project, I am able to compile a 64bit version of the console application and it works perfectly including nuget grabbing all necessary files.  If I set application to compile as x86, the application compiles but close immediately.  Would you expect that this would work with x86?

**Comment by KrzysztofCwalina** [comment]
This whole area moved to https://github.com/dotnet/cli
