### ISSUE TITLE
InvalidOperationException while reading a pipe with maximumSizeHigh

### ISSUE THREAD

**Issue by JanEggers** [dotnet/corefxlab#1803]
Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting
 bei System.IO.Pipelines.PipelinesThrowHelper.ThrowInvalidOperationException(ExceptionResource resource, String location)
   bei System.IO.Pipelines.Pipe.System.IO.Pipelines.IPipeReader.Advance(ReadCursor consumed, ReadCursor examined)

i get this exception while reading from a pipe created with maximumSizeHigh: 10 * 1024 and reading until the end.
if i dont use the option my testapp generates outofmemory fast. so how am i supposed to synchronize this? or what is the correct way to limit the buffersize?

**Comment by davidfowl** [comment]
If you're getting that exception it means that you keep advancing without consuming anything. Are you're trying to parse a length prefixed payload?

**Comment by JanEggers** [comment]
i consume bytes in that case.

![image](https://user-images.githubusercontent.com/6747376/31048680-9e1a749e-a622-11e7-9791-4876d7ab4444.png)

the code is at 
https://github.com/JanEggers/MQTTnet/tree/system.io.pipelines

if you enable the test at https://github.com/JanEggers/MQTTnet/blob/603313353089e8d274c49563fd645075eacf58eb/MQTTnet.TestApp.NetCore/PerformanceTests/PerformanceTestSelector.cs#L31

and change the parameter to 10 * 1024 at https://github.com/JanEggers/MQTTnet/blob/603313353089e8d274c49563fd645075eacf58eb/MQTTnet.TestApp.NetCore/PerformanceTests/MqttChannelAdapterTest.cs#L106

the exception is triggered when reading until the end of the buffer.

i can prepare a branch with the changes mentioned above so you just have to hceck out and run if you want to have a look at it

**Comment by JanEggers** [comment]
found the issue myself :) problem was that i didnt provide maximumSizeLow and default is 0 so the writer was never sheduled when reading. so maybe the constructor of the pipe should verify the options so that if max is provided min must be > 0
