### ISSUE TITLE
Binary Write/Put/Poke/Set and Read/Peek/Get

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1807]
cc: @ahsonkhan, @stephentoub, @davidfowl, @weshaggard, @terrajobst, @joshfree, @AtsushiKan, @pakrym, @anurse, @GrabYourPitchforks, @ianhays, @bartonjs, @benaadams 

Today, [Binary](https://github.com/dotnet/corefxlab/blob/74ca8904031daf2d734104b90a6a5dadd22285c0/src/System.Binary/System/Binary/BufferReader.cs#L7) class has methods named Read/Write, e.g.
```c#
span.WriteInt32(value);
value = span.ReadInt32();
```

During the API review people commented that the names imply that there is some index being advanced when the methods are called, i.e. subsequent calls to Read would read subsequent values.

Here are some alternative names we would like to explore. Please vote for the proposals, or add your own:

**Comment by KrzysztofCwalina** [comment]
```c#
span.WriteInt32(value);
value = span.ReadInt32();
```

**Comment by KrzysztofCwalina** [comment]
```c#
span.PokeInt32(value);
value = span.PeekInt32();
```

**Comment by KrzysztofCwalina** [comment]
```c#
span.SetInt32(value);
value = span.GetInt32();
```

**Comment by KrzysztofCwalina** [comment]
```c#
span.PutInt32(value);
value = span.GetInt32();
```

**Comment by KrzysztofCwalina** [comment]
```c#
span.PutInt32(value);
value = span.AsInt32();
```

**Comment by anurse** [comment]
Agreed with the name confusion on `Write`. I think I would lean towards `Set` (I'm not too worried about the confusion around replacing the whole span, it's got "32 bits" right in the name so I'd assume it would fill the first 32 bits only) or `Put`. I'd love to have `Poke` but I think other than the nostalgia, it's not a very approachable name :)

**Comment by benaadams** [comment]
`Set` (or `Put`)

However, this should definitely exist 😉 
```csharp
namespace Microsoft.VisualBasic
{
    public static class SpanExtensions
    {
        public static void Poke<T>(this Span<byte> buffer, T value) => buffer.Set(value);
    }
}
```

**Comment by KrzysztofCwalina** [comment]
Well, we chose the boring old Read/Write :-)

**Comment by benaadams** [comment]
But you know it makes sense for the VB namespace...

https://en.wikipedia.org/wiki/PEEK_and_POKE

> These commands are particularly associated with the BASIC programming language

**Comment by KrzysztofCwalina** [comment]
good idea for my April 1st PR
