### ISSUE TITLE
Consider implementing Base64url transformation

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/corefxlab#1808]
Base64url is widely used by web applications.  
Current implementations are based on base64 encoding then replacing characters and trimming padding.
It can be optimized by directly implementing the base64url specifics within the main transformation loop.

**Comment by GrabYourPitchforks** [comment]
Ideally we'd support base64, base64url, and hex transformations as the first batch when the transformation API design is finalized.

**Comment by KrzysztofCwalina** [comment]
The following sample shows how it can be done today: https://github.com/dotnet/corefxlab/blob/master/src/System.Azure.Experimental/System/Azure/CosmosDbAuthorizationHeader.cs#L45

How much more efficient can the specialized encoder be?

**Comment by ycrumeyrolle** [comment]
Not sure to understand the sample. It is Base64 encoding, not Base64Url encoding. 
If we have to encode in Base64Url in this sample, it is required to replace '+' and '/' characters by '-' and '_', and to trim the trailing '=' .

**Comment by KrzysztofCwalina** [comment]
I was just showing how IBufferOperation can be used to combine transformations, wondering if ToBase64Url transformation that swaps the chars a(e.g. + => -) and returns before the trailing == would not be fast enough. I think specialized transformation will be more convenient though.

**Comment by ycrumeyrolle** [comment]
Ok I see your point.

Another argument in addition to the performance is the API surface. Just last day I spotted a bug on our API gateway, written in Java. The developers were decoding in Base64 the content, then URL decoding, as there is not explicit Base64Url API.
And sometimes "data corruption" strangely occurred...
