### ISSUE TITLE
Channel.WaitToReadAsync ignores cancellation token when there are items in buffer

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefxlab#1813]
https://github.com/dotnet/corefxlab/blob/9ac45562a90a46201d15cf17c3b538ebbdbb013c/src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnboundedChannel.cs#L117-L119

Generally expected behavior when a token is cancelled is for methods to throw, but here it will check the item buffer and short circuit without checking the token if an item exists.

**Comment by stephentoub** [comment]
FWIW, I did this on purpose for performance reasons.  If you look back through the commit history, there's a PR somewhere where I made all of the channels consistently check for data first before checking for cancellation.

**Comment by BrennanConroy** [comment]
Oh. It's just unexpected, the issue I ran into with it is very easily worked around, just wanted to raise an issue because of how odd it seemed.
________________________________

**Comment by ppcuban** [comment]
Shouldn't this issue be closed?

**Comment by stephentoub** [comment]
> Shouldn't this issue be closed?

Not if it's surprising enough that we want to change the implementation.
