### ISSUE TITLE
Tensor slicing

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefxlab#1819]
The scenario is that you have a Tensor and want to provide a slice of it as another Tensor.

The slice could take a number of forms:
1. n-d Tensor, slice to n-1-d where value for reduced dimension is passed in.  EG: give a tensor for row 5.
2. Slice a range of an n-d Tensor to an n-d Tensor.  Similar to above but over a range. EG: give a tensor for rows 3-6.

It's possible to have more than one sliced dimension and also possible to slice dimensions in the middle (not just first/last dimension).

Slicing should be possible merely by manipulating the dimensions and strides independently using the same backing memory.   In this way a slice is a view of the backing storage.  Calling To*Tensor on a sliced tensor would copy it and compact the sliced data.

**Comment by ericstj** [comment]
Here's a real example of the second scenario.

Given a 2-dimensional image represented as a tensor, suppose we wish to crop to a portion defined by rectangle ((100, 600), (200, 800)).  This is really two slicing operations where we slice the first dimension from (100, 600) and the second dimension from (200, 800).

**Comment by eerhardt** [comment]
Here's an experiment as a step towards this

https://github.com/ericstj/corefxlab/commit/870d7b8a22b432d362b783f501d510ce98ceffaf

**Comment by eerhardt** [comment]
Completed with https://github.com/dotnet/corefxlab/pull/1927
