### ISSUE TITLE
HTTP headers are ASCII not UTF8

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#182]
https://tools.ietf.org/html/rfc7230#section-3.2.4

> Historically, HTTP has allowed field content with text in the
>    ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
>    through use of [RFC2047] encoding.  In practice, most HTTP header
>    field values use only a subset of the US-ASCII charset [USASCII].
>    Newly defined header fields SHOULD limit their field values to
>    US-ASCII octets.  A recipient SHOULD treat other octets in field
>    content (obs-text) as opaque data.

So https://github.com/dotnet/corefxlab/blob/master/demos/LowAllocationWebServer/HttpRequestParser.cs
 should be parsing bytes based on US-ASCII rather than UTF8 data

**Comment by KrzysztofCwalina** [comment]
Good to know. When we add validation to the code we will make sure non-ascii characters are handled properly.
