### ISSUE TITLE
Investigate branchless Utf8 Decoder

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#1831]
http://nullprogram.com/blog/2017/10/06/

https://github.com/skeeto/branchless-utf8

Needs 4 bytes in buffer

/cc @KrzysztofCwalina

**Comment by davidfowl** [comment]
I just emailed this to people 😬

**Comment by benaadams** [comment]
Discussion https://news.ycombinator.com/item?id=15423674

**Comment by GrabYourPitchforks** [comment]
Give me a while to investigate this. My focus right now is on bulk validation / conversion of incoming UTF-8 data, and the branchless decoder seems geared more toward enumeration of individual scalars from a UTF-8 sequence.

I set up a quick benchmark using the branchless decoder in a bulk conversion scenario, and the performance was unfortunately quite bad, even after manually inspecting the codegen to ensure no branching, stack spillage, or complex indirection (e.g., accessing static fields). I suspect some of this is due to the fact that the JITter doesn't perform as low-level optimizations as the C compiler does, but TBH that wouldn't account for the 10x difference in performance I saw.

**Comment by kasper3** [comment]
@GrabYourPitchforks, do you have the implementation handy? We can create a PR and then compare the codegen to find out where we are losing the performance.

Here is the handwritten assembly version of [that C code](https://github.com/skeeto/branchless-utf8/tree/master/test):

Assembly: https://github.com/bdonlan/branchless-utf8/blob/master/test/decode.s
Assembly with SIMD: https://github.com/bdonlan/branchless-utf8/blob/master/test/decode-simd.s

cc @4creators, @tannergooding, @fiigii

**Comment by kasper3** [comment]
Maybe it can be implemented in C in CoreCLR. Rough transpilation of C->C# looks like this (not sure how to test it with all those `uint` parameters)

```c#
using System;

public class BranchlessEncoder
{
    private const byte Utf8Accept = 0;

    private static byte[] s_utf8d = {
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 00..1f
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 20..3f
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 40..5f
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 60..7f
        1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9, // 80..9f
        7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7, // a0..bf
        8,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2, // c0..df
        0xa,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x4,0x3,0x3, // e0..ef
        0xb,0x6,0x6,0x6,0x5,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8, // f0..ff
        0x0,0x1,0x2,0x3,0x5,0x8,0x7,0x1,0x1,0x1,0x4,0x6,0x1,0x1,0x1,0x1, // s0..s0
        1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,1, // s1..s2
        1,2,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1, // s3..s4
        1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,3,1,1,1,1,1,1, // s5..s6
        1,3,1,1,1,1,1,3,1,3,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1, // s7..s8
    };

    public static void Utf8Decode(ref uint state, ref uint codep, uint input)
    {
        uint type = utf8d[input];

        codep = (state != Utf8Accept) ?
            (input & 0x3fu) | (codep << 6) :
            (0xff >> type) & (input);

        state = s_utf8d[256 + state * 16 + type];
    }

    public static void Utf8Encode(ref ReadOnlySpan<char> buf, long c)
    {
        char s = buf[0];
        if (c >= (1L << 16))
        {
            s[0] = 0xf0 | (c >> 18);
            s[1] = 0x80 | ((c >> 12) & 0x3f);
            s[2] = 0x80 | ((c >> 6) & 0x3f);
            s[3] = 0x80 | ((c >> 0) & 0x3f);
            return s + 4;
        }
        else if (c >= (1L << 11))
        {
            s[0] = 0xe0 | (c >> 12);
            s[1] = 0x80 | ((c >> 6) & 0x3f);
            s[2] = 0x80 | ((c >> 0) & 0x3f);
            return s + 3;
        }
        else if (c >= (1L << 7))
        {
            s[0] = 0xc0 | (c >> 6);
            s[1] = 0x80 | ((c >> 0) & 0x3f);
            return s + 2;
        }
        else
        {
            s[0] = c;
            return s + 1;
        }
    }
}
```

**Comment by GrabYourPitchforks** [comment]
The loss in performance seems due to the fact that UTF8 doesn't consist of randomly distributed characters. If you see a character from a certain character set, the next several characters (excluding whitespace and punctuation) are almost certainly going to be in that same range. This implies that branching is good as long as it's used wisely. We have a prototype decoder in corefxlab which takes advantage of this behavior, and it's significantly faster than other decoders we've tried using our sample corpuses.

**Comment by kasper3** [comment]
From the ycombinator thread, the author of [assembly versoin](https://github.com/bdonlan/branchless-utf8/blob/master/test/decode.s) and [SIMD version](https://github.com/bdonlan/branchless-utf8/blob/master/test/decode-simd.s) claims to have better performance than the C version:

```
assembly: 577.333 MB/s
branchless: 490.666725 MB/s, 0 errors
0xe9 small: 380.000045 MB/s, 0 errors
Hoehrmann:  337.333374 MB/s, 0 errors
```

would be nice if we could compare corefxlab implemention's performance against [their tests](https://github.com/skeeto/branchless-utf8/blob/master/test/tests.c) and those number.

**Comment by Astn** [comment]
Maybe you all have already seen this, but here it is just in case you haven't.
https://github.com/bdonlan/branchless-utf8/commit/3802d3b0e10ea16810dd40f8116243971ff7603d

> This decoder decodes four characters at a time using vector operations.
> 
> Performance results on an Intel i7-7500U @ 2.7GHz (running ubuntu kernel 4.10.0-35-generic):
> 
> asm: 664.000079 MB/s, 0 errors
> simd: 754.666757 MB/s, 0 errors
> branchless: 448.000053 MB/s, 0 errors
> Hoehrmann:  372.000044 MB/s, 0 errors
> 
> Performance on an i7-4770 @ 3.40 GHz (running Windows Linux mode):
> asm: 653.333411 MB/s, 0 errors
> simd: 21.333336 MB/s, 0 errors
> branchless: 464.000055 MB/s, 0 errors
> Hoehrmann:  386.666713 MB/s, 0 errors
> 
> As you can see, depending on the CPU microarchitecture it may or may not be a win.

**Comment by kasper3** [comment]
cool, asm's throughput is still outstanding.

**Comment by mburbea** [comment]
My guess is that the SIMD forces thermal limits on the kaby lake laptop processor. I can't see why it would deviate so much otherwise.
