### ISSUE TITLE
Broken link in Span documentation

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/corefxlab#1837]
In [the `Span<T>` documentation,](https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md) it talks about a `Memory<T>` type that makes `Span<T>` easier to use, and includes a link to an implementation.  This link resolves to a GitHub 404 page, as do all the subdirectories above it for several levels.

**Comment by Drawaes** [comment]
It's probably because they moved to core proper ;)

**Comment by masonwheeler** [comment]
@drawaes In that case the documentation should be updated to reflect that.

**Comment by ahsonkhan** [comment]
Other links need to be updated too, such as:
> A prototype of such fast `Span<T>` can be found [here](https://github.com/dotnet/coreclr/blob/SpanOfT/src/mscorlib/src/System/Span.cs).

> A prototype of this design can be found [here](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Span.cs).

> See a prototype of `Memory<T>` [here](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Buffers/Memory.cs).

**Comment by YohDeadfall** [comment]
#1894

**Comment by ahsonkhan** [comment]
Resolved in https://github.com/dotnet/corefxlab/pull/1894
