### ISSUE TITLE
Pipelines Writer .... Please bring back BytesWritten

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1838]
This was removed from the API review, but its pretty critical and here is why....

You have a framing method that has a size header.

You call a bunch of functions to "write" data into the frame

You exit said functions and now you need to write a footer or back in the header the size of the frame.

How do I know how much I have written?

I have to add a return value from every method that writes or might write to the buffer to "track" how much has been written and sum it all up. Miss some.. well then you are stuffed...

So can we please bring this back ...

(If it was an problem with perf, then surely that can be fixed now or later, but the API shape is important)

**Comment by davidfowl** [comment]
@KrzysztofCwalina Should this be on IOutput/IBufferWriter?

**Comment by KrzysztofCwalina** [comment]
I think this is useful on BufferWriter (by-ref struct wrapping IBufferWeriter/PipeWriter). I am not sure it's useful on IBufferWriter, or even PipeWriter.

@Drawaes, if you used BufferWriter to write, you'd have [BufferCount](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Experimental/System/Buffers/Text/BufferWriter.cs#L36) property. Would it work for you?

**Comment by Drawaes** [comment]
Yeah that might work. I need to refactor to the new API surface but have been waiting for the dust to settle. I will close for now if there is already Buffer count and reopen if it's an issue .

**Comment by KrzysztofCwalina** [comment]
Which makes me think that IBufferWriter/PipeWriter are actually not writers. They are byte sinks. IBufferWriter is a synchronous sink. PipeWriter is an asynchronous sync.

**Comment by Drawaes** [comment]
It's kind of a bit odd naming with how things have evolved as you really shouldn't be using them as your writer primative
