### ISSUE TITLE
Pipelines bring back the AsReadable on the writer

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefxlab#1839]
Kinda linked to #1838 

If you again are writing several layers deep, then at the end you need to say sign the data (hash, or CRC etc) there is no way to get it back. You have to pass around a hash object and write to that for every write....

This makes me sad... can we have it back?

**Comment by muratg** [comment]
@Drawaes could you move this one to CoreFX repo please?

**Comment by muratg** [comment]
@Drawaes could you move this one to CoreFX repo please?

**Comment by davidfowl** [comment]
Not sure this is relevant anymore.

**Comment by Drawaes** [comment]
It might be relevant for others, but in my case I coded around it... so happy for it to stay closed and not moved.
