### ISSUE TITLE
Consider implementing struct Enumerator on Tensor<T>

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefxlab#1893]
See https://github.com/dotnet/corefxlab/pull/1884#issuecomment-340010018.

Implementing a struct Enumerator has better performance characteristics when directly enumerating the type - no allocations; no virtual calls, inlining.

We should determine if this makes sense for Tensor, and implement it, if so.

**Comment by tannergooding** [comment]
This issue was moved to dotnet/corefx#34524
