### ISSUE TITLE
Need unit tests for parsing methods on Date and Time types

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/corefxlab#1912]
Need to add unit tests for all `Parse`, `ParseExact`, `TryParse`, and `TryParseExact` public methods on the `Time` and `Date` types.

**Comment by gmilani** [comment]
Hello, I want to start contributing. Can I start with this task?

**Comment by mj1856** [comment]
Yes, please do!

Note that ultimately these types will move forward to corefx via the API proposal process, which won't necessarily include the implementation or tests - so your code may possibly not make it through to the shipping product.  However, the final implementer may indeed borrow or copy from the implementation here as a starting point, so it is still useful to be as complete as possible.

**Comment by AndreKraak** [comment]
Hi,

I am looking into contributing to open source projects, it will be my first time doing so.
I found this project/issue and would like to try and help. Is this issue still available to work on?

I have started with a test [DateParseTests.zip](https://github.com/dotnet/corefxlab/files/1821716/DateParseTests.zip) and before continuing I would like to ask some questions.
If there is a more appropriate forum to asks these questions please let know and I will post them there.

1. Are there any coding guidelines I should be aware off and following?
For example I see that the code explicitly uses data types in the variable declaration instead of 'var'.
2. Based on [DateFormattingTests](https://github.com/dotnet/corefxlab/blob/master/tests/System.Time.Tests/DateFormattingTests.cs) it seems that testing is only done for InvariantCulture, is this correct?
3. When testing should I also test with the possible values off [TwoDigitYearMax](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar.twodigityearmax?view=netframework-4.7.1)?
Depending on the value "29 December" is parsed differently.

Cheers,
André

**Comment by AndreKraak** [comment]
> A string with a time but no date component.The method assumes the current date unless you call the Parse(String, IFormatProvider, DateTimeStyles) overload and include DateTimeStyles.NoCurrentDateDefaultin the styles parameter, in which case the method assumes January 1, 0001.

**Comment by AndreKraak** [comment]
What is the expected result when parsing a string without a date?

Right now parsing "10:49:12" with Date.Parse result in a Date for today. This is as documented in [DateTime.Parse](https://msdn.microsoft.com/en-us/library/system.datetime.parse(v=vs.110).aspx).
> A string with a time but no date component.The method assumes the current date unless you call the Parse(String, IFormatProvider, DateTimeStyles) overload and include DateTimeStyles.NoCurrentDateDefaultin the styles parameter, in which case the method assumes January 1, 0001.

With no date present in the string I would expect a FormatException to be thrown, as there is no date to be parsed.

**Comment by AndreKraak** [comment]
Would the [DateTime.Parse](https://msdn.microsoft.com/en-us/library/system.datetime.parse(v=vs.110).aspx) tests from [DateTimeTests](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/DateTimeTests.cs) in the [corefx repository](https://github.com/dotnet/corefx) be enough to test the Date.Parse method?

I get the feeling my test [DateParseTests.zip](https://github.com/dotnet/corefxlab/files/1821716/DateParseTests.zip) are to 'much' if compared with the tests from [DateTimeTests](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/DateTimeTests.cs).
The only additional test might be one for the situation from my previous comment, depending on the outcome of that discussion.

**Comment by ahsonkhan** [comment]
> Are there any coding guidelines I should be aware off and following?

We tend to follow the same guidelines as corefx:
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

**Comment by mj1856** [comment]
Hi, and thanks for picking up this work!  One think that might be helpful is to get a Work-In-Progress PR going.  Basically, start a feature branch in your fork, add your initial tests, send a PR, but put WIP in the title.  We can then collaborate via GitHub comments on specific lines of code.  When you make edits to your feature branch and push, the PR updates automatically.

On the specific questions asked:

> 1. Are there any coding guidelines I should be aware off and following?

Yes, use the ones @ahsonkhan pointed to.  Item 10 describes `var` usage.  (Note there may be existing cases where `var` *could* have been used but wasn't.  I don't think anyone will care too much if it's not perfect.)

> 2. Based on `DateFormattingTests` it seems that testing is only done for `InvariantCulture`, is this correct?

Use the invariant culture when not specifically testing for cultural concerns.  It would be nice to have a few tests that work with at least one other culture that uses a different date format (perhaps `en-GB`), and maybe also for one with an alternate calendar (perhaps `ar-SA`).  I don't expect a comprehensive set of tests for every culture that exists in the framework.

> 3. When testing should I also test with the possible values off `TwoDigitYearMax`?
Depending on the value "29 December" is parsed differently.

This would be acceptable, but extra.  Focus your tests primarily on the APIs that are in the objects being tested.  I understand they are influenced by the behavior of the culture, such as with that setting, but I think there's a reasonable amount of expectation around `Calendar` and `DateTimeFormatInfo` already working sufficiently.  Not all of it needs re-testing here.

> What is the expected result when parsing a string without a date?

If parsing a `Date` without enough information to construct a date, then yes I'd want a `FormatException` to be thrown.  Same for `TimeOfDay` without a time data.  I think also that we'd want to throw if the string contained extraneous data, such as if given `3/20/2018 8:43 AM`, that should be parsable only as a `DateTime`.  If parsed as a `Date` or a `TimeOfDay`, I'd expect a `FormatException` as well.

> Would the `DateTime.Parse` tests from `DateTimeTests` in the corefx repository be enough to test the `Date.Parse` method?

Not the exact tests, but in the spirit of those.  You will need to copy and modify them to work with the `Date` or `TimeOfDay` types, including the edge cases discussed already.

Good luck! 😄

**Comment by YohDeadfall** [comment]
@tarekgh I would like to take this issue and productize date and time types, but there is a blocker. I need to modify the `DateTimeParse` class to throw an exception if some required part wasn't supplied. Should I copy the whole class, or is there another approach?

/cc @karelz

**Comment by tarekgh** [comment]
@YohDeadfall  

@mj1856 mentioned in his last comment the following:

> Not the exact tests, but in the spirit of those. You will need to copy and modify them to work with the Date or TimeOfDay types, including the edge cases discussed already.

This recommend copying the needed tests from corefx and try to use it here. could you please give more details what exactly you are trying to do?

**Comment by YohDeadfall** [comment]
I need a bit different thing. For now `Date` and `Time` use `DateTime` to parse values, but there are corner cases like a date without time which can't be parsed as a `Time`, there is no such part. If there is a time without the date part, then an exception should be thrown too. This requires some changes in the parser.

So my question is should I copy the whole parser here and change what I want, or is there other way>

**Comment by tarekgh** [comment]
> I need a bit different thing. For now Date and Time use DateTime to parse values, but there are corner cases like a date without time which can't be parsed as a Time, there is no such part. If there is a time without the date part, then an exception should be thrown too. This requires some changes in the parser.

I am not sure this need to change the parser. If you are parsing Date without time using Time, after parsing operation, we can validate the case that the Date should be 0 ticks and otherwise we can throw. and vice versa with Date class too. 

In general I am not recommending copying the parsing code as this will create maintainability problems. except if we decide we are doing a real fork and we assume 2 unrelated parsers.
