### ISSUE TITLE
Please add file support to System.IO.Pipelines

### ISSUE THREAD

**Issue by AceHack** [dotnet/corefxlab#1928]
I would like to be able to use high performant file reads and writes in a pipeline.  Unbuffered async/overlapped I/O would be great as well so it could be used for a safe durable write ahead log.

**Comment by davidfowl** [comment]
There's a prototype here https://github.com/dotnet/corefxlab/blob/97ae47716ed5b25fbe3188429d433914d4550c16/src/System.IO.Pipelines.File/FileReader.cs. It's windows only though.

**Comment by AceHack** [comment]
Is this just the reader?  What about the writer?  Is the plan to support this on all OSs?  Thanks.

**Comment by muratg** [comment]
@AceHack Could you file a bug in CoreFX if you're still interested in this?  Thanks.

**Comment by muratg** [comment]
@AceHack The APIs were mainly intended for testing only, and not public usage. Closing this one.
