### ISSUE TITLE
System.IO.Compression.Brotli depends on package not published

### ISSUE THREAD

**Issue by Dadstart** [dotnet/corefxlab#1942]
The System.IO.Compression.Brotli package depends on System.Runtime.CompilerServices.Unsafe and System.Memory versions 4.5.0+. However the latest published version is 4.4.0.

````
  GET https://api.nuget.org/v3-flatcontainer/system.memory/index.json
  GET https://dotnet.myget.org/F/dotnet-corefxlab/FindPackagesById()?id='System.Memory'
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/index.json
  GET https://dotnet.myget.org/F/dotnet-corefxlab/FindPackagesById()?id='System.Runtime.CompilerServices.Unsafe'
  OK https://dotnet.myget.org/F/dotnet-corefxlab/FindPackagesById()?id='System.Runtime.CompilerServices.Unsafe' 197ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.compilerservices.unsafe/index.json 271ms
  OK https://dotnet.myget.org/F/dotnet-corefxlab/FindPackagesById()?id='System.Memory' 276ms
  OK https://api.nuget.org/v3-flatcontainer/system.memory/index.json 283ms
Unable to find package System.Runtime.CompilerServices.Unsafe with version (>= 4.5.0-preview1-25915-02)
  - Found 7 version(s) in nuget.org [ Nearest version: 4.4.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in dotnet.myget.org dotnet-corefxlab
Unable to find package System.Memory with version (>= 4.5.0-preview1-25915-02)
  - Found 2 version(s) in nuget.org [ Nearest version: 4.4.0-preview2-25405-01 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in dotnet.myget.org dotnet-corefxlab
````

**Comment by ahsonkhan** [comment]
Please add the appropriate dotnet-core myget feed to get the packages that System.IO.Compression.Brotli depends on:
https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

For example, see here for the latest 4.5.0+ System.Runtime.CompilerServices.Unsafe package:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Runtime.CompilerServices.Unsafe


cc @dotnet/corefxlab-contrib

**Comment by jmkni** [comment]
I am getting the same issue.

Unfortunately, This doesn't seem to work with .net core 2.0

**Comment by ahsonkhan** [comment]
@Dadstart, was your issue resolved?

@jmkni, can you please share your NuGet.Config?

**Comment by joshfree** [comment]
Closing out this issue since @ahsonkhan posted the dotnet-core myget feed details and there wasn't any additional replies.  Please let us know if you're still having problems and we can reactivate.
