### ISSUE TITLE
ReadWriteBytes/ReadOnlyBytes why not T?

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#1948]
The Sequences `ReadWriteBytes`/`ReadOnlyBytes` have become quite interesting; any reason for limiting them to only bytes?

e.g.
```csharp
public readonly struct ReadWriteSequence<T> : ISequence<Memory<T>>
{
    readonly Memory<T> _first; // pointer + index:int + length:int
    readonly IMemoryList<T> _all;
```
```csharp
public readonly struct ReadOnlySequence<T> : ISequence<ReadOnlyMemory<T>>
{
    readonly ReadOnlyMemory<T> _first; // pointer + index:int + length:int
    readonly IMemoryList<T> _all;
```

/cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
I was thinking about it. If we think there is value, we should consider doing it. So far I avoided it because some people don't like how the generic parameter makes the type name longer (or more complicated).

cc: @davidfowl, @joshfree, @ahsonkhan, @terrajobst

**Comment by benaadams** [comment]
Don't know if the Jit would like it but could keep `ReadWriteBytes`/`ReadOnlyBytes` as wrappers?

```csharp
public readonly struct ReadOnlyBytes : ISequence<ReadOnlyMemory<byte>>
{
    readonly ReadOnlySequence<byte> _sequence;

    // forwarding methods to _sequence.
```
