### ISSUE TITLE
No way to get a cursor to the data in some cases from a ReadableBuffer

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1953]
With the current logic it's sometimes impossible to get a cursor to valid data. Consider the following:

```
var buffer = BufferUtilities.CreateBuffer(new[] { new byte[] { }, new byte[] { 1 } });
```

- The length of this buffer is 1 so the first segment is empty 
- buffer.Start points to nothing (segment 0, index 0 but conceptually -1)
- buffer.End points to (segment 1, index 1) which is past the end of the buffer

Attempting to call buffer.Move(buffer.Start, 1) returns buffer.End, skipping over any valid data.

/cc @pakrym

**Comment by pakrym** [comment]
What should `buffer.Move(buffer.Start, 1)` return? 

I think it doesn't matter if `buffer.Start` points to an empty first segment or beginning of the next  segment consumption shouldn't care.

**Comment by davidfowl** [comment]
I ran into this when trying to verify a bug fix in the ReadableBufferReader, it can create cursors that the ReadableBuffer can’t.
