### ISSUE TITLE
It seems that there is a ValueDelegate issue, any one knows it?

### ISSUE THREAD

**Issue by juepiezhongren** [dotnet/corefxlab#1966]
can't find it anywhere, help

**Comment by YohDeadfall** [comment]
Do you mean https://github.com/dotnet/csharplang/issues/80?

**Comment by juepiezhongren** [comment]
@YohDeadfall  got it, it's https://github.com/dotnet/csharplang/issues/492

**Comment by juepiezhongren** [comment]
@gafter, is u the person who's contributed the ValueDelegate?

**Comment by tannergooding** [comment]
@juepiezhongren, the actual language proposal is here: https://github.com/dotnet/csharplang/blob/master/proposals/static-delegates.md

I was the submitter of the proposal and @jaredpar is currently the champion (person who will take the proposal to the language design meeting for discussion).

The feature does not exist today. 

It would be helpful if you could provide some more details as to what you  questions you are looking to get answered.

**Comment by gafter** [comment]
https://github.com/dotnet/csharplang/issues/302 is being used to track the proposal.
