### ISSUE TITLE
Pipelines API review issues

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefxlab#1972]
- [x] Readonliness of ReadableBuffer
- [x] Use `IMemoryList`
- [x] Move Write* extension methods to a single class, change them to take ReadOnly*
- [x] Move ReadableBuffer/Cursor->Position to BufferPrimitives
- [x] Should we keep `ReadableBuffer.Preserve`? No
- [x] Should we keep `WriteableBuffer.Append`? No, it includes lifetime management.
- [x] Operators on cursors/positions - Remove
- [x] Return default + false from ISequence and remove End?.
- [x] Change IOutput.Span to GetSpan (as it can be expensive)
 
Things that are to be moved to BCL:
- [x] `ValueAwaiter`
- [x] `IScheduller`

This is not the full list, it would be added to during upcoming API reviews

/cc @davidfowl @KrzysztofCwalina @halter73 @muratg

**Comment by muratg** [comment]
cc @joshfree

**Comment by KrzysztofCwalina** [comment]
Here are some others I would like to add:
[ ] I would make the enumerators nested types in Readable/Writable Buffers. Today, the enumerator can be shared between these two types, but once ReadableBuffer gives out only ReadOnlyMemory, the buffers will need separate enumerators.
[ ] Why do we need IPipe, IPipeConnection, IReadableBufferAwaiter, IWritableBufferAwaiter interfaces? Nothing consumes them. Can we just have Pipe class?
[ ] I find Advance with two cursors confusing. We talked about having simplified API where if consumed is empty, then examined is all and if consumed is not empty, then examined is the same as consumed. Remind me what scenarios are not covered by this?
[ ] MaximumSizeHigh and MaximumSizeLow are not very self explanatory. Can we find better names?
[ ] Do we really need preserved buffer? It's a whole new type (not polymorphic with ReadableBuffer) just so we can dispose it? 
[ ] IsSingleSpan should be renamed to IsSingleSegment. 
[ ] We should use ReadOnly as a prefix for ReadableBuffer. We use ReadOnly all over the BCL
[ ] We should remove RB.Create(byte[], int, int). We should use Memory<T> or Span<T> for those.
[ ] Should all the awaitables be moved to .Threading subnamespace?
[ ] Cursor needs to be unified with Position
[ ] When we move ReadableBuffer to System.Memory, it should have a create method that takes Memory<byte> (and fish out OwnedMemory or byte[])

**Comment by pakrym** [comment]
> I find Advance with two cursors confusing. We talked about having simplified API where if consumed is empty, then examined is all and if consumed is not empty, then examined is the same as consumed. 
> Remind me what scenarios are not covered by this?

Header parser only consumes header when it is completely received but examines everything.
So for the following incomplete data:

```
                      v Consumed
Host: http://localhost
Accep
     ^Examined
```

**Comment by pakrym** [comment]
@KrzysztofCwalina 
I would also like to remove `CopyTo` from `IMemoryList`, I think it's not very useful in current state of things when no-one would get access to IML directly.

**Comment by karelz** [comment]
Is there a simple basic sample how to set up the pipeline and use it for basic (even inefficient) scenario? Then for advanced scenarios? I assume it will be needed for the API review anyway ;)

**Comment by davidfowl** [comment]
Before we go deleting all of the abstractions there was this very early plan to figure out how to expose the pipe interface on our existing body streams so that we could expose them in ASP.NET:

https://github.com/aspnet/AspLabs/issues/2

I'd like to see a new plan for this with the suggested API changes here (if we remove the abstractions)

**Comment by pakrym** [comment]
@davidfowl if we implement `await pipe.Writer.ReadStarted` we can just run loop that pipes bytes from body stream to body pipe every time someone sets the body stream without wrapping anything.

**Comment by davidfowl** [comment]
> @davidfowl if we implement await pipe.Writer.ReadStarted we can just run loop that pipes bytes from body stream to body pipe every time someone sets the body stream without wrapping anything.

I'm not concerned about ReadStarted. I'm concerned about implementing IPipeReader on the request body stream and IPipeWriter on the response body stream. How do we fix that after we remove the interfaces? Expose new properties that don't work well with the existing ones?

**Comment by pakrym** [comment]
We don't, we copy from stream to pipe if someone reads from pipe.

**Comment by davidfowl** [comment]
That defeats much of the purpose.

**Comment by pakrym** [comment]
@davidfowl isn't it temporary?

**Comment by bording** [comment]
Has there been any consideration about bringing back `WritableBuffer.BytesWritten` as mentioned in #1838? 

Being able to support the scenario described in that issue is important for a lot of protocols.

**Comment by davidfowl** [comment]
Agreed. I think we should bring it back

**Comment by benaadams** [comment]
`WritableBufferWriter` => `BufferWriter` that its writable is inferred, what other type of buffer could it be writing to?

**Comment by kasper3** [comment]
Also please suffix all the awaitable methods with `Async`

**Comment by davidfowl** [comment]
@kasper3 which ones aren't?

**Comment by davidfowl** [comment]
@KrzysztofCwalina @pakrym We should rename BufferReader.Skip -> Advance

**Comment by tmds** [comment]
Some open issues regarding pipelines

- I had created an issue about changing the MaximumSize{Low,Heigh} semantics: https://github.com/dotnet/corefxlab/issues/1355#issuecomment-295141102

- I also wonder what is the proper place to deal with sending part of files using OS sendfile system call: https://github.com/aspnet/KestrelHttpServer/issues/1673.

- Is there a way to allow foreign buffers in the pipeline (i.e. not allocated using the pipe's memorypool), to avoid copy like: https://github.com/aspnet/KestrelHttpServer/blob/73a37363e1a44e221f070c530a5b987e118cc7a7/src/Kestrel.Core/Internal/Http/Http1OutputProducer.cs#L166-L188

**Comment by davidfowl** [comment]
> I had created an issue about changing the MaximumSize{Low,Heigh} semantics: #1355 (comment)

We can look at this again but I'm not sure it can't be added later.

> I also wonder what is the proper place to deal with sending part of files using OS sendfile system call: aspnet/KestrelHttpServer#1673.

Not really pipe specific. This is about the core assembly (its at the stream level).

> Is there a way to allow foreign buffers in the pipeline (i.e. not allocated using the pipe's memorypool), to avoid copy like: https://github.com/aspnet/KestrelHttpServer/blob/73a37363e1a44e221f070c530a5b987e118cc7a7/src/Kestrel.Core/Internal/Http/Http1OutputProducer.cs#L166-L188

We've removed append so far but the foreign buffer would likely need to be an OwnedBuffer or something similar since buffers can outlive the call to WriteAsync (in the specific example you provided).

**Comment by tmds** [comment]
> Not really pipe specific. This is about the core assembly (its at the stream level).

I don't understand what you mean. This requires some interaction between the _application code_ (that knows it is sending a file) and the _Transport_ (that knows how to optimize the file sending). The pipe is between those parts.

> We've removed append so far but the foreign buffer would likely need to be an OwnedBuffer or something similar since buffers can outlive the call to WriteAsync (in the specific example you provided).

Yes. There needs to be some _lifetime_ management possible for these buffers.
Also, some Transport may need special treatment of foreign buffers. I guess this is the case for RIO, the foreign buffers will still need to be copied into a RIO buffer.

**Comment by pakrym** [comment]
Work items from the latest review:
2. Add `Move` to `ISequence` 
1. Remove operator from positions and change everything to use `Move`
3. Make `ROB.ctor(Pos, Pos)` private.

**Comment by tmds** [comment]
I've created a feature request for foreign buffer support: https://github.com/dotnet/corefxlab/issues/2031.

**Comment by KrzysztofCwalina** [comment]
I changed the comment to a list.

**Comment by benaadams** [comment]
Flush/Notify https://github.com/dotnet/corefxlab/issues/2029

**Comment by pakrym** [comment]
- [ ] Add MinimumBlockSize to pipe options to enable pools that return exact size requested (ArrayPool).

**Comment by pakrym** [comment]
- [ ]  Productize `ArrayMemoryPool`

**Comment by pakrym** [comment]
- [ ] Add `Span` overloads to `OutputWriter`

**Comment by davidfowl** [comment]
> I don't understand what you mean. This requires some interaction between the application code (that knows it is sending a file) and the Transport (that knows how to optimize the file sending). The pipe is between those parts.


Again, transports are kestrel specific, this is about the core pipe API. I don't see how that has any bearing on decisions being made here. Can you be more specific about what you think is relevant?

**Comment by tmds** [comment]
> Again, transports are kestrel specific, this is about the core pipe API. I don't see how that has any bearing on decisions being made here. Can you be more specific about what you think is relevant?

I'm thinking a design alternative is to support ReadOnlyMemory to represent a file segment ({SafeFileHandle, offset, length}). No idea on how technically feasible this is.

**Comment by davidfowl** [comment]
@tmds how does that affect any of the pipe APIs?

**Comment by tmds** [comment]
> @tmds how does that affect any of the pipe APIs?

This would require support for two operations:
- append a file segment to a WritableBuffer
- extract the file segment info from the ReadOnlyMemory
The file handle is a resource that must be disposed, so it may use the _foreign buffer_ feature to track the lifetime.

These looks like adding methods only, so probably it doesn't affect the API under review.

**Comment by davidfowl** [comment]
> append a file segment to a WritableBuffer

I don't think a file segment primitive makes sense. All of the writable buffer operations are synchronous and buffered and I think you'd want file streaming to not buffer the entire file into memory. You'd instead want to copy to the IPipeWriter in chunks. It's like a Stream.CopyToAsync operation on an IPipeWriter (https://github.com/dotnet/corefxlab/blob/e74a2eb7ba796ac35506454dfa07eedf475965d7/src/System.IO.Pipelines.Extensions/StreamExtensions.cs).

I don't think it's any more complicated than that really.

**Comment by tmds** [comment]
> I think you'd want file streaming to not buffer the entire file into memory

Yes, if someone calls Span on the ReadOnlyMemory that would cause this to happen. That would not be good.

> You'd instead want to copy to the IPipeWriter in chunks.

I'm trying to figure out how an application that uses Pipes can avoid the copying by using the [sendfile](http://man7.org/linux/man-pages/man2/sendfile.2.html) system function: https://github.com/aspnet/KestrelHttpServer/issues/1673.

**Comment by KrzysztofCwalina** [comment]
> Productize ArrayMemoryPool

@pakrym, we we need anything more than MemoryPool<byte>.Default?

**Comment by davidfowl** [comment]
> I'm trying to figure out how an application that uses Pipes can avoid the copying by using the sendfile system function: aspnet/KestrelHttpServer#1673.

That's fine it's just not relevant to this review, that is a kestrel feature.

**Comment by juliusfriedman** [comment]
This is fast, efficient (Memory and CPU) and has the culpability to be brought to fruition using SIMD and ot other intrinsic improvements inter alia.

The class does basically the same thing as what's advertised here IMHo and 0.0000002

http://net7mma.codeplex.com/SourceControl/latest#Common/Classes/SegmentStream.cs

**Comment by davidfowl** [comment]
@KrzysztofCwalina I'm going to close this out.

**Comment by bording** [comment]
@davidfowl Any more info yet regarding https://github.com/dotnet/corefxlab/issues/1972#issuecomment-353739809?

**Comment by davidfowl** [comment]
No there's an issue filed for it but I'd rather not turn this issue into a bunch of feature requests. Once the main API is in then we'll review and add individual features.

**Comment by KrzysztofCwalina** [comment]
@davidfowl, sounds good.
