### ISSUE TITLE
A proposal about the design of System.CommandLine

### ISSUE THREAD

**Issue by zhangyuwu** [dotnet/corefxlab#1991]
After my reading of the <a href="https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/README.md"> README.md </a>, I got a few thoughts:

1. The command line parser can be designed in a MVC like model, a command line can be treated like a URL, and arguments & options can be treated like the `Model`, thus the parsing operation is binding.
2. Using meta programming to declare the rules of parsing over coding is more intuitive and readable.
3. Data validation can be carried out by leverage the existing validation attributes in System.ComponentModel.DataAnnotations, e.g. Range, StringLength, etc.
4. Help messages can be generated through the meta declaration.

I have a repository with a few small <a href="https://github.com/nklib/nklib/tree/master/apps"> samples </a> on Github which are based on .NET Core, here I'm using one of them as an example and hope this helps, first I declare a model as below:

    [CommandDescription("ping to a range of IP address concurrently")]
    class CmdParam : BaseCmdParam
    {
        [CommandOptionRequired]
        [CommandOption(Syntax = "[-ip]=IP_RANGE", Description = "ip address(es), e.g. '192.168.{1,3-5}.{100-103}", Pattern = @"(((\{(\d+([-,])?)+\})|(\d+))(\.)?)+")]
        public string IPAddressText { get; set; }

        [CommandOption(Syntax = "[-timeout]=TIMEOUT", Description = "timeout of operation in milliseconds, default is 3000 ms")]
        [Range(100, 10000)]
        public int Timeout { get; set; }

        [CommandOption(Syntax = "[-max]=MAX_NUM", Description = "maximum number of concurrent tasks, deafult is 10")]
        [Range(1, 1000)]
        public int MaxNumTasks { get; set; }

        public CmdParam()
        {
            MaxNumTasks = 10;
            Timeout = 3000;
        }
    }

And an automatic generated help message looks like:
<pre>
Usage: pings.dll [-ip]=IP_RANGE [[-timeout]=TIMEOUT] [[-max]=MAX_NUM] [--help] [--version]
ping to a range of IP address concurrently

Options:
  [-ip]=IP_RANGE     *  ip address(es), e.g. '192.168.{1,3-5}.{100-103}
  [-timeout]=TIMEOUT    timeout of operation in milliseconds, default is 3000 ms
  [-max]=MAX_NUM        maximum number of concurrent tasks, deafult is 10
  --help                display this help and exit
  --version             output version information and exit
</pre>

**Comment by YohDeadfall** [comment]
It's a good idea, but [README.md](https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/README.md) says:

> We need something that is quite low level. In particular we don't want to have a library that requires reflection for attribute discovery or for setting properties.

I think that such thing can be in an additional library built around `System.CommandLine`.

**Comment by zhangyuwu** [comment]
Thanks for your quick reply and clarification.
