### ISSUE TITLE
Add Scheduler.Schedule(Action action)

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#2000]
Otherwise you end up with the wrap for 
```csharp
private static readonly Action<object> _scheduleContinuation = o => ((Action)o)();

private static void TrySchedule(Scheduler scheduler, Action action)
{
    if (action != null)
    {
        scheduler.Schedule(_scheduleContinuation, action);
    }
}
```
Which means a double wrap and allocation for a Faster TaskScheduler https://github.com/dotnet/corefxlab/pull/1999 as it also needs to do the same wrap to enqueue.

i.e. the wrapping should be handled by the Scheduler not the pipe

**Comment by davidfowl** [comment]
This looks like a fine change now that we have a base class.
