### ISSUE TITLE
ILookup for MultiValueDictionary

### ISSUE THREAD

**Issue by aobatact** [dotnet/corefxlab#2013]
Since ILookup is something like "ReadOnlyMultiValueDictionary" , I suggest that MultiValueDictionary inherits ILookup.
```csharp
public class MultiValueDictionary<TKey, TValue> :
        IReadOnlyDictionary<TKey, IReadOnlyCollection<TValue>>,
        ILookup<TKey, TValue>
{

   IEnumerator<IGrouping<TKey, TValue>> IEnumerable<IGrouping<TKey, TValue>>.GetEnumerator()
        => dictionary.Values.GetEnumerator(); 
   bool ILookup<TKey, TValue>.Contains(TKey key) => ContainsKey(key);

   private class InnerCollectionView :
            ICollection<TValue>,
            IReadOnlyCollection<TValue>,
            IGrouping<TKey,TValue>
   {
   }
// no other change
}
```

**Comment by joshfree** [comment]
Please note that MultiValueDictionary has been moved to the archived_projects directory and isn't under active development.  It may be removed entirely in the future: https://github.com/dotnet/corefxlab#archived-projects

/cc @ianhays

**Comment by joshfree** [comment]
Closing old issues related to archived projects.
