### ISSUE TITLE
Consider adding JWT types

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/corefxlab#2017]
JSON Web Token (JWT) is a compact, URL-safe means of representing claims to be transferred between two parties. 
See https://tools.ietf.org/html/rfc7519.

This structure is widely used with the OAuth2/OpenID Connect protocols as access token, [ID token](http://openid.net/specs/openid-connect-core-1_0.html#IDToken), [user info response](http://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse), [request parameters](http://openid.net/specs/openid-connect-core-1_0.html#JWTRequests), [client authentication](http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication), [aggregated & distributed claims](http://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims), [logout token](http://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken) or [authorization grant](https://tools.ietf.org/html/rfc7521#section-4.1).
Others drafted usages of the JWT structure are [state](https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-07) and [Security Event Tokens](https://tools.ietf.org/html/draft-ietf-secevent-token-03).

Current implementation .Net of the JWT structure is provided by the [System.IdentityModel.Tokens.Jwt](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/dev) package as a `JwtSecurityToken`. 

This implementation is tightly coupled to the IdentityModel. 
For example the validation of a JWT provide a `IPrincipal` as result. This is acceptable if the JWT is used to authenticate an entity, but it is useless when the JWT is as state object or a request object.
And building a new JWT is not as convenient as it could be, specifically with the mapping form the JSON structure to the `System.Security.Claims.Claim`.

The idea is to expose JWT types like a `JsonWebToken` structure with the core features (building, validation, signature/encryption, key management, ...) without the IdentityModel related features (mapping JWT claims to MS claims, claims transformation, ...). In other words extracting the JWT core logic from Wilson.

Thoughts ?

@brentschmaltz

**Comment by brentschmaltz** [comment]
@ycrumeyrolle see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/660 The spirit of 660 is related to the issues you have addressed above.

**Comment by RussKie** [comment]
+1
For us the problem is that it no longer exposes `IPrincipal` but `ClaimsPrincipal`.
I've called the issue out back in Aug 16 https://github.com/dotnet/corefx/issues/11082
