### ISSUE TITLE
BufferReader API : consider moving to 64-bit (System.Buffers.Primitives)

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#2019]
In particular, `ConsumedBytes` - but possibly also `Skip(long length)`.

Ultimately, the reader can be spanning an arbitrary number of spans; the classic implementation is over a `ReadOnlyBuffer`, and that has already moved to `public long Length => ...` / `Slice(long start, long length)`. So since the *thing it wraps* clearly considers the >2GiB world, so should this.

Obviously things like `Index` are unaffected, since that relates to the current span which is `int`-indexed

**Comment by Drawaes** [comment]
I hit this issue when experimenting with making a ReadOnlyBuffer over a large memory mapped file. The 2GiB limit was something I then had to code around

**Comment by pakrym** [comment]
Yep, it's a bug.

**Comment by mgravell** [comment]
@pakrym  any thoughts on the `Skip` aspect? (64-bit)

**Comment by pakrym** [comment]
I think if you are skipping 2GB of memory Reader is not the right thing to use. ReadOnlyBuffer can do it much more efficiently,

**Comment by mgravell** [comment]
Maybe, but general purpose consumer code isn't necessarily well placed to
switch readily between those two. Conversely, if ROB is better at this,
perhaps large skips could be achieved by a check inside Skip, without the
caller needing to worry about it?

if(len > LARGE)
{
    var rob = new ROB(Cursor, End).Slice(len);
    this = new BufferReader(rob, bytesConsumed + Len);
}

?


On 5 Jan 2018 4:10 p.m., "Pavel Krymets" <notifications@github.com> wrote:

I think if you are skipping 2GB of memory Reader is not the right thing to
use. ReadOnlyBuffer can do it much more efficiently,

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/corefxlab/issues/2019#issuecomment-355593467>,
or mute the thread
