### ISSUE TITLE
Pipe question: why is FlushAsync() on the buffer?

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#2029]
Currently `FlushAsync` is on the `WritableBuffer`, with it simply calling the `internal Pipe.FlushAsync()` method. This makes it feel like the flush is an operation of the write buffer, and mentally forces a model where you flush at the end of each `Alloc`, when that isn't actually necessary as long as you `Commit` each `WritableBuffer` and then remember to `FlushAsync` on the last. When `FlushAsync()` is called, what it does has nothing whatsoever to do with the `WritableBuffer`, what was written, or the current state.

Question: wouldn't it be more obvious for this to be made public on the `IPipeWriter`? and probably removed from the `WritableBuffer`?

I'm guessing the current location makes it easier for helper extension methods to "write and flush", but IMO "write and flush" isn't the right model for extension methods on a `WritableBuffer`, as in order to flush it needs to be committed, and committing kills the buffer. Which makes it seem like "write and flush" should only ever be an extension on an `IPipeWriter`, or alternatively: the extension method should only `Advance`, not `Commit` and `FlushAsync`.

**Comment by Drawaes** [comment]
I agree its a pain having to have the "allocated" buffer to actually flush, it means it needs to be passed out of "non async" methods to the parent method, or... you have to alloc to flush if the inner stuff commits, I have raised this in the below issue.

https://github.com/dotnet/corefxlab/issues/1412

**Comment by benaadams** [comment]
Either that or `Commit` shouldn't kill and only `FlushAsync` should

**Comment by mgravell** [comment]
But then: what does Commit *mean* in that case, and how is it different to
Advance?

**Comment by benaadams** [comment]
Advance its still your data
Commit its now someone else's data

**Comment by mgravell** [comment]
So... a "partial flush"? (giggles and runs; this may or may not be a
continuation of an off-board conversation)

**Comment by benaadams** [comment]
I think one method is missing `NotifyAsync`
```
Advance()
Commit()
NotifyAsync() // + Commit, May flush, may give backpressure
FlushAsync() // + Commit + Notify + Forced Flush, may give backpressure
```

```csharp
while
{
    while
    {
        await GetData()
        while
        {
            Process+Commit()
            await NotifyAsync(); // A maybe flush, have more data
        }
    }
    await FlushAsync(); // A forced flush, waiting for more input
}
```

`NotifyAsync()` works with reducing syscalls; the next stage can coalesce until it has enough data to make a meaningful write; but can return immedately if not  (e.g. at least a full packet)
`FlushAsync()` means write now, don't wait for more

/cc @davidfowl

**Comment by Drawaes** [comment]
Agreed so a good example for above might be

You are sending protobuf data across a TLS connection. You have written 10k a TLS frame is 16k. 

The read side (TLS) looks like this

```

while(true)
{
     var result = await pipeline.ReadAsync();
     if(result.IsPartial && result.Buffer.Length < 16k)
     {
              pipeline.Advance(result.buffer.start, result.buffer.end);
              continue;
      }
      
      Otherwise write a frame 
}
```

That way you can ship out data as it is generated, but you can fill a full frame rather than firing off partial frames unless the upper application wants to force it (its completed a unit of work)

**Comment by benaadams** [comment]
Same with processing pipelined requests; you want to inform the transport its got something to send, but also let it wait until its got a full packet before sending them - while you still have more input requests to process:
```csharp
public async Task ExecuteAsync()
{
    try
    {
        var parser = new HttpParser<HttpConnectionContext>();

        var bytesWritten = 0u;
        WritableBuffer outputBuffer = default;
        while (true)
        {
            if (!Input.Reader.TryRead(out var result))
            {
                if (bytesWritten > 0)
                {
                    await Output.Writer.FlushAsync(); // Flush the Writer, before waiting for more
                }

                result = await Input.Reader.ReadAsync();
            }
            
            // Processing
            
            outputBuffer = Output.Writer.Alloc();
            outputBuffer.Write(_plainTextBytes);
            outputBuffer.Commit();
            bytesWritten += (uint)_plainTextBytes.Length;

            Input.Reader.Advance(consumed, examined); // Advance Input

            await Output.Writer.NotifyAsync(); // Notify the Writer
        }
        
        // Finished
        await Output.Writer.FlushAsync(); // Flush the Writer, before exiting
        Input.Reader.Complete();
    }
    catch (Exception ex)
    {
        Input.Reader.Complete(ex);
    }
    finally
    {
        Output.Writer.Complete();
    }
}
```

**Comment by benaadams** [comment]
Same with processing pipelined requests; you want to inform the transport its got something to send, but also let it wait until its got a full packet before sending them - while you still have more input requests to process:
```csharp
public async Task ExecuteAsync()
{
    try
    {
        var parser = new HttpParser<HttpConnectionContext>();

        var bytesWritten = 0u;
        while (true)
        {
            if (!Input.Reader.TryRead(out var result))
            {
                if (bytesWritten > 0)
                {
                    await Output.Writer.FlushAsync(); // Flush the Writer, before waiting for more
                }

                result = await Input.Reader.ReadAsync();
            }
            
            // Processing
            
            WritableBuffer outputBuffer = Output.Writer.Alloc();
            outputBuffer.Write(_plainTextBytes);
            outputBuffer.Commit();
            bytesWritten += (uint)_plainTextBytes.Length;

            Input.Reader.Advance(consumed, examined); // Advance Input

            await Output.Writer.NotifyAsync(); // Notify the Writer
        }
        
        // Finished
        await Output.Writer.FlushAsync(); // Flush the Writer, before exiting
        Input.Reader.Complete();
    }
    catch (Exception ex)
    {
        Input.Reader.Complete(ex);
    }
    finally
    {
        Output.Writer.Complete();
    }
}
```

Decrease syscalls (Meltdown/Spectre); improve packet density, without increasing latency

**Comment by mgravell** [comment]
the context I was missing here was single block vs multi block; now that I've reminded myself that multi-block writers are a thing, this makes more sense where it is and I don't think it is necessarily a problem
