### ISSUE TITLE
`OutputWriter<T>` : add `BytesWritten` / `WrittenBytes` / whatever

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#2039]
(also: nomenclature; it is odd that it is `BufferReader<T>` and `OutputWriter<T>`; should that be `BufferWriter<T>` ?)

`BufferReader<T>` has `ConsumedBytes`

it is odd and inconsistent that `OutputWriter<T>` does *not* have a `WrittenBytes` or similar. Note that quite often the pattern will be:

    var writer = OutputWriter.Create(buffer);
    // lots of arbitrary writing operations using conditional paths and helper methods

It is impossible for the code that creates `writer` to accuately track the number of bytes written here, but it would be *very* valuable to be able to access it - especially for debugging purposes. The scenarios I have in mind are things like:

    var writer = OutputWriter.Create(buffer);
    long payloadLength = ComputePayloadLength(obj);
    long prefixLength = writer.WriteLengthPrefix(payloadLength); // some helper "ref this" method
    
    
    // lots of arbitrary writing operations using conditional paths and helper methods

    Verbose.Log("Serialization of {obj.GetType().Name} complete; {writer.WrittenBytes} bytes");
    // this needs to be stronger than Debug.Assert; this matters a lot
    if(writer.WrittenBytes != prefixLength + payloadLength)
        throw new DammitException("Incorrect length calculated; please contact library author");

    return writer.WrittenBytes; // because parent objects *also* need to check their lengths

(I'd be happy to PR it if folks aren't against it)

Now yes, I *could* do something like having every step of the process increment my own "bytes written" counter, but that is introducing more ways to have a bug; it feels like the `OutputWriter<T>` could *trivially* track this in the same way that the reader does.

(the number tracked would be the sum of `Advance(val)`, obviously)

**Comment by pakrym** [comment]
Dup https://github.com/dotnet/corefxlab/issues/1838

**Comment by davidfowl** [comment]
I'd prefer the BufferWriter symmetry as well.
