### ISSUE TITLE
Performance regression after adding segment type switch

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefxlab#2046]
We've seen 10% regression in kestrel and the source seems to be that multiple ReadOnlyBuffer methods became less efficient after the change namely:
1. `Seek` (because of CheckBounds)
2. `TryGet`
3. `Reader.MoveNext` - I suspect mostly because of TryGet

**Comment by benaadams** [comment]
![image](https://user-images.githubusercontent.com/1142958/34855154-0ac23a00-f736-11e7-8b70-abf54e00d8c6.png)

**Comment by benaadams** [comment]
Aside, this might be helpful https://github.com/dotnet/coreclr/issues/15755

**Comment by KrzysztofCwalina** [comment]
What was the TryGet change?

**Comment by benaadams** [comment]
> What was the TryGet change?

[Pattern matching](https://github.com/dotnet/corefxlab/blob/b5a998d2758b8ee968dad324f104c9310057eda3/src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer_helpers.cs#L18-L81) the different types?

**Comment by KrzysztofCwalina** [comment]
I talked with @pakrym and he will try to use the high order bit in one of the Position's ints to identify the IBUfferList case. Maybe we can even use the other bit to identify T[]

**Comment by benaadams** [comment]
Loose 2 bits; is still 1GB; if you need more you aren't segmenting correctly :)
Would also allow a 4th type at some point...

**Comment by benaadams** [comment]
Loose 2 bits; is still 1GB; if you need more you aren't segmenting correctly :)
Would also allow a 4th type at some point... (string for a StringBuilder type scenario?)

**Comment by halter73** [comment]
@benaadams Those of us with email notifications can see your ninja edits 😆 .

**Comment by ahsonkhan** [comment]
@pakrym, has this issue been resolved? Can it be closed?

**Comment by pakrym** [comment]
Yes
