### ISSUE TITLE
Pipelines / API: WritableBuffer is a false abstraction or is badly named (one of)

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#2051]
`WritableBuffer` presents itself as the "write analogue" to `ReadOnlyBuffer`, but in reality it is completely different. Unlike `ReadOnlyBuffer`, which is a general abstraction over one or more chunks of memory (including just a single `byte[]`), `WritableBuffer` is 100% tied to a `Pipe`, and in fact is simply a thin veneer over `Pipe` methods, with literally no state of it's own except:

    internal Pipe Pipe {get; }

At best, it feels like this type is in fact: `PipeWriter` / `PipeOutput`, or similar. At worst, it looks like the entire type could be removed with zero consequence, by simply making `Pipe : IOutput`. An argument could be made that that you need to `Alloc` to get the `WritableBuffer`, but the lifetime of the `WritableBuffer` *is not* tied to the `Alloc`/`Commit` cycle of the `Pipe`, and *because* it is a stateless veneer over `Pipe`, a `WritableBuffer` from one `Alloc` remains usable *after* the `Commit` as long as *another unrelated* `Alloc` has been performed. Essentially, all `Alloc`/`Commit` do here is toggle a "I'm writable at the moment" flag. The checks that enforce this flag already exist in the `Pipe` code - it isn't `WritableBuffer` that add these.

As an exchange type, `WritableBuffer` is completely different to `ReadOnlyBuffer`, with `ReadOnlyBuffer` being general-purpose and `WritableBuffer` being entirely implementation-specific (`Pipe`).

It isn't entirely clear to me why it exists, frankly. Can someone clarify?

---

Edit: there is one non-trivial method added by `WritableBuffer`, specifially: `public void Write(ReadOnlySpan<byte> source)`. However, this method can easily be provided as an extension method over `<T> where T : IOutput`.

**Comment by davidfowl** [comment]
You should watch the latest API review, we got rid of it.

**Comment by mgravell** [comment]
@davidfowl  lol! I haven't seen that one - do you have a link? I was around for the first one; I thought there was one on Friday that was talking about threading - wasn't around - did I miss one? Sorry to add confusion, I genuinely didn't know about this change.
