### ISSUE TITLE
Brotli Compression not working in an Azure Web App

### ISSUE THREAD

**Issue by jmkni** [dotnet/corefxlab#2068]
Hi all

I have the Brotli compression working nicely in development, but when I push it to Azure the files just don't compress.

The Content-Encoding is returned as **br**, but the files are no smaller than with GZIP. Running locally, they are significantly smaller.

On my Azure Web App, I have installed the **Brotli HTTP Compression (x86)** extension, and I am running on 32-bit.

Any ideas?

Cheers

**Comment by jmkni** [comment]
Edit, have tried switching to 64-bit, and using the 64-bit extension. Same issue. I have also tried both 32 and 64 bit without the extension, no joy!

**Comment by ahsonkhan** [comment]
cc @ianhays

**Comment by jyrkialakuijala** [comment]
which quality and window size are you running brotli with?

**Comment by jmkni** [comment]
Buffer size: 65520
Quality: CompressionLevel.Optimal

@jyrkialakuijala 

Again, it runs perfectly locally.

**Comment by joshfree** [comment]
@jmkni I've moved this issue to the corefx repo where the brotli code now lives - https://github.com/dotnet/corefx/issues/27317
