### ISSUE TITLE
MemoryPool shouldn't discard space per block

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#2098]
As MemoryPool's blocks are page sized and page aligned and the cpu doesn't prefetch across a page boundary the 64 byte buffer is not required.

Having the full 4096 bytes available is helpful when a pipe is used as output/input to a file which also reads and writes in 4096 chunks. https://github.com/aspnet/KestrelHttpServer/pull/2049

**Comment by ahsonkhan** [comment]
MemoryPool lives in corefx now. Can you please move the issue there? Thanks!
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/MemoryPool.cs#L10

**Comment by benaadams** [comment]
That's `MemoryPool<T>` rather than `MemoryPool : MemoryPool<byte>`

**Comment by davidfowl** [comment]
This got moved and done in ASP.NET
