### ISSUE TITLE
Bit Conversions for Spans?

### ISSUE THREAD

**Issue by BenjaminHolland** [dotnet/corefxlab#2151]
We've got some neat low level stuff happening with Spans. Can and should we provide BitConverter-like facilities that work with these, and is this an opportunity to extend the functionality of those facilities (like providing byte order or extension mode arguments)?

**Comment by BenjaminHolland** [comment]
Specifically, I'm suggesting something along these lines:
https://gist.github.com/BenjaminHolland/49cf8755295d1cccfe0afa84b81e9d43

**Comment by khellang** [comment]
You mean like these? https://github.com/dotnet/corefx/issues/22355 https://github.com/dotnet/corefx/issues/24144

**Comment by ahsonkhan** [comment]
> We've got some neat low level stuff happening with Spans. 

Thanks, we are super excited about these changes!

> Can and should we provide BitConverter-like facilities that work with these, and is this an opportunity to extend the functionality of those facilities (like providing byte order or extension mode arguments)?

We already have this being shipped as part of .NET Core 2.1 Feel free to give it a try (available in System.Memory preview 1 package on NuGet).

See BinaryPrimitives - https://github.com/dotnet/corefx/blob/master/src/System.Memory/ref/System.Memory.cs#L361

**Comment by ahsonkhan** [comment]
I am going to close this issue. Feel free to re-open if needed.
