### ISSUE TITLE
RioTcpServer.cs typo?

### ISSUE THREAD

**Issue by Palku** [dotnet/corefxlab#2174]
`public const int MaxOutsandingCompletionsPerThread =`
Should be MaxOutstandingCompletionsPerThread?

[https://github.com/dotnet/corefxlab/blob/010238eb489ccfb04a47774cc606653afb82464a/src/System.IO.Pipelines.Networking.Windows.RIO/RioTcpServer.cs](url)

**Comment by ahsonkhan** [comment]
https://github.com/dotnet/corefxlab/blob/697b5cc9afb4ba7ec7c18faed028869e7cabb71d/src/System.IO.Pipelines.Networking.Windows.RIO/RioTcpServer.cs#L19

**Comment by ahsonkhan** [comment]
System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs got deleted as part of the repo clean-up. https://github.com/dotnet/corefxlab/pull/2244

Hence, closing this issue.
