### ISSUE TITLE
There is no remote client ip information on UvTcpConnection

### ISSUE THREAD

**Issue by arontsang** [dotnet/corefxlab#2202]
One should at the very least have access to the client IP address for the Tcp connection from a UvTcpListener.

**Comment by arontsang** [comment]
https://github.com/dotnet/corefxlab/pull/2203

**Comment by ahsonkhan** [comment]
System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs got deleted as part of the repo clean-up. https://github.com/dotnet/corefxlab/pull/2244

Hence, closing this issue.

cc @davidfowl
