### ISSUE TITLE
.NET upgrades

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefxlab#2219]
Based on the error message I am getting (and recent commits), it looks like we are automatically updating version numbers, but not including the updated SDK in the project. Am I wrong? Is this by design? What's the best way to work with this?

> Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview3-26415-05' was not found.
>   - Check application dependencies and target a framework version installed at:
>       D:\Repos\corefxlab\dotnetcli\
>   - Installing .NET Core prerequisites might help resolve this problem:
>       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>   - The .NET Core framework and SDK can be installed from:
>       https://aka.ms/dotnet-download
>   - The following versions are installed:
>       1.0.4 at [D:\Repos\corefxlab\dotnetcli\shared\Microsoft.NETCore.App]
>       1.1.1 at [D:\Repos\corefxlab\dotnetcli\shared\Microsoft.NETCore.App]
>       2.0.0 at [D:\Repos\corefxlab\dotnetcli\shared\Microsoft.NETCore.App]
>       2.1.0-preview2-26406-04 at [D:\Repos\corefxlab\dotnetcli\shared\Microsoft.NETCore.App]
>       2.1.0-preview3-26410-06 at [D:\Repos\corefxlab\dotnetcli\shared\Microsoft.NETCore.App]
> 
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
> 
> Test Run Aborted.
> D:\Repos\corefxlab\scripts\build.ps1 : Some tests failed in project
> D:\Repos\corefxlab\scripts\..\tests\Benchmarks\Benchmarks.csproj
> At line:1 char:1
> + D:\Repos\corefxlab\scripts\build.ps1
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build.ps1

**Comment by ahsonkhan** [comment]
Run `git clean -fdx` or more simply delete the dotnetcli directory and then run build.ps1. The script does a naive check to see if that directory exists and skips the SDK install. If the directory doesn't exist, it installs the correct version (as required by the repo).

The long term fix would be to check if the required version is not installed, and install it (rather than only looking at whether the directory exists or not).

**Comment by MisinformedDNA** [comment]
Build now succeeds. Thanks.
