### ISSUE TITLE
Q: Span<T> Memory<T> Split

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/corefxlab#2261]
I'm looking for a way to split a Span<T> or Memory<T> into a ReadOnlySpan<ReadOnlySpan<T>> or ReadOnlyMemory<ReadOnlyMemory<T>> that delimited by a ReadOnlySpan<T> or Memory<T> is this possible? or supported ?

or is there a better way?
 
FYI: this is for a parsing data

**Comment by benaadams** [comment]
ReadOnlySequence? Can't find good example; but https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlyBuffer/ReadOnlySequenceTests.Common.cs#L177-L191

It acts as a Sequence of ReadOnlyMemory (e.g. List)

**Comment by ahsonkhan** [comment]
We have an issue for adding Split on `ReadOnlySpan<char>`: https://github.com/dotnet/corefx/issues/26528

Can you expand on your parsing scenario? I would be curious to know how you intend to use it.

We can't return a `ReadOnlySpan<ReadOnlySpan<T>>` since span cannot be put into a collection.

**Comment by ahsonkhan** [comment]
Yes, `ReadOnlySpan<ReadOnlyMemory<T>>` or `ReadOnlyMemory<ReadOnlyMemory<T>>` are doable.

**Comment by ahsonkhan** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/26528
