### ISSUE TITLE
System.Time - Ticks can be a UInt64 or ulong

### ISSUE THREAD

**Issue by deinok** [dotnet/corefxlab#2300]
Ticks can be unsigned, it have no sense to have -1 Ticks.

Also, in some methods exists the check of:
` if (ticks < MinTicks ){throw Exception();}`
This kind of checks can be deleted as the compiler will already check it.

**Comment by Kukkimonsuta** [comment]
While true traditionally types in BCL avoid using unsigned numbers to avoid constant conversions between signed and unsigned for developer:

https://msdn.microsoft.com/en-us/library/system.datetime.ticks(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.timespan.ticks(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.io.stream.length(v=vs.110).aspx

Is is even recommended in coding conventions:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#unsigned-data-type

So I don't believe this should be an exception.
