### ISSUE TITLE
Where is System.IO.Pipelines.Networking.Windows.RIO?

### ISSUE THREAD

**Issue by ForkBug** [dotnet/corefxlab#2301]
Sorry for not catching up. 
According to https://github.com/dotnet/corefxlab/pull/2244, it has been cleaned due to "old projects"?

**Comment by davidfowl** [comment]
Deleted

**Comment by davidfowl** [comment]
It was a prototype that will likely come back as a kestrel transport.

**Comment by ForkBug** [comment]
Thank you for the clarification.
It's a good attempt to provide the cutting edge network performance on windows. Expecting for the project reborn

**Comment by joshfree** [comment]
Related: 

- https://github.com/dotnet/corefxlab#archived-projects
- Delete old projects and remove failing samples from the solution. https://github.com/dotnet/corefxlab/pull/2244
- Move MultiValueDictionary, CommandLine, and Drawing.Graphics projects to archives. https://github.com/dotnet/corefxlab/pull/2245

**Comment by joshfree** [comment]
@ForkBug let us know if you have any any other questions; and feel free to reactivate this issue if needed.  Thanks
