### ISSUE TITLE
Add a performance benchmark for Range GetEnumerator

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2312]
We use BenchmarkDotNet for our performance benchmarks. See https://github.com/dotnet/corefxlab/tree/master/tests/Benchmarks for examples.

Add a performance test that measures the cost of iterating through a range of values.
https://github.com/dotnet/corefxlab/blob/d68a9a4cfae4c62a0cb05c204cf8d98d6876833a/src/System.Buffers.Experimental/System/Range.cs#L81

cc @KrzysztofCwalina

**Comment by i3arnon** [comment]
I'll take it.

**Comment by kant2002** [comment]
This closed by #2336

**Comment by karelz** [comment]
Thanks for reminder! Closing.
