### ISSUE TITLE
Add more JsonWriter performance tests.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2317]
Add a performance test similar to https://github.com/dotnet/corefxlab/blob/89ea88c64f2dabe362c0a3df21d07313542c1d80/tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs#L103-L130 with calls to WriteValue of different primitive types to measure the impact of the optimizations from https://github.com/dotnet/corefxlab/issues/2313 / https://github.com/dotnet/corefxlab/issues/2314.

**Comment by ahsonkhan** [comment]
Will assign to @hack2root, once he has collaborator invite.

**Comment by ahsonkhan** [comment]
cc @karelz

**Comment by karelz** [comment]
Invitation sent. @hack2root let us know when you accept, we can then assign the issue to you (GH limitation).

**Comment by fredeil** [comment]
I could take this one @ahsonkhan @karelz , could you fix collaborator invite?

**Comment by karelz** [comment]
@fredeil invitation sent. Be aware that becoming collaborator will auto-subscribe you to all repo notifications (500+ per day). You might want to switch it to "Not Watching" which will send you just your mentions assignments and explicit subscriptions.
