### ISSUE TITLE
Port Base64 Performance test to BenchmarkDotNet

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2318]
We have some Base64 performance tests that need to be ported from xunit.performance to BenchmarkDotNet.
https://github.com/dotnet/corefxlab/blob/89ea88c64f2dabe362c0a3df21d07313542c1d80/tests/System.Binary.Base64.Tests/PerformanceTests.cs#L12

Follow the examples from previous efforts to port the performance tests:
https://github.com/dotnet/corefxlab/pull/2240
https://github.com/dotnet/corefxlab/pull/2241
https://github.com/dotnet/corefxlab/pull/2242
https://github.com/dotnet/corefxlab/pull/2243
https://github.com/dotnet/corefxlab/pull/2249
https://github.com/dotnet/corefxlab/pull/2254
https://github.com/dotnet/corefxlab/pull/2260

cc @adamsitnik

**Comment by kant2002** [comment]
Would like take a stab
