### ISSUE TITLE
Port Utf8Utility Performance test to BenchmarkDotNet

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2319]
We have some Utf8Utility performance tests that need to be ported from xunit.performance to BenchmarkDotNet.
https://github.com/dotnet/corefxlab/blob/89ea88c64f2dabe362c0a3df21d07313542c1d80/tests/System.Text.Primitives.Tests/Encoding/Performance/Utf8UtilityPerfTests.cs#L11

Follow the examples from previous efforts to port the performance tests:
https://github.com/dotnet/corefxlab/pull/2240
https://github.com/dotnet/corefxlab/pull/2241
https://github.com/dotnet/corefxlab/pull/2242
https://github.com/dotnet/corefxlab/pull/2243
https://github.com/dotnet/corefxlab/pull/2249
https://github.com/dotnet/corefxlab/pull/2254
https://github.com/dotnet/corefxlab/pull/2260

cc @adamsitnik, @GrabYourPitchforks

**Comment by kant2002** [comment]
I will take a look at this.
