### ISSUE TITLE
Port Encoding (UTF-8/UTF-16/UTF-32) performance comparison test to BenchmarkDotNet

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2320]
We have some Utf8/Utf16 encoding performance tests that need to be ported from xunit.performance to BenchmarkDotNet.
https://github.com/dotnet/corefxlab/blob/22c2d4edc6fc16ed50489f6709ee54ab8aede113/tests/System.Text.Primitives.Tests/Encoding/Performance/PerfTests.CoreCLR.cs#L9
https://github.com/dotnet/corefxlab/blob/679861d43063637d523bd36d54c7dd25994c475e/tests/System.Text.Primitives.Tests/Encoding/Performance/PerfTests.Span.cs#L14

Follow the examples from previous efforts to port the performance tests:
https://github.com/dotnet/corefxlab/pull/2240
https://github.com/dotnet/corefxlab/pull/2241
https://github.com/dotnet/corefxlab/pull/2242
https://github.com/dotnet/corefxlab/pull/2243
https://github.com/dotnet/corefxlab/pull/2249
https://github.com/dotnet/corefxlab/pull/2254
https://github.com/dotnet/corefxlab/pull/2260

cc @adamsitnik, @GrabYourPitchforks

**Comment by kant2002** [comment]
will take a look
