### ISSUE TITLE
Cleanup Formatting PerfSmokeTests and port to BDN

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2323]
https://github.com/dotnet/corefxlab/blob/89ea88c64f2dabe362c0a3df21d07313542c1d80/tests/System.Text.Formatting.Tests/PerformanceTests.cs#L15

cc @KrzysztofCwalina, @adamsitnik

**Comment by fredeil** [comment]
Should this be moved to the "Benchmarks" part of the project?

**Comment by ahsonkhan** [comment]
> Should this be moved to the "Benchmarks" part of the project?

Yes, and the tests need to be ported over to use BenchmarkDotNet rather than xunit.performance (like the other tests within "Benchmarks").

**Comment by fredeil** [comment]
Cool, I will try to port it over when I have some time!

**Comment by fredeil** [comment]
I was experimenting with this, but I see that the `Benchmarks.csproj` uses:
```
  <TargetFramework>netcoreapp3.0</TargetFramework>
```
So I wasn't able to run the performance tests because of this.. Should I downgrade to 2.1 to run the performance tests?

cc @ahsonkhan, @karelz, @adamsitnik

**Comment by ahsonkhan** [comment]
Does targeting netcoreapp2.1 **on its own** resolve the issue (or do you have to downgrade the BDN package to 0.11.1 as well)?
https://github.com/dotnet/corefxlab/blob/ef7dd7bffcb1eedda5ed27e63b59af9c6b365a26/tools/dependencies.props#L13

**Comment by fredeil** [comment]
I got the project running and tests running. It was VS for Mac that complained that I didn't havet .NET Core installed, so I´ve started using VS Code for this particular repo now.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefxlab/pull/2480.
