### ISSUE TITLE
Address PR feedback from #2329

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefxlab#2337]
See https://github.com/dotnet/corefxlab/pull/2329#pullrequestreview-125412852 for PR feedback. The PR was already merged, so opening a new issue to track this.

**Comment by kant2002** [comment]
This is closed by https://github.com/dotnet/corefxlab/pull/2338

**Comment by ahsonkhan** [comment]
Closing since the remaining issues are no longer relevant (since we only have UTF-8 JsonWriter now and the UTF-16 specific one got removed).
