### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefxlab#2345]
- Updated my master branch (4924c291bc93c73c040745a23284b4cf212a133c)
- Ran `clean.cmd`
- Ran `build.cmd`

**Error**

> D:\Repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -2147450749. [D:\Repos\corefxlab\src\System.Time\System.Time.csproj]
> D:\Repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -2147450749. [D:\Repos\corefxlab\src\System.IO.FileSystem.Watcher.Polling\System.IO.FileSystem.Watcher.Polling.csproj]
> D:\Repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -2147450749. [D:\Repos\corefxlab\src\System.Buffers.Primitives\System.Buffers.Primitives.csproj]
> D:\Repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -2147450749. [D:\Repos\corefxlab\src\System.Reflection.Metadata.Cil\System.Reflection.Metadata.Cil.csproj]
> D:\Repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -2147450749. [D:\Repos\corefxlab\src\System.Numerics.Tensors\System.Numerics.Tensors.csproj]
> D:\Repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -2147450749. [D:\Repos\corefxlab\src\System.Memory.Polyfill\System.Memory.Polyfill.csproj]
> D:\Repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code -2147450749. [D:\Repos\corefxlab\src\System.Memory.Polyfill\System.Memory.Polyfill.csproj]

**dotnet --info**

> D:\Repos\corefxlab> dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.100-preview1-008958
>  Commit:    7ce47778b4
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.16299
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   D:\repos\corefxlab\dotnetcli\sdk\2.2.100-preview1-008958\
> 
> Host (useful for support):
>   Version: 2.1.0-rtm-26516-03
>   Commit:  caa7b7e2ba
>

**Comment by ahsonkhan** [comment]
I can't repro the failure on latest master (or on the commit you listed). Is it intermittent? Is there some dotnet.exe or other process still running in the background locking csc.dll?
 
Please feel free to re-open if you are still seeing issues with the build.

**Comment by MisinformedDNA** [comment]
I ran `clean` so all the processes should have been killed. Also, when `corefxlab/dotnetcli` is added to the beginning of the path, it totally jacks up my ASP.NET projects: Templates are missing, build warnings, etc.

**Comment by MisinformedDNA** [comment]
And no, it's not intermittent. It happens every time in the same place.

**Comment by ahsonkhan** [comment]
> And no, it's not intermittent. It happens every time in the same place.

Do you have VS running? Also, do you have any msbuild or VBCSCompiler.exe processes as well? I am not sure why you are seeing any failures. We don't see such failures in locally, in CI, or on official builds. 
Can you share the entire log from the build command?

As a last resort, consider restarting your machine.
