### ISSUE TITLE
Cleanup milestone and possible roadmap update

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#2367]
Now that 2.1 is released, can milestone [2.1](https://github.com/dotnet/corefxlab/milestone/2) be closed?

Also, could the team release an update on main focus for 2.2 and possibly 3.0 for this repo?  I really like the work that was put into this [previous doc](https://github.com/dotnet/corefxlab/blob/master/docs/roadmap.md).

Thx

**Comment by joshfree** [comment]
I closed the 2.1 corefxlab milestone.  Thanks for bringing this up.

The roadmap you linked continues to be valid - while Span, Memory, and Pipelines shipped internally in 2.0 and as public APIs in 2.1 (span design and prototyping actually began just days after .NET Core 1.0 shipped), the rest of https://github.com/dotnet/corefxlab/blob/master/docs/img/areas.png is still coming.

I'll update the roadmap doc to make it clearer that we're still progressing on this path and that we're investing in utf8 string, buffer management, and serialization next.

**Comment by shaggygi** [comment]
Sounds good.  Thx.  If possible, it would also be nice to see details on the Microservices thinking.  But this might be something @glennc is working on and might be detailed in one of the ASP repos.

**Comment by joshfree** [comment]
Yes, the dotnet/corefxlab repo is largely for long lead prototypes that we anticipate could be promoted to dotnet/corefx features in a future release.  Things like Bedrock would be documented in the aspnet repos.

/cc @davidfowl
