### ISSUE TITLE
System.Drawing.Graphics tests fail 

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#237]
... because libgd.dll is missing

**Comment by tarekgh** [comment]
I'll take a look.

**Comment by tarekgh** [comment]
fixed with the commit

Commit hash:	fc78615f9847111f09fac0c76490f760f176d77d
Parent(s):	f558fd9eea

Fix the break in System.Drawing.Graphics tests and updating lock.json files
