### ISSUE TITLE
Common Serial Port Class

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#2387]
It would be nice to have a common way to interact with serial devices across platforms as mentioned [here](https://github.com/dotnet/corefxlab/blob/3f85ca26d47d0de689c6c1c26f980c3def56a270/src/System.Devices.Gpio/System.Devices.Gpio/Documentation/GPIORef.cs#L160).

Below are some references to similar work.  Not sure the best approach, but there should be a common way for this scenario.

- https://github.com/dotnet/corefx/issues/984
- https://github.com/dotnet/corefx/issues/18012
- https://github.com/dotnet/corefx/issues/18023
- https://github.com/dotnet/corefx/issues/21810

**Comment by joshfree** [comment]
cc: @wfurt

**Comment by shaggygi** [comment]
See https://github.com/dotnet/corefx/issues/33374
