### ISSUE TITLE
API Proposal: FileSystemState

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefxlab#2390]
I decided that `PollingFileSystemWatcher` was not a great fit for my project. First off, my operations department has all sorts of tools for monitoring scheduled jobs, but not so much for continuous jobs. The other problem with continuous jobs is that they will stop at some point and file system changes could be missed. Furthermore, to make `PollingFileSystemWatcher` behave how I wanted it to, I've been jumping through a lot of hoops and asking for [features](https://github.com/dotnet/corefxlab/issues/2222) that may not otherwise be needed.

So I created [FileSystemState](https://github.com/MisinformedDNA/YellowCounter.FileSystemState). (NOTE: I created it in a separate repo since I need it for a project sooner than later.)

`FileSystemState` is mostly just a stripped down version of `PollingFileSystemWatcher`. It gets rid of the timer and eventing features. If you want changes, you ask for it and you get a list back. You can save and load state so you aren't required to have it running all the time.

## Requirements

- Can run as a scheduled job, instead of a continuous job
- All file changes are eventually detected
- Can be used as the basis of `PollingFileSystemWatcher`

## APIs

```csharp
namespace System.IO
{
    public class FileSystemState
    {
        public FileSystemState(string path, string filter = "*", EnumerationOptions options = null);
        public string Path { get; set; }
        public string Filter { get; set; }
        public EnumerationOptions EnumerationOptions { get; set; }

        public void LoadState();
        public void LoadState(Stream stream);
        public void SaveState(Stream stream);
        public FileChangeList GetChanges();

        protected internal virtual void DetermineChange(string directory, ref FileChangeList changes, ref FileSystemEntry file);
        protected internal virtual bool ShouldIncludeEntry(ref FileSystemEntry entry);
        protected internal virtual bool ShouldRecurseIntoEntry(ref FileSystemEntry entry);
    }

    public class FileChangeList : List<FileChange> { }

    public class FileChange
    {
        public string Directory { get; }
        public string FileName { get; }
        public WatcherChangeTypes ChangeType { get; }
    }
}
```

**Notes:**
- Testing is much easier and cleaner without polling and eventing
- `PollingFileSystemWatcher` would inherit from `FileSystemState` and the timer would simply call `GetChanges` and raise an event, in items were returned
- We could remove serialization from `PollingFileSystemWatcher`
- Changed `FileChange` from struct to class, similar to [FileSystemEventArgs](https://msdn.microsoft.com/en-us/library/system.io.filesystemeventargs(v=vs.110).aspx)

**Comment by BreyerW** [comment]
What happened to the idea of providing specialized constructor on already existing `FileSystemWatcher` (which return `FileSystemWatcher` but with polling semantic rather than event-based)? Seems like best way from discoverability point since everyone who need monitoring files sooner or later stumble upon this class) and reduce type/namespace clutter. Oh, and refactoring between polling and event-based would likely be much simplier this way.

**Comment by MisinformedDNA** [comment]
While both have similar goals and have _some_ similar APIs, the way they go about it are completely different. For one, `FileSystemWatcher` raises a single event for each change detected and `PollingFileSystemWatcher` raises all the changes in one event. That alone makes it hard to bring these into a single abstraction.

Another obstacle might be that `FileSystemWatcher` is built on .NET Standard, but `PollingFileSystemWatcher` is built on .NET Core 2.1 (due to the use of `FileSystemEnumerable`).

If someone wants to put forth an API proposal on how to resolve all the differences, they should go for it. I don't see an obvious way to do it without modifying `FileSystemWatcher`'s public surface and I'm guessing that would be a hard sell.

**Comment by danmosemsft** [comment]
@jeremykuhne fyi
