### ISSUE TITLE
Add a StringKeyedDictionary<T> type

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/corefxlab#2438]
## Motivation
As part of the #2406 initiative I would like a `StringKeyedDictionary<T>` type added in order to allow using a `ReadOnlySpan<char>` value for dictionary lookups without having to allocate a `string`.

## Proposed API
```diff
 namespace System.Collections.Specialized {
+    public class StringKeyedDictionary<T> : Dictionary<string, T> {
+        public StringKeyedDictionary();
+        public StringKeyedDictionary(IStringEqualityComparer comparer);
+        public StringKeyedDictionary(int capacity);
+        public StringKeyedDictionary(int capacity, IStringEqualityComparer comparer);
+        public StringKeyedDictionary(IDictionary<string, T> dictionary);
+        public StringKeyedDictionary(IDictionary<string, T> dictionary, IStringEqualityComparer comparer);
+        public StringKeyedDictionary(IEnumerable<KeyValuePair<string, T>> collection);
+        public StringKeyedDictionary(IEnumerable<KeyValuePair<string, T>> collection, IStringEqualityComparer comparer);
+        public new IStringEqualityComparer Comparer { get; }
+        public T this[ReadOnlySpan<char> key] { get; }
+        public bool ContainsKey(ReadOnlySpan<char> key);
+        public bool Remove(ReadOnlySpan<char> key);
+        public bool TryGetValue(ReadOnlySpan<char> key, out T value);
+    }
+    public interface IStringEqualityComparer : IEqualityComparer<string> {
+        bool Equals(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
+        int GetHashCode(ReadOnlySpan<char> obj);
+    }
 }
 namespace System {
-     public abstract class StringComparer : IComparer<string>, IEqualityComparer<string>, IComparer, IEqualityComparer {
+     public abstract class StringComparer : IComparer<string>, IEqualityComparer<string>, IComparer, IEqualityComparer, IStringEqualityComparer {
+        public virtual bool Equals(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
+        public virtual int GetHashCode(ReadOnlySpan<char> obj);
      }
     public sealed class CultureAwareComparer : StringComparer {
+        public override bool Equals(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
+        public override int GetHashCode(ReadOnlySpan<char> obj);
     }
     public class OrdinalComparer : StringComparer {
+        public override bool Equals(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
+        public override int GetHashCode(ReadOnlySpan<char> obj);
     }
 }
```

## Implementation Details
* The default implementation of the new virtual methods on `StringComparer` would convert the span to a string and use the string methods instead.
* Internal details of `Dictionary<TKey, TValue>` would be needed to implement the `ReadOnlySpan<char>` overloads.
* A `null` comparer passed to the constructor would default to `StringComparer.Ordinal`.
* Would need to be implemented in [corefx](https://github.com/dotnet/corefx) to access internal `Dictionary<TKey, TValue>` details as well as update `StringComparer`.

## Possible Addition
While not specifically needed for this request an `IStringComparer` interface should probably be added as well like so since we're updating `StringComparer`. It could then be used in a specialized `StringKeyedSortedDictionary` or `StringSortedSet`.

```diff
 namespace System.Collections.Specialized {
+    public interface IStringComparer : IComparer<string> {
+        int Compare(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
+    }
 }
 namespace System {
-    public abstract class StringComparer : IComparer, IEqualityComparer, IComparer<string>, IEqualityComparer<string>, IStringEqualityComparer {
+    public abstract class StringComparer : IComparer, IEqualityComparer, IComparer<string>, IEqualityComparer<string>, IStringEqualityComparer, IStringComparer {
+        public virtual int Compare(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
     }
     public sealed class CultureAwareComparer : StringComparer {
+        public override int Compare(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
     }
     public class OrdinalComparer : StringComparer {
+        public override int Compare(ReadOnlySpan<char> x, ReadOnlySpan<char> y);
     }
 }
```

## Open Questions
* Should the additional `IStringComparer` interface also be implemented?

## Updates
* Switched to proposing implementation that derives from `Dictionary<string, T>` due to the massive code duplication of re-implementing `Dictionary<TKey, TValue>`'s logic.

**Comment by cdmihai** [comment]
And the equivalent `ConcurrentStringKeyedDictionary` :)

**Comment by TylerBrinkley** [comment]
To prevent the massive code duplication or re-implementing `Dictionary<TKey, TValue` I'm thinking `StringKeyedDictionary<T>` should just derive from it and have access to some of its internal fields to incorporate the `ReadOnlySpan<char>` overloads.

**Comment by danmosemsft** [comment]
@safern

**Comment by TylerBrinkley** [comment]
I've moved the proposal to [corefx#31942](https://github.com/dotnet/corefx/issues/31942) as it couldn't reasonably be implemented outside of corefx as it needs access to some internal fields on `Dictionary<TKey, TValue>` as well as updating `StringComparer`.
