### ISSUE TITLE
TypeLoader shouldn't police whether a public key is "valid."

### ISSUE THREAD

**Issue by ghost** [dotnet/corefxlab#2447]
When converting a public key blob to a public key token, System.Reflection.TypeLoader uses the trick of allocating an AssemblyName, setting the public key blob, then accessing the public key token property which triggers AssemblyName's automatic computation of the token:

https://github.com/dotnet/corefxlab/blob/29fa2def98d6de0a41aa9e9b10d7b01ba82fc30c/src/System.Reflection.TypeLoader/src/System/Reflection/TypeLoading/General/Helpers.cs#L129

The problem is that AssemblyName does not just compute the token, it checks that the public key is a valid CAPI public key blob and stops the proceedings cold with an exception if it isn't.

This isn't desirable for System.Reflection.TypeLoader as its job is to report what's there (including possibly "illegal" but parsable metadata.) It's not doing any signing or signing verification - it's just reporting and it should not be applying validation rules specific to the running runtime.

Code-wise, the fix is simple: have the helper to compute the PKT itself (compute the SHA1 of the public key, throw away all but the last 8 bytes, reverse the order of the 8 bytes.) 

The problem is the process: the very mention of the word "SHA1" throws things into a panic these days and corefx even has an analyzer that breaks the build if it sees a SHA1 object being created. So this change will presumably require some sort of security review and exemption.

**Comment by AtsushiKan** [comment]
The world won't end if we don't fix this but it's a nice to have.

**Comment by danmosemsft** [comment]
Checking mentioned above is at
https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/strongname/api/strongnameinternal.cpp#L187

Presumably another option is to catch the SecurityException and use a dummy PKT in that case.

**Comment by safern** [comment]
@steveharter there is some code in dotnet/runtime pointing to this issue, should we transfer it to dotnet/runtime?

https://github.com/dotnet/runtime/blob/b27a4b3566deb235c2746e3145dd0438ee38773f/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Helpers.cs
