### ISSUE TITLE
Question - System.Reflection.TypeLoader

### ISSUE THREAD

**Issue by ilmax** [dotnet/corefxlab#2451]
Hi, I've just noticed a PR that added `System.Reflection.TypeLoader` so I cloned the repo and started looking into it. Since this is built on top of System.Reflection.Metadata, can we see this as a slightly "faster" reflection? If that's not the case, I'm curious about the purpose of this library. 

I've looked into issues but I wasn't able to find anything.

Thanks, Max.

**Comment by mattwarren** [comment]
Have you read the [TypeLoader spec](https://github.com/dotnet/corefxlab/blob/master/docs/specs/typeloader.md)? It's got some useful info.

**Comment by ilmax** [comment]
Thanks @mattwarren, exactly what I was looking for
