### ISSUE TITLE
Test Debt: System.Reflection.TypeLoader.Tests.dll will need lots of work to run on AOT platforms.

### ISSUE THREAD

**Issue by ghost** [dotnet/corefxlab#2467]
This issue isn't actionable until we productize System.Reflection.TypeLoader to corefx but I'm opening this now to persist the action items.

While `System.Reflection.TypeLoader` itself should work as is on AOT platforms, the same can't be said for `System.Reflection.TypeLoader.Tests`. A significant amount of work is needed to get these tests to pass on that platform.

The tests in that assembly can be divided into the following buckets:

### Tests that get their test data from byte arrays in TestData.cs.

A good example is this:

https://github.com/dotnet/corefxlab/blob/d9aede5d9500412ea8265b51d667a439422b09c6/tests/System.Reflection.TypeLoader.Tests/src/Tests/TypeLoader/LoadApi.cs#L16

For this class of tests, the test assemblies were built by hand using csc, ilasm and in some cases, outright hex editing, and persisted into a base64-encoded blob, like this: https://github.com/dotnet/corefxlab/blob/d9aede5d9500412ea8265b51d667a439422b09c6/tests/System.Reflection.TypeLoader.Tests/src/TestUtils/TestData.cs#L60

This ensures that the test data is stable, at the cost of making it harder to revise the test in the future. 

**This class of tests should not require any changes to pass on an AOT platform.**

### Tests that use internal Reflection on S.R.TypeLoader.dll

These tests use this helper method (https://github.com/dotnet/corefxlab/blob/d9aede5d9500412ea8265b51d667a439422b09c6/tests/System.Reflection.TypeLoader.Tests/src/TestUtils/NetStandardBridge.cs#L46) to invoke non-NetStandard Reflection api from a NetStandard test library.

The only reason this exists is that for the time being, we're stuck in a situation where corefxlab only builds the netstandard build of S.R.TypeLoader but we want to maintain on-going test coverage of NetCore-specific paths that can only be reached from outside by NetCore builds. So we use a little sneaky Reflection to allow a netstandard application (the test) to "call" NetCore-only apis.

Once moved to the corefx, both `TypeLoader` and `TypeLoader.Tests` should be building in multiple configurations with on-going CI testing on both CoreCLR and NETFX. So the need for this hack should go away.

**This helper should be expunged and the dependent code separated by #if's before attempting to make the tests AOT-compatible.**

### Tests that use the `Project()` extension method.

This is the largest class of tests and consists of higher-level Reflection api tests, many of which are reused test assets from older projects. 

The test data for these tests are compiled directly into the test assembly itself. For example:

https://github.com/dotnet/corefxlab/blob/d9aede5d9500412ea8265b51d667a439422b09c6/tests/System.Reflection.TypeLoader.Tests/src/Tests/TypeInfoFromProjectN/TypeInfo_MethodTests.cs#L18

These tests use **regular** Reflection to obtain the Type being tested, then call the extension method `Project()` (https://github.com/dotnet/corefxlab/blob/d9aede5d9500412ea8265b51d667a439422b09c6/tests/System.Reflection.TypeLoader.Tests/src/TestUtils/TestUtils.JittedRuntimes.cs#L18). The job of `Project()` to load up the type's containing assembly into global `TypeLoader` and then find the corresponding `Type` object in the TypeLoader-provided Assembly. Though this is certainly indulgent at the runtime level, it makes it far easier to maintain and add new tests, as well as allowing us to use the same test code to test both `TypeLoader`-based Reflection and normal Reflection (just turn `Project()` into an identity function.)

The strategy for making this work would be as follows:

- On AOT configurations, `TestUtils.JittedRuntimes.cs` should by replaced by a `TestUtils.AotRuntimes.cs` file that implements the `Project()` and `CreateStreamForCoreAssembly()` helper routines on an AOT platform.

- This requires ensuring that the build process for `TypeLoader.Tests` deposits the IL for `System.Reflection.TypeLoader.Tests.dll` someplace where the `Project()` routine can find it at runtime.

- This also requires that the IL for some form of `mscorlib.dll` be located someplace where `CreateStreamForCoreAssembly()` can find it. Some possibilities:

1. Use the `mscorlib` façade that NetCore uses.
2. Look for "c:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll" (an installed NETFX). Ties test to Windows artificially but this might an early unblocker.
3. Build a minimal mscorlib (containing just the types that the test data refers to) and blob it a base64-encoded byte array in `TestData.cs`. This might be workable if the blob isn't excessively large.

### Tests relying on P/Invoke metadata.

For example: https://github.com/dotnet/corefxlab/blob/d9aede5d9500412ea8265b51d667a439422b09c6/tests/System.Reflection.TypeLoader.Tests/src/SampleMetadata/SampleMetadata.cs#L317

This is test metadata that references non-existent native DLLs and `MarshalAs` attributes that have no plausible relationship to the type of the field they decorate. And we can get away with that on jitted platforms since these types are never executed or jitted - we just read them as metadata and as long as the garbage that comes out matches the garbage we put in, that's good enough to validate the `TypeLoader` code.

On an AOT platform, however, all this nonsense metadata will likely result in an build-time ILC error or a test assembly that refuses to launch ("Cannot find foo.dll").

It may not be worth salvaging these tests for AOT but if that's desirable, the only likely solution is to capture this subset of metadata as a blobbed assembly in `TestData.cs` and make the P/Invoke tests read from those.

**Comment by AtsushiKan** [comment]
This is something that will come up as part of migrating TyeLoader to corefx.
