### ISSUE TITLE
[Proposal] Create System.Devices.I2c API

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#2487]
## Initial Rambles...
This proposal is to define a new API for I2C devices.  It is somewhat related to the new System.Devices.Gpio work.  However, the intent is to remove and separate into different APIs to focus on each specific type of I/O instead of one gigantic library (with a mix/match of unneeded dependencies.  There are many ways to accomplish this and hope others would chime in.  This proposal is opinionated and related to my initial thoughts here (#2388).  Also, this issue is a WIP and I will be making updates over the next few days/weeks during spare time.

As mentioned before, I believe we could take advantage of some of the work that came from the <a href="https://docs.microsoft.com/en-us/uwp/api/windows.devices" target="_blank">Windows.Devices.XXX APIs</a>.  It should be possible to have similar namespaces like `System.Devices.Gpio`, `System.Devices.I2c`, `System.Devices.Spi`, etc..  Later, we could have more advanced APIs following the same thinking like `System.Devices.Serial`, `System.Devices.Bluetooth`, `System.Devices.Usb`, etc..  I plan to create a PR soon with initial code, but is only a starting point.  Samples, tests, docs and such will be added overtime if this approach seems like a good path to research/implement.

This proposal is focused on `System.Devices.I2c` to verify capabilities and limitations.  However, I also have started some other work related to other APIs mentioned above (e.g. SPI, GPIO, etc.).

## System.Devices.I2c API

While GPIO is general (hence the name) and can reference I2C-type pins, I like having the option of separate APIs based on functionality and project requirements.  Sometimes you might only need to toggle a few pins and other times you need to communicate with just a bus (I2C/SPI) device such as temperature, real-time clocks or EEPROMs.  The `System.Devices.I2c` API will provide the basic classes and interfaces related to I2C.  This includes enums like bus speed and sharing modes.  It also will include advanced helpers to support off-loading [I2C Bus Providers](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/busproviders) (e.g. Ardruino, etc.).

### System.Devices.II2cDevice

Within `System.Devices.I2c`, there should be an `II2cDevice` interface to allow different types of I2C device implementations based on OS, hardware platform, etc.  While it would be ultimately awesome to have a single `I2cDevice` class that works everywhere, I have not seen a good solution (with my limited knowledge/research).  Therefore, you could easily create implementations such as UnixI2cDevice, WinRtI2cDevice, etc.. I noticed how Unix implementation call into libc/ioctl, but not sure if it is possible to do this for Windows flavors.  Again, if anyone knows a good approach (including someone from the Windows team), please chime in that would allow a better solution of having one preferred I2cDevice implementation that could be referenced/work across various OS & hardware platforms.

**Update 9/20/2018**.  I have most of the code setup in a project with the core I2C code.  I'm still working on the XML documentation and such and plan to create a PR in the near future.  Afterwards, I will followup with a UnixI2cDevice implementation project (some of which is based on the work already added for (#2426).

**Update 9/21/2018**.  Updated code based on feedback.  @KrzysztofCwalina I really appreciate the insight.  Thank you. 👍 

**Update 9/29/2018**.  Attempted to clean within System.Devices.Gpio.I2c.Unix namespace.  As I'm still not sure how/if possible to have single UnixDevice to run across different OS/hardware, it seems like it would be helpful to separate out (at least during prototyping).

**Comment by joshfree** [comment]
Thank you @shaggygi for the I2c/I2cDevice proposal.  @ianhays will be back late next week and should be able to collaborate on this then. 😄   Our goal is to get the API shape through https://aka.ms/api-review by November and into the dotnet/corefx repo by then.

**Comment by shaggygi** [comment]
Tried another go at it...  #2505

**Comment by joshfree** [comment]
@joperezr @ianhays PTAL
