### ISSUE TITLE
Concurrent AppendableList<T> collection

### ISSUE THREAD

**Issue by AnthonyLloyd** [dotnet/corefxlab#2541]
I've hit a case where I only need to Add to a list and never update items in the list.
This should be able to be done by adding the item and increasing the size. Or when a resize is needed to do the resize first then the add.
That way you don't need read locks and just need a lock on add.

This can't be done using `List<T>` as `_size` is set first.

https://github.com/dotnet/corefx/blob/b0f6ef48cca9ae70b0e8d81ffa640cbdd1b26f55/src/Common/src/CoreLib/System/Collections/Generic/List.cs#L215

ConcurrentBag is a much more general concurrent implementation.

Is there something I'm missing? Any interest in this as a collection? Or can `List<T>` be modified so it can be used in this way?

**Comment by benaadams** [comment]
`ConcurrentQueue<T>`?
