### ISSUE TITLE
Option to support trailing commas with JsonReader

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefxlab#2576]
Comments and trailing commas are the most common differences from the JSON spec found in configuration files.

Consider adding an option to allow JsonReader to support trailing comments in JSON arrays and objects.

```json
{
  "myproperty": true,
}
```

```json
[
  "first",
  "second",
  "third",
]
```

**Comment by danmosemsft** [comment]
Comments above presumably souls be commas
