### ISSUE TITLE
What is the purpose of Threading.Channels?

### ISSUE THREAD

**Issue by BBGONE** [dotnet/corefxlab#2588]
Threading.Channels looked promising at first but after testing them in different scenarios - they behaved not much better, but sometimes worse than the simple BlockingCollection. And they block the thread on writes as well. I also tried to replace the Channels with a BlockingCollection in the AsyncFileWriter https://github.com/electricessence/AsyncFileWriter and with BlockingCollection the results were a bit (10%) better than with the Channels.
Also i created sample projects https://github.com/BBGONE/TestThreadAffinity
which compare Threading.Channels with the simple BlockingCollection : 	ThreadPoolTest (simple BlockingCollcetion) and  ThreadingChannels (replaced the BlockingCollection with the Channels).

**Comment by BBGONE** [comment]
Oops, it seems i figured it out. Although, the performance is the same in all usages, the channels have the benefit of nonblocking wait for when the channel can be written. This happens in the bounded scenarios. The BlockingCollection blocks the thread - not allowing to write, the Channels leave the thread to be used by others.

**Comment by BBGONE** [comment]
I checked it like this:

```
foreach (var num in partion)
{
                    ++cnt;
                    var enqueTask = svc.AddToQueue(CreateNewPayload(), Interlocked.Increment(ref SEQUENCE_NUM), token);
                    if (!enqueTask.IsCompleted)
                    {
                        Console.WriteLine($"Patrition #{partion.Key} On Count: {cnt} waiting async");
                    }
                    await enqueTask;
                    Interlocked.Increment(ref sentMessagesCount);
                }
```

**Comment by BBGONE** [comment]
Although it behaves as expected while waiting for the channel can be written One question remains open: Why the performance dropped 2,0- 2,5 if to the channel is written in 4 concurrent threads.
The performance drops with the BlockingCollection as well. But i think that with the channels it can be optimized. 
If it can not be optimized, then close the issue please.
I will reopen it for checking this.

**Comment by stephentoub** [comment]
> Why the performance drops 2,0- 2,5 if to the channel is written in 4 concurrent threads.

Because there's contention.  If you can optimize it, please submit a PR to do so.  I'm going to close this issue, though, as it's not actionable as is, and the right repo now for channels-related issues is corefx.  Thanks.

> the channels have the benefit of nonblocking wait for when the channel can be written

And asynchronous reads when channels are empty.

**Comment by BBGONE** [comment]
Sorry. I converted it to CoreFX. It started to perform **2,5 times faster** - with the same code and the same settings
I did not know that it had so big influence on the perfomance.
