### ISSUE TITLE
Run HelloWorld on the CoreCLR my own build

### ISSUE THREAD

**Issue by bartmao** [dotnet/corefxlab#26]
I did the following steps described at http://blogs.msdn.com/b/dotnet/archive/2015/02/03/coreclr-is-now-open-source.aspx?Redirected=true&PageIndex=2
1. Modify CoreCLR to your heart’s content
2. Build CoreCLR via build.cmd x64 release
3. Copy the following files from coreclr\binaries\x64\release to corfxlab\demos\CoreClrConsoleApplications\HelloWorld\NotYetPackages\CoreCLR:
coreclr.dll
CoreConsole.exe
mscorlib.dll
4. Rebuild HelloWorld.sln (either using the command line or in VS)
It seems nothing happen. Why should I copy files to the folder 'NotYetPackages\CoreCLR', and how the HelloWorld.exe find the newly added dlls/exes?

**Comment by KrzysztofCwalina** [comment]
Try the following:
1. Build Helloworld.sln
2. Build x86 configuration of CoreCLR
3. Copy your custom CLR binaries from coreclr\binaries\x64\release\ to the hello world output folder.
4. rename CoreConsole.exe to HelloWorld.exe
5. run HelloWorld.exe

If you still have problems, run the exe with the /_v switch

**Comment by KrzysztofCwalina** [comment]
I will close this issue for now. Let me know if it still does not work for you.

**Comment by bartmao** [comment]
Thanks , and sorry for my late reply. Your steps do work well for me! But I still can not figure out what happens  under the hood. Seems I need learn more on CoreClr :(
