### ISSUE TITLE
DictionarySlim does not implement IEnumerable consistently

### ISSUE THREAD

**Issue by FilipTowarnicki** [dotnet/corefxlab#2621]
The System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.' exception is not thrown in the following scenarios:

```
            var dict = new DictionarySlim<int, int>();
            foreach (var item in new[] {1, 2, 3, 4, 5})
            {
                ref int value = ref dict.GetOrAddValueRef(item);
                value = item + 100;
            }
            

            foreach (var item in dict)
            {
                ref int value = ref dict.GetOrAddValueRef(321);
                value = 321;

                if (item.Value == 321)
                {
                    // this is never true, no exception is thrown
                }
            }

            foreach (var item in dict)
            {
                dict.Clear();
                // thrown: System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'
            }
```

**Comment by mikedn** [comment]
Well, it's called "Slim" for a reason.

**Comment by danmosemsft** [comment]
Yes that's pretty much it: we did have iterations of this with the traditional checks in the enumerators, but removed them. At the cost of adding a `_version` field and incrementing it all over, you get some exceptions that might not even indicate a problem. I am skeptical about the value that the `_version` checks add in the traditional collections. 

If it was possible to somehow cause enumeration to continue indefinitely, we should fix that, akin to `ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();`

**Comment by MarcoRossignoli** [comment]
@danmosemsft slightly different but related to IEnumerable implementation, remove item during enum throw exception https://github.com/dotnet/corefx/blob/5524fb540121fa69380c3279708d5fc5c462fbee/src/System.Collections/tests/Generic/Dictionary/Dictionary.Generic.Tests.netcoreapp.cs#L117

https://github.com/dotnet/corefxlab/blob/master/src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/DictionarySlim.cs#L330 removing doesn't decrement enum cached count,  _count == 0 is skipped and while throw out of range. I don't know if it's expected.

**Comment by danmosemsft** [comment]
@MarcoRossignoli yes if I understand you correctly, that's also a consequence of removing `version`. It's deterministic, so it's simply a different exception than big Dictionary.

**Comment by MarcoRossignoli** [comment]
More or less, Dictionary support this scenario removing item doesn't change version, only TryInsert, EnsureCapacity and TrimExcess. 
I think that's only a feature.

**Comment by danmosemsft** [comment]
Ah yes, the way Dictionary is implemented, it is safe to remove during enumeration so we removed the version check there. I don't think it is worth making things less "slim"

**Comment by danmosemsft** [comment]
By design as above.
