### ISSUE TITLE
Can System.IO.FileSystem.Watcher.Polling be used with .net Full Framework?

### ISSUE THREAD

**Issue by StefanKoell** [dotnet/corefxlab#2627]
Hi!

There's a dependency on FileSystemEnumerator - which seems only be available in .net core. Is there a way to get this on .net full framework to run as well?

Thanks!
Stefan

**Comment by danmosemsft** [comment]
I don't think is any plan to put up a public Nuget package for FileSystemEnumerator 
 that would run on .NET Framework. @JeremyKuhne owns it, though.

**Comment by KrzysztofCwalina** [comment]
The implementation used to support .NET Framework. It's indeed unfortunate that it regressed.

**Comment by danmosemsft** [comment]
@StefanKoell you could probably build one yourself though.
