### ISSUE TITLE
Update and replace uses or RangeLab with System.Range within corefxlab

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2628]
.NET Core 3.0 contains the new `Range` type https://github.com/dotnet/corefx/blob/4378851bc5fd0e3c5043a6d0a3ac835e838fcf7d/src/Common/src/CoreLib/System/Range.cs#L9

We need to remove the RangeLab type from corefxlab and update its uses with the new `Range`.

cc @tarekgh

**Comment by tarekgh** [comment]
ok, will get into this at some point after finishing the Range/Index in corefx.

**Comment by ahsonkhan** [comment]
@tarekgh - friendly ping now that 3.0 is done

**Comment by tarekgh** [comment]
Will try to do it this week (I hope) :-)
