### ISSUE TITLE
Plans and roadmap for Tensor class?

### ISSUE THREAD

**Issue by dotChris90** [dotnet/corefxlab#2630]
Hello experts! :)

a friend of me and I just found out today that your lab is doing something impressive for our taste. 
I am talking about the Tensor class in System.Numerics. 

The reason why we impressed and interested is that we are (just for fun) working on a numpy port with nearly identical APIs - https://github.com/SciSharp/NumSharp. Unfortunately it is not too mature like we wish but we still proud of it. ;D 

Since numpy offering a specific NDArray we also developed a (**TENSORLIKE**) NDArray in C#. 
In opposite to System.Numerics.Tensor - it is non generic and stores data in an internal Storage class. Storage class has a System.Array property which stores all data independent of shape in 1D array (Fortran or C style layout).  There exist a generic version which inheritage (aka is a child of) from the non generic version - and it rewrite the indexing method (so output is not object but specific data type).

We are little bit curious if there exist already concrete plans to ship this Tensor class to standard corefx or at moment it is more "playground" :)
Just want to know how we can adapt our NumSharp Project + maybe other projects so we can use more internal classes like Tensor. 

Thanks for your time and - thanks for working so hard on the corefx libs - you guys really make .NET ready for the future.

**Comment by ahsonkhan** [comment]
cc @eerhardt, @tannergooding

**Comment by dotChris90** [comment]
@Oceania2018

**Comment by danmosemsft** [comment]
@NiklasGustafsson fyi.

**Comment by tannergooding** [comment]
This issue was moved to dotnet/corefx#34527
