### ISSUE TITLE
Q: System.IO.Pipelines - Performance and Memory Allocation

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/corefxlab#2632]
Great work, give the improvements in performance and memory allocations are there any plans to provide new/additional implementations for features like XmlSerializer and other features that currently use System.IO. Stream etc.. IMHO it would be good if implementations of Text, Xml, Json, and/or Csv reader/writers where included especially given the memory improvement for when a developer is targeting IoT devices.

**Comment by khellang** [comment]
It's already being worked on, with JSON as first priority (see https://github.com/dotnet/corefx/pull/33216 and https://github.com/dotnet/corefx/pull/34485). I doubt XML and CSV will come around in the near future as most things are JSON anyway nowadays. Maybe a nice opportunity for a community project?

**Comment by grahamehorner** [comment]
@khellang that is great to hear; I do think however XML serialization is important as a large number of services are very much WSDL/SOAP based and XML is IHMO the performance of SOAP client/server performance would benefit greatly from using the pipeline version of the serialization; while maintaining backwards compatibility.

I'll have a look at the WIP referenced and possible start of an XmlParser/CsvParser etc. based on the concepts/interfaces around the Json implementation using pipelines

**Comment by ahsonkhan** [comment]
> Maybe a nice opportunity for a community project?

Definitely.

> I'll have a look at the WIP referenced and possible start of an XmlParser/CsvParser etc. based on the concepts/interfaces around the Json implementation using pipelines

If you have a concrete usage scenario and can showcase significant performance improvements, feel free to file an API proposal within corefxlab (following up with a project with the implementation).

I am sure we can find some steward to review it and provide feedback along the way. Feel free to ping me on the issues as well.

cc @danmosemsft, @joshfree, @krwq, @davidfowl, @pakrym
