### ISSUE TITLE
[Proposal] Start a project around various numeric types

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefxlab#2635]
We have a number of proposals on CoreFX around exposing various new numeric types. It would likely be a good idea to have a project here to prototype some of these.

Some of the ideas that I think would likely be applicable are the following:

Types which are generally considered ABI primitives:
* The IEEE `binary128` (quad-precision) floating-point type
* The IEEE `decimal32`, `decimal64`, and `decimal128` floating-point types
* The `Int128` and `UInt128` types

Types which are fairly core to machine-learning and graphics scenarios:
* The IEEE `binary16` (half-precision) floating-point type
* The `bfloat16` floating-point type

Types which allow arbitrary precision arithmetic:
* The IEEE `binary{k}` (where `k >= 128` and `(k % 32) == 0`) floating-point type (effectively a `BigFloat` type)
* The IEEE `decimal{k}` (where `k >= 32` and `(k % 32) == 0`) floating-point type (effectively a `BigDecimal` type)

**Comment by AlgorithmsAreCool** [comment]
This is cool, I just had to roll my own BigRational to support exact precision decimal arithmetic for a project.

Would you consider mutable arbitrary precision numbers?
I recall the original discussions around wanting to keep the semantics of BigInteger the same as normal ints.

But when you are doing alot of calculations the copying becomes a big (heh) pain.

It would be really nice to have a BigIntegerBuilder class or something that could accumulate repeated updates and only reallocate buffers when it was actually needed (or rent buffers in smaller segments).

I can provide a more concrete use case if you are open to the concept.

**Comment by fanoI** [comment]
Happy to see this moving forward.

Can I hope the implementations of these new numeric types will be all in managed code?

**Comment by tannergooding** [comment]
> Can I hope the implementations of these new numeric types will be all in managed code?

Yes. Although they likely will take advantage of the new hardware intrinsics feature, where applicable.

**Comment by tannergooding** [comment]
@AlgorithmsAreCool, I think having the various `arbitrary precision types` and corresponding `Builder` types is probably the correct way forward.

This is a pattern that has been used with fairly good success for other data types and `BigInteger` has already shipped as `readonly`, so it would likely be good to keep things consistent moving forward.

**Comment by Happypig375** [comment]
If anyone need this right now, there is https://github.com/peteroupc/Numbers which implements all of this via configurable context settings.
