### ISSUE TITLE
Memory spec question

### ISSUE THREAD

**Issue by j-diffy** [dotnet/corefxlab#2650]
[Reference](https://github.com/dotnet/corefxlab/blob/master/docs/specs/memory.md)

Q: This line:
`...at the cost of significant performance penalties for reading and writing to the memory.`

What is it about using `Memory` over `Span` that incurs "significant performance penalties"? This is not explained and I can't find anything anywhere about this.

**Comment by ahsonkhan** [comment]
If you want to read/write from/to a `Memory`, you have to first access its `Span` property and then index into it/etc. Accessing the property, though optimized recently (https://github.com/dotnet/coreclr/pull/20386 / https://github.com/dotnet/coreclr/pull/20771), isn't free (especially if you are going through the `MemoryManager`), and that's where part of the performance cost comes from. The `Memory` struct is also larger so passing it around/slicing it/etc. are generally slower too. Initially the delta was more noticeable, but it exists none the less.

https://github.com/dotnet/corefx/blob/908cba9d8f275935a9e91b32fd363b5687dc8f86/src/Common/src/CoreLib/System/Memory.cs#L293-L375

Certainly you wouldn't want to loop through the memory like this:
```C#
for (int i = 0; i < memory.Length; i++)
{
   sum += memory.Span[i];
}
```
But rather like this:
```C#
var span = memory.Span;
for (int i = 0; i < span.Length; i++)
{
   sum += span[i];
}
```

>  I can't find anything anywhere about this.

Maybe this article would help: https://www.codemag.com/article/1807051/Introducing-.NET-Core-2.1-Flagship-Types-Span-T-and-Memory-T
- See Let’s Take a Peek Inside Memory<T> and Tricks of the Trade (particularly tip 1)

**Comment by j-diffy** [comment]
Great info thx👍
