### ISSUE TITLE
System.Time millisecond constructor should be a double

### ISSUE THREAD

**Issue by eeegs** [dotnet/corefxlab#2653]
In the current constructors that take milliseconds as an argument it is an int.  The precision of the time object is 100 nS.  The millisecond argument should be a double to allow for this.

**Comment by YohDeadfall** [comment]
It's made for compatibility with existing types which accept milliseconds as an `int`. If you want to specify a more precise value use the `Time(long ticks)` constructor or do something like `default(Time).AddMilliseconds(value)` if you have milliseconds only.

Probably there is a lack of the `Zero` constant and some methods to construct a value from one of time parts, i.e. `FromMilliseconds`, etc.

/cc @mj1856

**Comment by eeegs** [comment]
Time is a new type, so I don't entirely agree with compatibility rational - I get that you mean in other similar circumstances.

**Comment by roji** [comment]
One more thought - it seems like floating point types are best avoided in this context because of their precision issues. Rather than floating point, it seems wiser to use ulong if more precision is needed.

**Comment by YohDeadfall** [comment]
`ulong` is CLS compliant, but otherwise @roji is right. Ticks provide better precision.

**Comment by mj1856** [comment]
Review the [constructors of `DateTime`](https://docs.microsoft.com/dotnet/api/system.datetime.-ctor) or the [constructors of `TimeSpan`](https://docs.microsoft.com/dotnet/api/system.timespan.-ctor).  I wouldn't want to set a different precedent here.
