### ISSUE TITLE
Make DictionarySlim to use ArrayPool?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/corefxlab#2654]
Could 

https://github.com/dotnet/corefxlab/blob/master/src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/DictionarySlim.cs

allocate via `ArrayPool`?

In next calls:
```
_buckets = new int[capacity];
_entries = new Entry[capacity];
 var entries = new Entry[newSize];
var newBuckets = new int[entries.Length];
```

Similar to https://github.com/jtmueller/Collections.Pooled.

**Comment by DaZombieKiller** [comment]
Wouldn't this cause `DictionarySlim` to then need to implement `IDisposable` so it can return the arrays? That'd cause the correct usage of the type to change from what it is currently.

**Comment by dzmitry-lahoda** [comment]
May be need to implement, may be need to call, may be some other named method. Really, my question is broader - how to produce pooled counterpart for each container, with no need to copy whole source code?

**Comment by YohDeadfall** [comment]
A finalizer could help in that scenario.

**Comment by dzmitry-lahoda** [comment]
Another possible issue - `new` is fast, how fast is `abstract  ArrayPool.Rent`. If default `Rent` could be implemented as `new` and inlined by JIT/AOT like new than it could be OK. But if not, than if I want pooled slim dictionary I have to maintain my copy of code.

**Comment by dzmitry-lahoda** [comment]
Finalizer may help. With caveat that it runs on background thread and when it throws exception - things look bad. So single thread or thread affined allocators may not work.

**Comment by danmosemsft** [comment]
I think the issues as mentioned above are (1) speed of allocation vs. avoiding allocation and (2) dispose pattern which adds overhead and is unexpected for a collection. It seems to me this is out of scope and copying the code would be the way forward if you need this.

> So there seems no C# language level feature exist to have custom zero cost allocators?

There is no way to change what `new` does but you can certainly use a factory like ArrayPool instead which potentially the JIT could inline.

**Comment by dzmitry-lahoda** [comment]
Let me have `abstract class DictionarySlimBase` with `abstract T[] New(int size);` and `MyDictionarySlim` with `override  T[] New(int )=> new T[size]`. `DictionarySlimBase` is same as `DictionarySlim` except for allocation calls.

Would ` speed of allocation` of `MyDictionarySlim` and `DictionarySlim` be same? If not, than copying code is the solution and issue could be closed.
