### ISSUE TITLE
BigInteger deficiencies and solutions

### ISSUE THREAD

**Issue by verelpode** [dotnet/corefxlab#2655]
[System.Numerics.BigInteger](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger) is really great, except for a few issues that could be easily fixed.  

## Nasty conversion from 128-bit integer to BigInteger
Currently, in order to convert a 128-bit integer to BigInteger, it requires the following ugly workaround that creates **4** instances of BigInteger including the 4 internal array objects on the heap!  When this conversion is performed many times in a loop, it creates a bunch of unnecessary garbage for GC.

```
public static BigInteger UInt128ToBigInteger(UInt64 lowPart, UInt64 highPart)
{
	if (highPart == 0) return new BigInteger(lowPart);
	return (new BigInteger(highPart) << 64) | new BigInteger(lowPart);
}

public static BigInteger SInt128ToBigInteger(UInt64 lowPart, Int64 highPart)
{
	if (highPart == 0) return new BigInteger(lowPart);
	if (highPart == -1) return BigInteger.Negate(new BigInteger(unchecked((~lowPart) + 1)));
	return (new BigInteger(highPart) << 64) | new BigInteger(lowPart);
}
```

I suggest adding the following optimized constructors to BigInteger:

```
// For unsigned 128-bit integer:
public BigInteger(UInt64 lowPart, UInt64 highPart) { ... }

// For signed 128-bit integer:
public BigInteger(UInt64 lowPart, Int64 highPart) { ... }

// For 128-bit integer with sign supplied separately (this is useful):
public BigInteger(UInt64 lowPart, UInt64 highPart, bool isNegative) { ... }
```

## Construct from array of UInt32
I'd also enjoy an efficient constructor that uses an array of UInt32 like the internal "_bits" field inside BigInteger:

```
public BigInteger(UInt32[] data, bool isNegative, bool useDirectly = false) { ... }
```

The "data" parameter represents the words of an unsigned integer and the sign is supplied separately via the "isNegative" parameter.
By default, it would copy the "data" parameter to a new array instance, but if "useDirectly" is true, then it'd directly store the "data" reference to the internal "_bits" field inside BigInteger.  This is quite helpful to enable various high-performance optimizations for situations where many math calculations are performed using BigInteger -- big number-crunching situations.  
("useDirectly" would be defined as a preference to respect "if possible", not strict requirement, thus the implementation of BigInteger would still be permitted to copy "data" regardless of useDirectly, thus the BigInteger implementation is not required to forever keep "_bits" as UInt32 array in future versions.)

## Copy to array of UInt32
For the opposite direction, it'd be great to have a method that copies "_bits" to the specified array:
```
// "destinationOffset" is offset/ordinal/index within "destinationArray".
/// <returns>Length copied to "destinationArray".  Returns 0 if BigInteger.IsZero.</returns>
public int ToArray(uint[] destinationArray, int destinationOffset, out bool outNegative)
{
	outNegative = (_sign < 0);
	...
	if (_bits is null)
	{
		if (_sign == 0) return 0;
		destinationArray[destinationOffset] = unchecked((uint)Math.Abs(_sign));
		return 1;
	}
	...
}
```

## Typecast but with failure reported as null instead of OverflowException
It'd be very useful to have the following "TryConvertToXXXX" methods that would attempt to typecast/convert the BigInteger *without* throwing System.OverflowException, unlike the existing typecast operators in BigInteger.  The following methods should return null if conversion is unsucccessful (meaning return null if the BigInteger does not fit within the specified smaller integer type).
```
public Int32? TryConvertToInt32() { ... }
public Int64? TryConvertToInt64() { ... }
public UInt32? TryConvertToUInt32() { ... }
public UInt64? TryConvertToUInt64() { ... }
```
In the case of converting to unsigned UInt64, if the BigInteger is less than zero (UInt64.MinValue) or greater than UInt64.MaxValue, then TryConvertToUInt64 would return null.

For 128-bit integers, the following TryConvertToInt128 method would return true if the conversion is successful.  The sign would be output separately via the boolean "outNegative" parameter (I've found that separated sign is quite useful), thus the "outLowPart" and "outHighPart" parameters are in-effect set to what would be the result of `BigInteger.Abs`.
```
public bool TryConvertToInt128(out UInt64 outLowPart, out UInt64 outHighPart, out bool outNegative)
{
	outNegative = (_sign < 0);
	...
}

// Conversion to unsigned 128-bit integer:
public bool TryConvertToUInt128(out UInt64 outLowPart, out UInt64 outHighPart)
{
	bool neg;
	return (this.TryConvertToInt128(out outLowPart, out outHighPart, out neg) && !neg);
}

// Conversion to signed 128-bit integer with high part represented as signed 64-bit integer:
public bool TryConvertToInt128(out UInt64 outLowPart, out Int64 outHighPart)
{
	UInt64 unsignedHighPart;
	bool neg;
	if (this.TryConvertToUInt128(out outLowPart, out unsignedHighPart, out neg))
	{
		if (neg)
		{
			if (unsignedHighPart <= unchecked((UInt64)Int64.MinValue))
			{
				outHighPart = unchecked(-(Int64)unsignedHighPart);
				return true; // success
			}
		}
		else if ((unsignedHighPart >> 64) == 0)
		{
			outHighPart = unchecked((Int64)unsignedHighPart);
			return true; // success
		}
	}
	outLowPart = 0;
	outHighPart = 0;
	return false; // unsuccessful
}
```

If desired, TryConvertToXXXX could also be supported for floating-point as follows.
```
public double? TryConvertToFloat64() { ... }
public single? TryConvertToFloat32() { ... }
public decimal? TryConvertToDecimal() { ... }
```
Note TryConvertToFloat64 etc should only return exactly converted values.  If the BigInteger would be inexactly/approx represented by float64 (System.Double), then null should be returned.  If you want an inexact conversion to float64, then use the preexisting `public static explicit operator Double(BigInteger value)` that is already present in BigInteger.  Alternatively, if desired, TryConvertToFloat64 might have a parameter to control exact versus inexact conversion, as follows:
```
public double? TryConvertToFloat64(bool approximation = false) { ... }
public single? TryConvertToFloat32(bool approximation = false) { ... }
public decimal? TryConvertToDecimal(bool approximation = false) { ... }
```

## Tiny mistake in BigInteger.Abs, easily improved
The existing `BigInteger.Abs` method is useful but seems to be mistakenly implemented inefficiently:
```
public static BigInteger Abs(BigInteger value)
{
    return (value >= BigInteger.Zero) ? value : -value;
}
```
I think it should be changed to:
```
public static BigInteger Abs(BigInteger value)
{
    return (value._sign < 0) ? -value : value;
}
```

## GetBitLength
A "GetBitLength" method would also be useful.  It would return the number of binary bits consumed by an absolute/unsigned/positive representation of the binary integer (excluding any leading zero bits).  The result is the same regardless of whether the BigInteger is positive or negative.  If BigInteger.IsZero, then GetBitLength returns 0.
```
public uint GetBitLength() { ... }
```

## BigInteger result from 64-bit operands
It'd be good to have math operations that produce a BigInteger result from two 64-bit operands, as follows:
```
public static BigInteger Add(Int64 left, Int64 right) { ... }
public static BigInteger Add(UInt64 left, UInt64 right) { ... }
public static BigInteger Subtract(Int64 left, Int64 right) { ... }
public static BigInteger Subtract(UInt64 left, UInt64 right) { ... }
public static BigInteger Multiply(Int64 left, Int64 right) { ... }
public static BigInteger Multiply(UInt64 left, UInt64 right) { ... }
// Divide(Int64,Int64) is not applicable.

// Already exists:
public static BigInteger Add(BigInteger left, BigInteger right) { ... }
public static BigInteger Subtract(BigInteger left, BigInteger right) { ... }
public static BigInteger Multiply(BigInteger left, BigInteger right) { ... }
```

## Two operations in one
Also worth considering:
```
public static BigInteger MultiplyAdd(BigInteger inOperandA, BigInteger inOperandB, BigInteger inOperandC)
{
	// To be optimized now or in future with use of System.Numerics.BigIntegerBuilder.
	return (inOperandA * inOperandB) + inOperandC;
}

public static BigInteger MultiplyAdd(BigInteger inOperandA, sint64 inOperandB, sint64 inOperandC)
{
	// To be optimized now or in future with use of System.Numerics.BigIntegerBuilder.
	return (inOperandA * inOperandB) + inOperandC;
}

```

**Comment by verelpode** [comment]
The last one, MultiplyAdd, is intended to be like:  https://en.wikipedia.org/wiki/Multiply–accumulate_operation

**Comment by ahsonkhan** [comment]
Issue moved to [dotnet/corefx #36682](https://github.com/dotnet/corefx/issues/36682) via [**ZenHub**](https://www.zenhub.com/)
