### ISSUE TITLE
Add string support to the DataFrame columns

### ISSUE THREAD

**Issue by pgovind** [dotnet/corefxlab#2658]
[2656](https://github.com/dotnet/corefxlab/pull/2656) only implements primitive data type support. Add support for string columns

**Comment by danmosemsft** [comment]
@pgovind did this correspond to a PR? If so it's nice to link them. As you probably know you can have Github do this automatically when merging the PR

**Comment by pgovind** [comment]
Corresponding PR: https://github.com/dotnet/corefxlab/pull/2660
