### ISSUE TITLE
Character width context design proposal

### ISSUE THREAD

**Issue by breyed** [dotnet/corefxlab#2667]
**Proposal:** Define a "character width context" that indicates whether `System.Char` represents a UTF-16 code unit, a UTF-8 code unit, or could represent either. The character widths are designated as "16", "8", and "Any". Character width contexts can be designated at the project or code levels akin to [nullable contexts](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts). An assembly whose default character width is Any specifies a preferred character width for when it is the entry point for an application. `System.String` uses the current character width context. The runtime automatically converts between strings that use different character widths. 

**Motivation:** The same motivation for `Utf8String` in #2350 - primarily performance of working with web content, database content (e.g. the new UTF-8 support in SQL Server), and other UTF-8 text. This proposal is an alternative (or perhaps complementary) approach.

**Roll-out:** Assemblies without an explicit character width setting default to character width 16 for backward compatibility. The project templates for new assemblies will initially default to character width Any with 16 preferred, to avoid excessive width conversions with existing code. Developers will delineate web-centric code to prefer width 8 via project settings or pragmas. Over time, assemblies in the framework and NuGet packages will be converted to character width Any. Once the .NET ecosystem reaches critical mass, project templates for new assemblies will switch to prefer character width 8.

**Comparison to `Utf8String`**: A character width context avoids the need to create overloads of tons of methods that take `System.String`. It will instead require that methods supporting character width Any use encoding-neutral primitives and avoid assumptions about width. Converting existing code to character width Any would likely take less effort than creating overloads. Existing code already has to deal with 16-bit characters representing only a code unit and not a full code point, which would remain true with Any width characters. Additionally, the compiler will warn about operations involving char that aren't valid for an 8-bit width. 

**Analogy with target platform:** The concept of an assembly having different character widths or Any with a preferring width is analogous to platform targets of x86 or x64, or Any CPU with x86 or x64 preferred. A distinction is that platform target is per-process and so cannot be changed within a project using pragmas as character widths can.

**Open question:** Even after the .NET ecosystem supports character width Any, should project templates for assemblies expected to have heavy interaction with wide operating systems functions default to preferring character width 16?

**Comment by ahsonkhan** [comment]
cc @GrabYourPitchforks
