### ISSUE TITLE
DictionarySlim arithmetic overflow

### ISSUE THREAD

**Issue by Krakean** [dotnet/corefxlab#2672]
There is a few issues with DictionarySlim.cs mentioned in my comment here - https://github.com/dotnet/corefxlab/pull/2458#issuecomment-491014279

**Comment by danmosemsft** [comment]
@Krakean a PR would be easy? I think it would be OK to not have a test for it, since it would require building a new assembly for the test.

**Comment by danmosemsft** [comment]
I do'nt think we'll fix this - as mentioned, best not used in a checked context.
