### ISSUE TITLE
Question : How to add corefxlab packages through the dotnet cli/manually

### ISSUE THREAD

**Issue by Jaygem** [dotnet/corefxlab#2675]
I can't find any documentations about adding a myget feed manually (i can't use visual studio), so i'd like to know if there's a way to do it without VS.
Thanks in advance

**Comment by ahsonkhan** [comment]
The feed is listed here: https://github.com/dotnet/corefxlab#how-to-use

You could add the feed to a NuGet.config file local to your app or within your user app data folder (on Windows - `C:\Users\<user>\AppData\Roaming\NuGet`).

From the dotnet cli, you can do `dotnet restore -s https://dotnet.myget.org/F/dotnet-corefxlab/`

See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x#options for more info on that.

**Comment by Jaygem** [comment]
Well I don't know why the dotnet restore had no effect but i could use the [link found here](https://github.com/dotnet/corefxlab#how-to-use) this way :
```powershell
dotnet add package Microsoft.Data.DataFrame --version 1.0.0-e190513-1 --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json
```
