### ISSUE TITLE
Move to latest .Net Core

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefxlab#2685]
Can we move to latest .Net Core 3.0 Preview 5?

There is a compile problems with Json. Perhaps it is a time to remove the code from the lab.

**Comment by ahsonkhan** [comment]
I did update recently. See the SDK version that should get installed: https://github.com/dotnet/corefxlab/blob/47818b94f7cf25dad586d171030981ad4d713c65/DotnetCLIVersion.txt#L1

See https://github.com/dotnet/corefxlab/pull/2676.

Are you still seeing issues compiling from head of master? Try building from root (it should install the latest preview 6 SDK).

**Comment by iSazonov** [comment]
@ahsonkhan Thanks! I rebased and the new update.

**Comment by ahsonkhan** [comment]
Great. Closing the issue.
