### ISSUE TITLE
DataFrameBuffer should have a ReadOnlyMemory version

### ISSUE THREAD

**Issue by pgovind** [dotnet/corefxlab#2697]
The C# Arrow implementation only exposes ReadOnlyMemory<byte>. DataFrameBuffer at the moment expects a Memory<byte>. For zero-copy interop, we should consider adding an immutable DataFrameBuffer

**Comment by pgovind** [comment]
This was done with PR2694. Closing

**Comment by ahsonkhan** [comment]
> This was done with PR2694. Closing

https://github.com/dotnet/corefxlab/pull/2694

Which PR? That one was closed.

**Comment by pgovind** [comment]
Ah, good catch. Bad copy-paste. [This](https://github.com/dotnet/corefxlab/pull/2701) one
