### ISSUE TITLE
Status of Microsoft.Collections.Experimental?

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/corefxlab#2707]
What is the Roadmap for `Microsoft.Collections.Experimental`? I want to use `MultiValueDictionary<TKey, TValue>` but being an experiment...

**Comment by danmosemsft** [comment]
We definitely want to take this forward but have been absorbed by 3.0 work. We are also thinking whether it may make sense to have a dedicated repo. You could easily embed it if for internal use..

**Comment by SamuelEnglard** [comment]
I'm going the embedding route for now. What should I do for legal?

**Comment by Rodrigo-Andrade** [comment]
Is this alive?

**Comment by danmosemsft** [comment]
@Rodrigo-Andrade no, we would take PR's but our time available for it is limited. We don't expect to break the API without good reason, if that answers the original question: it should be good for production use.

As for the future -- I would be interested to see a dotnet/collections repo, that is community owned, for any collections that aren't broadly applicable/stable enough to go into the core libraries. Thoughts? Some discussion started here https://github.com/dotnet/corefxlab/pull/2613#issuecomment-665120239

**Comment by SamuelEnglard** [comment]
@danmosemsft Where should we do the discussion over the "dotnet/collections" idea? Here, on #2613, somewhere else?

**Comment by danmosemsft** [comment]
cc @eerhardt

**Comment by eerhardt** [comment]
> Where should we do the discussion over the "dotnet/collections" idea? 

Maybe the best place would be to create a new discussion at https://github.com/dotnet/runtime/discussions. That seems the most appropriate, and will give the most visibility to the discussion.

**Comment by danmosemsft** [comment]
Linking to https://github.com/dotnet/runtime/discussions/42205

**Comment by SamuelEnglard** [comment]
Closing in favor of the discussion
