### ISSUE TITLE
Strange assignment

### ISSUE THREAD

**Issue by drearyrainDeng** [dotnet/corefxlab#2738]
when i debug code "_arguments = arguments" in System.CommandLine. member variables _parser be set.is it normal?
![test1](https://user-images.githubusercontent.com/35326823/65857893-5d83db00-e397-11e9-8b35-2986d9bb11ed.gif)

**Comment by khellang** [comment]
You've defined a watch on the `Parser` property which, when evaluated by the debugger, will initialize the `_parser` field:

https://github.com/dotnet/corefxlab/blob/53e73d0a8862d7604773c7c82917d4df3efd888a/archived_projects/src/System.CommandLine/System/CommandLine/ArgumentSyntax.cs#L357-L363

**Comment by drearyrainDeng** [comment]
ooh! i miss it,thank for your reminder！
