### ISSUE TITLE
Flaky unit test on ALCProxy: OSX

### ISSUE THREAD

**Issue by pgovind** [dotnet/corefxlab#2745]
The OSX - InnerLoop CI fails quite often. I'll update the issue with the failing unit test the next time I see it. 

@cablooshe

**Comment by cablooshe** [comment]
I'm looking at the failing test [here](https://dev.azure.com/dnceng/public/_build/results?buildId=381572&view=logs&jobId=7b614801-ed38-51b7-97d8-b2f3e799aa24), seems to be something failing with the delegate to the server. I'll take a closer look later on why that's failing on OSX specifically.

**Comment by cablooshe** [comment]
I'm not 100% sure exactly why this is happening, but the delegate between client and server sometimes doesn't seem to exist for the OSX release. I can PR a patch that uses the old Reflection.Invoke as a backup in case the delegate fails, which doesn't exactly solve the problem but should hopefully prevent more random failures.
