### ISSUE TITLE
InsertColumn has a bug in DataFrame 

### ISSUE THREAD

**Issue by pgovind** [dotnet/corefxlab#2746]
If a DataFrame has 1 column of Length 0, and I insert a new column of Length > 0, `InsertColumn` should throw. It doesn't at the moment.

**Comment by RamonWill** [comment]
Hello @pgovind ,

Firstly, i'd like to thank you and the rest of your team for creating this data library. It was very useful and performed well on a finance project i have been working on.

Can i help contribute to this project and this issue?

I have recreated this issue and created a test for it as well.

The below proposed check fixes the issue as well as passes all the existing tests. Shall i create a PR for this?

```diff
       protected override void InsertItem(int columnIndex, DataFrameColumn column)
        {
            column = column ?? throw new ArgumentNullException(nameof(column));
            if (RowCount > 0 && column.Length != RowCount)
            {
                throw new ArgumentException(Strings.MismatchedColumnLengths, nameof(column));
            }
            
+           if(Count >= 1 && RowCount==0 && column.Length != RowCount)
+          {
+               throw new ArgumentException(Strings.MismatchedColumnLengths, nameof(column));
+           }
            
            if (_columnNameToIndexDictionary.ContainsKey(column.Name))
            {
                throw new ArgumentException(string.Format(Strings.DuplicateColumnName, column.Name), nameof(column));
            }
            RowCount = column.Length;
            _columnNames.Insert(columnIndex, column.Name);
            _columnNameToIndexDictionary[column.Name] = columnIndex;
            for (int i = columnIndex + 1; i < Count; i++)
            {
                _columnNameToIndexDictionary[_columnNames[i]]++;
            }
            base.InsertItem(columnIndex, column);
            ColumnsChanged?.Invoke();
        }
```

**Comment by pgovind** [comment]
> Can i help contribute to this project and this issue?

Yes!!! I think your fix looks good as proposed! I'd say go ahead and open a PR!!

**Comment by RamonWill** [comment]
Thanks pgovind, I will make the PR at some point today including the test

**Comment by pgovind** [comment]
Fixed with https://github.com/dotnet/corefxlab/pull/2937
