### ISSUE TITLE
ArrowStringColumn should implement FillNulls with inPlace: false

### ISSUE THREAD

**Issue by pgovind** [dotnet/corefxlab#2756]

**Comment by RamonWill** [comment]
Hi @pgovind ,

I'd be happy to help on this if thats alright? Looking at the current set up of FillNulls would I have to create an override method first in ArrowStringDataFrameColumn.cs called FillNullsImplementation (for the dataframe) then another method which will be called FillNulls which will affect the actual column?

Kind Regards,

Ramon

**Comment by pgovind** [comment]
@RamonWill Yup, that's the right approach. In addition, I would make the method throw if `inPlace` is set to `true` (I need to investigate it more, but at a glance I'm not sure that Apache Arrow format supports filling nulls for variable length arrays). Note that for `ArrowStringDataFrameColumn`, because we're not supporting `inPlace = true` yet, we will always return a new column. You won't be able to call the `Clone` method though. Instead you'll need to modify the implementation of clone (shown below):

``` csharp

// Copy and modify this implementation
        private ArrowStringDataFrameColumn Clone(PrimitiveDataFrameColumn<long> mapIndices = null, bool invertMapIndex = false)
        {
            if (mapIndices is null)
            {
                // Modify this block
                ArrowStringDataFrameColumn ret = new ArrowStringDataFrameColumn(Name);
                for (long i = 0; i < Length; i++)
                {
                    ret.Append(IsValid(i) ? GetBytes(i) : default(ReadOnlySpan<byte>)); // When IsValid returns false, you'll need to append `value` instead of `default`
                }
                return ret;
            }
            else
                return CloneImplementation(mapIndices, invertMapIndex);
        }
```

Let me know if you run into issues. I'm happy to help!

**Comment by RamonWill** [comment]
Thank you for the guidance @pgovind , I will make a PR shortly.

I do actually have two questions (although one is a bit off topic):
1. Is there a particular design pattern you followed/following when designing this library? 
I've been learning how to program for just over a year now and the way you have made code reusable code through inheritance and the way the Clone method works is very impressive.

2. Are there any deadlines for the 1.0.0 release?

Kind Regards,
Ramon
