### ISSUE TITLE
Feature suggestion: Calendar Month

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefxlab#2774]
Hi,

I often come across dealing with situations where all I need is a Year and Month (for example in bookkeeping, calendar month).

For example: 07/1999 for July '99.

Would be nice if that is added to this repo too.

Thanks!

**Comment by ahsonkhan** [comment]
For context, what type were you thinking of having such an API on that would be useful here? What's the input? It would help if you could provide a code snippet of what you'd like to write.

**Comment by weitzhandler** [comment]
I now have an app that stores data about teacher substitution. The data should be registered per month, i.e. May 2019 etc.
Other example is anniversary month "Grandma Jenna, born March 1919".
