### ISSUE TITLE
Rename DataFrame Sort methods to OrderBy

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefxlab#2788]
This matches more closely with Linq methods that .NET developers are used to.

https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderbydescending

**Comment by jwood803** [comment]
@eerhardt I can work on this. Is it simply just renaming the `Sort` methods to `OrderBy`?

**Comment by eerhardt** [comment]
> Is it simply just renaming the Sort methods to OrderBy?

I think we should also remove the `ascending` parameter and add an `OrderByDescending` method, to match Linq.

**Comment by jwood803** [comment]
@eerhardt Just curious, is anything else needed for this? I can work on any updates if they are needed.

**Comment by eerhardt** [comment]
I don't think anything else is needed for this. #2814 resolved this. Closing.
