### ISSUE TITLE
Status on System.Reflection.Metadata.Cil

### ISSUE THREAD

**Issue by Perksey** [dotnet/corefxlab#2789]
It's been a hot minute since any notable work has been done on the [System.Reflection.Metadata.Cil](https://github.com/dotnet/corefxlab/tree/master/src/System.Reflection.Metadata.Cil/) project, is there any plans for it to be championed in the near future (or is it dead for the time being)?

**Comment by ahsonkhan** [comment]
I am not aware of any plans atm, so right now it seems to be on the back burner. cc @safern

**Comment by safern** [comment]
Yeah there are no immediate plans for it right now. However contributions are always welcome 😄 

Also, there is [System.Reflection.MetadataLoadContext](https://apisof.net/catalog/System.Reflection.MetadataLoadContext) which exposes the `System.Reflection` APIs but this one is built using `System.Reflection.Metadata`.

**Comment by Perksey** [comment]
Darn that sucks - yeah I was actually looking for an API that builds on System.Reflection.Metadata as it's not the most welcoming API in the world :P 

I guess I'll have to manage :)
