### ISSUE TITLE
Latest System.IO.FileSystem.Watcher.Polling nuget doesn't install

### ISSUE THREAD

**Issue by lenniebriscoe** [dotnet/corefxlab#2804]
I attempted to install the latest System.IO.FileSystem.Watcher.Polling nuget preview (0.1.1-preview2-190117-2) into my .net Core library and was getting a Rollback due to Signing issues. Is this package going to rebuilt for later .net core versions ? or is it no longer maintained with no planned future?

> Error	NU3027	Package 'System.IO.FileSystem.Watcher.Polling 0.1.1-preview2-190117-2' from source 'https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json': The signature should be timestamped to enable long-term signature validity after the certificate has expired.	

> Error	NU3018	Package 'System.IO.FileSystem.Watcher.Polling 0.1.1-preview2-190117-2' from source 'https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json': The author primary signature found a chain building issue: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.	

If I switch to the previous version I then get:
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	NU1202	Package System.IO.FileSystem.Watcher.Polling 0.1.1-preview2-190117-1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.IO.FileSystem.Watcher.Polling 0.1.1-preview2-190117-1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)

**Comment by ahsonkhan** [comment]
cc @pgovind, @safern (since you guys were looking into corefxlab infra recently and might be able to help)

**Comment by safern** [comment]
We recently changed where we publish to and how we sign and version. Could you please try:

0.1.1-prerelease.19603.2

From feed:
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json

https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-experimental&package=System.IO.FileSystem.Watcher.Polling&protocolType=NuGet&version=0.1.1-prerelease.19603.2&view=overview
