### ISSUE TITLE
Unable to convert DataFrame to IDataView

### ISSUE THREAD

**Issue by jwood803** [dotnet/corefxlab#2825]
I'm probably doing something wrong, but adding this just in case.

Was working on a notebook to use the `DataFrame` in ML.NET but it seems, when I try to cast the `DataFrame` to an `IDataView`, it gave the below error.

```
Cannot convert from 'Microsoft.ML.IDataView' to 'Microsoft.ML.IDataView'
```

The error happens when, after performing a cast on the `DataFrame` object to an `IDataView`, I use it in the ML.NET `TrainTestSplit` method.

```
context.Data.TrainTestSplit(dataView, testFraction: 0.2)
```

[Here](https://github.com/jwood803/MLNetExamples/blob/master/MLNetExamples/Notebooks/Bank%20Analysis%20and%20ML.NET%20Default%20Classification.ipynb) is the full notebook, if needed.

**Comment by danmosemsft** [comment]
cc @eerhardt

**Comment by jwood803** [comment]
Thanks @eerhardt! I forgot try upgraded to interactive. Once upgrading it all now works.
