### ISSUE TITLE
unable to get header row

### ISSUE THREAD

**Issue by liugaocn** [dotnet/corefxlab#2840]
I don't know if there is any quick way to get the header row, since the new dataframe won't contain the row set as header. 
A header row is important for sub-grouping.

**Comment by liugaocn** [comment]
since nobody answers.

**Comment by pgovind** [comment]
Sorry! I must've missed this issue. Can you elaborate a little bit more on what you want? Do you just want to see the column names? If you are using Jupyter, you can just execute `dataframe_variable_name` in a cell and (if you also have the formatter set up) you should see the column names in the output. If you are not in a notebook, `dataframe_variable_name`.Columns (`DataFrameColumnCollection.cs`)stores the column names inside it internally. They are just not exposed publicly at the moment. If you put up a PR to create a public property that exposes the column names, we'd be happy to review it!

**Comment by liugaocn** [comment]
Thank you for replying. I don't use Jupyter, I use Visual Studio and Rider. 
I will be very happy to contribute when I get a better understanding.

**Comment by liugaocn** [comment]
@pgovind Maybe this would work. 
```
public List<string> GetColumnNames()
{
    // df is a dataframe.
    DataFrameColumnCollection dataFrameColumnCollection = df.Columns;
    List<string> columnNames = new List<string>(); // A list of all columnNames
    foreach (var column in dataFrameColumnCollection)
    {
        columnNames.Add(column.Name);
    }

    return columnNames;
}``

**Comment by pgovind** [comment]
1) I would call the API `ColumnNames" and make it a property instead of a method. I would also define this method in `DataFrame.cs`
2) I would change the return type to `IReadOnlyList<string>` so that the returned list is immutable
3) In the implementation, I think you can just do `return Columns._columnNames;`
