### ISSUE TITLE
Writing dataframe to txt doesn't work properly

### ISSUE THREAD

**Issue by liugaocn** [dotnet/corefxlab#2917]
I don't know if I am using the write method to export dataframe to txt. Anyways, I just use StreamWriter, but the question is that when My dataframe is really large, it won't write to txt properly. My code is: 
```c#
using(StreamWriter sw = new StreamWriter(SpecialDirectories.Desktop + "\\test.txt", false, encoding: System.Text.Encoding.UTF8))
{
    sw.Write(df);
    sw.Flush();
    sw.Write("End!");
}
```
My table has more then 30 thousand rows, but i only can get about 30 rows from my txt. However, it can write "End!" to the end of the txt properly, by the way.
When I use Console.WriteLine(df), it works properly, though. Then I wonder if it is a bug or just I am not using it right.

**Comment by pgovind** [comment]
Hmmm, how did you create your DataFrame? If you read in data from a csv file, can you share it here and I can repro and debug locally?

**Comment by liugaocn** [comment]
@pgovind 
[This is the link to the file. ](https://www.jianguoyun.com/p/Dc0ocqEQpIb6BhiRrKED )

**Comment by liugaocn** [comment]
@pgovind Is there any solutions to this problem? 
Maybe the dataframe is garbage collected. I guess.

**Comment by pgovind** [comment]
I haven't had a chance to look at it. I'm busy helping out with a .net preview release. I can get back to this in a couple of weeks though and will try to repro/diagnose this then.

**Comment by dcostea** [comment]
@pgovind in my work with dataframe I need to write the changes to an external CSV file.
I think a method like ```public static void WriteCsv(DataFrame dataFrame, string filename,
                                char separator = ',', bool header = true,
                                bool addIndexColumn = false, Encoding encoding = null)``` would be helpful.
I have already the method body using StreamWriter.

May I open a PR?

**Comment by pgovind** [comment]
@dcostea : Yes!! We'd love to see a PR. Tag me or @eerhardt  and we'll be happy to help review it! 

Note: I think this should eventually end up in the new MDAIO project (https://github.com/dotnet/corefxlab/pull/2938). But if you add it into MDA itself for now, that's ok too. I'll move it the next time I go through there :)

**Comment by liugaocn** [comment]
> @pgovind in my work with dataframe I need to write the changes to an external CSV file.
> I think a method like `public static void WriteCsv(DataFrame dataFrame, string filename, char separator = ',', bool header = true, bool addIndexColumn = false, Encoding encoding = null)` would be helpful.
> I have already the method body using StreamWriter.
> 
> May I open a PR?

I don't recommend you to use ',' as a csv seperator. Microsoft.Data.Analysis doesn't work very well with it.
