### ISSUE TITLE
DataFrame status

### ISSUE THREAD

**Issue by MgSam** [dotnet/corefxlab#2944]
Has the DataFrame library project been abandoned? It looks like there's been no development on it in several months. If Microsoft is not going to pursue developing it any further it would be helpful to communicate this and the reasons for doing so. We need to plan accordingly if this is not going to be in a future version of .NET. Transparency is beneficial for everyone.

**Comment by pgovind** [comment]
It's most certainly not. We've just been busy the last couple months working on other parts of .NET 5. We did have some PRs get merged in (https://github.com/dotnet/corefxlab/pull/2933 for example, so users get formatting automatically). Also, we have plans to add an extension in the notebook experience that I'd suggest keeping an eye out for. With intellisense in notebooks, and the new extension I'll add this week, the experience will be even better :)
