### ISSUE TITLE
[DataFrame] Add a LoadCsv overload or other method that takes CSV content directly  

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/corefxlab#2984]
Getting from a CSV string to a `DataFrame` requires some ceremony involving creating a stream first. While this might not be the ideal approach from a performance perspective for larger volumes of data, it's very useful for prototyping with sample subsets of data. An API like this will also play nicely with the .NET Interactive `#!value` magic command.

```csharp
DataFrame.LoadCsvFromString(@"col1,col2,col3
1,2,3
4,5,6
");
```

**Comment by pgovind** [comment]
I think this is a good idea. I'll put a PR up for this soon and we can include this in the next preview
