### ISSUE TITLE
dataframe row escape characters

### ISSUE THREAD

**Issue by madschristiansen** [dotnet/corefxlab#3023]
Hi,

I am in the process of going from python to c# dataframe, but it is a bit of a pain.

After I load the csv all data I extract from it is string but contains escape characters so I have to replace all data  - that is cumbersome..

Is there any way to deal with this?

**Comment by pgovind** [comment]
Hello! Yes, there is. There will be a 0.5.0 release soon that handles escape characters properly. I have it working locally already!

**Comment by madssibbern** [comment]
Great news Prashanth. Thank you
