### ISSUE TITLE
OrderedDictionary indexer conflict

### ISSUE THREAD

**Issue by space-alien** [dotnet/corefxlab#3028]
`OrderedDictionary<T>` exposes two indexers; one for the dictionary key and one for the list index.

This raises a potential conflict if the dictionary is keyed by `int`, and perhaps some potential confusion/risks if it is keyed by another integral type.

Any thoughts on an `OrderedHashSet<T>`? I am actually using `OrderedDictionary` in lieu of this.

Still, I think `OrderedDictionary` is a great addition and I'd be delighted to see it added to a future .NET release.

**Comment by pgovind** [comment]
Hey @space-alien! This repo is going to be archived soon. However, `Microsoft.Experimental.Collections` will be moved to dotnet/runtimelab. Just a heads up that this issue will be closed automatically, but the issue will be moved to runtimelab when `Microsoft.Experimental.Collections` completes its move.
