### ISSUE TITLE
Utf8String doesn't show its value under VS debugger

### ISSUE THREAD

**Issue by krwq** [dotnet/corefxlab#320]
ToString exists so in theory we should see it. Investigate why it doesn't work, check if DebuggerViewerProxy needs to be implemented.

**Comment by mj1856** [comment]
http://stackoverflow.com/questions/31562791/what-makes-the-visual-studio-debugger-stop-evaluating-a-tostring-override

**Comment by livarcocc** [comment]
This was actually working for me two days ago, then yesterday it stopped showing. I had to manually add Watchers and do .ToString()
