### ISSUE TITLE
Remove .exe file (IL helper tool) for Slices

### ISSUE THREAD

**Issue by krwq** [dotnet/corefxlab#331]
https://github.com/dotnet/corefxlab/pull/329

With that commit I checked in .exe file.
- [ ] Add project to project reference with option not to reference it
- [ ] Remove .exe and substitute its path in .csproj with some magic msbuild value

**Comment by krwq** [comment]
I tried fixing this, first had to port , but if you add project to project reference and try to run it it seems that the

**Comment by KrzysztofCwalina** [comment]
we removed IL rewriting from corfxlab altogehter.
