### ISSUE TITLE
Add a way to rent ByteSpan from an ambient BufferPool

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#356]
I would like to use a buffer pool in Qotd service (demo app). But I need to be able to get ByteSpan from it. I could use NativeBufferPool, but it does not have Shared property, and so it's lots of busy setup code. Could we either add Shared property to NativeBufferPool or allow renting ByteSpan from ArrayBufferPool, or combine these two pools.

**Comment by sokket** [comment]
Fixed with #436
