### ISSUE TITLE
Make sure Utf8String has APIs similar to what's available to System.String

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#358]
Here are some usage scenarios of Utf8Strings that we may want to support. If any of the ones listed below are invalid or require further discussion, please comment.
- [ ] 1. Concatenation: + and +=
- [ ] 2. bool Utf8String.IsNullOrWhiteSpace(Utf8String str)
- [ ] 3. bool IsDigit(Utf8CodeUnit)
- [ ] 4. bool Utf8String.IsSubstringAt(int index, Utf8String str)
- [ ] 5. new Utf8CodeUnit(char)
- [ ] 6. Utf8String.Remove(Int32 startIndex)
- [ ] 7. Utf8String.Remove(Int32 startIndex, Int32 count)
- [ ] 8. Utf8String.Replace(Utf8String oldValue, Utf8String newValue)
- [ ] 9. Utf8String.TrySubstringTo(Utf8String value, Utf8String skip, out Utf8String result)
- [ ] 10. Utf8String.TrySubstringFrom(Utf8String value, Utf8String skip, out Utf8String result)

**Comment by krwq** [comment]
1. I don't think this is a good idea for strings which represent a view. I.e. what do you do when youd:
Utf8String s = "asdasd"u8;
Utf8String s2 = s.Slice(1);
s2 += "xyz"u8;
what value should s have after that?
I think Formatters are meant for that or we should create some other kind of string builder (maybe separate type)

2. We already have Utf8CodeUnit.IsWhitespace, not sure if we should have Utf8String.IsWhitespace (structs can't be null), it probably is a good idea assuming I personally used that on more than one ocassion for System.String.
3. :+1: 
4. Pending
5. Arguable - IMO. This probably isn't a good idea as char won't always fit inside Utf8CodeUnit - unless we decide to throw an exception although I still think it is not a good idea (unless you call it something like TryCreateFromChar)
6-8. Same as 1
9-10. I'm not sure what that skip parameter is. Considering that I ask this question I think it might be confusing (I have no idea what it means). We already have an overload without skip do.

**Comment by KrzysztofCwalina** [comment]
We have such StringBuilder. See https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Formatting/src/System/Text/Formatting/StringFormatter.cs

**Comment by KrzysztofCwalina** [comment]
In general, the workitem is to:
1. Review existing System.String APIs and decide which of these would make sense on Utf8String
2. Design the APIs to be added to Utf8String
3. Implement the APIs.
