### ISSUE TITLE
Setup CI for corefxlab

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#371]
@davidfowl

**Comment by davidfowl** [comment]
Yesss please 😁

**Comment by weshaggard** [comment]
@mmitche what would it take to get CI setup for this repo?

**Comment by mmitche** [comment]
Follow the workflow here: https://github.com/dotnet/dotnet-ci/blob/master/docs/CI-SETUP.md

**Comment by sokket** [comment]
Fixed by #405

**Comment by davidfowl** [comment]
@sokket Are packages being pushed on every build to the  myget feed?

**Comment by sokket** [comment]
@davidfowl No, packages are pushed nightly to the CoreFxLab MyGet feed (https://www.myget.org/F/dotnet-corefxlab/api/v3/index.json). We do run a build+test CI build, but we do not publish those binaries

**Comment by davidfowl** [comment]
As long as up to date packages are available then that's fine.

**Comment by davidfowl** [comment]
Sooo why is there only a single version of System.Buffers:

https://www.myget.org/F/dotnet-corefxlab/api/v3/flatcontainer/system.buffers/index.json

**Comment by KrzysztofCwalina** [comment]
Probably because the system does not change the nuspecs. @sokket, what's the plan for fix this?

**Comment by sokket** [comment]
@KrzysztofCwalina is correct, I don't (currently) change the nuspec files nightly. I'm waiting for @livarcocc's work moving us over to use dotnet cli before making the change to update the nuspec's nightly because that is changing how we build in general, which will affect packaging.

**Comment by KrzysztofCwalina** [comment]
@livarcocc, what's the ETA for your changes? The problem with publishing different contents under the same package version is that it totally confuses nuget caching. Then people run into very difficult to diagnose nuget resolution problems.

**Comment by sokket** [comment]
@KrzysztofCwalina Gotcha...good to know. After my current PR goes in (to update the buffer pools) I'll put out a new PR to manually rev all the versions, after all the changes I put in yesterday, and then I'll run a new official build to push out an updated version of all the packages.

/fyi @davidfowl

**Comment by sokket** [comment]
PR #438 is addressing this
