### ISSUE TITLE
Move AppendNewLine from IFormatterHttpExtensions in LowAllocationHttpServer to System.Text.Formatting

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefxlab#385]
Also consider moving AppendWhitespace.

**Comment by davidfowl** [comment]
Should those really be in the core formatting library? Seems like weird coupling no?

**Comment by KrzysztofCwalina** [comment]
Where would you put this?

**Comment by davidfowl** [comment]
System.Text.Formatting.Http

**Comment by KrzysztofCwalina** [comment]
How is it specific to HTTP?

**Comment by KrzysztofCwalina** [comment]
I think this is done.
