### ISSUE TITLE
In the Http extensions of IFormatter, we need to ensure that all the characters follow the basic rules of rfc2616

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefxlab#387]
In the Http extensions of IFormatter, we need to ensure that all the characters follow the basic rules of http://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2 (i.e. it's not really UTF8, but rather ASCII and such). I think it's fine if you do this as a separate commit, just add a TODO and file an issue.

**Comment by benaadams** [comment]
Want to follow https://tools.ietf.org/html/rfc7230#section-3.2.4 mostly the same though; i.e. the HTTP portion of the request is ASCII bytes rather than UTF8 or other encoding
