### ISSUE TITLE
System.CommandLine doesn't strip outer quotes from argument values

### ISSUE THREAD

**Issue by agocke** [dotnet/corefxlab#401]
When passing an argument on the command line I would expect the semantics to be something like

```
cmd --arg "value"
```

produces a long argument `arg` that has value `value`. Note the absence of quotes. This is also important for preserving interior characters. For example,

```
cmd --arg "--interior-arg "abc""
```

Should produce an argument `arg` with value `--interior-arg "abc"`, missing the outer quotes, but preserving interior quotes.

I think the proper behavior here is just to check if there is a matching quote pair at the beginning and end of an argument value after lexing and, if so, drop exactly those two quotes.

**Comment by terrajobst** [comment]
Thanks for reporting. I'll take a look.

**Comment by terrajobst** [comment]
@agocke Would you really expect the single quote to work? It seems to me that you'd have to escape the inner quote by either doubling it or prefixing it with a backslash, like:

```
cmd --arg "--interior-arg ""abc"""
```

**Comment by agocke** [comment]
We should probably talk in person. I've looked at this a bunch and

1) am skeptical my original bug report is valid
2) Am not sure my proposed design is the right one either

The main thing I'm missing in this bug is that the behavior is different on the command line as opposed to the response file.

**Comment by terrajobst** [comment]
That could be because the parser simply converts each line into a separate element in the logical `string[] args` array.

**Comment by terrajobst** [comment]
BTW: I just validated that `cmd --arg "value"` is parsed as you'd expect.

Also, I've written a simple console app that just echos the arguments received by main to see how the shell process the args. Here are the results from different shells:

CMD:

```
> ConsoleApplication1.exe --args "--inner-arg ""value"""
--args
--inner-arg "value"
```

```
> ConsoleApplication1.exe --args "--inner-arg \"value\""
--args
--inner-arg "value"
```

PowerShell:

```
$ .\ConsoleApplication1.exe --args "--inner-arg ""value"""
--args
--inner-arg value
```

```
$ .\ConsoleApplication1.exe --args "--inner-arg \"value\""
--args
--inner-arg " value\
```

@stephentoub, what does Linux look like?

**Comment by terrajobst** [comment]
Here is @stephentoub's reply:

```
stoub@stoublinux1:~/netcore$ ./test --arg "--interior-arg "abc""
./test
--arg
--interior-arg abc
```

**Comment by terrajobst** [comment]
@stephentoub, which shell is that? I assume it's BASH?

**Comment by agocke** [comment]
I get that result in bash.

What do we want to do for `--arg:"value"`?

It seems kind of weird if `--arg "value"` is parsed differently.

**Comment by DemiMarie** [comment]
On *nix `--arg:"value"` and `--arg:value` result in the exact same argv passed to `main()`.

**Comment by agocke** [comment]
I think I satisfied myself that the current behavior is correct.
