### ISSUE TITLE
Implement sweet enumerators in Utf8String

### ISSUE THREAD

**Issue by krwq** [dotnet/corefxlab#413]
Something similar as in here:
https://github.com/dotnet/corefxlab/pull/400

**Comment by krwq** [comment]
This https://github.com/dotnet/corefxlab/pull/430 should make it possible to reuse Span<Utf8CodeUnit> enumerators

**Comment by GrabYourPitchforks** [comment]
Closing as no longer relevant due to the fact that `Utf8String` is a proper reference type. It will have a special non-boxing `GetEnumerator` just like `System.String`.
