### ISSUE TITLE
Non-allocating parsing APIs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefxlab#443]
One thing I'd find very useful are fast methods for parsing characters to int, double, decimal, with false returned if the number overflows or contains invalid characters.

I know there are some here for uint and ulong - https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Formatting/src/System/Text/Parsing/InvariantParser.cs. I'd like it to be expanded for signed integers, doubles and decimals.

**Comment by KrzysztofCwalina** [comment]
@JamesNK, we definitely want to do these, but it's going to take some time.

**Comment by KrzysztofCwalina** [comment]
I think it's now covered in https://github.com/dotnet/corefx/blob/master/src/System.Memory/ref/System.Memory.cs#L335. 

I will close the issue. @JamesNK, if you still need some datatype that is not covered, please open an issue in corfx repo. thanks.
