### ISSUE TITLE
Utf8String.ToString use vector intrinsics?

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#452]
see: http://woboq.com/blog/utf-8-processing-using-simd.html

**Comment by KrzysztofCwalina** [comment]
@krwq

**Comment by mellinoe** [comment]
This would definitely be an interesting project to look at. We had talked about looking into some string optimization prototypes a very long time ago, but nothing concrete came about, so this could be a good opportunity to try something small-scale using the SIMD library.

**Comment by GrabYourPitchforks** [comment]
The UTF8/UTF16 transcoding logic being worked on (see https://github.com/GrabYourPitchforks/fast-utf8/blob/master/FastUtf8Tester/Utf8Util.ConvertToUtf16.cs for example) is already fully vectorized. This code will eventually be merged into corefxlab as the `Utf8String` type is productized.

**Comment by GrabYourPitchforks** [comment]
The `Utf8String` type in coreclr / corefx - along with the `System.Text.AsciiEncoding` and `System.Text.UTF8Encoding` implementations - have been enlightened to use vectorization for most operations. I'm resolving this as fixed. If there's something else that needs to be tracked please reopen the issue.
