### ISSUE TITLE
Some System.Text.Http tests are failing

### ISSUE THREAD

**Issue by sokket** [dotnet/corefxlab#463]
Discovering: System.Text.Http.Tests
  Discovered:  System.Text.Http.Tests
  Starting:    System.Text.Http.Tests
     System.Text.Http.Tests.GivenAnHttpHeaders.Its_Enumerator_iterates_through_all_headers [FAIL]
        System.ArgumentException : headerString
        Stack Trace:
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(96,0): at System.Text.Http.HttpHeaders.ParseHeaderLine(Utf8String headerString, KeyValuePair`2& header)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(127,0): at System.Text.Http.HttpHeaders.Enumerator.MoveNext()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\tests\GivenAnHttpHeaders.cs(82,0): at System.Text.Http.Tests.GivenAnHttpHeaders.Its_Enumerator_iterates_through_all_headers()
     System.Text.Http.Tests.GivenAnHttpHeaders.It_can_get_the_value_of_a_particular_header [FAIL]
        System.ArgumentException : headerString
        Stack Trace:
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(96,0): at System.Text.Http.HttpHeaders.ParseHeaderLine(Utf8String headerString, KeyValuePair`2& header)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(127,0): at System.Text.Http.HttpHeaders.Enumerator.MoveNext()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(28,0): at System.Text.Http.HttpHeaders.get_Item(String headerName)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\tests\GivenAnHttpHeaders.cs(54,0): at System.Text.Http.Tests.GivenAnHttpHeaders.It_can_get_the_value_of_a_particular_header()
     System.Text.Http.Tests.GivenAnHttpHeaders.It_counts_the_number_of_headers_correctly [FAIL]
        System.ArgumentException : headerString
        Stack Trace:
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(96,0): at System.Text.Http.HttpHeaders.ParseHeaderLine(Utf8String headerString, KeyValuePair`2& header)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(127,0): at System.Text.Http.HttpHeaders.Enumerator.MoveNext()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(50,0): at System.Text.Http.HttpHeaders.get_Count()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\tests\GivenAnHttpHeaders.cs(48,0): at System.Text.Http.Tests.GivenAnHttpHeaders.It_counts_the_number_of_headers_correctly()
     System.Text.Http.Tests.GivenAnHttpHeaders.It_parsers_Utf8String_as_well [FAIL]
        System.ArgumentException : headerString
        Stack Trace:
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(96,0): at System.Text.Http.HttpHeaders.ParseHeaderLine(Utf8String headerString, KeyValuePair`2& header)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(127,0): at System.Text.Http.HttpHeaders.Enumerator.MoveNext()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(50,0): at System.Text.Http.HttpHeaders.get_Count()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\tests\GivenAnHttpHeaders.cs(95,0): at System.Text.Http.Tests.GivenAnHttpHeaders.It_parsers_Utf8String_as_well()
     System.Text.Http.Tests.GivenAnHttpHeaders.Its_enumerator_Current_returns_the_same_item_until_MoveNext_gets_called [FAIL]
        System.ArgumentException : headerString
        Stack Trace:
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(96,0): at System.Text.Http.HttpHeaders.ParseHeaderLine(Utf8String headerString, KeyValuePair`2& header)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(127,0): at System.Text.Http.HttpHeaders.Enumerator.MoveNext()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\tests\GivenAnHttpHeaders.cs(68,0): at System.Text.Http.Tests.GivenAnHttpHeaders.Its_enumerator_Current_returns_the_same_item_until_MoveNext_gets_called()
     System.Text.Http.Tests.GivenAnHttpHeaders.It_returns_empty_string_when_header_is_not_present [FAIL]
        System.ArgumentException : headerString
        Stack Trace:
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(96,0): at System.Text.Http.HttpHeaders.ParseHeaderLine(Utf8String headerString, KeyValuePair`2& header)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(127,0): at System.Text.Http.HttpHeaders.Enumerator.MoveNext()
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\src\System\Text\Http\HttpHeaders.cs(28,0): at System.Text.Http.HttpHeaders.get_Item(String headerName)
           Y:\Repositories\personal\dotnet\corefxlab\src\System.Text.Http\tests\GivenAnHttpHeaders.cs(60,0): at System.Text.Http.Tests.GivenAnHttpHeaders.It_returns_empty_string_when_header_is_not_present()
  Finished:    System.Text.Http.Tests

**Comment by livarcocc** [comment]
Couldn't repro this. Passed on local machine and CI. Re-enabled tests with 41a16eda89d5b7d5400e204280fd45b1102a61a8.
