### ISSUE TITLE
Add to README details on expected usage of IReadableChannel and IWritableChannel 

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#475]
Fro example, is it how IReadableChannel  is to be used?
```C#
while (await rChannel.WaitToReadAsync())
{
    T value;
    if (rChannel.TryRead(out value))
    {
        // consume value
    }
}
```

**Comment by stephentoub** [comment]
It depends what you're trying to do.  What you write is a fine way to consume everything in the channel.  You could also do:
```C#
IAsyncEnumerator<T> e = rChannel.GetAsyncEnumerator();
while (await e.MoveNext())
{
    // use e.Current
}
```
or:
```
try
{
    while (true)
    {
        T value = await rChannel;
        // use value
    }
}
catch (InvalidOperationException) { /* channel closed */ }
```
Etc.

**Comment by omariom** [comment]
Already three ways to read. Why is that?
What are the slight justifying differences?

**Comment by stephentoub** [comment]
Different use cases.  The idea behind the IAsyncEnumerator approach is that that interface would become a general way of enumerating asynchronously through various sources, of which one would be channels; it'd be like asking why you can either index through each item in a collection or enumerate it with foreach.  The idea behind being able to await the channel directly (which is just shorthand for awaiting rChannel.ReadAsync) is that if you don't need to be concerned about the channel ever ending, you can simply read from it and not worry about having to separately wait for data to be available.  The approach of using WaitForReadAsync allows you to write code like you had, which will exit out when the channel has closed, but it's actually there as a building block for other higher-level operations, such as enabling the Case/SelectAsync functionality, which requires being able to asynchronously wait separate from reading.

**Comment by omariom** [comment]
Aaah.. Convenience vs efficiency..

**Comment by stephentoub** [comment]
And vs functionality and vs abstraction.  Implementing that Select/Case functionality would not be possible without the Wait* support.  Implementing arbitrary foreach'ing (eventually) over arbitrary sources (including channels) would not be possible without some general abstraction.

**Comment by omariom** [comment]
I got the answer.
