### ISSUE TITLE
CompositeFormat.AppendUntyped is incomplete

### ISSUE THREAD

**Issue by azyobuzin** [dotnet/corefxlab#477]
# Problem
I found that `formatter.Format` does not work well when I specify a DateTimeOffset as a parameter, like this.
```csharp
var formatter = new StringFormatter(ManagedBufferPool<byte>.SharedByteBufferPool);
formatter.Format("{0:G}\n{0:R}\n{0:O}", DateTimeOffset.Now);
```

This code causes a NotSupportedException with the message "value is not formattable."

# Cause
See [the code](https://github.com/dotnet/corefxlab/blob/48cd9fe091954b4bdefbb53aa62cf6f0260a7e7c/src/System.Text.Formatting/src/System/Text/Formatting/CompositeFormat.cs#L154-L227). It does not support all types which are supported in PrimitiveFormatters.

Is there a plan to fix this? Thank you.

**Comment by KrzysztofCwalina** [comment]
#840 fixes this. 
Thanks for pointing out this issue and sorry that it took so long to fix.
