### ISSUE TITLE
Restoring takes forever

### ISSUE THREAD

**Issue by krwq** [dotnet/corefxlab#493]
I git-pulled, cleaned and started building few hours ago and it still haven't finished. It is stuck on restoring packages. I'm not sure if this is nuget or this repo bug. I have dotnet cli on my env path - not sure if this is related.

**Comment by davidfowl** [comment]
Restore is usually pretty verbose about the time it takes for each http request. Do you have that log?

**Comment by krwq** [comment]
Hmm, is there any environmental variable I can set to see verbose output? This is what I see right now:
```
x:\oss\corefxlab>build
  Restoring build tools...
  Restoring all packages...
```

**Comment by krwq** [comment]
Nvm the question `/v:d` works just fine. I'm building again and see if it is stuck or just taking insanely long (2h is enough though...)

**Comment by krwq** [comment]
I don't know - probably some transient or intermittent issue, can't repro it - closing
