### ISSUE TITLE
System.Threading.Tasks.Channels Roadmap and NuGet

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#498]
Any updates on if/when this project will be added to CoreFX?

Thx.  Nice project!

**Comment by KrzysztofCwalina** [comment]
It's available as a prerelease on https://www.myget.org/feed/dotnet-corefxlab/package/nuget/System.Threading.Tasks.Channels

Why do you want it in corefx?

**Comment by shaggygi** [comment]
It doesn't have to be in CoreFX.  Was just wondering more what the roadmap is and if it is a project that looks promising for future use.  Since the project was located in corefxlab, I wasn't sure if it was going to be shelved or not.

**Comment by shaggygi** [comment]
I've tried playing around with the bits, but get errors.  Do you have any examples to use?  Can it be used with PCL libraries?  Any help to get started is appreciated.

**Comment by KrzysztofCwalina** [comment]
@stephentoub, could you please resolve this? Thanks.

**Comment by stephentoub** [comment]
> but had some errors related to Task.Extensions

What are the errors you're hitting?

> Any updates on if/when this project will be added to CoreFX?

I'm still collecting feedback on the library, so if you have any, please do share.  I plan to spend some more dedicated time on it in the near future, getting it into a state closer to what I think would be shippable as a stable library.

**Comment by shaggygi** [comment]
@stephentoub It's been some time, but I believe it was more related to referencing the NuGet packages.  I think I had to download the repo and build the DLL locally to reference in my projects.  It might have also been related to trying with early bits of .NET Core and a PCL I was working on.

I have some time in the morning, I will look back on that code and let you know.  However, I believe it might have been fixed in later builds.

Side question... when you mentioned "shippable as a stable library", do you mean Tasks.Channels will come out of CoreFxLabs and be in 1.) CoreFx, 2.) It's own repo or 3.) something else?

**Comment by stephentoub** [comment]
> do you mean Tasks.Channels will come out of CoreFxLabs and be in 1.) CoreFx, 2.) It's own repo or 3.) something else?

I'm guessing (1) in some form, but... does it matter?  If it's available as a consumable NuGet library you can rely on, does it matter to you which repo the code lives in?

**Comment by shaggygi** [comment]
I'm good with any.  It just always seemed CoreFxLabs was more of a playground/experimental.  It would be good to get the final package bits over to NuGet as I recall it was located elsewhere.  Thx

**Comment by stephentoub** [comment]
Yup, that's where these are currently going.  Thanks.
