### ISSUE TITLE
Span indexer computes the element offset using Int32 which can overflow

### ISSUE THREAD

**Issue by mikedn** [dotnet/corefxlab#516]
The following program crashes with an `AccessViolationException`:

```C#
using System;

class Program {
    static void Main() {
        var array = new long[300000000];
        var span = new Span<long>(array);
        Console.WriteLine(span[array.Length - 1]);
    }
}
```

This program requires `gcAllowVeryLargeObjects` to be enabled in the config file.

The element offset is 300000000 * 8 = -1894967296 but it should be 2400000000. 

It's unfortunate that C# doesn't have `+` and `*` operators on `UIntPtr`/`IntPtr`. The computation might have to be moved to `PtrUtils.Get/Set` where it can be implemented in IL.

**Comment by omariom** [comment]
@mikedn 
I played with IL and almost accidentally fixed the bug :) https://github.com/dotnet/corefxlab/pull/528
