### ISSUE TITLE
Can System.CommandLine be used in a .NET Framework 4.6 project?

### ISSUE THREAD

**Issue by daveaglick** [dotnet/corefxlab#517]
I'm still not totally clear on what the implications are of using libraries from CoreFx alongside those from "classic" .NET Framework. From what I've been able to gather (mostly from the thread here: https://github.com/dotnet/corefx/issues/973) it should be okay. However, I'm having a very hard time getting System.CommandLine to run without throwing.

My first problem was the `System.IO.FileNotFoundException` reported in #488. That was easily resolved by including the System.Console package. Now I'm getting a `System.ExecutionEngineException` within `ArgumentSyntax.Validate()` (this is decompiled, so it probably doesn't match the src exactly):

![2015-12-28_17h42_47](https://cloud.githubusercontent.com/assets/1020407/12026713/fd919570-ad8a-11e5-8f4d-ea43381fbf99.png)

I'm guessing that it might be caused by missing other packages, in which case PR #489 potentially takes care of it. However, when I included all the packages listed in that manifest, I still get the exception.

Any tips?

**Comment by alexanderkozlenko** [comment]
Unfortunately, this is by design - package calls ```Environment.FailFast``` to terminate an application. It happens in two cases: when ```HandleHelp``` set to ```true``` and help is requested, and when ```HandleErrors``` set to ```true``` and there is an error. Also, there is a PR #418, which fixes that behavior, but it is still opened.

**Comment by daveaglick** [comment]
Thanks for the quick response! What you describe is what's going on here - I noticed the problem while requesting the generated help message with `-?`. That's certainly unexpected - so much so I didn't even think to look for non-CoreFx compatibility causes.

I'll give the code in the PR a run and see if it resolves things.

**Comment by daveaglick** [comment]
The referenced PR appears to resolve the crashing behavior (which is indeed by design at the moment), so I'm closing this issue.
