### ISSUE TITLE
System.CommandLine - support for options with optional arguments

### ISSUE THREAD

**Issue by daveaglick** [dotnet/corefxlab#520]
A nice addition would be to support flag options that may or may not define a value (I.e., they can be either a flag-style option or an option with an argument).

Consider an application that starts a server of some kind. You may want to start the server with the default port or you may want to specify one. Right now you'd need to specify two options, one flag option for starting the server and another for the port (which would be ignored if the server one isn't specified). Your potential commands might look something like this:
- No server: `myapp.exe`
- With server on default port: `myapp.exe --server`
- With server on specific port: `myapp.exe --server --port 1234`
- No effect (should probably be an error/generate the help message): `myapp.exe --port 1234`

This seems redundant. I'd much rather be able to write:
- No server: `myapp.exe`
- With server on default port: `myapp.exe --server`
- With server on specific port: `myapp.exe --server 1234`

As far as I can tell, this wouldn't be too hard to implement. My current thought is that the API should have a additional `DefineOption()` overloads that define an additional default if there's no argument. That way we can continue to use the same `Argument<T>` class and `ref` conventions to represent return values, you'll just get a different value in the absence of any argument.

``` C#
public Argument<string> DefineOption(string name, string defaultValue, string defaultArgumentValue)
{
    //...
}

// Other overloads that return Argument<T>

public Argument<T> DefineOption<T>(string name, ref T value, Func<string, T> valueConverter, string defaultArgumentValue, string help)
{
    // ...
}

public Argument<string> DefineOption(string name, ref string value, string defaultArgumentValue, string help)
{
    // ...
}

// Etc.

```

Then you could handle the above server case with the following:

``` C#
int port = 0;  // 0 indicates the server shouldn't be started
System.CommandLine.ArgumentSyntax.Parse(args, syntax =>
{
    syntax.DefineOption("s|server", ref port, DefaultPort, "Start the server with the default or specified port");
});
```

Of course, the generated help would also have to indicate the optional nature of the argument:

```
usage:  [-s [arg]]
    -s,  --server [arg]     Start the server with the default or specified port
```

I'm going to give it a go, but I'd be interested in feedback or if there's some reason this is a terrible idea that I've overlooked.

**Comment by brthor** [comment]
@daveaglick 
What is the intended benefit of this feature? Is it just to save on typing?

In your app when you have `--server` as a Boolean option it has a defines a specific action for your app to take (or not take). The second option `--port` defines a value to override a default value your app is already looking for. The interdependency between these two options is something purely app specific and shouldn't be handled by the CommandLine framework IMO.

The mixing of the concerns of providing a Boolean for an app to take action on and a value for the app to override some other value with does not seem appropriate.

It creates a ternary set of possibilities that any app utilizing the functionality would need to reason about:
1. `--server` is not defined, take some action
2. `--server` is defined, but without a value, take some other action with a default value
3. `--server` is defined, but with a value, take some other action with an overridden value

 The current set of binary possibilities seems easier to reason about, and encourages better separation of concerns IMO.

1. `--server` is not defined, take some action
2. `--server` is defined, take some other action
3. `--port` is not defined, use a default value
4. `--port` is defined, override the default value.

I'm open to being convinced but this is my initial reaction :smile: 

cc @piotrpMSFT

**Comment by daveaglick** [comment]
@brthor I think you've gotten it pretty much correct. The intent is to provide such a ternary set of possibilities. The benefit is not so much to the developer as much as the end user of the CLI application. When only three states are valid, it is clearer IMO to only allow the user to input those three states.

By contrast, the use of two separate options provides the potential for a confusing error when only three of the four possible states are valid. In the example above, using only `--port` would trigger such an error.

Note that the syntax I ended up with in the PR is different and more concise than the original proposal. It requires very little extra by way of syntax to use, and at least to me is quite intuitive:

Normally, options must supply an argument value (or it's considered an error). However, there may be times when you want to allow a particular option whether it supplies a value or not. To do this, use the overloaded `DefineOption()` methods:

```C#
int port = 1234;
var option = syntax.DefineOption("s|server", ref port, false,
    "Start the server, optionally specifying a port");
```

Then the value in code will be set regardless of whether the command line option specifies one and an error will not be thrown if the option value is omitted. You can check for whether the option was specified at all by checking the `Argument.IsSpecified` flag. For example, given the above option definition:

    $ tool
    # port = 1234, option.IsSpecified = false
    
    $ tool --server
    # port = 1234, option.IsSpecified = true
    
    $ tool --server 9876
    # port = 9876, option.IsSpecified = true
