### ISSUE TITLE
Rename `Cast`

### ISSUE THREAD

**Issue by CodesInChaos** [dotnet/corefxlab#532]
`Cast` shares a name with `Enumerable.Cast` but does something different, leading to confusion. Moreover `ReadOnlySpan<T>` will likely need another cast method to support safe co-variance.

`ReinterpretCast` might be a good choice, similar to what C++ uses.

**Comment by omariom** [comment]
:+1: 

CastAs or just As may be? 
Though I agree that  ReinterpretCast  better explains what is happening.

**Comment by KrzysztofCwalina** [comment]
Do you have any evidence that it indeed leads to confusion? There are subtle differences in many concepts that share simple names (in any field), and for the most part it's ok. Another way to look at it is that you cannot explain all semantics of APIs in method names. They are just short mnemonics.

**Comment by CodesInChaos** [comment]
1. Reinterpret casting is pretty error prone, so it should be obvious that it's used, prompting readers to be extra careful.
2. It's doesn't just have a similar name, it shadows the existing LINQ `Cast<T>` method but differs in behaviour.
3. `ReadOnlySpan<Derived>` needs to be convertible to `ReadOnlySpan<Base>` for reference types. That'll produce another similar but subtly different function.

**Comment by KrzysztofCwalina** [comment]
The corclr Span<T> now has the follwoing methods:
NonPortableCast (between any types)
AsBytes (casts any span to Span<bytes>

corfxlab version of Span should have the same APIs.

**Comment by KrzysztofCwalina** [comment]
this is dup of #705
