### ISSUE TITLE
Slices: Overflows

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#537]
There are possible overflows when addresses or number of items calculated  in a few places in Slices.
One is [described  here](https://github.com/dotnet/corefxlab/issues/516).
We should fix them.

**Comment by omariom** [comment]
Overflow in Span.Cast https://github.com/dotnet/corefxlab/pull/608

**Comment by ahsonkhan** [comment]
@omariom, is this still an issue?

**Comment by omariom** [comment]
Closing..
