### ISSUE TITLE
Fix System.CommandLine documentation.

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/corefxlab#539]
While the System.CommandLine description states the goals for the library, it claims that Mono.Options does not fulfill the requirements set on the document.   Yet, it fulfills every one of those requirements.
- Support for Unix and GNU-style?  Check.   (Also Windows style)
- Low level, no reflection or attribute discovery?  Check
- Minimal setup? Check

Yet, the document portrays Mono.Options as not fulfilling those roles.   That said, Mono.Options is also arguably more pleasant to use and provides better customization.

**Comment by terrajobst** [comment]
@migueldeicaza 

Thanks for the feedback. I should probably expand this a bit more. `Mono.Options` -- as far as I can tell -- doesn't support the notions of registering parameters and commands. It seems it only covers options and leaves it for the consumer to handle parameters and commands.

**Comment by am11** [comment]
With the stated benefits of `System.CommandLine`, will it make sense that the following repos take dependency on this assembly, so to test / evolve the implementation and overcome the shortcomings rapidly?

* https://github.com/dotnet/buildtools
* https://github.com/dotnet/codeformatter
* https://github.com/dotnet/cli
* https://github.com/dotnet/roslyn
* https://github.com/Microsoft/msbuild (this presents challenges of parsing BATCH style arguments `/p:Configuration=Debug` etc.)

Each one of these repos have their own ways of parsing command line arguments..

However, following repos are referencing `System.CommandLine`:

* https://github.com/dotnet/corert
* https://github.com/dotnet/core-setup
* https://github.com/dotnet/jitutils
