### ISSUE TITLE
Slices: String and ReadOnlySpan

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#542]
String is an immutable type so it should only  be presented as ReadOnlySpan&lt;char&gt;.
It requires to define relations between Spans and ReadOnlySpans.

@KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
@omariom, could you clarify? Where do we "present" strings as Spans?

BTW, I do agree with the comment you made, I just want to make sure I am not missing something actionable. At some point, we want to add String.Split APIs that return slices and these will have to be ROS<char>

**Comment by omariom** [comment]
"Present" was a wrong  word.
I meant currently  we can do this
```C#
string str = new string('a', 5);
Span<char> strSpan = str2.Slice();
strSpan[0] = 'b';
```

**Comment by KrzysztofCwalina** [comment]
Ah, got it. Yes, we should add a ReadOnlySpan<T> first. I filed issue #543

**Comment by KrzysztofCwalina** [comment]
@omariom, I though it might be useful to keep this open to change the span helper API (Slice(this string ...) to return ROS<char>

**Comment by omariom** [comment]
Aaaah.. )

**Comment by KrzysztofCwalina** [comment]
this is fixed
