### ISSUE TITLE
Any chance of strong-name/signed builds of these packages?

### ISSUE THREAD

**Issue by simmdan** [dotnet/corefxlab#544]
My team needs MultiValueDictionary that is usable cross platform.  Is there any chance that a strong-named / authenticode signed nuget package could be built and made available on the dotnet-corefxlab nuget feed?  I know they are still pre-release, but right now I can't use the output of the feed at all without changing all relevant machines to allow delay signed bits...

**Comment by livarcocc** [comment]
https://github.com/dotnet/corefxlab/pull/601
