### ISSUE TITLE
Non-allocating binary reader/writer

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#559]

**Comment by omariom** [comment]
Reading/writing from byte Spans?

**Comment by KrzysztofCwalina** [comment]
Spans (and arrays), and possibly Stream. Stream itself is not ideal from allocation perspective, but it's such an entrenched .net abstraction that I think many of the non-allocating APIs should still integrate with it.

**Comment by KrzysztofCwalina** [comment]
System.Binary is a good start.
