### ISSUE TITLE
Concurrency runtime

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#560]

**Comment by omariom** [comment]
What is Concurrency runtime? 
Sounds  very intriguing )

**Comment by KrzysztofCwalina** [comment]
cc: @stephentoub 

I meant this to be a bucket for APIs related to https://github.com/dotnet/corefxlab/tree/master/src/System.Threading.Tasks.Channels.

I was just opening bunch of issues to track high level parts needed to write high scale services.

**Comment by KrzysztofCwalina** [comment]
For now what we have in channels is what we will use.
