### ISSUE TITLE
Ability to regression test GC allocations

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#561]

**Comment by ahsonkhan** [comment]
I am assuming this is part of performance testing? Does using BenchmarkDotNet to track allocations resolve this issue?

cc @adamsitnik

**Comment by KrzysztofCwalina** [comment]
GC allocations are very predictable. I worry that BDN's harness is just way too heavyweight for it. I was imagining something very lightweight that can be used within a simple unit test, i,.e. capture allocations before the test, run test, ensure that only expected number of bytes are allocated after the test runs. 

I think this can be done with the new thread allocation metrics exposed in core 2.1?
