### ISSUE TITLE
Slices: Alignment

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#572]
Currently Slices allow unaligned reads/writes

``` C#
long l = new byte[9].Slice(1).Cast<byte, long>()[0];
```

Is it a concern?

**Comment by mikedn** [comment]
Well, it is a concern for whoever writes that kind of code. The same thing can happen if you use pointers so I don't think it is a concern specific to slices.

**Comment by omariom** [comment]
But what if I am consumer of a slice? 

I am asking  if it is a concern because there are places in CLR where alignment is handled. Like in [BinConverter.ToInt64](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/BitConverter.cs#L249) or [Marshal.ReadInt64](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs#L556).

**Comment by mikedn** [comment]
> But what if I am consumer of a slice?

What if you are the consumer of `long*`? Same problem.

> I am asking if it is a concern because there are places in CLR where alignment is handled. Like in BinConverter.ToInt64 or Marshal.ReadInt64.

Yes but that kind of handling affects performance of the common case - properly aligned data.

I think the best approach is to consider what can be done to avoid this problem. If something can be done that doesn't impact performance then it should be done. If not then so be it, if you use that kind of cast you should know what you are doing in the first place.

I think the best solution is:
* Add `ref` returns to the language
* Change the `Span` indexer to return a `ref T`
* Provide `T Unsafe.ReadUnaligned<T>(ref T)`

**Comment by omariom** [comment]
>Yes but that kind of handling affects performance of the common case - properly aligned data.

I am for perf and against alignment checking ) 
 Just wanted to know if  there is .NET team wide agreement on that.

**Comment by omariom** [comment]
> •Change the  Span  indexer to return a  ref T  
> •Provide  T Unsafe.ReadUnaligned<T>(ref T)  

Indexer will be returning potentially unaligned ref and 
ReadUnaligned will be checking for alignment, right?

**Comment by mikedn** [comment]
> Indexer will be returning potentially unaligned ref 

Yup, that way unaligned access is no longer span's problem.

> ReadUnaligned will be checking for alignment, right?

I'm thinking something along the lines of the recently discusses `Unsafe.Read<T>(void *)`:

```C#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static T ReadUnaligned<T>(ref T p)
{
    ldarg.0          
    unaligned. 1 ldobj !!T
    ret
}
```

**Comment by omariom** [comment]
@mikedn 
[Ok to read unaligned on x64](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L380). It is official )

**Comment by mikedn** [comment]
It's OK in the sense that the program doesn't crash if it tries to do unaligned loads/stores. However, the performance of such loads/stores may be lower.

**Comment by omariom** [comment]
`cpblk` can be marked as `Unaligned`. [Reference to the PR using cpblk for copying from/to Slices](https://github.com/dotnet/corefxlab/pull/732). 
Just in case.

**Comment by KrzysztofCwalina** [comment]
We decided to have Cast to Span<bytes> and NonPortableCast to other types.
