### ISSUE TITLE
Should the StackOnly attribute be split?

### ISSUE THREAD

**Issue by CodesInChaos** [dotnet/corefxlab#577]
There seem to be [two reasons](https://github.com/dotnet/corefxlab/issues/257) for using the `StackOnly` attribute:
1. Ensuring integrity of the whole struct / preventing torn writes. Allocating on the stack is a sufficient but not necessary condition for that.
   
   For example, if the `this` reference doesn't escape from a constructor, a readonly field should be safe from torn writes as well.
   
   Another example would be  local variables in `async` functions or local variables that were captured in a display class by a lambda. If the compiler can statically prove that the variable won't be written to after it becomes visible to other threads, this should be safe.
   
   Restricting yourself to stack-only in the first version may be a valid simplification, I'd like to see support for additional scenarios at some point.
2. It helps with tracking all references to the underlying object and returning it to a pool.
   
   It's not entirely clear to me how this mechanism is supposed to work, especially since returning a slice from a function lets a reference escape from the original scope. See [Why doesn't C# support the return of references? on stackoverflow](http://stackoverflow.com/questions/6339602/why-doesnt-c-sharp-support-the-return-of-references) and [Eric Lippert - Ref returns and ref locals](http://ericlippert.com/2011/06/23/ref-returns-and-ref-locals/) for similar issues with returning references.
   
   I'm not even sure if restricting the usage of a type is even the correct approach for this, of if you'd rather annotate the return value of the pool allocation function.
   
   Also this problem is pretty similar to ensuring that `Dispose` gets called on a disposable type, so it might be a good idea to use a mechanism that handles that case as well.

Anyways, these two reasons look like separate concerns to me, that should be handled with separate attributes, instead of using one with related but subtly different semantics. That way the semantics of each purpose can evolve separately and types that only need to support one of these purposes can opt into only those restrictions on usage they need.

**Comment by KrzysztofCwalina** [comment]
@CodesInChaos, the attribute and the analyzer are mainly (only?) to ensure memory safety. As you observed, we don't have bullet proof solution for the second issue; you need to use Rust for that ;-)

**Comment by CodesInChaos** [comment]
For the first purpose I'd prefer something like `EnsureStructIntegrityAttribute` over `StackOnly` and expand its meaning to cover safe usage patterns beside the stack. (Possibly expand only in later versions, since it's no breaking change)

*Can't you publish the language used by Midori? From what I have read, it had Rust like ownership tracking, but much better tooling.*

**Comment by KrzysztofCwalina** [comment]
We will provide language checks for this. No need for an analyzer nor the attribute.
