### ISSUE TITLE
System.CommandLine: Bring back PCL/net45x compatibility

### ISSUE THREAD

**Issue by borgdylan** [dotnet/corefxlab#589]
I was using the System.CommandLine package on mono i.e. net451 to port the .NET CLI to Linux/x86 version of Mono since .NET Core is only for x64. Prior to today the System.CommandLine package was a PCL that let me target net451, but the recent change to targeting dotnet5.6 means that only .NET Core could be targeted. Please add back a target that is net451 compatible such as dotnet5.3, the PCL target used before or net451 itself. This package worked perfectly on Mono and it would be a shame to retire it from platforms where it worked ok and was useful.

**Comment by khellang** [comment]
I think this (Mono compat) is precisely the reason why most ASP.NET packages have kept `net451` around, in addition to `dotnet5.6` :smile:

**Comment by borgdylan** [comment]
If using the latest mono, net461 would be enough.

**Comment by borgdylan** [comment]
@piotrpMSFT is this building with the CLI or DNX? That would allow cross-compiling without issues.

**Comment by onovotny** [comment]
.NET 4.5 is done in this PR #688

**Comment by alexperovich** [comment]
Closing because #688 is merged.
