### ISSUE TITLE
Slices and ref locals and returns

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#606]
As [Ref locals and returns](https://github.com/dotnet/roslyn/pull/8030) are approaching, Slices API should probably take that into account.

**Comment by omariom** [comment]
For example, `Span<byte>` could have the following extension method (name can be different):
```C#
public static ref T AsRef<T>(this Span<byte> span)

// usage
ref var header = buffer.AsRef<Header>();
```
 If future C# has `readonly ref` returns:
```C#
public static readonly ref T AsRef<T>(this ReadOnlySpan<byte> span)
```

**Comment by KrzysztofCwalina** [comment]
Yeah, definitely we would add something like that.

**Comment by KrzysztofCwalina** [comment]
per API review (https://github.com/dotnet/apireviews/tree/master/2016/11-04-SpanOfT) we will add ref returning indexer.
