### ISSUE TITLE
Channels: Why IReadableChannel<T>.ReadAsync is not an extension method?

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#611]
@stephentoub 
Looks like it can be implemented using just TryRead and WaitToReadAsync:
```C#
public static class ChannelExtensions
{
    public static async Task<T> ReadAsync<T>(IReadableChannel<T> channel, CancellationToken cancellationToken = default(CancellationToken))
    {
        T item;
        do if (channnel.TryRead(out item))
        {
            return item;
        }
        while (await channnel.WaitToReadAsync(cancellationToken));

        throw new Exception("Channel closed?");
    }
}
```

Then why is it a part of IReadableChannel<T>? Is it because of performance or some implicit ordering/fairness guarantee?

**Comment by stephentoub** [comment]
There's certainly a performance aspect to it, in that channel implementations can typically implement this more efficiently than you can in an extension method (even just avoiding the overhead of extra interface calls).

But there's also a functional reason.  Your approach to ReadAsync could also be done for WriteAsync, e.g. pseudo-code:
```C#
public static async Task WriteAsync<T>(this IWriteableChannel<T> channel, T value)
{
    while (true)
    {
        if (channel.TryWrite(value)) return;
        await channel.WiteToWriteAsync();
    }
}
```
but certain kinds of channels will not function well if you have such read/write implementations.  Consider a reader and writer trying to coordinate on an UnbufferedChannel; they'll never successfully join with such implementations as they'll never actually be waiting on the channel at the same time.

**Comment by omariom** [comment]
I thought about separate interfaces for ReadAsync/WriteAsync but it then realized it would complicate the matters.

**Comment by omariom** [comment]
@stephentoub 
Then another question.
Are there any implicit ordering/fairness guarantees in ReadAsync/WriteAsync? 
I am asking because I see that all the channels do FIFO not only for data but for waiting activities as well.

**Comment by stephentoub** [comment]
> Are there any implicit ordering/fairness guarantees in ReadAsync/WriteAsync?

No, it's up to the implementation.

>  see that all the channels do FIFO not only for data but for waiting activities as well.

That's not strictly true, as Monitor isn't necessarily fair.

**Comment by omariom** [comment]
Thanks @stephentoub. Now it is more than less clear )
