### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#613]
When I do `dotnet test` in `src\System.Slices\tests` it spits
```
'"dotnet-test-xunit"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by livarcocc** [comment]
@omariom this folder shouldn't even exist anymore if you have synced. But if you didn't, have you done a dotnet restore, dotnet build?

**Comment by omariom** [comment]
I tried with a new clone. Did restore & build in 'corefxlab\src\System.Slices'. Then  restore & build  in `corefxlab\tests\System.Slices.Tests`.  But `dotnet test` outouts `'"dotnet-tests"' is not recognized as an internal or external command, operable program or batch file.`

**Comment by omariom** [comment]
I installed the latest version of CLI. Now tests run.

**Comment by livarcocc** [comment]
@omariom yes, you were missing the dotnet binaries in the path and the DOTNET_HOME environment variable, which the MSI sets for you.
