### ISSUE TITLE
Slices: Array covariance strikes back

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#614]
@KrzysztofCwalina  @mikedn @VSadov 
```C#
var persons = new [] { new Person() };
((object[])persons).Slice()[0] = "ouch!";
Person first = persons[0];
first.Test();

public class Person
{
    private int age;

    public void Test()
    {
        Console.WriteLine(this);
        Console.WriteLine(GetType());
        Console.WriteLine(age);
    }
}
```

Outputs:
```
ouch!
System.String
5
```

We probably need to check in ctors that element type of the array is exactly `T`. That implies using Reflection.

**Comment by mikedn** [comment]
Ouch.

>  That implies using Reflection.

Seems to me that `requires(array.GetType() == typeof(T[]))` should be enough and relatively efficient.

**Comment by omariom** [comment]
@mike :+1: 
though for arrays the check is not as good for plain objects.
And the check is not eliminated for arrays of value types. That's sad because I was going to make ctors lighter.

```C#
[MethodImpl(MethodImplOptions.NoInlining)]
private static bool TestArrayElementType<T>(T[] array) => array.GetType() == typeof(T[]);

TestArrayElementType(new int[0]);
TestArrayElementType(new object[0]);
```

```ASM
; Lcl frame size = 32
       56                   push     rsi
       4883EC20             sub      rsp, 32
       E85658615F           call     System.Object:GetType():ref:this
       488BF0               mov      rsi, rax
       48B9925CCA8FFB7F0000 mov      rcx, 0x7FFB8FCA5C92
       E8C4B7CC5E           call     CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
       483BF0               cmp      rsi, rax
       0F94C0               sete     al
       0FB6C0               movzx    rax, al
       4883C420             add      rsp, 32
       5E                   pop      rsi
       C3                   ret      

; Total bytes of code 43, prolog size 5
================================================================
; Lcl frame size = 40
       57                   push     rdi
       56                   push     rsi
       4883EC28             sub      rsp, 40
       48894C2420           mov      qword ptr [rsp+20H], rcx
       488BF1               mov      rsi, rcx
       488BCA               mov      rcx, rdx
       E80A58615F           call     System.Object:GetType():ref:this
       488BF8               mov      rdi, rax
       488B4E38             mov      rcx, qword ptr [rsi+56]
       488B4908             mov      rcx, qword ptr [rcx+8]
       4885C9               test     rcx, rcx
       7515                 jne      SHORT G_M25322_IG03
       488BCE               mov      rcx, rsi
       48BAA8173F32FB7F0000 mov      rdx, 0x7FFB323F17A8
       E808ACCC5E           call     CORINFO_HELP_RUNTIMEHANDLE_METHOD
       488BC8               mov      rcx, rax

G_M25322_IG03:
       E860B7CC5E           call     CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
       483BC7               cmp      rax, rdi
       0F94C0               sete     al
       0FB6C0               movzx    rax, al
       4883C428             add      rsp, 40
       5E                   pop      rsi
       5F                   pop      rdi
       C3                   ret      

; Total bytes of code 80, prolog size 11
```

**Comment by mikedn** [comment]
> though for arrays the check is not as good as for plain objects.

Indeed, maybe this could be improved in the JIT. I don't see why `typeof(T[])` would generate worse code than `typeof(T)`, I'll have to check the JIT code.

**Comment by mikedn** [comment]
> Indeed, maybe this could be improved in the JIT. I don't see why  typeof(T[])  would generate worse code than  typeof(T) , I'll have to check the JIT code.

Turns out that this is a VM/JIT issue. Array method tables aren't the "real thing", they're more like indirections to the actual method table. The net result is that you can't compare an array's object method table pointer with the result of `ldtoken`.

I suppose the JIT compiler could be smarter and try to change the `ldtoken` result into something that can be compared to an array's method table. But it seems quite complicated...

**Comment by KrzysztofCwalina** [comment]
@omariom, good issue! Hopefully we can find a way to do the check efficiently.

@CarolEidt, any thoughts on this?

**Comment by omariom** [comment]
I found it trying to understand if it is possible for JIT not to use pretty heavyweight [JIT_Stelem_Ref](https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/JitHelpers_Fast.asm#L708) for  `T[]` when T is a sealed class and realized that JIT doesn't treat `PtrUtils.Set` as array indexer's setter.

But that fact makes Slice's setter  almost 14 times faster than array's one: 3083 vs 224 :)

**Comment by KrzysztofCwalina** [comment]
maybe soon you won't have to use [RefAsValueType](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/RefAsValueType.cs) :-)

cc @terrajobst, @AArnott, @jaredpar

**Comment by VSadov** [comment]
FWIW  Roslyn uses struct element wrappers in every place where we have hot mutable arrays of reference types. - in ObjectPool in syntax builders ...

It would be nice to get rid of that.

Note that it is not uncommon that these element writes are done via InterlockCmpXchg, so byref indexer would be very handy  :-)
