### ISSUE TITLE
Add support for surrogates

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#62]
One of the tests has the following line commented:
//utf8Writer.Append("\uD950\uDF21"); // TODO: surrogate pair; this is NIY

Uncommenting this and running tests will cause test failures. This is because the library does not support surrogates. The fix should be moderately difficult.

**Comment by krwq** [comment]
I think this scenario is working for some time:
https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Formatting/src/System/Text/Formatting/PrimitiveFormatters.cs#L165
