### ISSUE TITLE
Find out why some of the latest dependencies from corefx are not compatible the tfms we use in corefxlab

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefxlab#627]
I had to pin the version of some of our dependencies because they were incompatible with the tfms we use (dotnet5.2, 5.6). We need to understand why they became incompatible and if we are generating these libraries for the right tfms.

**Comment by KrzysztofCwalina** [comment]
I suspect we need to change the project files to use:

        "netstandard1.x": {
            "imports": [ "dotnet5.y" ]
        }

**Comment by khellang** [comment]
@KrzysztofCwalina yes, where x = y - 1 :wink: see https://github.com/aspnet/Mvc/pull/4170 for an example

**Comment by KrzysztofCwalina** [comment]
@livarcocc, I think I fixed this. Could you verify?

**Comment by KrzysztofCwalina** [comment]
seems to be fixed
