### ISSUE TITLE
Slices: consider non-unit strides

### ISSUE THREAD

**Issue by JeffreySax** [dotnet/corefxlab#637]
The current implementation of slices assumes that the elements of the slice are contiguous. In other words: the stride is one, which means that the distance in memory between successive elements is equal to one times the size of the element.

There are a three scenarios where it would be beneficial to allow non-unit strides.

* Slices of 2 and higher dimensional arrays. This would allow taking slices of columns of 2D arrays. The distance between elements can be calculated from the dimensions of the array.
* Along the same lines, 2D matrices are often represented using 1D arrays, often in column-major order because of API's derived from FORTRAN libraries. Non-unit slices would be essential to get row or column slices, which are extremely common.
* Getting a _structure of arrays_ from an _array of structures_. For example: get a double array of the real parts of an array of complex numbers; get an array of the X-coordinates in an array of points structures... The distance between elements is the size of the entire structure.

**Comment by KrzysztofCwalina** [comment]
I don't think it can be implemented efficiently enough. I think for these scenarios, we would need a higher level type.
