### ISSUE TITLE
Write more performance tests and optimize runtime performance

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#64]
1. Formatting UTF8 strings does not have performance tests
2. Number formatter is calling ToUpper on the format character. This regressed perf a bit in the past.
3. Math.DivRem (used in hot formatting loop) generates two idiv instructions. it should be just one.
4. It would be worth to again profile the perf tests. There were significant changes since last time.
5. Composite formatting does not have perf or memory tests.

**Comment by GrabYourPitchforks** [comment]
@KrzysztofCwalina What remains to be done here? The formatters / parsers are now productized and the RTM code appears to have addressed much of these concerns.
