### ISSUE TITLE
Multispan.CopyTo should take a T[], not byte[]

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefxlab#644]
Just came to this repo and clicked on the latest commit, when I noticed that `Multispan.CopyTo` takes a [byte array](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Experimental/System/Buffers/Multispan.cs#L36) and not a generic array. Just thought I'd raise an issue to let you know.

cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
fixed by #645
