### ISSUE TITLE
Can't build repo

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefxlab#651]
Dotnet.exe no longer sits under the `bin` subdirectory and since the build scripts just pick up whatever is the bleeding edge, the build fails.

**Comment by nguerrera** [comment]
+1

**Comment by nguerrera** [comment]
@mellinoe

**Comment by mellinoe** [comment]
@MichalStrehovsky This should be fixed now. Please let me know if you hit more issues.
