### ISSUE TITLE
Investigate lowering `netstandard` target on System.CommandLine

### ISSUE THREAD

**Issue by anurse** [dotnet/corefxlab#655]
We want to use .NET CLI packages on `net451` (which targets `netstandard1.2`) but they depend on System.CommandLine which targets `netstandard1.3`. Is it possible to lower that version? Does System.CommandLine depend on anything that was added in `netstandard1.3`?

/cc @piotrpMSFT @Eilon

**Comment by Eilon** [comment]
This is quite important even for the current RC2 release, so can we get someone to take a look at this ASAP?

@Petermarcu

**Comment by mellinoe** [comment]
I'll take a look at this.

**Comment by mellinoe** [comment]
It doesn't seem like System.Console actually supports netstandard1.2. The minimum supported version is 1.3.

**Comment by piotrpMSFT** [comment]
What's the blocker, @mellinoe? Can we make it work?

**Comment by mellinoe** [comment]
I'm not sure we can actually support System.Console on netstandard 1.2. Can we, @ericstj? The best we can probably do is have the System.CommandLine package offer a target specifically for net451. I'm not sure that will help for the original issue, however.

**Comment by piotrpMSFT** [comment]
@anurse thoughts?

**Comment by mellinoe** [comment]
It does seem like Console is only used in a few places, so I could try to remove it's usage and see if any other dependencies are problematic.

**Comment by Petermarcu** [comment]
@piotrpMSFT , Are you still considering just removing the dependency on this from the CLI?

**Comment by piotrpMSFT** [comment]
@Petermarcu yes. It looks like the only real option.

**Comment by mellinoe** [comment]
There are a few other problematic dependencies, but they could potentially be removed if we wanted to neuter certain functionality:

* `Environment.Exit()` isn't available
* `Console` isn't available at all: used for error reporting, etc.
* `System.IO.FileSystem` isn't available at all. Response files wouldn't work at all.

**Comment by anurse** [comment]
I think we use response files in the CLI. Could we cross-compile this for `net451`? That or we'll have to see if `netstandard1.3` (.NET 4.6+) is sufficient for ASP.NET

**Comment by mellinoe** [comment]
I am assuming that compiling for net451 is possible based on what is missing above. I haven't tried it. Would that be a sufficient for you guys? It seems like you would still need to target netstandard1.3, regardless.

**Comment by anurse** [comment]
Cross-compiling would be sufficient. We'd still like the `netstandard` version dropped as low as it can go, but `1.3` would be fine for that, and if it's going to be hard to drop it to that we can work with as high as `1.5` I believe as long as there is ALSO a `net451` target.

**Comment by KrzysztofCwalina** [comment]
Instead of cross compiling, could we:
1. Use ILogger (or something like that for logging)
2. Provide ability to read response files form an arbitrary Stream specified by the app code
3. Refactor such that we don't have to call Environment.Exit in library code
?

**Comment by mellinoe** [comment]
We can do whatever we want, but upstream folks are going to need to recompile and make functional changes, and we will need to redesign portions of the library to accomodate things like no `Environment.Exit`, i.e. bool-returning methods that need to be handled by app code. Cross-compiling should be trivial, regardless. Although the state of building in this repo is not very good even before these changes.

**Comment by KrzysztofCwalina** [comment]
Yes, we need to redesign it if we want to run on netstandard < 1.3. But I feel like we should just do it and have a single dll (i.e. not cross compiled). If we cross compile, we will have behavioral differences that are then viral.

**Comment by mellinoe** [comment]
I wouldn't expect to see any behavioral differences if we cross-compiled. The code would be identical and I don't think there's really any meaningful behavioral differences that would impact this level of the stack. What kinds of problems are you thinking of?

**Comment by eerhardt** [comment]
FYI - with https://github.com/dotnet/cli/issues/2526 being implemented this issue is no longer needed any time soon.  CLI won't be using System.CommandLine at all.

**Comment by MichalStrehovsky** [comment]
Not calling Environment.Exit is overall goodness. I was surprised when I hit it.

Not writing to the Console is overall goodness too (an app having command line interface != console app - see `msiexec.exe /?` in Windows as an example).

Asking the user to provide means to read response files is kind of awkward though.

**Comment by daveaglick** [comment]
I agree with others on this thread - both `Environment.Exit()` and direct console writes should be removed (this was already partially addressed in #418 which never got merged).

**Comment by alexperovich** [comment]
This issue has been fixed. The System.CommandLine package has netstandard1.5 and net45 build using the new Tooling.
