### ISSUE TITLE
It's unfortunate that formatters need to be classes (hard problem)

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#66]

**Comment by ahsonkhan** [comment]
Why do they need to be classes? What is the drawback of them being classes? We have some that are classes and some that are structs.

[ArrayFormatter is a class](https://github.com/dotnet/corefxlab/blob/6656f0a05a8f7d7b1bcdf92f7901f40d559a6bdc/src/System.Text.Formatting/System/Text/Formatting/Formatters/ArrayFormatter.cs#L12)

[StreamFormatter is a struct](https://github.com/dotnet/corefxlab/blob/6656f0a05a8f7d7b1bcdf92f7901f40d559a6bdc/src/System.Text.Formatting/System/Text/Formatting/Formatters/StreamFormatter.cs#L10)
