### ISSUE TITLE
IReadOnlyCollection<T> support for ReadOnlySpan<T>

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/corefxlab#663]
It could be useful - especially - when used together with already existing code.

**Comment by KrzysztofCwalina** [comment]
I would like to keep span<T> very lightweight: small set of dependencies, no APIs that allocate without much transparency about it, simple implementation, etc. Out collection interfaces are not that. They cause silent allocations, heavily allocating LINQ APIs start showing up on them, etc. 

Also, I think we will need to make Span<T> truly stack-only, at which point it will be impossible (or very complicated) to implement these interfaces. As these interfaces require creation of heap objects (enumerator) wrapping Span<T>.

**Comment by fubar-coder** [comment]
You're already using IEnumerable<T>, and IReadOnlyCollection<T> is the same - with an additional "Count". So, why is that different?

**Comment by KrzysztofCwalina** [comment]
We actually need to remove IEnumerable\<T\> from span. Span will be a stack-only type and it won't be able to implement the interface.
