### ISSUE TITLE
The sizes of Span and ReadOnlySpan could be reduced

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefxlab#665]
Currently, `Span` is laid out like this:

```cs
public struct Span<T>
{
    internal readonly object Object; // array or string, null for native pointers
    internal readonly UIntPtr Offset; // offset into the managed object, or the pointer
    public readonly int Length; // length of the data
}
```

This takes up a total of 12-20 bytes in memory, depending if the target machine is 32 or 64-bit. Instead, it could be laid out/implemented as follows:

```cs
public struct Span<T>
{
    [StructLayout(LayoutKind.Explicit)]
    private struct Data
    {
        [FieldOffset(0)]
        internal readonly object AsObject;
        [FieldOffset(0)]
        internal readonly IntPtr AsPointer;
    }

    internal readonly Data Data;
    internal readonly int Offset; // high bit is set for native pointers
    public readonly int Length;

    public Span(T[] array, int offset, int length)
    {
        this.Data.AsObject = array;
        this.Offset = offset;
        this.Length = length;
    }

    public Span(void* pointer, int length)
    {
        this.Data.AsPointer = new IntPtr(pointer);
        this.Offset = int.MinValue;
        this.Length = length;
    }

    public T this[int index]
    {
        get
        {
            // Take note: No branching
            return PtrUtils.Get<T>(this.Data, Offset & ~int.MinValue, index);
        }
    }

    public bool TryGetArray(out ArraySegment<T> segment)
    {
        // Take note: No casting/type checks
        if (Offset < 0)
        {
            segment = default(ArraySegment<T>);
            return false;
        }

        // dotnet/corefx#7966
        var array = Unsafe.As<T[]>(this.Data.AsObject);
        segment = new ArraySegment<T>(array, Offset, Length);
        return true;
    }
}
```

cc @KrzysztofCwalina (I'm willing to make a PR for this if you approve)

**edit:** Actually if we add support for strings in the future we may have to add type checks to the `TryGetArray` method, like so:

```cs
var array = this.Data.AsObject as T[];
if (array == null) // can be true for strings
    return false;
```

However the point still stands that the size of the struct can be reduced.

**edit 2:** Actually, scratch that; we can bypass type checks even if we support strings, by taking of the advantage that `Length` can never be negative. So we can set the highest bit to 1 if the `Span` represents a string, and then use `Unsafe.As` instead of regular casting. You'd check if it's a string like so:

```cs
private readonly int _length;

public int Length => _length & ~int.MinValue;
public bool IsString => _length < 0;
```

**Comment by svick** [comment]
I don't think using `FieldOffset` this way is allowed:

> Could not load type 'Data' from assembly […] because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.

**Comment by omariom** [comment]
> [FieldOffset(0)]
        internal readonly object AsObject;
        [FieldOffset(0)]
        internal readonly IntPtr AsPointer;

I think it will confuse GC.

**Comment by jamesqo** [comment]
@omariom You're probably right, actually; maybe that's why @svick is running into the problem he mentions when he attempts to run the code, since the CLR would prohibit that since it violates type safety.

Maybe when/if `Span` is moved to coreclr/corert, then it can be laid out natively? Then I'm assuming we could have something like this layout, without confusing the GC.

**Comment by benaadams** [comment]
@jamesqo `IntPtr` is a struct so can't be overlapped with `object` which is a pointer. You can overlap two pointers (though mono sometimes gets upset) and you can overlap structs, but you can't overlap the pointer with a non pointer as the back reference/root becomes ambiguous

**Comment by whoisj** [comment]
```C#
[StructLayout(LayoutKind.Explicit)]
    private struct Data
    {
        [FieldOffset(0)]
        internal readonly object AsObject;
        [FieldOffset(0)]
        internal readonly IntPtr AsPointer;
    }
```

These are almost guaranteed to be two distinct values. Overlapping them would be... well, a really bad idea. Sorry :relaxed:

**Comment by jamesqo** [comment]
This looks like it's being done already in CoreCLR: https://github.com/dotnet/coreclr/compare/master...jkotas:SpanT#diff-65ad7735295eb25486124692067c8eb4R19

**Comment by omariom** [comment]
@jamesqo 
Thanks for pointing that out. Nice to see the team is getting **really** serious about Span )
