### ISSUE TITLE
Slices/Span: Use new `Unsafe` class from corefx

### ISSUE THREAD

**Issue by nietras** [dotnet/corefxlab#666]
Slices/Span can now use the `Unsafe` class for some of the unsafe code instead of their own via https://github.com/dotnet/corefx/pull/7966

**Comment by KrzysztofCwalina** [comment]
Thanks!

**Comment by benaadams** [comment]
Depends on entry point; if Span goes into coreclr/runtime it can't use the corefx version

**Comment by nietras** [comment]
Yes, of course. However, as far as I understand the same methods are useful in the runtime so they may be available in a similar form there. Anyway, seems like Span is going to use a lot of handwritten IL so defining its own copy of unsafe methods is probably not a big issue. Given how little code it is.

**Comment by KrzysztofCwalina** [comment]
Also, the new APIs are only in Net Standard 1.6. I would prefer to keep the Slices library supported on lower versions.
