### ISSUE TITLE
.NET Core RC2 Updates

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#668]
Any timeline on supporting RC2/RTM?  I tried referencing the Tasks.Channel proj with errors.  Also any updates to NuGet locations?  Thx

**Comment by mellinoe** [comment]
@shaggygi I'm working on updating the dependencies now. I'll have a PR up shortly once I validate everything.

**Comment by shaggygi** [comment]
@mellinoe that is great news :smile:

**Comment by mellinoe** [comment]
Check out #670 . You can grab my `compile-against-rc2` branch if you'd like to test things locally.

**Comment by mellinoe** [comment]
Once that change goes through, new nuget packages should be published automatically after tonight's build of the repository.

**Comment by mellinoe** [comment]
I merged #670 in. You can try to build stuff locally now, but they won't get published to nuget.org until our nightly build finishes later. Let me know if you encounter any problems using the packages.

**Comment by KrzysztofCwalina** [comment]
I just synced and built. Works great!
Thanks.

**Comment by shaggygi** [comment]
So I got the latest today and tried to rebuild the solution.  I got lots of "The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file." errors.  I also tried to restore the packages, but Output states all are installed.

I'm just now trying to understand .NET Core so I'm a little confused on what the error is.  Any help is appreciated.

Also, I could find the NuGet package for System.Threading.Tasks.Channel.  Where is this supposed to be pull from?

Thx

**Comment by mellinoe** [comment]
Could you list all the steps you're using? Also, which version of the .NET CLI are you using?

System.Threading.Tasks.Channels is available from this feed:
https://dotnet.myget.org/gallery/dotnet-corefxlab

**Comment by shaggygi** [comment]
I downloaded RC2 and Preview SDK from here:
https://github.com/dotnet/cli/releases/tag/v1.0.0-preview1

Downloaded corefxlabs zip, unzipped, open solution in VS 2015 w/ Update 2 and tried to build.

**Comment by mellinoe** [comment]
Have you run `dotnet restore`, either from the command line or from Visual Studio (with the "Restore Packages" button on the solution explorer) ? If not, that would explain the error you saw. Otherwise I'd have to dig for more info.

**Comment by shaggygi** [comment]
`dotnet restore` worked.  I was able to rebuild afterwards.  I'm confused why the "Restore Packages" for both Solution and individual projects didn't work.

Thanks for the help.  Closing issue.
