### ISSUE TITLE
Slices: Question on returning refs from spans

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#669]
I was thinking about a possible  implementation of AsRef method for slices of bytes
```C#
public static ref T AsRef<[Primitive]T>(this Span<byte> span)
```

It could use a version of [PtrUtils.Get](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/PtrUtils.cs#L21). The only difference would be returning `ref` and  the absence of the last `ldobj !!T`. 
But given the warning I am concerned about possible GC holes or other issues it can cause.

@KrzysztofCwalina @mikedn  @VSadov

**Comment by mikedn** [comment]
If it works for PtrUtils.Get it will work for AsRef as well.
