### ISSUE TITLE
Slices fails strong name validation on  Windows 7

### ISSUE THREAD

**Issue by omariom** [dotnet/corefxlab#687]
@livarcocc

It throws 
>FileLoadException: Could not load file or assembly 'System.Slices, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by omariom** [comment]
Can it be caused by not having local admin rights?

**Comment by benaadams** [comment]
And on Win10 
> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Slices, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by xenocons** [comment]
Hello,

This appears to be as a result of IL modifications after the dll is signed, it should just be a matter of resigning the binary after the IL modifications. I would love this fixed as it wreaks havoc with unattended deployments (azure)

Alternate workaround is to add a validation bypass via the registry for that pubkey token, or use sn.exe included with Windows SDK.

**Comment by xenocons** [comment]
Just as a note, I stumbled upon this https://github.com/gluck/il-repack , which seems to offer a parameter to supply a keyfile to sign the resulting assembly, I am not sure if the current solution can do this, so it might be a nice move.

**Comment by omariom** [comment]
> This appears to be as a result of IL modifications after the dll is signed

Yes, it started working after I commented out `keyFile` in projects.json

**Comment by KrzysztofCwalina** [comment]
cc @davidfowl

**Comment by KrzysztofCwalina** [comment]
I believe david fixed it.
