### ISSUE TITLE
Slices package does not properly pin arrays in all cases. We should review the code

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#703]
Some helpers were added to Span<T> that use unpined addresses computed by ComputeAddress. All these methods need to be either made unsafe, pin, or special cased for native memory.

**Comment by omariom** [comment]
In Slices  it is used in 5 places. 4 of them are safe - [arrays are prepinned](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/MemoryUtils.cs#L30). 
The last one is  [UnsafePointer](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Span.cs#L149) and it is used in other Lab's projects.
