### ISSUE TITLE
Create portable package for corfxlab Span<T> and coreclr Span<T>

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#705]
We are adding Span<T> to coreclr (https://github.com/dotnet/coreclr/issues/5851). The coreclr implementation will be fast, but it depends on runtime features that are no present in runtimes that already shipped (e.g. .NET Framework 4.5 CLR). But we would like to have Span<T> in portable surface area (i.e. net standard 1.0 and above). To do this we will:
1. Ship fast Span<T> in a future release of corclr. Add the API to System.Runtime.
2. Ship System.Slices package/contract for netstandard 1.0
3. The contract will forward to System.Runtime on runtimes that natively support Span<T>
4. If the package does not forward, it will use something similar to the corfxlab Span<T> implementation, i.e. slower but API compatible.

**Comment by KrzysztofCwalina** [comment]
@weshaggard, @terrajobst, @omariom, @adamsitnik

**Comment by benaadams** [comment]
Will it be a corefx type then? Like `Vector<T>` (+runtime `Vector<T>`)

**Comment by benaadams** [comment]
nvm, that would make it hard to reference in coreclr

**Comment by KrzysztofCwalina** [comment]
I am not sure we will be able to add Span overloads to previous runtimes/frameworks. Or rather I am sure we won't be able to add Stream.Write(Span<T>) to .NET 4.5. I think the goal should be to simply have span available in previous runtimes/frameworks, not to modify all the existing APIs to underastand spans.

**Comment by KrzysztofCwalina** [comment]
Note: this work item includes aligning the APIs.

**Comment by KrzysztofCwalina** [comment]
this workitem has been completed by @ahsonkhan, @AtsushiKan, @jkotas, and @russellhadley
