### ISSUE TITLE
Can BufferFormatter and StringFormatter be combined?

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#71]

**Comment by ahsonkhan** [comment]
The formatters have changed quite a bit. BufferFormatter became ArrayFormatter (https://github.com/dotnet/corefxlab/commit/579f5d27b1b91a689d2f2eb09b39bbfe69f4d8c2#diff-89da374db4a73e3bb2cba59f80588ec4).
In the past (around the time of this issue) we had the following formatters which implemented IFormatter, which became ITextOutput here https://github.com/dotnet/corefxlab/commit/0b053478f31debe327bc7f2f9fc488d420997f07#diff-89da374db4a73e3bb2cba59f80588ec4, and eventually became `IBufferWriter<byte>`:
https://github.com/dotnet/corefxlab/blob/83b5b055f44403cf1baeff6471279e6de0bd3232/src/System.Text.Formatting/src/System/Text/Formatting/BufferFormatter.cs#L5

https://github.com/dotnet/corefxlab/blob/83b5b055f44403cf1baeff6471279e6de0bd3232/src/System.Text.Formatting/src/System/Text/Formatting/StringFormatter.cs#L8

Does the question still hold for ArrayFormatter and StringFormatter today?
