### ISSUE TITLE
Implicit conversion to Span from Array?

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#734]
Extending the `Span`->`ReadOnlySpan` implicit conversion theme. 

For Span
```csharp
public static implicit operator Span<T>(T[] array)
{
    return new Span<T>(array);
}
```
For ReadOnlySpan
```csharp
public static implicit operator ReadOnlySpan<T>(T[] array)
{
    return new ReadOnlySpan<T>(array);
}
```
This would allow new apis to only need a single method which would convey intent rather than also requiring array overloads which are ambiguous in intention as the method name is generally reversed in action with the parameter.

e.g. `Stream.Write(ReadOnlySpan<byte> array)` and `Stream.Read(Span<byte> array)`

```csharp
SpanAwareStream s;
byte[] a = new byte[255];

s.Write(a); // conversion to ReadOnlySpan
s.Read(a); // conversion to Span
```

Would it have unintended side-effects?

**Comment by KrzysztofCwalina** [comment]
I think it would be a good addition. Some people are not thrilled by implicit (hidden) casts like that, but I think it's fine if the cost is low.
