### ISSUE TITLE
Referencing System.Threading.Tasks.Channels to WPF app

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#737]
Get errors while trying to install System.Threading.Tasks.Channels with a WPF app.  Using version 0.1.0-e160702-1.  Get the following in Output:

Could not install package 'Microsoft.NETCore.Targets 1.0.1-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by stephentoub** [comment]
@ericstj, @KrzysztofCwalina, do we need to make updates across corefxlab to address version issues, target 1.0 RTM, etc.?

**Comment by ericstj** [comment]
Yeah, we fixed that particular issue in RTM version of Microsoft.NETCore.Targets.

**Comment by shaggygi** [comment]
Does this mean we can get access to now or something that comes in future release of packages (or Visual Studio)?  Thx

**Comment by stephentoub** [comment]
> Yeah, we fixed that particular issue in RTM version of Microsoft.NETCore.Targets.

@ericstj, @KrzysztofCwalina, have all of the corefxlabs projects been updated to point to the released libs?

**Comment by shaggygi** [comment]
@stephentoub I tried again referencing 0.1.0-e161101-1 and appears to install in WPF app with no problems.  This issue can be closed unless you need your question above answered first.  Thx.

**Comment by stephentoub** [comment]
Great, thanks for confirming..
