### ISSUE TITLE
Read and Subscribe to a Channel at the same time

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefxlab#739]
I might have a normal process that waits/reads from a channel and when the next write occurs, the process starts again.

I then might have other processes that sometimes need to tap into the channel and do something else when a write occurs.

``` C#
IChannel<DateTime> _channel;
IObservable<DateTime> _channelObservable;
IObserver<DateTime> _channelObserver;
_channelObservable = _channel.AsObservable();
_channelObserver = _channel.AsObserver();

_channelObservable.Subscribe(dt =>
{
    // Do something 
});

private async void ReadChannel_Click(object sender, RoutedEventArgs e)
{
    var value = await _channel.ReadAsync();
    // Do something
}
```

It appears if the Subscribe code triggers before I get a chance to click the button and when it tries to ReadAsync, the channel has no items and needs to wait for another write to occur.  I'm assuming the Subscribe code is reading the item from the channel when it is processing.

I could create another Subscribe to perform the code that the button click is representing.  However, the code that needs to process can't overlap.  Meaning, it needs to complete before another write occurs and begins the process again.  For example, the code might have async calls, time delays, etc. and I want it to complete before reading and starting the next item read.  Does this make sense?

Any suggestions?

**Comment by stephentoub** [comment]
If I'm understanding your description correctly, you're saying that you have some data coming in, one consumer is always going to do something with the data, but another consumer is only going to be coming along every once in a while, and you'd like for them to have something consume, e.g. always storing the last received item somewhere in case they want to come along and read something?  The difficulty is coming up with a proper retention policy; if you were to store everything "just in case" that second consumer wanted something, you'd have a huge memory leak, so you need to figure out exactly what policy you're trying to enable.  If I'm misunderstanding, please let me know that, too.

**Comment by shaggygi** [comment]
I believe you described it.  I think the best approach would be to have one channel reading the data instead of trying to read and observe the channel at the same time.

I could have just the subscription(s) to observe the channel input.  However, I don't want other events from channel to occur until the normal process is complete as it could interfere with resources (e.g. serial port transmission and such).  That is why I was trying to do both with the channel.

Based on your input, I'm thinking the normal process should...
- Have one channel wait/read from the source.
- Include an observer (separate from the one mentioned in initial post above) the process could OnNext allowing others to subscribe to it if needed.
- Continue on with what the normal process was meant for.
- Return back to channel and wait/read next source coming in.  At this point, there might be something already in the  queue or would have to wait until the next was incoming.

Does this logic seem better?  Thanks again for your help.

**Comment by stephentoub** [comment]
That's one approach.  Another would be to essentially implement a channel that has a store-N-drop-oldest policy built into it, and every time the main reader reads from the main channel, it also writes it to this other special channel for the other consumer to pull from.  Then the logic around overwriting values and synchronizing consumers is consolidated into that special channel.  When i have some time, I can look at adding something along those lines, too.  Thanks.

**Comment by shaggygi** [comment]
Thanks, that would be great!

**Comment by shaggygi** [comment]
@stephentoub I was reviewing this again and I believe your solution would work for what I was trying to accomplish.  For example (assuming the special channel item would eventually be named something better):

```csharp
myChannel.In.LastChannelValueRead.AsObservable().Subscribe(item =>
{
    // Do work...
});
```

This would allow the other consumer(s) to pick up the latest item read from channel.

You could also possibly add AsObservable to the WriteableChannel to trigger on item written.  This assumes reading the written item does not alter the channel buffer for the consumer to read.

```csharp
myChannel.Out.AsObservable().Subscribe(item =>
{
    // Do work...
});
```
