### ISSUE TITLE
Support Uri parsing in InvariantParser.

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/corefxlab#749]

**Comment by jonfortescue** [comment]
Technically supported as of PR #761, but will leave unresolved due to the fact that it's a placeholder method.

**Comment by ahsonkhan** [comment]
@AtsushiKan, was Uri parsing intentionally left out of https://github.com/dotnet/corefx/issues/24607 / https://github.com/dotnet/corefx/pull/25078? Do we plan to add an API in the future?

**Comment by AtsushiKan** [comment]
Uri parsing was never on the table as far as I know.

Something like that should probably go on the Uri class rather than Utf8Parser. Utf8Parser focuses on more fundamental building blocks.

**Comment by KrzysztofCwalina** [comment]
I think we should do something in this space though. Utf8Parser might not be the best place for the API, but today parsing Uri is too expensive. Even worse, the current representation of System.Uri is too expensive (stores UTF16 strings)
