### ISSUE TITLE
API design changes to InvariantParser

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/corefxlab#763]
Based on API review, a few core suggestions were made:
- Rename the `InvariantParser` class
- Remove the `bytesConsumed` parameter and pass `index` by `ref`
- Investigate splitting culture & encoding data
- Rename methods so they are not all one overload of `TryParse` -- instead, have individual methods for `TryParseByte`, etc.
- Rename `utf8Text` parameter to reflect the fact that it can accept any number of encodings

**Comment by KrzysztofCwalina** [comment]
I think these are done
