### ISSUE TITLE
InvariantParser perf investigations

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/corefxlab#766]
- Parsing to long/ulong by creating a local long variable and doing casts may be expensive in some architectures, specifically 32-bit. If it is, we should change this so our APIs are optimized on these architectures. See https://github.com/dotnet/corefxlab/pull/700#discussion_r67569264
- Determine whether `byte?` or `byte=0` + `bool` is more performant for parsing trie
- Checking `MinValue`: See https://github.com/dotnet/corefxlab/pull/762#discussion_r75536675
- Determine whether `List<int>` of pointers or `List<TrieNode>` of nodes is more performant for the parsing trie in `FormattingData`.
- Compare perf to C++ implementations.

**Comment by jonfortescue** [comment]
See https://github.com/dotnet/corefxlab/pull/762#discussion_r75536675.

**Comment by KrzysztofCwalina** [comment]
@AtsushiKan, can you review if any of these are still relevant and either fix or close this issue?
Thanks.

**Comment by ahsonkhan** [comment]
> Parsing to long/ulong by creating a local long variable and doing casts may be expensive in some architectures, specifically 32-bit. If it is, we should change this so our APIs are optimized on these architectures. 

Part of this was fixed in https://github.com/dotnet/corefx/pull/25626.
