### ISSUE TITLE
Implement compile-time construction of the parsing trie

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/corefxlab#767]
Originally this issue was about lazy initialization. However, we have a solution now that preserves the benefits of upfront initialization fast parsing, simpler code) and lazy initialization (fast construction time): we will create a binary file which describes the trie at compile time which will be wrapped into the executable. At runtime, the trie will be constructed in one upfront allocation by reading from the binary file.

**Comment by KrzysztofCwalina** [comment]
Instead of lazy initializing, why don't we: a) store the trie in an array of value type nodes, b) initialize the trie (i.e. the array) from data created at compile time, similarly to how FormattingData initializes the formatting data array (i.e. reads the data from .bin files).

**Comment by jonfortescue** [comment]
Ah, compile-time, not design time. will adjust accordingly.
