### ISSUE TITLE
IFormatter.ResizeBuffer should pass a suggested size

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#778]
It seems kinda odd that ResizeBuffer doesn't pass any arguments. It assumes the underlying formatter knows what to do when it's the caller code that does.

/cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
What do you think it should take and what guarantees it should provide? Would it be just a hint or a hard guarantee?

**Comment by davidfowl** [comment]
It would be a hint. I would be similar to what libuv does this with their OnAlloc API.

**Comment by KrzysztofCwalina** [comment]
fixed in #783
