### ISSUE TITLE
Abstraction for reading that takes multiple buffers into account?

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#782]
Today the `IFormatter` abstraction allows for the underlying implementation to write into multiple spans via `ResizeBuffer` call. It lets the caller expand the underlying buffer as much as it needs to (or allocate more buffers) in order to write payloads. There needs to be a similar abstraction for reading so that if an underlying system stores data in multiple buffers, they can still be read. The invariant parsers all assume that data is all places in a single span but there are cases where this may not be true.

https://github.com/davidfowl/Channels/blob/master/samples/Channels.Samples/Formatting/ReadableBufferExtensions.cs#L12

The channel implementation stores a linked list of 4K buffers and abstracts that behind a ReadableBuffer abstraction (which is really just an `IEnumerable<Span<byte>>` https://github.com/davidfowl/Channels/blob/master/src/Channels/BufferSpan.cs). I would love to use these to build higher level APIs without reimplementing everything on top of `ReadableBuffer`. 

Another option is to copy but meh 😄 

/cc @KrzysztofCwalina @jonfortescue

**Comment by KrzysztofCwalina** [comment]
We need a higher level helpers that: a) try to parse from a single buffer, b) if the parse fails, they would copy some bytes from two adjacent buffers, and then parse. 

If we try make the primitive parsers multi-buffer aware, they will become much slower, and I don't think it's worth it for the rare cases of parsed bytes straddling two buffers.

**Comment by davidfowl** [comment]
> If we try make the primitive parsers multi-buffer aware, they will become much slower, and I don't think it's worth it for the rare cases of parsed bytes straddling two buffers.

That's fair. I'll add a bunch of helpers that do that.

**Comment by davidfowl** [comment]
https://github.com/davidfowl/Channels/blob/master/src/Channels.Text.Primitives/ReadableBufferExtensions.cs#L30

**Comment by davidfowl** [comment]
@KrzysztofCwalina been thinking about this and I think we should revisit.

**Comment by mgravell** [comment]
additional thought that came up when I was updating  a sample to use the current Channels API : the lack of core-clr Decoder.Convert support for pointer-based parameters makes parsing multiple segments impossible to do if those segments aren't backed by arrays, without involving an additional copy-to-array. Real world example of why one might need to do this - the sample I'm working on is web-sockets (RFC6455) which can involve parsing strings in multiple non-contiguous frames on the wire (with headers and control-frames in-between); the specification makes it explicit (§5.6) that a single utf-8 character is allowed to straddle two data frames. That means that when assembling them, it is necessary to be able to process that.

Not 100% related to "this" - but possibly part of a family of scenarios that should be considered in any changes.

**Comment by KrzysztofCwalina** [comment]
I merged ReadOnlyBytes and BytesReader to represent and read multi-segment buffers.

**Comment by ahsonkhan** [comment]
@davidfowl, @KrzysztofCwalina - can we close this issue?

**Comment by davidfowl** [comment]
Yep!
