### ISSUE TITLE
AsciiString Type

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#792]
To match `Utf8String`. Somethings are Ascii only (like headers, raw urls etc) and should only be ascii and not accept > 0x7f bytes (also probably not < 32?)

There are some ops that you can do when you know its just a bunch of bytes and doesn't have any surrogate pairs.

Should give compile time error for constant assignment with a string constant that contains > 0x7f bytes and a check on conversion from regular string, utf8 string, and byte at runtime if > 0x7f bytes? (So its a "validated to only be ascii" string)

**Comment by mattwarren** [comment]
To work with all possible HTTP Headers you'd actually need to use `ISO-8859-1 (Latin-1)` not `ASCII`, from [RFC 5987](https://tools.ietf.org/html/rfc5987#section-1)

> By default, message header field parameters in HTTP ([RFC2616](https://tools.ietf.org/html/rfc2616))   messages cannot carry characters outside the ISO-8859-1 character set ([ISO-8859-1](https://tools.ietf.org/html/rfc5987#ref-ISO-8859-1)). 

Although `ISO-8859-1 (Latin-1)` takes up the same space as `ASCII` so it's still a saving on `UTF-8`.

**Comment by benaadams** [comment]
Updated to ascii in [RFC 7230 3.2.4. Field Parsing](https://tools.ietf.org/html/rfc7230#section-3.2.4)

> Historically, HTTP has allowed field content with text in the ISO-8859-1 charset [ISO-8859-1], supporting other charsets only through use of [RFC2047] encoding.  In practice, most HTTP header field values use only a subset of the US-ASCII charset [USASCII]. Newly defined header fields SHOULD limit their field values to US-ASCII octets.  A recipient SHOULD treat other octets in field content (obs-text) as opaque data.

**Comment by mattwarren** [comment]
> Updated to ascii in RFC 7230 3.2.4. Field Parsing

Ahh my bad, didn't realise I was looking at an old spec

**Comment by benaadams** [comment]
Its because Latin-1 conflicts with Utf8 whereas Ascii is compatible (so you can cross detect between the two)

**Comment by KrzysztofCwalina** [comment]
I wonder if this could not be addressed with a setting/mode/parameter on Utf8String (possibly renamed) without introducing a new type. There are so many variants of encodings with byte code units.
Also, today, we don't do any validation of the Utf8String contents (when it's created). Would we do any such validation in the AsciiString?

**Comment by benaadams** [comment]
> There are so many variants of encodings with byte code units.

The relationship of ASCII with all the other encodings is special; in that isn't not just another byte type encoding; but is the basis for all of them (EBCDIC etc aside) and it has fast-path operations (uppercase, lowercase, insensitive compare); as well as being a constraint on many protocol comms.

> we don't do any validation of the Utf8String contents (when it's created). Would we do any such validation in the AsciiString?

Raw byte or span<byte> .ctor probably should follow that convention. However like utf8string validates for a narrowing conversion ([String -> Utf8String](https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Utf8/System/Text/Utf8/Utf8String.cs#L67-L70)); the validation should be on the narrowing cast Utf8String -> AsciiString and the conversion String -> AsciiString.

Having the AsciiString type would allow the ascii only constraint to be type system specified; rather than runtime checked. If you passed an AsciiString no validation would take place; if you passed Utf8String or String then the (ex?)implicit operator would be doing the validation.

Utf8String and AsciiString should probably have a `bool TryParse(ReadOnlySpan<byte>, out ...)` method that does validation?

**Comment by KrzysztofCwalina** [comment]
@benaadams, I would like to start with:
1. Adding IsAscii to Utf8String
2. Adding fast-path methods operating on Utf8String that assume ASCII.

If it's not enough, we can add AsciiString later. 

The main reason I am pushing back is that there is already lots of concern (from various people) about the fact that we are introducing Utf8String to .NET. People still have scars from battling C++ strings.

**Comment by benaadams** [comment]
Well Utf8Sting is a must have and AsciiString is a nice to have; so if it increases the resistance to Utf8String, then its a no go ;-)

Will close.

**Comment by KrzysztofCwalina** [comment]
exactly my thinking :-)
