### ISSUE TITLE
System.Buffers.Experimental: Cannot reuse a returned buffer

### ISSUE THREAD

**Issue by vlabrecque** [dotnet/corefxlab#807]
Returning a Span to the pool leads to an 0-length NativeBuffer (the native buffer is explicitly created that way in NativeBufferPool:Return) being returned to the bucket.   The next time this buffer is to be used (by another call to Rent on the same bucket), it will create a 0-length Span.  Which doesn't work.

Easy repro steps:
    let pool = System.Buffers.NativeBufferPool.Shared
    let u = pool.Rent 10 in pool.Return u
    let v = pool.Rent 10 in pool.Return v  // v.Length=0, and the .Return() call crashes

I think the bucket should just forcefully set the NativeBuffer's length before returning it.

**Comment by KrzysztofCwalina** [comment]
@sokket, would you have time to fix this?

**Comment by sokket** [comment]
@KrzysztofCwalina unfortunately my plate is full with infrastructure work right now; I can take a look at it after all that has completed if you want, but that won't be for ~2ish weeks.

**Comment by KrzysztofCwalina** [comment]
@vlabrecque thanks for pointing this out to us.
