### ISSUE TITLE
Implement proper NativeBufferPool

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#809]
- needs to support different bucket sizes (so it does not waste space when renting 100B buffers)
- needs to support renting buffers larger than those stored in the pool
- needs to support renting when all buffers are already rented
- needs to do better with concurrency (no global lock, no array of locks/free-rented bits)

**Comment by davidfowl** [comment]
Inspiration:

- https://github.com/netty/netty/issues/3910#issue-90391403

**Comment by benaadams** [comment]
If you want to go wild, can do a stack based MCS lock

Had [one here but its probably buggy](https://github.com/benaadams/KestrelHttpServer/blob/6aa2a562d036065aa63f5df2c8e2f8bb0c0930b9/src/Microsoft.AspNetCore.Server.Kestrel.Pools/Infrastructure/ComponentPool.cs) :smile:

**Comment by benaadams** [comment]
Also you can't sleep or yield on the MCS lock since its a fair lock and throughput dies if you do.
