### ISSUE TITLE
Samples for how to target .NET Core with MSBuild are missing

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/corefxlab#810]
It looks like #798 removed the samples that showed how to [target .NET Core with MSBuild](https://github.com/dotnet/corefxlab/tree/0c7ade4bc70a715cd9402ca32cb9b76a578f4511/samples/NetCoreSample).  Was this intentional?  Is there a replacement for these?  The link to CoreApp in .NET documentation for [Using MSBuild to build .NET Core projects](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/target-dotnetcore-with-msbuild) is now broken.

cc @weshaggard @davidfowl

**Comment by davidfowl** [comment]
Very. People should really be using the template + the upcoming conversation tool that will migrate them back to msbuild.

IMO this repo isn't the place for those "samples"

**Comment by davidfowl** [comment]
Oops, just read that the docs link there. Can we point to a specific commit sha or branch.

**Comment by mellinoe** [comment]
> IMO this repo isn't the place for those "samples"

Why not? They were extremely useful and helped a ton of people who referenced them. We shouldn't remove them unless there's equivalent documentation elsewhere.

**Comment by davidfowl** [comment]
Helpful doesn't have anything to do with where they live. They could be literally anywhere. Corefxlab is an experimental repository with things that may or may not end up in corefx. Show me other things from this repository documented on the official dotnet docs

**Comment by weshaggard** [comment]
@davidfowl while I agree some of these should probably be in some doc repo, I don't agree they shouldn't be here. As you say corefxlab is for experimental stuff and those samples are just that until we get our official tooling story figured out and shipped. So I don't have any issue with them being in this repo, were they causing some issue?

@richlander @terrajobst do we have another repo that would be a better place for these samples?

**Comment by benaadams** [comment]
There is a https://github.com/dotnet/dotnet-cli-samples repo that looks very lonely, might be a good place?

**Comment by dls314** [comment]
I think that the instructions on [Using MSBuild to build .NET Core projects](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/target-dotnetcore-with-msbuild) are otherwise wrong at the moment (https://github.com/aspnet/Tooling/issues/749 and comments on the docs page).

**Comment by davidfowl** [comment]
> @davidfowl while I agree some of these should probably be in some doc repo, I don't agree they shouldn't be here. As you say corefxlab is for experimental stuff and those samples are just that until we get our official tooling story figured out and shipped. So I don't have any issue with them being in this repo, were they causing some issue?

I was cleaning up the inconsistencies in the repository. There were demos and samples. Didn't see why we seemingly had `project.json` based csproj samples that weren't really using anything in corefxlab itself (like all the other samples were doing). They kinda just "existed" there, and now I know we had our official docs pointing to them.

**Comment by KrzysztofCwalina** [comment]
Yeah, I think samples repo is a better location.

**Comment by weshaggard** [comment]
Given that these links are in various places I would like to add these samples back into corefxlab.

**Comment by KrzysztofCwalina** [comment]
Sounds good.

**Comment by terrajobst** [comment]
> Given that these links are in various places I would like to add these samples back into corefxlab.

Any reason we can't move them to CoreFX? I agree with @davidfowl and @KrzysztofCwalina that the content really doesn't belong here.

**Comment by weshaggard** [comment]
With commit https://github.com/dotnet/corefxlab/commit/2eee4ff79dd6e5c08f151e3daa612725594e1b49 I've added back the samples. We can delete them again once we have an official tooling story released.
