### ISSUE TITLE
Port WebEncoders to use new Span APIs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#813]
https://github.com/dotnet/corefx/tree/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web

@rynowak showed interest in doing this.

@KrzysztofCwalina do you have any thoughts on this?

**Comment by KrzysztofCwalina** [comment]
We should once Span<T> is "stable"/productized

For now, we should just write extensions that consume spans.

**Comment by ahsonkhan** [comment]
cc @GrabYourPitchforks

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina, @muratg, @joshfree  - do we need this for 2.1?

**Comment by muratg** [comment]
@ahsonkhan this is more @rynowak and @Eilon territory... folks?

**Comment by Eilon** [comment]
I assume no APIs would change (except maybe adding new ones), but there are no specific requirements from ASP.NET Core 2.1 as far as I know. However, if new more-efficient APIs are available, we could consider using them opportunistically.

**Comment by GrabYourPitchforks** [comment]
Re-pathing to future since there's no specific request.

**Comment by GrabYourPitchforks** [comment]
Tracking this in https://github.com/dotnet/corefx/issues/27253 since that's the correct repo.
