### ISSUE TITLE
Move Bytes to System.Slices?

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#815]
Not sure System.Buffers.Experimental makes sense.

**Comment by KrzysztofCwalina** [comment]
Where would you put it in? Ultimately, it should be in System.Buffers, but for now?

**Comment by davidfowl** [comment]
Why System.Buffers?

**Comment by KrzysztofCwalina** [comment]
Where do you think it should be?

System.Buffers is about buffer pooling. Bytes is a promise of a buffer.
