### ISSUE TITLE
Support Span<byte>in common APIs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#816]
I'm just starting this list to keep track of APIs as I encounter them
- [ ] - HashAlgorithm.ComputeHash
- [ ] - System.Text.Encoding.{Blah}Encoding (utf8, ascii, unicode etc).
- [ ] - System.Text.Encodings.Web (tracked here https://github.com/dotnet/corefxlab/issues/813)
- [ ] - WebDecoders - These exists today in several forms but none use a common exchange type like `Span<byte>`.
- [x] - Base64 - https://github.com/dotnet/corefxlab/tree/master/src/System.Binary.Base64
- [ ] - Primitive parsers - (will list out the types needed)
- [ ] - ~~Stream APIs (not sure about this one) 😄~~
- [ ] - ~~Socket APIs~~

**Comment by benaadams** [comment]
Stream ;-)

**Comment by mgravell** [comment]
`SocketAsyncEventArgs.SetBuffer`

**Comment by mgravell** [comment]
@benaadams  but so many `Stream` implementations that I just can't see how that could be done in a way that  isn't "get the array from the span and call the old method, oops there's no array in the span, so we need to allocate and copy" - and that is **before** issues like `BeginRead` / `BeginWrite`, which would need to store state on the heap, which can't be done for span

**Comment by benaadams** [comment]
@mgravell something like https://github.com/dotnet/corefxlab/pull/817

BeginRead / BeginWrite were from a less civilised time...

**Comment by mgravell** [comment]
- [ ] not just `Encoding`; also `Encoder`/`Decoder`; need an API that allows us to work when we need multiple input/output buffers for the same logical data including tracking state between calls for multi-byte characters, which is what `Encoder` and `Decoder` bring to the party

**Comment by mgravell** [comment]
- [ ] RandomNumberGenerator.GetBytes

**Comment by KrzysztofCwalina** [comment]
done
