### ISSUE TITLE
Broken pool due to error in UVBuffer

### ISSUE THREAD

**Issue by Nomad1** [dotnet/corefxlab#820]
@KrzysztofCwalina 
I took a look at [Buffer.cs](
https://github.com/dotnet/corefxlab/blob/master/src/System.Net.Libuv/System/Net/Libuv/Buffer.cs) and pretty sure below code does not work and even more, it is tempering BufferPool and memory usage:
```
            internal void Dispose()
            {
                unsafe
                {
                    Length = 0;
                    Buffer = IntPtr.Zero;
                    FreeBuffer(new Bytes((byte*)Buffer.ToPointer(), (int)Length));
                }
            }
```
You are always submitting zeroes to FreeBuffer method. I'd suggest you to call it in the first place :)

**Comment by KrzysztofCwalina** [comment]
Yeah, this is what happens when you (I) merge code without having test coverage. 

Thanks for pointing this out. I filed an issue (#822) to add proper tests.

**Comment by KrzysztofCwalina** [comment]
fixed, hopefully
