### ISSUE TITLE
Add tests for libuv component

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#822]

**Comment by grahamehorner** [comment]
I'm happy to pick this up as I'm also doing some Libuv UDP work

**Comment by KrzysztofCwalina** [comment]
Ideally, we would have a raw libuv library which would be used by pipelines.

The problem is that it's much more difficult/costly to design a general purpose library like that, than just use libuv as an implementation detaail of pipelines.

But, if you wanted to work on the libuv library, and make it into a nice reusable component, it would be great and I think @davidfowl would like to use it (confirm?)

BTW, the main things I think the library needs:
1. tests
2. make it non allocating, i.e. I am not convinced UVstreams should be classes with inheritance chain. I was hoping to turn them into simple struct handles.
3. We need to make it multithreaded (somehow). There are many ideas for how it could work, none of the great.
4. The APIs support sockets only. They should support other async concepts (like libuv): file i/o, timers, etc.

**Comment by ahsonkhan** [comment]
We removed Libuv as part of https://github.com/dotnet/corefxlab/pull/2244. Closing this issue.
