### ISSUE TITLE
Make IFormatter the more formal replacement for a writing abstraction

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#824]
IFormatter shouldn't be the replacement for just writing text, instead, it should be the exchange type for writing arbitrary things (text, binary etc).

As such, the `IFormatter` (which is a strange name BTW) should not have encoding on it since that's text specific. System.Text.Formatting can have the text based extension methods and System.Binary.Formatting can have the binary formatting methods. As for where the EncodingData should go... maybe we need derived classes/interfaces for text based formatting.

**Comment by DamianEdwards** [comment]
#816?

**Comment by davidfowl** [comment]
Nope, this is a corefxlab specific thing, we need a method here https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Formatting/System/Text/Formatting/IFormatterExtensions.cs that can append a span.

**Comment by davidfowl** [comment]
Thinking more about this, I think we need equivalent binary formatting extensions on `IFormatter` and `IFormatter` needs to be separate from System.Text.*.

**Comment by davidfowl** [comment]
Not sure what to do about encoding data though.

**Comment by KrzysztofCwalina** [comment]
Yeah, I would like to have someling like:
1. IStream (IFormatter without text related APIs)
2. IFormatter extending it.

I also think IStream could be unified with some abstractions in Channels, e.g. IWritableBuffer.

**Comment by davidfowl** [comment]
@KrzysztofCwalina yes!

**Comment by KrzysztofCwalina** [comment]
Fixed by #845
