### ISSUE TITLE
Endian read/write API; incomplete, suboptimal; not overly useful

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#828]
Problems with `BigEndianReader`/`BigEndianWriter` in `System.Binary`:

- little-endian isn't considered at all - assumes caller will just use native here? but assumes caller is little-endian
- big endian doesn't check CPU architecture to optimize
- the fact that they are  extension methods is hella awkward; it is all well and good having `using BigEndian` to get `ReadInt16`, but  what if I also need to do *little*-endian reads/writes at  the same time? (yes, I've had to do this - in particular when writing code to change data formats) - if I add  `using LittleEndian` (just imagine it exists... it doesn't), I now have ambiguous name collisions
- inefficient repeated indexer usage
- limited type support / not paired read vs write - only 1 method in `BigEndianWriter`

In the current state, it is of limited use; however, as an option, all the relevant options can be provided with minimal code quite easily, using existing code; for example (from "Channels"):

        /// <summary>
        /// Writes a structure of type T to a span of bytes.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteBigEndian<[Primitive]T>(this Span<byte> span, T value) where T : struct
            => span.Write(BitConverter.IsLittleEndian ? Reverse<T>(value) : value);

        /// <summary>
        /// Writes a structure of type T to a span of bytes.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteLittleEndian<[Primitive]T>(this Span<byte> span, T value) where T : struct
            => span.Write(BitConverter.IsLittleEndian ? value : Reverse<T>(value));

        /// <summary>
        /// Reads a structure of type T out of a span of bytes.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static T ReadBigEndian<[Primitive]T>(this Span<byte> span) where T : struct
            => BitConverter.IsLittleEndian ? Reverse<T>(span.Read<T>()) : span.Read<T>();

        /// <summary>
        /// Reads a structure of type T out of a span of bytes.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static T ReadLittleEndian<[Primitive]T>(this Span<byte> span) where T : struct
            => BitConverter.IsLittleEndian ? span.Read<T>() : Reverse<T>(span.Read<T>());

(I won't copy out `Reverse<T>` here, but it isn't  complex, and is JIT optimized, etc)

[here](https://github.com/davidfowl/Channels/blob/master/src/Channels/DefaultReadableBufferExtensions.cs) and [here](https://github.com/davidfowl/Channels/blob/master/src/Channels/DefaultWritableBufferExtensions.cs)

---

The names here kinda suck; another option is

    static class BigEndian {
        public void Write*(...);
        public Whatever Read*(...);
    }

    static class LittleEndian {
        public void Write*(...);
        public Whatever Read*(...);
    }

with usage like:

    int  i = BigEndian.ReadInt32(span); // if you hate generics
    int  j = BigEndian.Read<int>(span); // if you love generics

but arguably the extension methods are clearer, and certainly more comparable  to the `Read<T>` / `Write<T>` in `SpanExtensions`.

**Comment by KrzysztofCwalina** [comment]
Yeah. Definitely. That's the plan. The current library is mainly a placeholder and a draft of the APIs. There was somebody who wanted to work on it, but then it did not pan out.

**Comment by mgravell** [comment]
@KrzysztofCwalina  well, we've had to do a **lot** of thinking and coding in this area for "Channels"; hopefully these downstream use-cases will help to find an API that works. But IMO the existing placeholder is harmful :(
