### ISSUE TITLE
Remove IEnumerable<T> from Spans.

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#838]
Since Span<T> will be stack-only, it cannot implement this interface.

**Comment by adamsitnik** [comment]
should struct enumerators be removed as well?

**Comment by KrzysztofCwalina** [comment]
I think we can (and should) leave these.

**Comment by omariom** [comment]
What do you  think about this?
```C#

public static IEnumerable<T> AsEnumerable(this ReadOnlySpan<T> span)
{
   foreach (T item in span)
   {
      yield return item;
   }
}
```

**Comment by KrzysztofCwalina** [comment]
The compiler expands it to something that captures the span in a class, doesn't it?

**Comment by omariom** [comment]
It does.. I was thinking about LINQ, but looks like `ToArray()` is the only way to plug it into LINQ pipeline
