### ISSUE TITLE
Alignment and 2 GiB overflow issues in Span<T>.TryCopyTo

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefxlab#848]
Only affects the `IsPrimitiveValueType<T>` case;

- overflow for large `src.Length` and non-trivial `T`; might need to loop, since `cpblk` is limited to `uint` sizes (thus is not quite the same issue as #846)
- `CopyBlock` assumes that the pointers are aligned; otherwise, `cpblk` needs the `unaligned` prefix

(also impacts `ReadOnlySpan<T>`)

**Comment by benaadams** [comment]
Raised issue for unaligned https://github.com/dotnet/corefx/issues/12243
