### ISSUE TITLE
Optional parameter

### ISSUE THREAD

**Issue by Allov** [dotnet/corefxlab#857]
Is it possible to support optional parameter using `System.CommandLine`?

example:

``` bash
myapp mycommand [could provide a parameter or not]
```

To be clear, I'm not talking about `DefineOption()` but about `DefineParameter()`.

**Comment by bricelam** [comment]
It is possible. If the parameter isn't specified, the `value` won't be set.

**Comment by alexperovich** [comment]
This question has been answered. If you encounter problems feel free to reopen.
