### ISSUE TITLE
Add Fast SpanExtensions overloads operating on bytes

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#867]
e.g. SequenceEqual

**Comment by davidfowl** [comment]
Doesn't BlockEquals do this?

**Comment by KrzysztofCwalina** [comment]
Maybe, the point is that we should measure perf of some of the generic operations and see if specialized byte overload would improve perf.

**Comment by KrzysztofCwalina** [comment]
completed by @AtsushiKan
