### ISSUE TITLE
Alternative string formatting design

### ISSUE THREAD

**Issue by MikePopoloski** [dotnet/corefxlab#88]
I'd be interested in hearing your thoughts on a library I've been working on that's similar in spirit to what you're doing here: https://github.com/MikePopoloski/StringFormatter

Mostly I needed a way to do formatting without allocations during my game loop. I think what I came up with is a pretty nice API.

**Comment by KrzysztofCwalina** [comment]
Ah, nice! It would be great if you had runtime perf results so we could compare. Feel free to use my tests for that. My APIs are quite fast for invariant cultures, but I am not super happy with the perf of cuture specific formatting.
