### ISSUE TITLE
Memory<T> should implement IReadOnlyList<T>

### ISSUE THREAD

**Issue by smmalis37** [dotnet/corefxlab#903]
I would love to use ReadOnlySpan<T> in a project I'm working on as it would simplify a lot of code, however in order for it to be useful for us it would need to implement IReadOnlyList, as that is how all of our data is passed around. This should be a minimal amount of work, as the interface only mandates an indexer and a Count property, and both of those already have been implemented.

**Comment by KrzysztofCwalina** [comment]
Span\<T\> will be a stack only type. See https://github.com/dotnet/corefxlab/blob/master/docs/Span.md.
In practice it means it won't be possible cast it to an interface (as this boxes and so puts the instance on the heap). Maybe Memory\<T\> could implement some interfaces, but I would have to first understand what code you were hoping to simplify with Span?

**Comment by smmalis37** [comment]
Essentially we're constructing a list of objects in C++ code and then accessing this list on the C# side. Since we don't want to duplicate all of these objects (as the lists can be quite large and memory consumption is a concern) we've created a type that acts similarly to the unsafe constructor on Span<T> to access the items without duplicating them and handle type safety. There are some other lists we create on the C# side, and so to make consumption of our API simpler we just expose everything as an IReadOnlyList (since users shouldn't be modifying what we expose as well).

**Comment by KrzysztofCwalina** [comment]
Interesting.
Initially I thought [Memory\<T\>](https://github.com/dotnet/corefxlab/blob/master/tests/System.Slices.Tests/MemoryTests.cs) is the type you could use, but I am not sure we want to implement the interface on Memory either. I will think about yous scenario though once the design of Memory\<T\> gets clarified a bit more.

**Comment by KrzysztofCwalina** [comment]
Changing title to ReadOnlyMemory<T>. Spans won't be able to implement any interface. Memory type will be able to. We need to decide if we want to do it.

**Comment by smmalis37** [comment]
That'd work fine for us as long as there's a constructor that takes a pointer and a count and I can use it to index into it like an array. The reason I initially looked at ReadOnlySpan was because of its `public unsafe ReadOnlySpan(void* ptr, int length)` constructor. I don't see a similar constructor on ReadOnlyMemory?

**Comment by KrzysztofCwalina** [comment]
OwnedNativeMemory<T> can be created out of ptr and len, and then used as follows:
https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Experimental.Tests/MemoryTests.cs#L47

**Comment by smmalis37** [comment]
That would be perfect then. Thanks for keeping us in mind!

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, can you triage this issue? I would like to remove all System.Memory issues from corfxlab. thanks.

**Comment by joshfree** [comment]
Moving this issue to the corefx repo for future consideration and tracking

https://github.com/dotnet/corefx/issues/28282
