### ISSUE TITLE
BufferPool should be IBufferPool<T>

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#907]
Its not particularly doing anything as an abstract class

If it was `IBufferPool<T>` then you could have a single buffer pool that handed out multiple types using the same memory.

e.g. 

```csharp
public class  NativeBufferPool 
    : IBufferPool<byte>, IBufferPool<sbyte>, 
      IBufferPool<char>, IBufferPool<short>, IBufferPool<ushort>
```

**Comment by omariom** [comment]
Isn't it job of `Span` to handle different blittable types?

**Comment by benaadams** [comment]
Its a more general type not sure why it needs the Span casts?

Else you'd be doing 
```csharp
var buffer = NativeBufferPool.Rent(length * sizeof(long));
var span = buffer.Span.Cast<byte, long>();
```

Additionally would mean `Memory<T>` is always `Memory<byte>` if you wanted to use any of the built in pooling and you'd always have to cast through span?

**Comment by benaadams** [comment]
e.g. if you are working with `Memory<long>` and `Span<long>` why not use pools that give you them directly?

**Comment by KrzysztofCwalina** [comment]
I worry about the following:
1. How will implementers of the interface decide which constructed types to implement?
2. Will implementing many of these interfaces significantly increase code size, especially for AOT runtimes.
3. It's hard to evolve interfaces (add members after they ship). Is this feature worth the risk that we won't be able to evolve the interface once we ship stable.

**Comment by benaadams** [comment]
@KrzysztofCwalina 

1. Depends what they need; you've created a protected primitive pool that works over multiple memory types; its bigger than Span and Memory over bytes. For Managed it just needs to flow the T to the ArrayPool.

2. Not significantly, for multiple in the example above its just multiplying the length by sizeof in Rent; the actual Rent and Returns can call to a non-generic method. However if only `IBufferPool<byte>` is required that is all that needs to be implemented - its merely opening up the possibilities.

3. have a different hierarchy in https://github.com/dotnet/corefxlab/pull/909#issuecomment-255181177 are only 2 methods Rent and Return (return being an explicit implementation). 

Arguably adding new methods is a new interface and it can either be implemented via interface inheritance where they make sense or an entirely parallel interface where there are not cross cutting concerns (e.g. blocking and async in Streams are two parallel interfaces and auto implementing them on the base class has only been a source of pain other than for MemoryStream) or via extension methods where its a recomposition of the current methods?

**Comment by davidfowl** [comment]
I think BufferPool should be non generic and hard coded to byte 😄 .

**Comment by benaadams** [comment]
They are basically generic pools; could happy switch to `MyStuct` types

**Comment by benaadams** [comment]
Gone next level... will open better issue
