### ISSUE TITLE
Expose Id as protected property on OwnedMemory<T>

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#914]
So I don't have to keep a list of DisposableReservations when I increment and decrement the ref count.  See https://github.com/davidfowl/Channels/blob/3e0a4e7cff81992714b2e812e309cf7ac7ebb443/src/Channels/ReferenceCountedBuffer.cs

OR:

```C#
public abstract class OwnedMemory<T> : IDisposable, IKnown
{
   protected void AddReference() { AddReference(_id); }
   protected void RemoveReference() { RemoveReference(_id); } 
}
```

That would be great. That way if I'm implementing `OwnedMemory` I can get direct access to AddRef/ReleaseRef

**Comment by KrzysztofCwalina** [comment]
this is done.
