### ISSUE TITLE
The reference count of OwnedMemory  needs to start at 1

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#916]
Imagine I used an implementation of `OwnedMemory<T>` that tried to return data to the pool on ref count 0.

```C#
OwnedMemory<byte> data = BufferPool.Rent(1024); // ref count 0
using(data.Reserve())  // ref count 1
{
} // ref count 0 tries to return to pool but it's premature
DoSomethingWithData(data); // BOOM
```

**Comment by davidfowl** [comment]
I had to work around it:

https://github.com/davidfowl/Channels/blob/760d62d89cbf7bcbd7a7d01c29b61575b14e2ac9/src/Channels/ReferenceCountedBuffer.cs

**Comment by KrzysztofCwalina** [comment]
Yeah, we should fix that, i.e. enable your scenario. But I am not sure starting with ref count 1 solves the problem. You then have the problem of having to decrement the ref count so it does reach zero.

**Comment by KrzysztofCwalina** [comment]
Would the following work:
```c#
class Buffer : OwnedMemory<byte>
{
    DisposableReservation _reservation;

    protected override void OnReferenceCountChanged()
    {
        _reservation = Memory.Reserve();
    }

    protected override void DisposeCore()
    {
        _reservation.Dispose();
    }
```

**Comment by davidfowl** [comment]
Not a fan of this. Changing the ref count to 1 works as well right? 

You also need to call reserve on initialize as well.

**Comment by KrzysztofCwalina** [comment]
Why "not a fan of this"?
Also, I am not sure if changing ref count to 1 works. How will you decrements it? Currently DisposableReservation is the way to decrements it.

**Comment by benaadams** [comment]
`OwnedMemory<T>` is disposable? That should decriment it to zero

**Comment by KrzysztofCwalina** [comment]
Then the "BOOM" from @davidfowl code sample at the top of this issue would still BOOM!.

**Comment by benaadams** [comment]
Would be ok?
```csharp
OwnedMemory<byte> data = BufferPool.Rent(1024); // ref count 1
using(data.Reserve())  // ref count 2
{
} // ref count 1
DoSomethingWithData(data); // OK
```

**Comment by davidfowl** [comment]
I keep wondering if there are 2 different reasons you want to ref count:

1. Explode for premature disposal.
2. Automatic disposal when ref count gets to 0.

Today OwnedMemory<T> does 1 and 2 can be built on top today (https://github.com/davidfowl/Channels/blob/20d2a4721f8b3f0dc575d10d7c1c825c02c7edb8/src/Channels/ReferenceCountedBuffer.cs) but I'm keeping track of another reference count which is less than ideal. Seems like these 2 things fight each other, but ideally the `BufferPool` abstraction would return an `OwnedMemory<byte>` that cared about 2.

The other thing that `OwnedMemory<T>` does (which is nice) is mark a piece of memory as *dead* when a call to Dispose happens. I'd like an abstraction where Dispose meant decrement the ref count and if it's 0 Dispose the object.

**Comment by KrzysztofCwalina** [comment]
OK, I see. I think this would work.
BTW, I added an API to manually control the refcount in the subclasses of OwnedMemory, and so I think the scenario is enabled now.

**Comment by KrzysztofCwalina** [comment]
@davidfowl, yeah this is a good observation. And this is why I felt a bit uneasy about #1. But I think we can make it work.

**Comment by benaadams** [comment]
For https://github.com/dotnet/corefxlab/pull/915 I went for this Disposal pattern

```csharp
public void Dispose()
{
	Dispose(true);
}

~OwnedMemory()
{
	Dispose(false);
}

internal virtual void Dispose(bool disposing)
{
	if (disposing)
	{
		ThrowIfDisposed();

		var count = Interlocked.Decrement(ref _references);
		OnReferenceCountChanged(count);
		if (count == 0)
		{
			_owner?.Deallocate(this);

			DisposeCore(); // Derived classes clear up

			Clear(); // Drop private vars

			_id = InitializedId;

			GC.SuppressFinalize(this);
		}
		else if (count < 0)
		{
			throw new InvalidOperationException("Owned Memory over disposed");
		}
	}
	else
	{
		Clear();
        // Throw only in debug?
		throw new InvalidOperationException("Owned Memory not fully disposed");
	}
}
```
Then added the extra checks to the other methods
```csharp
protected bool TryGetArrayCore(out ArraySegment<T> buffer)
{
	ThrowIfDisposed();
```

**Comment by KrzysztofCwalina** [comment]
@934 shows how to implement auto-dispose owned memory.
