### ISSUE TITLE
Pools should test Return via ownership not via casting

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#919]
Currently the pools test whether to accept an object on whether it casts; they should accept based on them being the issuing pool

**Comment by ahsonkhan** [comment]
@benaadams, is this issue still relevant? https://github.com/dotnet/corefx/blob/8e53c7efea4efd28ba9d111dd4e70e3ca2f987f3/src/System.Memory/src/System/Buffers/MemoryPool.cs#L10
