### ISSUE TITLE
OwnedMemory<T> should be more abstract

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#930]
After a discussion today with @KrzysztofCwalina we'd like to model `OwnedMemory<T>` so that ref counting can be optional. The underlying abstraction just needs operations that represent `Reserve()` and `Dispose()`. Here's a proposal:

```C#
public abstract class OwnedMemory<T> : IDisposable
{
    private long _id;
    private static long _nextId = InitializedId + 1;
    private const long InitializedId = long.MinValue;

    public Memory<T> Memory => new Memory<T>(this, _id);
    public Span<T> Span => GetSpanCore();

    public virtual void Dispose()
    {
        _id = InitializedId;
        DisposeCore();
    }

    public bool IsDisposed => _id == InitializedId;

    public virtual void Initialize()
    {
        if (!IsDisposed)
        {
            throw new InvalidOperationException("this instance has to be disposed to initialize");
        }
        _id = Interlocked.Increment(ref _nextId);
    }

    public virtual int Length => Memory.Length;

    protected long Id => _id;

    // abstract members
    protected abstract Span<T> GetSpanCore();
    protected abstract void DisposeCore();

    protected abstract bool TryGetArrayCore(out ArraySegment<T> buffer);

    protected abstract unsafe bool TryGetPointerCore(out void* pointer);

    public abstract OwnedMemory<T> Reserve();

    // used by Memory<T>
    internal unsafe bool TryGetPointer(long id, out void* pointer)
    {
        if (_id != id) throw new ObjectDisposedException(nameof(Memory<T>));
        return TryGetPointerCore(out pointer);
    }

    internal bool TryGetArray(long id, out ArraySegment<T> buffer)
    {
        if (_id != id) throw new ObjectDisposedException(nameof(Memory<T>));
        return TryGetArrayCore(out buffer);
    }

    internal Span<T> GetSpan(long id)
    {
        if (_id != id) throw new ObjectDisposedException(nameof(Memory<T>));
        return GetSpanCore();
    }

    // protected
    protected OwnedMemory()
    {
        _id = InitializedId;
        Initialize();
    }
}
```

```C#
public abstract class ReferenceCountedMemory<T> : OwnedMemory<T>
{
    private int _references;

    public override void Initialize()
    {
        _references = 1;
    }

    public override OwnedMemory<T> Reserve()
    {
        Interlocked.Increment(ref _references);
        return this;
    }

    public override void Dispose()
    {
        if (Interlocked.Decrement(ref _references) == 0)
        {
            base.Dispose();
        }
    }
} 
```

You can imagine the buffer pool only having lease since the underlying buffer would just be returned when disposed:

```C#
public abstract class BufferPool<T>
{
    public abstract OwnedMemory<T> Lease(int minimumSize);
}
```

The pool could choose to return an implementation of `OwnedMemory<T>` that ref counts or copies on `Reserve()` and the caller wouldn't have to know the difference.

`Memory<T>.Reserve()` would just delegate to `OwnedMemory<T>.Reserve()` and would update it's backing representation of the `_owner` property.

/cc @jkotas @KrzysztofCwalina @benaadams

**Comment by benaadams** [comment]
Any reason the hot paths have all gone virtual again?

**Comment by KrzysztofCwalina** [comment]
I think this is a good scenario to enable, but I don't think it will work. When a copy is made, the Memory's _index and _id fields need to be changed, not just the _owner field. And so, I think the virtual reserve method needs to have the following signature, if we want to enable reserving Memory and ReadOnlyMemory:
```c#
protected internal virtual DisposableReservation Reserve(ref OwnedMemory<T> owner, ref long id, ref int index, ref int length)
```
If we want to enable reserving only on ReadOnlyMemory, then it could be:
```c#
protected internal virtual DisposableReservation Reserve(ref ReadOnlyMemory<T> memory)
```

... which prompts another question/issue: does it make sense to reserve r/w memory via copy? Any modifications to the copy won't be visible to the original and so such semantics might be very surprising to a point where it's impossible to write reliable software, i.e. the caller of Rerserve will never know if a copy was made or not.

**Comment by davidfowl** [comment]
So after thinking about this, I think we should keep it simple. I've removed the copy vs not copy from the abstraction itself and have internalized it into a special case in channels. This is much cleaner and localized to a specific scenario (which is uncommon). We might still want to delegate Reservations to the base class.

PS:
https://github.com/davidfowl/Channels/commit/cc55f9d675b4187f7add494732f62636d967e688
