### ISSUE TITLE
Make Initialize virtual again.

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#936]
The latest changes removed the virtual from Initialize().

https://github.com/dotnet/corefxlab/blob/0b998595fc71c25df5e17feb84c50fb32a87e111/tests/System.Slices.Tests/MemoryTests.cs#L180

I'm reusing my equivalent `AutoDisposeMemory` and was using Initialize to start the reference count at 1.

**Comment by davidfowl** [comment]
I had to do this:

https://github.com/davidfowl/Channels/commit/0ab8067f3834277649e4828c2446b4a8012b69e8#diff-5771d95dc15ca396dd271baf4ea8f567R57

**Comment by KrzysztofCwalina** [comment]
Could you clarify what's the problem with what you had to do?

**Comment by davidfowl** [comment]
If Initialize was virtual I would just put the AddReference inside there instead of doing it in that method.

**Comment by davidfowl** [comment]
The meta point being that I'd like ReferenceCountedBuffer to be reusable and self contained. All of the logic to do with ref counting should be isolated in that single class. Because there's no place to run code for re-initialization, I have to move the AddReference after re-initialization into a sub class (in this case MemoryPoolBlock). Ideally it would look like this:

```C#
public abstract class ReferenceCountedBuffer : OwnedMemory<byte>, IBuffer
{
    public ReferenceCountedBuffer(byte[] buffer, int offset, int length, IntPtr pointer = default(IntPtr)) 
        : base(buffer, offset, length, pointer)
    {
    }

    protected override void Initialize(T[] array, int arrayOffset, int length, IntPtr pointer = default(IntPtr))
    {
        base.Initialize(array, arrayOffset, length, pointer);
        AddReference();
    }

    public IBuffer Preserve()
    {
        AddReference();
        return this;
    }

    protected override void OnReferenceCountChanged(int newReferenceCount)
    {
        if (newReferenceCount == 0)
        {
            Dispose();
        }
    }

    void IDisposable.Dispose()
    {
        Release();
    }
}
```

This would make it work for both initial construction as well as re-initialization.

**Comment by KrzysztofCwalina** [comment]
Who calls Initialize (besides the base ctor)? Could the method that calls Initalize AddReference?

**Comment by davidfowl** [comment]
@KrzysztofCwalina I do manually, when I want to reuse the object that was pooled:

https://github.com/davidfowl/Channels/blob/ad581c99f119b99780adfd0bdbf48da2dd7e2be9/src/Channels/MemoryPoolBlock.cs#L57

Isn't this the pattern? Call initialize when you want to reuse the thing?

**Comment by omariom** [comment]
May be Memory and related stuff needs a document with goals and strategy, like the one Span has?

**Comment by KrzysztofCwalina** [comment]
Yeah, I will start writing one soon (possibly next week).

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, can you triage this issue? I would like to remove all System.Memory issues from corfxlab. thanks.

**Comment by joshfree** [comment]
Closing old corefxlab issues on Span now that the type is in the dotnet/corefx repo; future issues should be opened there
