### ISSUE TITLE
OwnedMemory properties should be private set

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#937]
Else you risk a derived class tearing the object

https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Buffers/OwnedMemory.cs#L13-L17

/cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
The class needs to be mutable, otherwise it cannot be object pooled. If I make the fields private, I would have to provide a different way to mutate them. This new way would have to be synchronized to avoid code observing intermediate state while the object is being mutated. Such synhronization would totally kill perf (as for example Span property would have to participate in the synchronization).

**Comment by benaadams** [comment]
Mutate via Initalization? Single `IsDisposed` check e.g. must be disposed to be changed

The dispose would likely need to change a little as you can override it to not clear. So would need to call a derived dispose then clear? (Else you'd lose the ability to clear if dispose was overriden by derived class)

**Comment by davidfowl** [comment]
It's already mutable by calling Initialize again @KrzysztofCwalina can you think of other cases where we need to individually set these fields?

**Comment by KrzysztofCwalina** [comment]
In today's implementations, we mutate the fileds in Initialize and in the following ctor
```c#
public unsafe OwnedPinnedArray(T[] array) : base(array, 0, array.Length, IntPtr.Zero) 
{
    _handle = GCHandle.Alloc(array, GCHandleType.Pinned);
    base.Pointer = _handle.AddrOfPinnedObject();
}
```
Initialize already does the IsDisposed check, so we are covered. I changed the ctor above to the following:
```c#
public unsafe OwnedPinnedArray(T[] array) : this(array, GCHandle.Alloc(array, GCHandleType.Pinned))
{}

private OwnedPinnedArray(T[] array, GCHandle handle) 
    : base(array, 0, array.Length, handle.AddrOfPinnedObject()) 
{
            _handle = handle;
}
```
Let's hope it scales to other scenarios (subclasses).

I will submit a PR to make the field setters private.
