### ISSUE TITLE
Move Span<T> and friends to corefx repo

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#946]
Span<T>, ReadOnlySpan<T>, and SpanExtensions, and their dependencies should be moved to corefx repo. 

When the APIs are moved to corefx, they should be placed in System.Memory dll/package. System.Slices will stay in corefxlab and will contain Memory<T>, OwnedMemory<T> and friends.

**Comment by KrzysztofCwalina** [comment]
cc: @joshfree, @terrajobst

**Comment by joshfree** [comment]
@AtsushiKan can you pick this item up first?  It'll make it easier for folks in Roslyn and ASP.NET to consume bits

**Comment by shaggygi** [comment]
Is this similar to https://github.com/dotnet/corefxlab/issues/1005?

**Comment by KrzysztofCwalina** [comment]
this is done
