### ISSUE TITLE
Do we want to prevent double Dispose from one DisposableReservation?

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#949]
See #944 

The PR makes the following code work:
```c#
var reservation = memory.Reserve();
var rouge = memory.Reserve();
var copy = rouge;
copy.Dispose();
rouge.Dispose();
Assert.False(reservation.IsDisposed);
```
It's done by having unique IDs per reservation.
The cost of the feature is that now OwnedMemory has to maintain a list of reservation IDs. The list could be optimized, but non the less it might mean array allocations in some real world scenarios.

**Comment by benaadams** [comment]
Related should disposing a reservation invalidate outstanding memory on that reservation?

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, can you triage this issue? I would like to remove all System.Memory issues from corfxlab. thanks.
