### ISSUE TITLE
We need common BufferPool Abstraction

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#950]
Currently, Channels and corfxlab use two different buffer pool abstractions. This means there are many different shared pools in a channels process using some of the corfxlab libraries (e.g. Json). We need a common pool abstraction to solve this problem.

Strawman for the abstraction is in https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Experimental/System/Buffers/BufferPool.cs

```C#
    public abstract class BufferPool : IDisposable {
        protected BufferPool();
        public void Dispose();
        protected abstract void Dispose(bool disposing);
        ~BufferPool();
        public abstract OwnedMemory<byte> Rent(int minimumBufferSize);
        public abstract void Return(OwnedMemory<byte> buffer);
    }
```
Updated
```C#
    public abstract class BufferPool<T> : IDisposable {
        protected BufferPool();
        public void Dispose();
        protected abstract void Dispose(bool disposing);
        ~BufferPool();
        public abstract OwnedMemory<T> Rent(int minimumBufferSize);
        public abstract void Return(OwnedMemory<T> buffer);
    }
```

**Comment by KrzysztofCwalina** [comment]
cc: @davidfowl

**Comment by benaadams** [comment]
Needs to be of `<T>` rather than `byte` also there are two types non-disposable/raw data (string, array) and disposables/data holders. Ideally the `IDisposable` would be exposed for second without casting.

However with the second the Return could also be hidden and wrapped into disposal e.g. [AutoPooling](https://github.com/benaadams/corefxlab/blob/8adb78370ad0d1263bdca1437db5dc59f89ce0b4/src/System.Buffers.Experimental/System/Buffers/AutoBufferPool.cs) whereas in the raw data form it needs to be manual pooling.

Not sure if that means there are two pool types, a hierarchy of pools or not?

**Comment by davidfowl** [comment]
> However with the second the Return could also be hidden and wrapped into disposal e.g. AutoPooling whereas in the raw data form it needs to be manual pooling.

I'm a fan of this approach because the `OwnedMemory<T>` implementation handed out to consumers just knows its lifetime. Calling dispose on memory vs Return to the pool is a very strange thing to deal with. That's why the pool in channels has no return.

**Comment by davidfowl** [comment]
I just tried to use the existing buffer pool abstraction and it bit me again. I have to pass the `BufferPool` and the `OwnedMemory<byte>` to the places that need to Dispose owned memory which is a PITA. The `OwnedMemory<byte>` should just be self describing and should return to the pool on disposal.

**Comment by davidfowl** [comment]
```C#
    public abstract class BufferPool : IDisposable {
        protected BufferPool();
        public void Dispose();
        protected abstract void Dispose(bool disposing);
        ~BufferPool();
        public abstract OwnedMemory<byte> Rent(int minimumBufferSize);
    }
```

**Comment by Drawaes** [comment]
Agreed. It's ugly you end up passing the buffer pool into classes so they can clean up the memory rental on dispose surely just a pointer to the owning pool?

**Comment by davidfowl** [comment]
See https://github.com/dotnet/corefxlab/pull/1309

**Comment by KrzysztofCwalina** [comment]
#1309 fixes it.
