### ISSUE TITLE
Review Memory<T> architecture

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#952]
Not a detailed design, but we should review general architecture of OwnedMemory<T>, Memory<T>, etc.

Here are the main points to discuss:
1. Relationship between main types: OwnedMemory<T>, Memory<T>, ROMemory<T>, IMemory<T>, IROMemory<T>, IReferenceCounted
2. Do we want the abstractions? how much abstraction?
3. Reservation IDs
4. Reference counting

After the review, I will write down the spec.

**Comment by buybackoff** [comment]
Could you please add a disposable `ReservedMemory<T>` with a field `Memory<T>` instead of `DisposableReservation`? Similar pattern to [this](https://github.com/davidfowl/Channels/blob/master/src/Channels/PreservedBuffer.cs). Now I have to combine `DisposableReservation` and `Memory<T>` in a new struct to pass `Memory<T>` around. Not sure it is the supposed way, and it would be nice to have a built-in API for that.

**Comment by benaadams** [comment]
@buybackoff would https://github.com/dotnet/corefxlab/pull/944 meet those needs? In particular [`ReservedMemory`](https://github.com/benaadams/corefxlab/blob/8adb78370ad0d1263bdca1437db5dc59f89ce0b4/src/System.Slices/System/Buffers/ReservedMemory.cs)

**Comment by buybackoff** [comment]
@benaadams Exactly, thanks! Haven't noticed that PR.

**Comment by buybackoff** [comment]
Currently `Memory<T>` equality is missing and `struct`'s equality is used by default. Probably the default way should be what `Span.ReferenceEqual` is doing, e.g. only owner, offset and length comparison.

**Comment by KrzysztofCwalina** [comment]
The reservation token cannot have Memory property because Memory\<T\> is mutable. We would need to have R/O and R/W reservation tokens.

**Comment by benaadams** [comment]
Already in #944 as [ReservedReadOnlyMemory](https://github.com/benaadams/corefxlab/blob/8adb78370ad0d1263bdca1437db5dc59f89ce0b4/src/System.Slices/System/Buffers/ReservedReadOnlyMemory.cs)

**Comment by mjp41** [comment]
@KrzysztofCwalina I have a question about the OwnedMemory class.  


[https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Buffers/OwnedMemory.cs#L113-L116](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Buffers/OwnedMemory.cs#L113-L116)
```csharp
         protected internal virtual DisposableReservation Reserve(ref ReadOnlyMemory<T> memory) 
         { 
             return new DisposableReservation(this, Id); 
         } 
```
In this function, what is the purpose of `memory`?  It is not used?

It is passed as a parameter in 
https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Buffers/ReadOnlyMemory.cs#L54

```csharp
           public DisposableReservation Reserve() 
           { 
             return _owner.Reserve(ref this); 
           } 
```

**Comment by KrzysztofCwalina** [comment]
The idea was that if you all Reserve on a small slice of large memory buffer, the implementation can copy just this small slice to a new buffer and return it in reserve. See https://github.com/dotnet/corefxlab/blob/master/tests/System.Slices.Tests/MemoryTests.cs#L105

But, I am not convinced we want this feature. @davidfowl was going to use it at some point, but I am not sure he does.

**Comment by davidfowl** [comment]
It no longer needs to be part of `OwnedMemory<T>`, `ReadableBuffer` already has a different version of it.

**Comment by KrzysztofCwalina** [comment]
closing as I think we settled on the architecture we want.

**Comment by ahsonkhan** [comment]
> After the review, I will write down the spec.

Tracked by https://github.com/dotnet/corefx/issues/23863
