### ISSUE TITLE
Generic Constraint only Interfaces

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefxlab#954]
There are a number of interfaces that it would be helpful to implement on types e.g. `IEquatable<T>` or `IDisposable` on stack only types e.g `Span<T>` which would work as generic constraints, however would want to not be used as heap boxable interfaces.

Would this be possible in some way, is it worthwhile?

@jaredpar @jkotas @KrzysztofCwalina @davidfowl

**Comment by jkotas** [comment]
We do plan to allow stack only types as generic type arguments in foreseeable future.

**Comment by jamesqo** [comment]
It seems rather unfortunate/limiting that `Span<T>` can't be used as a generic type argument at all, e.g. `List<Span<T>>` just to save those extra 4-8 bytes in its field size.

**Comment by jkotas** [comment]
Saving the extra 4-8 bytes is the least of the problem. Check https://github.com/dotnet/corefxlab/blob/master/docs/Span.md - `Requirements` paragraph and `Span<T> will be stack-only` paragraph that goes into more details. Allowing ref-like types as generic arguments would need to satisfy all requirements; or change the requirements but then it is a different type.
