### ISSUE TITLE
PrimitiveParser: Decide on a policy and API surface area for parsing hexadecimal numbers from text

### ISSUE THREAD

**Issue by botaberg** [dotnet/corefxlab#968]
When parsing hexadecimal characters from text, should there be specific overloads for strings containing uppercase ABCDEF and lowercase abcdef? Should there be one overload that is case-insensitive?

**Comment by botaberg** [comment]
@KrzysztofCwalina FYI - this issue has been created and I have assigned myself. @yizhang82 has recommended that the overloads be case-insensitive, since the alternative seems to be bloated in terms of API surface area. What do you think?

**Comment by svick** [comment]
The advantage of having separate overloads would be better performance, right? So, what is the performance difference?

**Comment by botaberg** [comment]
We don't know yet. We will be writing performance benchmarks to better understand and compare our options.

**Comment by KrzysztofCwalina** [comment]
The parsers has been productized and moved to corefx. I think hex parsing is now case insensitive:
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/Text/Utf8Parser/ParserHelpers.cs#L29
