### ISSUE TITLE
CommandLine: Support end-of-options token (i.e. '--')

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefxlab#986]
The double-dash operator allows you to specify parameters that start with `-` by signifying the end of option arguments. Everything after it will be treated as a parameter.

For example, `grep -- --version file` searches the file for the string `--version`.

This also interacts with #825. Specifying `-a 1 -- -a 2` wouldn't override the value of `a` with `2`. Instead, `-a 2` would become unparsed arguments.

**Comment by khellang** [comment]
This is already supported, no? The lexer just treats all arguments after `--` as literals. See https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/System/CommandLine/ArgumentLexer.cs#L56

**Comment by bricelam** [comment]
Sweet! Lol, I knew I should have tested it...
