### ISSUE TITLE
Add EncodingData.InvariantUtf16BE

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#988]
We should add EncodingData.InvariantUtf16BE (big-endian) static to allow formatting and parsing big-endian UTF16 text.

**Comment by KrzysztofCwalina** [comment]
cc: @hammett

**Comment by GrabYourPitchforks** [comment]
@KrzysztofCwalina Is this still relevant now that we have UTF8-specific parsing / formatting types, `StandardFormat`, and `SymbolTable`?
